### PR TITLE
Build: Add option USE_IMPORTC=0 to switch back to compiling zlib with C compiler

### PR DESCRIPTION
**Pull request by kinke**
Wrt. Bugzilla Issue 24389.

### CODE REVIEW

**Comment by kinke** [comment]
Okay, both modes CI-tested successfully (`USE_IMPORTC=0`: https://github.com/dlang/phobos/actions/runs/7906378178?pr=8914).

**Review by thewilsonator — APPROVED** [review]

**Comment by jmdavis** [comment]
Is this supposed to work by setting `USE_IMPORTC=0` on the command line? If I edit the Make file so that `USE_IMPORTC` is 0, then this works on FreeBSD 14, but if I run `USE_IMPORTC=0 gmake`, then it acts like it's still 1.

**Comment by ibuclaw** [comment]
It's probably `=` vs `:=` vs `?=`

Put the declaration inside an `ifeq (,$(IMPORTC))` condition (`ifneq (0,$(IMPORTC))`?)

**Comment by jmdavis** [comment]
> It's probably `=` vs `:=` vs `?=`
> 
> Put the declaration inside an `ifeq (,$(USE_IMPORTC))` condition (`ifneq (0,$(USE_IMPORTC))`?)

Changing the Makfile to use `USE_IMPORTC?=1` instead of `USE_IMPORTC:=1` does seem to fix it.

**Comment by kinke** [comment]
Make variables are set/overridden via `gmake USE_IMPORTC=0`. Your previous syntax set the env variable, that's something else.

**Comment by jmdavis** [comment]
> Make variables are set/overridden via `gmake USE_IMPORTC=0`. Your previous syntax set the env variable, that's something else.

Well, my knowledge of make is clearly lacking then. I don't think that I've ever seen make variables set without being environment variables (or if I did, I mistook them for environment variables), but either way, I can confirm that if the value is set on the right-hand side, it works properly.

**Pull request merged**
