### PR TITLE
Avoid string concatenations in put() calls to avoid GC allocations

### PR DESCRIPTION
**Pull request by nordlow**

### CODE REVIEW

**Comment by nordlow** [comment]
> Hold on, the strings being concatenated are all known at compile-time, so they should be concatenated at compile time. I doubt this actually does any GC allocations currently, and this way of doing more calls to `put` seems like a performance regression.

Good catch. Will the compiler guarantee compile-concatenation or do we need to assign the concatenation to an enum?

**Comment by dkorpel** [comment]
I'm pretty certain dmd always constant folds strings when it can, just like `10 + 20` never results in run-time arithmetic, but you can test it to be sure.

**Comment by PetarKirov** [comment]
@nordlow if you want to make the code more clear, you could assign these expressions to `enum` variables. That way it should be clear that the concatenation happens at compile-time.

**Comment by nordlow** [comment]
> @nordlow if you want to make the code more clear, you could assign these expressions to `enum` variables. That way it should be clear that the concatenation happens at compile-time.

See https://github.com/dlang/phobos/pull/8281.

**Pull request merged**
