### PR TITLE
Changelog for std.regex

### PR DESCRIPTION
**Pull request by DmitryOlshansky**
Also remove nextPow2 entry, it was added in previous release.

### CODE REVIEW

**Comment by wilzbach** [comment]
looks good ;-)

**Comment by Hackerpilot** [comment]
Auto-merge toggled on

**Comment by JackStouffer** [comment]
This should have mentioned the speed enhancements and the new keepSeparators flag.

**Comment by DmitryOlshansky** [comment]
It does mention optimizations, but misses keepSeparators flag. Would you like to add it in a pull or should I?

**Pull request merged**
