### PR TITLE
Fix Issue 17330 - [REG 2.072] BigInt's constructor used to be pure

### PR DESCRIPTION
**Pull request by JackStouffer**
If anyone else has a cleaner solution, I'd like to know. I'll quote Walter in describing the problem 

> I think that trouble here is that attribute inference is not done until the template is instantiated. But the compiler does not instantiate a template until it matches a template, and

    this(Range)(Range s)

> does not match for constructing an immutable. I don't see a way out of this chicken-and-egg problem.

### CODE REVIEW

**Comment by quickfur** [comment]
+1 for killing autodecoding because it's totally unnecessary here.

But... can you explain again how this fixes the bug, and why killing autodecoding works around the template instantiation chicken-and-egg problem?  Maybe I'm missing something obvious, but I don't get it.

**Comment by JackStouffer** [comment]
@quickfur Auto-decoding was already worked around via `byCodeUnit` in the original code.

The problem is that it's impossible for the compiler, according to Walter, to properly infer that the original ctor is to be used for the immutable construction of a BigInt. This PR manually specifies `pure` for all string inputs in order to get around the regression because we can be sure that their range methods are pure.

**Comment by quickfur** [comment]
Ahh, I see.

Hmph. Does that mean that passing in a non-builtin range of char will run into the same problem?

**Comment by JackStouffer** [comment]
If you specify it to be immutable as in the example, it won't compile, no. To be fair though, it never compiled.

**Comment by quickfur** [comment]
Though, to be honest, we didn't originally support constructing a BigInt with any old char range to begin with, so it's probably not horrible to say that it currently works except for constructing immutable BigInts.  And fixing the regression is a higher priority, IMO.

**Comment by quickfur** [comment]
Yeah I thought so. Well, let's at least get this regression fixed first, and worry about how to support non-builtin char ranges later.

**Comment by quickfur** [comment]
I'd say we need to fix the compiler at some point, though.  I can just imagine now we'll be needing to add a pure overload to any ctor that takes a range, just so we can construct immutable objects from it.  I think the compiler ought to figure out that since this is a template function, and therefore may just happen to be inferred as pure, it should try instantiating it (speculatively) to see if it's usable for immutable construction or not. Probably not as simple as I imagine, but still.  User code shouldn't be penalized just because they take a range.

**Pull request merged**
