### PR TITLE
Remove deprecated symbols from std.digest.digest

### PR DESCRIPTION
**Pull request by MoonlightSentinel**
Blocked by:

- [x] CyberShadow/ae#42
- [x] Upgrade [dlang-bot](https://github.com/dlang/dlang-bot) to newer vibe-d

### CODE REVIEW

**Comment by CyberShadow** [comment]
Uh-oh, looks like there's some un-announced breakage. The symbols in `std.digest.digest` were deprecated, but the module itself was not. I guess it would need to go through a deprecation cycle too, but maybe we can expedite this one since by itself the import either does nothing, or would have already caused deprecation messages due to used aliases.

**Comment by MoonlightSentinel** [comment]
You're right, this seems to be an oversight as the deprecation messages already indicated that the entire module will be removed.

I would suggest removing the entire file instead of keeping an empty module as it only requires changes in `ae` and `vibe-d:mongo` (which requires 2.077.1 while the deprecation was introduced in 2.076.1).

But I can adapt this PR if an additional deprecation cycle is preferred.

**Comment by CyberShadow** [comment]
> as it only requires changes in `ae` and `vibe-d:mongo`

The projects we have in the project tester are really just canaries to catch some % unexpected breaking changes. We can't know about the effects of changes on code we can't see (private codebases, and also the long tail of smaller open-source codebases), but seeing how there is more than one breakage in the project tester, we can extrapolate that it seems likely that it will affect other projects too.

**Comment by MoonlightSentinel** [comment]
Changed to only remove the deprecated symbols and started the deprecation cycle

**Comment by MoonlightSentinel** [comment]
Added the missing changelog

**Comment by thewilsonator** [comment]
```
../.dub/packages/vibe-d-0.8.4/vibe-d/mongodb/vibe/db/mongo/settings.d(16,8): Error: module `std.digest.digest` import `toHexString` not found
```

**Comment by MoonlightSentinel** [comment]
This should be green now thanks to dlang/dlang-bot#239

**Pull request merged**
