### PR TITLE
Reset pending changelog after 2.075.0

### PR DESCRIPTION
**Pull request by wilzbach**
We should probably include this into the release pipeline ...
CC @MartinNowak 

Other PRs:
- [ ] https://github.com/dlang/dmd/pull/6924
- [ ] https://github.com/dlang/druntime/pull/1849

### CODE REVIEW

**Comment by CyberShadow** [comment]
> We should probably include this into the release pipeline ...

What do you think about instead of having one directory for the pending changelog, instead have one subdirectory per target version and just leaving them there?

**Comment by wilzbach** [comment]
> What do you think about instead of having one directory for the pending changelog, instead have one subdirectory per target version and just leaving them there? I.e.:

Hmm I liked this on first minute, but I think then we would have a bit of the old problem: if someone makes a PR with a changelog entry, he shouldn't need to rebase the PR just because we released a new version.
We could solve this by having a `pending` folder, but then there would be no gain compared to purging the folder after every release ... so I am not sure that we win much/anything by this?

**Comment by wilzbach** [comment]
We should probably just add a simple script or feature to Dlang-Bot that creates these purge PRs. After all, it's always the same action, e.g.:

```sh
git clone ${repo}
rm changelog/*.dd
git checkout -b changelog-purge-branch-123
git add changelog
git commit -m "Purge changelog"
hub pull-request
```

**Comment by CyberShadow** [comment]
> Hmm I liked this on first minute, but I think then we would have a bit of the old problem: if someone makes a PR with a changelog entry, he shouldn't need to rebase the PR just because we released a new version.

Good point.

**Comment by wilzbach** [comment]
@CyberShadow so what's our course of action here? Clean the changelog manually this time & create these PRs automatically in the future?

**Comment by CyberShadow** [comment]
Is this PR blocked by the 2.075.0 release?

**Comment by wilzbach** [comment]
Imho no.
The branch-off has already happened, right?

**Comment by CyberShadow** [comment]
It will clear the pre-release changelog on dlang.org, which is undesirable.

**Comment by MartinNowak** [comment]
Same as for https://github.com/dlang/druntime/pull/1849.

**Comment by MartinNowak** [comment]
> @CyberShadow so what's our course of action here? Clean the changelog manually this time & create these PRs automatically in the future?

It's in the release script and they get purged when they are released on a branch (e.g. stable). They get purged on master when merging the changes and the release tag into master. This is a useful scheme that should also scale to parallel release branches (e.g. 2.074.x, 2.075.x).

**Comment by CyberShadow** [comment]
Yeah, it's just that it would be nice if we could figure out a way to get a preview of upcoming changes on dlang.org between the points of said purge and the release (which bumps the version number). Maybe we could use different filename suffixes e.g. (`_pre` for the static (purged) one and `_next` for the autogenerated one).

**Pull request closed without merging**
