### PR TITLE
Add minimum HPPA support to phobos

### PR DESCRIPTION
**Pull request by ibuclaw**
So it at least compiles...

### CODE REVIEW

**Comment by thewilsonator** [comment]
`make: *** [dscanner] Segmentation fault`, Oy, that doesn't look good. @BBasile

**Comment by BBasile** [comment]
@thewilsonator unfortunately D-Scanner doesn't crash locally. I even tested the exact PR. It looks like you'll have to run in in gdb, like in the past iirc.

**Comment by thewilsonator** [comment]
Hmm, bummer. @ibuclaw you could try giving it another kick to see if it as a random failure.

**Comment by BBasile** [comment]
Still the results from 9 hours ago. amend + force push is necessary.

**Pull request merged**
