### PR TITLE
parallelism: Always run one round of the stress test

### PR DESCRIPTION
**Pull request by klickverbot**
This is just to see whether there are any remaining issues on the auto tester.

### CODE REVIEW

**Comment by JackStouffer** [comment]
Do you know about this PR: https://github.com/dlang/phobos/pull/4399?

No need to duplicate work.

**Comment by burner** [comment]
@klickverbot it will be, thank you

**Comment by DmitryOlshansky** [comment]
LGTM

**Comment by burner** [comment]
@klickverbot yes

**Pull request closed without merging**
