### PR TITLE
Add messages to some asserts in std/socket.d

### PR DESCRIPTION
**Pull request by Flying-Toast**
Work on project [#2](https://github.com/dlang/phobos/projects/2)

### CODE REVIEW

**Comment by Flying-Toast** [comment]
I'm not sure what the message should be for this assert:
https://github.com/dlang/phobos/blob/64eac952e385696880cbf6eac26516115fc60eef/std/socket.d#L970

**Comment by thewilsonator** [comment]
`Failed to retrieve AddressInfo`? Not surer why thats an assert rather that an ErrnoException (or something a bit more descriptive). 

cc @CyberShadow `git blame` blames you as author of the assert in question. Any insight?

**Comment by lesderid** [comment]
AFAICT that can never happen. Both POSIX[1] and Windows[2] will always return "one or more" results when `getaddrinfo` returns 0, so that should already be handled by: https://github.com/dlang/phobos/blob/64eac952e385696880cbf6eac26516115fc60eef/std/socket.d#L956

[1] https://pubs.opengroup.org/onlinepubs/9699919799/functions/getaddrinfo.html
[2] https://docs.microsoft.com/en-us/windows/desktop/api/ws2tcpip/nf-ws2tcpip-getaddrinfo

**Comment by Flying-Toast** [comment]
I think that https://github.com/dlang/phobos/blob/64eac952e385696880cbf6eac26516115fc60eef/std/socket.d#L271 could also be removed, because it is already covered by https://github.com/dlang/phobos/blob/64eac952e385696880cbf6eac26516115fc60eef/std/socket.d#L120?

**Comment by lesderid** [comment]
I think it's better to keep that. If the `static assert(0)` is removed, what should it return?

**Pull request merged**
