### PR TITLE
Fix Issue 10448: min and max are not NaN aware

### PR DESCRIPTION
**Pull request by JackStouffer**
min and max now return NaN when ever one of the arguments is NaN.

### CODE REVIEW

**Comment by tsbockman** [comment]
I have submitted a pull request with some micro-optimizations: https://github.com/JackStouffer/phobos/pull/9

**Comment by 9il** [comment]
This will slowdown math algorithms

**Comment by JackStouffer** [comment]
> This will slowdown math algorithms

Yes it will, but

1. The current version is wrong. Just look at the examples in the bug report
2. This will only slow down if one of the arguments is a floating point number
3. We can't keep stalling obvious improvements and fixes (e.g. https://github.com/dlang/phobos/pull/4328) because of DMD's performance

**Comment by 9il** [comment]
> The current version is wrong. Just look at the examples in the bug report

This is normal. If you are interesting in correct sorting, use http://dlang.org/phobos/std_math.html#.cmp

http://dlang.org/phobos/std_math.html#.cmp

> This will only slow down if one of the arguments is a floating point number

This fix only floating point number so this slowdown only floating point number. But sci folk use floating point numbers every day and performance is very important.

**Comment by JackStouffer** [comment]
> For example, the IEEE 754 standard defines (section 5.3) functions minNum and maxNum as follows:

@klickverbot If I'm reading it correctly, we're already breaking the standard.

For example,

```
import std.stdio;
import std.algorithm.comparison;

void main()
{
    writeln(min(10, double.nan));
    writeln(min(double.nan, 10));
}
```

prints

```
nan
10
```

and not two 10's.

Based on the table you posted the only languages that follow the standard are Julia, C, and Octave. And the conclusion of that thread was

> The consensus in this thread seems to be that the behavior in the existing standard is both surprising and not a good idea. The rationale given for the standard behavior, given upthread, certainly doesn't make sense now.

and I totally agree. Things like `min(sqrt(-1), 10) == 10` make no sense.

**Comment by JackStouffer** [comment]
For the scientific usage argument, consider that numpy currently always returns NaN when using either `numpy.min` or `numpy.max`. Numpy has the `numpy.nanmin` or `numpy.nanmax` functions for ignoring NaN values. So by default, on one of the largest scientific libraries is also ignoring the standard.

**Comment by 9il** [comment]
@JackStouffer If you want to improve min/max, you may add `fmin` and `fmax` functions calls from std.math (if common type is FP)

**Comment by tsbockman** [comment]
@9il 
> If you want to improve min/max, you may add fmin and fmax functions calls from std.math (if common type is FP)

Are you suggesting that the NaN handling of this PR be implemented in `fmin()` and `fmax()` instead?

(I am confused by the way you worded that.)

**Comment by 9il** [comment]
> Are you suggesting that the NaN handling of this PR be implemented in fmin() and fmax() instead?

Yes

**Comment by tsbockman** [comment]
> Yes

By which you meant "No":

> my suggestion was to use `fmax` and `fmin` in `max` and `min`.
> `fmin` and `fmax` should be compiler intrinsics.

**Comment by 9il** [comment]
Yes and No in the same time. The behavior should depend on compiler flags/ and function attributes (see https://github.com/ldc-developers/ldc/pull/1472 ). This should be a compiler intrinsics, which can be optimized using SIMD instructions (for example `minps`). So, min and max should just call fmin and fmax and don't care about NaN handing. So, _yes_: NaN handing should be in fmin and fmax. And _no_: we should not add code to this functions, but make them intrinsics instead.

**Comment by tsbockman** [comment]
> The behavior should depend on compiler flags/ and function attributes (see ldc-developers/ldc#1472 ).

OK. Thanks for explaining more clearly.

**Comment by 9il** [comment]
Sorry for the first unclear message

**Pull request closed without merging**
