### PR TITLE
fix spacing after if

### PR DESCRIPTION
**Pull request by MartinNowak**

### CODE REVIEW

**Comment by wilzbach** [comment]
Thanks - we should try to have a closer eye on warnings from Travis in the future :) 
LGTM!

**Comment by BBasile** [comment]
Let's get the merge, asap.

**Comment by DmitryOlshansky** [comment]
Auto-merge toggled on

**Comment by andralex** [comment]
Thank you! Do we have that stuff on hook so commits cannot proceed if in violation of such simple rules?

**Pull request merged**
