### PR TITLE
Give Flag!"each" a more descriptive name

### PR DESCRIPTION
**Pull request by pbackus**
This makes it more obvious that "no" means "stop" and "yes" means
"continue".

---

Should be backwards compatible since the new enum uses `Flag!"each"` as its base type.

@atilaneves This introduces a new public symbol, `Continue`.

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by thewilsonator** [comment]
```
std/algorithm/iteration.d(841:6)[warn]: Public declaration 'Continue' has no documented example.
```

**Comment by andralex** [comment]
I'm unclear whether creating a federation of names is better than one simple convention.

**Comment by pbackus** [comment]
@andralex In isolation, it's ambiguous whether `return Yes.each;` means "yes, stop" or "yes, keep going." `return Continue.yes;` is unambiguous.

If the question is, why not change the flag type to `Flag!"continue"` (`Yes.continue`, `No.continue`) instead of creating a new enum—it's to avoid breaking backwards compatibility.

**Comment by andralex** [comment]
> @andralex In isolation, it's ambiguous whether `return Yes.each;` means "yes, stop" or "yes, keep going." `return Continue.yes;` is unambiguous.

To me `Yes.each` means to go on with `each` and `No.each` would mean to stop. If these are not obvious, a look at the documentation should settle it once and for all. Escalating this to an addition to the standard library seems much.

The larger problem is this creates a precedent whereby creating slightly clearer names becomes an art of it own. It's Good Work that will create opportunities for more Good Work.

> If the question is, why not change the flag type to `Flag!"continue"` (`Yes.continue`, `No.continue`) instead of creating a new enum—it's to avoid breaking backwards compatibility.

I just see no utility in adding ever slightly better synonyms - this is an unending pit.

**Comment by pbackus** [comment]
I guess it's up to @atilaneves. If Phobos policy is "all names are final" then I'll withdraw this. In any case, I do not intend to set a precedent here.

Perhaps it would be better to start a list of "names to improve in future `std` versions."

**Comment by WalterBright** [comment]
The named argument DIP (approved) should render this flag usage obsolete. It's not necessary to improve the names. As to what "yes" means, I'm reminded of https://www.youtube.com/watch?v=2rHW0Gl2lbM

**Comment by pbackus** [comment]
Withdrawn in accordance with feedback.

**Comment by atilaneves** [comment]
@thewilsonator Please don't approve PRs that introduce new public symbols (it could have taken me more than 72 hours to see it). Thanks!

**Comment by dkorpel** [comment]
> The named argument DIP (approved) should render this flag usage obsolete.

The flag is not passed as a parameter, and you can't give a return value a name, so I don't think that applies to this particular flag.

**Pull request closed without merging**
