### PR TITLE
Simplify Visual C configuration for -m64/-m32mscoff builds

### PR DESCRIPTION
**Pull request by CyberShadow**
Ping @rainers

### CODE REVIEW

**Comment by DmitryOlshansky** [comment]
Is is still actual and blocked?

**Comment by rainers** [comment]
> Is is still actual and blocked?

Yes. Latest build on the auto tester is just a couple of days ago with just the same merge problem.

**Comment by rainers** [comment]
Current win64.mak contains targets phobos32mscoff and unittest32mscoff, though. So the coff32 part of this PR is probably no longer necessary.

**Comment by quickfur** [comment]
ping
Any updates? Been months...

**Comment by greenify** [comment]
ping pong - this is now officially the oldest open Phobos PR.
Why is it blocked?

**Comment by CyberShadow** [comment]
Again, see discussion in Druntime pull:
https://github.com/D-Programming-Language/druntime/pull/960#issuecomment-56156790

It's blocked by @braddr doing the necessary changes to the autotester. See https://issues.dlang.org/show_bug.cgi?id=14381

**Comment by MetaLang** [comment]
@CyberShadow this is passing the auto-tester. Does that mean the necessary changes have been made and this can go ahead? If not, please close as there has been no action on this PR for 3 years and counting.

**Comment by CyberShadow** [comment]
Wow, I never thought I'd see the day.

Yes, this is a simple refactoring. It was failing the autotester because it was conflicting with a patch that the autotester was applying before running this makefile.

The very fact that the autotester needs to patch the makefile shows that there is a problem with it. However, if this PR now passes the autotester, it means that it no longer needs to patch anything, or at least the patch is no longer incompatible with this PR.

In any case, this PR should simplify some use cases of building Phobos on Windows, so I still think it's a good change.

**Comment by MetaLang** [comment]
@MartinNowak

**Comment by wilzbach** [comment]
CC @rainers @marler8997 - would this help you?

**Comment by marler8997** [comment]
Yes it provides a nice set of hooks to correctly specify where visual C is installed and what version to use.

**Comment by rainers** [comment]
> CC @rainers - would this help you?

Not personally, as my build script passes the existing variables on the command line anyway. That's pretty ugly if they contain spaces, though.

This PR has been waiting so long to be merged that it is now incompatible with the current Visual Studio 2017. As this is the only version downloadable on the Microsoft pages without login it would be good if it could be supported, too.

**Pull request closed without merging**
