### PR TITLE
fix a regression in std.xml (2.075a)

### PR DESCRIPTION
**Pull request by aG0aep6G**
Regression was introduced by #5380. I don't know what exactly is wrong with it. Just reverting and adding a test.

### CODE REVIEW

**Comment by JackStouffer** [comment]
Issue number?

**Comment by aG0aep6G** [comment]
> Issue number?

Haven't filed one.

**Comment by JackStouffer** [comment]
Every regression needs a bug report

**Comment by aG0aep6G** [comment]
> Every regression needs a bug report

There you go.

**Pull request merged**
