### PR TITLE
fix issue 18993 (REG ~master) - toLower is broken for UTF chars

### PR DESCRIPTION
**Pull request by BBasile**

### CODE REVIEW

**Comment by BBasile** [comment]
ping, there's a problem with the project tester here.

**Comment by wilzbach** [comment]
Yep - https://ci.dlang.io is offline.

**Comment by Temtaime** [comment]
@BBasile would it go to master branch ?

**Comment by BBasile** [comment]
I can try but this must be this is usually done by the release czar or at least a member.

**Comment by BBasile** [comment]
Unfortunately This cant be cherry picked due to a conflict. Don't know if they'll take it (commit hash will be different)

**Comment by BBasile** [comment]
@Temtaime , see https://github.com/dlang/phobos/pull/6605

**Pull request merged**
