### PR TITLE
update dscanner to 0.4.0 final release

### PR DESCRIPTION
**Pull request by John-Colvin**

### CODE REVIEW

**Comment by DmitryOlshansky** [comment]
Auto-merge toggled on

**Comment by JackStouffer** [comment]
@DmitryOlshansky The auto-merge label does that already, but also won't merge if circle fails.

**Comment by DmitryOlshansky** [comment]
> The auto-merge label does that already, but also won't merge if circle fails.

That's something new, so now the preferred way of merging is setting auto-merge label?

**Comment by wilzbach** [comment]
> That's something new, so now the preferred way of merging is setting auto-merge label?

It's not officially released (yet), but hopefully will be soon:

https://github.com/dlang-bots/dlang-bot#auto-merge-wip
https://github.com/dlang-bots/dlang-bot/pull/17
http://forum.dlang.org/post/o3ogr0$27hu$1@digitalmars.com

Btw the `auto-merge-squash` label does exactly what you assume it to do. It will squash all commits into one before merging - this option was also enabled here some time ago (and because it was as well never announced was rarely used so far).
(=it behaves as if you would press the "Squash" button instead of the "Merge" one).

**Pull request merged**
