### PR TITLE
[dub] remove cfg related to `stdx`

### PR DESCRIPTION
**Pull request by thewilsonator**
the source path `source/stdx` no longer exists and `allocator` and `checkedint` have been moved out of there  so this configuration at best does nothing. If we want to re-sub-package phobos we should do that from scratch.

### CODE REVIEW

**Comment by LightBender** [comment]
Passes tests, and sets the stage for Phobos3. LGTM

**Review by LightBender — APPROVED** [review]

**Comment by thewilsonator** [comment]
Phobos as it pertains to editions. Not a fork.

**Comment by TurkeyMan** [comment]
But what does this mean?

**Comment by LightBender** [comment]
@TurkeyMan Good question, this document has some of the answer you are seeking: https://github.com/LightBender/PhobosV3-Design/blob/main/Design.md

For the purposes of the question as it pertains to this particular change, we'll be starting to develop Phobos 3 alongside Phobos 2 (current) in the same repo. The design calls for both to ship side-by-side.

**Comment by TurkeyMan** [comment]
Awesome, thanks!
Sorry, odd place for a discussion! Just spotted it out the corner of my eye...
I'm concerned that any work on phobos3 without move semantics implemented (work was started like 5 years ago, but seems to have stalled), will lead to bad design that needs to be reworked again some time in the future.
I've started a small project recently trying specifically to depend on phobos, and the experience is profoundly terrible. I've thought about forking my own standard library so many times. An actual phobos 3 is a huge opportunity.

**Comment by LightBender** [comment]
No worries, and Phobos 3 is a massive opportunity. Which is why we're trying to be at least a little more deliberate about it. And V3 still has a while to cook, it's not due out until the first edition, and _that_ does not even have a date yet.

**Comment by TurkeyMan** [comment]
I posted a nag on the forum about rval ref's; if phobos 3 doesn't have a container library after all this time, then I am will to declare D officially dead ;)

**Comment by LightBender** [comment]
There is a ton of discussion about containers specifically going on in the Discussions area of that repo. It is _the_ hot topic, but there are some hang-ups that need to get sorted out in the language first. I don't know if they'll be ready for V3, but probably V4.

**Comment by TurkeyMan** [comment]
move semantics, that's basically it. is walter just stopped what he's doing and implemented an rvalue reference, then this whole thing would be history 10 years ago.

**Pull request merged**
