### PR TITLE
[trivial] Mark internal unicode declarations as package

### PR DESCRIPTION
**Pull request by JackStouffer**
Slowly chipping away at the number of public undocumented symbols

### CODE REVIEW

**Comment by 9il** [comment]
What the reason of that change??

**Comment by 9il** [comment]
Internal phobos code is useful.

**Comment by JackStouffer** [comment]
If it's something that we want people to use, then it shouldn't be in internal. It should be in a top level module with documentation. Internal, by its very name, is not ment for public use.

**Comment by jmdavis** [comment]
@JackStouffer I assume that `package(std)` tells the compiler to put it in the `std` package? When did we get that feature?

@9il The only reason that these weren't `package` in the first place was because when they were added, there was no way to restrict them that way and have them in `internal`. I think that it's quite clear that anything in internal is not intended for use outside of Phobos, and it's definitely been the case that undocumented symbols have not been considered part of the API. If someone chooses to use stuff from `internal`, they're going to have to copy it. And if it's stuff that really should be generally available, then it should be moved somewhere else and documented appropriately. Regardless, if someone's code breaks because they used something in `internal`, then tough luck. They shouldn't have been using undocumented symbols - and from `internal` no less.

**Comment by JackStouffer** [comment]
> I assume that package(std) tells the compiler to put it in the std package? When did we get that feature?

No idea. I first saw it in the std.algorithm code

**Comment by 9il** [comment]
This constraints gives nothing. Phobos becomes too hightlevel 👎

**Comment by JackStouffer** [comment]
Again, if we want to expose this to the user, then this should be moved out of internal and put into its own module with a well defined and documented API. 

All of the Trie structs in `std.uni` are already private, so these are pretty much useless anyway.

**Comment by 9il** [comment]
> Again, if we want to expose this to the user, then this should be moved out of internal and put into its own module with a well defined and documented API.

This requires efforts

**Comment by jmdavis** [comment]
> This requires efforts

So do many things. These symbols are not only undocumented, but they're specifically in a package named _internal_. I don't see how anyone can reasonably expect that they can use these symbols without any risk of them being changed without prior notice. They are clearly intended to be used by Phobos only.

**Comment by andralex** [comment]
OK, increasing encapsulation and information hiding is good.

**Pull request merged**
