### PR TITLE
Remove Allman checks from grep lints as DScanner covers these.

### PR DESCRIPTION
**Pull request by LightBender**
@thewilsonator As requested.

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]
These checks are done [here](https://github.com/dlang/phobos/blob/master/.dscanner.ini#L93) in a better manner (i.e. comments are properly considered)

**Review by CyberShadow — APPROVED** [review]
:+1: for fewer Makefile hacks.

**Comment by thewilsonator** [comment]
Hmm, I'm not entirely convinced that the dscanner Allman checks are enabled for that. My dscanner-fu is not up to snuff.

**Comment by LightBender** [comment]
Closing this for now.

**Pull request closed without merging**
