### PR TITLE
implement Phobos end of -dip1008

### PR DESCRIPTION
**Pull request by WalterBright**
Blocked by https://github.com/dlang/dmd/pull/6681

If I did it right, we just gotta throw the switch.

### CODE REVIEW

**Comment by wilzbach** [comment]
For reference: the link to DIP 1008 is https://github.com/dlang/DIPs/blob/master/DIPs/DIP1008.md

**Comment by MetaLang** [comment]
@WalterBright the merge conflicts need to be resolved to fix the autotester.

**Comment by MetaLang** [comment]
@WalterBright ping

**Comment by JackStouffer** [comment]
Closing due to inactivity.

**Pull request closed without merging**
