### PR TITLE
fix Issue 21801 - std.typecons.ReplaceType does not work for `in` parameters

### PR DESCRIPTION
**Pull request by JohanEngelen**
See related: https://github.com/dlang/phobos/pull/7570

### CODE REVIEW

**Review by Geod24 — APPROVED** [review]

**Comment by Geod24** [comment]
Stable ?

**Review by RazvanN7 — APPROVED** [review]

**Comment by JohanEngelen** [comment]
don't know the exact dev policy. Feel free to retarget to `stable`.

**Comment by Geod24** [comment]
For trivial bug fixes it's better to target `stable`. It also means your fix will be available with the next LDC release, since Kinke usually release new minors based on the latest patch release.

**Comment by JohanEngelen** [comment]
CI is apparently broken for stable branch?

**Comment by JohanEngelen** [comment]
I don't know what the bot thinks, but looks like everything is OK, just one commit on top of stable. (I've done everything through the webinterface). Thanks a lot for merging :)

**Comment by berni44** [comment]
Strange thing here. I'm getting the same failures like the failing tests, when running the tests with dmd from master instead of dmd from stable. Don't know if this helps to track down the problem...

**Comment by JohanEngelen** [comment]
> Strange thing here. I'm getting the same failures like the failing tests, when running the tests with dmd from master instead of dmd from stable. Don't know if this helps to track down the problem...

The CI errors are completely unrelated to this PR.

**Comment by JohanEngelen** [comment]
https://github.com/dlang/phobos/pull/7958

**Comment by thewilsonator** [comment]
merged, please rebase.

**Comment by JohanEngelen** [comment]
rebased

**Pull request merged**
