### PR TITLE
Remove dependency on internal druntime modules

### PR DESCRIPTION
**Pull request by ryuukk**
Write portable code

Build better foundation

For an unbreakable future

### CODE REVIEW

**Comment by jmdavis** [comment]
1. I don't understand what the problem is with Phobos using druntime internals. Phobos depends on druntime, and it's all standard library stuff. We've done it for years, it reduces code duplication, and it hasn't been a problem for us. What do you actually think the problem is with Phobos using druntime internals like this?
2. This removes templates from Phobos that are needed regardless of whether they're using druntime internals.

**Comment by jmdavis** [comment]
> If druntime internal code needs to change behavior or be removed, then phobos users will be fuckt
> 
> Hence this is not robust, hence this is not future proof
> 
> If user wants to target esoteric platform or embedded with custom runtime, then he won't be able to use phobos
> 
> Foundation has to be done right, besides, this code solves no problems found in phobos 3
> 
> Let's also not make druntime dependent on phobos 3

druntime is not dependent on Phobos 3. Rather, Phobos 3 is dependent on druntime, just like Phobos 2 is dependent on druntime. And if anyone wants to target an esoteric platform, they can copy druntime and edit it as necessary. Either way, there's zero expectation that anyone is going to be able to use Phobos without druntime. Even if they're using -betterC with parts of Phobos that happen to work with -betterC, and they're not linking in the runtime, the druntime code will need to be available to use, because a number of things from druntime are used by Phobos (some from the internals and some from the public API), and that's not going to change with v3.

And since druntime and Phobos are developed, tested, and released together, if any change is made to druntime which breaks Phobos, it will be fixed. The two projects go together, and there's a decent chance that Phobos will even end up in the dmd repo at some point just like druntime was moved into there.

**Review by thewilsonator — CHANGES_REQUESTED** [review]
First, it is a desired feature that phobos relies on druntime for code deduplication so this PR is likely dead on arrival. 

Second, this PR removes the implementation of these functions without removing the unit tests that test them (thanks for the alert that the CI for phobos 3 clearly does not work!).

**Comment by atilaneves** [comment]
Phobos is written in D; D requires a runtime.

**Review by ljmf00 — CHANGES_REQUESTED** [review]
This doesn't make sense, sorry. We should actually do the opposite, move those traits all to `core` and just use them. We shouldn't do these aliases, if we are going to think of it as Phobos 3 and keep only one definition. The whole reason for these aliases was backward compatibility when they got eventually deduplicated.

**Comment by ljmf00** [comment]
It makes sense Phobos depending on Druntime, because normal D it self can't work without a runtime library.

**Comment by ljmf00** [comment]
> What people do not understand in
> 
> CORE.INTERNAL
> 
> Are you guys blind?

Fortunerly, I'm not blind... 

I think what you want to suggest first is, instead, move those out of internal package? I can agree with removing them if it is indeed considered public API and also if we are going to redo Phobos, but keeping them for compatibility is also good.

Your first step should have been suggesting it on the DMD repo in the first place.

**Pull request closed without merging**
