### PR TITLE
Fix broken link

### PR DESCRIPTION
**Pull request by Imperatorn**
@ is not encoded. Replaced with %40

Warning: FAT PR

### CODE REVIEW

**Review by ljmf00 — APPROVED** [review]

**Review by Geod24 — CHANGES_REQUESTED** [review]
It should probably be one of the `LINK` macro. This doesn't work for non-HTML output, plus it doesn't seem to work for DDOX: http://dtest.dlang.io/artifact/website-5fa0f90b5ecef1443a97d518df89eb487d1fef02-315c0211dd1867ae393303a4119038d9/web/library-prerelease/std/variant/max_size.html

**Comment by aG0aep6G** [comment]
The '@' is allowed there. Maybe fix DMD's URL matcher instead.

**Comment by Imperatorn** [comment]
> The '@' is allowed there. Maybe fix DMD's URL matcher instead.

That would be the proper fix yes

**Comment by Imperatorn** [comment]
> It should probably be one of the `LINK` macro. This doesn't work for non-HTML output, plus it doesn't seem to work for DDOX: http://dtest.dlang.io/artifact/website-5fa0f90b5ecef1443a97d518df89eb487d1fef02-315c0211dd1867ae393303a4119038d9/web/library-prerelease/std/variant/max_size.html

True, can try if it works with that

**Review by RazvanN7 — APPROVED** [review]

**Pull request merged**
