### PR TITLE
Minor improvements to std.csv docs

### PR DESCRIPTION
**Pull request by miham**
I fixed two grammatical errors and added parentheses in one place to make text easier to understand.

### CODE REVIEW

**Comment by Hackerpilot** [comment]
I approved your Github account with the auto-tester.

**Comment by Hackerpilot** [comment]
Auto-merge toggled on

**Comment by miham** [comment]
> I approved your Github account with the auto-tester.

What does that do (what is different than before)?

**Comment by yebblies** [comment]
[It actually tests your PRs now.](https://auto-tester.puremagic.com/pull-history.ghtml?projectid=1&repoid=3&pullid=4215)

**Comment by miham** [comment]
Thanks.

**Pull request merged**
