### PR TITLE
Add JSON Serialization/Deserialization

### PR DESCRIPTION
**Pull request by GrimMaple**

### CODE REVIEW

**Comment by CyberShadow** [comment]
Hi, was this proposal previously discussed somewhere?

**Comment by GrimMaple** [comment]
> Hi, was this proposal previously discussed somewhere?

No, not really. Why?

**Comment by CyberShadow** [comment]
A straight-forward implementation of serialization in D is not too difficult and there are quite a few implementations in D already, whether on top of std.json or as part of serialization libraries. I think the main difficulty with adding this (and anything else) to the standard library is coming up with a set of decisions to guide implementations which are the least disagreeable to everyone (for instance in your proposal I can see the argument about whether `@jsonField` is needed at all, or if the interface needs to be generalized to support other serialization formats). D developers who have implemented serialization frameworks will also be happy to talk about issues emerging from real-world use of such libraries, such as const/immutable data types and the emergent approaches to construct vs. populate D values, the need for partial (de)serialization, and transformations (defined in the type or at the top-level (de)serialization call).

I think the most recent attempt to study and overcome these questions was by @FeepingCreature. I'm not sure, was there a DConf talk about it?

So, on one hand, "The Best is the Enemy of Good", and on the other hand, there is e.g. `std.sumtype` which was initially published as a Dub package, and only after being proven by real-world use it was submitted for inclusion to Phobos.

**Comment by FeepingCreature** [comment]
I have a dconf talk about [my serialization lib](https://github.com/funkwerk-mobility/serialized) [here](https://www.youtube.com/watch?v=lMf-nOAnic8). Though it's a bit specialcase because we rely on [boilerplate](https://github.com/funkwerk-mobility/boilerplate/) to query a canonical list of constructor parameters for every datatype, and also we really want separation of type definition and encoding definition for ideological reasons. :)

**Comment by GrimMaple** [comment]
> A straight-forward implementation of serialization in D is not too difficult and there are quite a few implementations in D already, whether on top of std.json or as part of serialization libraries. I think the main difficulty with adding this (and anything else) to the standard library is coming up with a set of decisions to guide implementations which are the least disagreeable to everyone (for instance in your proposal I can see the argument about whether `@jsonField` is needed at all, or if the interface needs to be generalized to support other serialization formats). D developers who have implemented serialization frameworks will also be happy to talk about issues emerging from real-world use of such libraries, such as const/immutable data types and the emergent approaches to construct vs. populate D values, the need for partial (de)serialization, and transformations (defined in the type or at the top-level (de)serialization call).
> 
> I think the most recent attempt to study and overcome these questions was by @FeepingCreature. I'm not sure, was there a DConf talk about it?
> 
> So, on one hand, "The Best is the Enemy of Good", and on the other hand, there is e.g. `std.sumtype` which was initially published as a Dub package, and only after being proven by real-world use it was submitted for inclusion to Phobos.

I have literally no idea what to do with this information, or how to respond to it ¯\_(ツ)_/¯

**Comment by CyberShadow** [comment]
Well, ultimately the authoritative decision of what can get added to Phobos is done by @atilaneves.

I am not him, but I think the path forward here would be to discuss this with the community on the forum, maybe put this as a Dub package which extends std.json so people can try it out, and if there's community consensus that this is a good direction to go forward in then submit it for inclusion and review.

**Comment by maxhaton** [comment]
One suggestion might be to have serialisation UDAs be a generic thing separate to std.json, that way libraries can standardize on them a little

**Comment by Herringway** [comment]
> One suggestion might be to have serialisation UDAs be a generic thing separate to std.json, that way libraries can standardize on them a little

This would simplify dependencies for a few of my libraries. I'm definitely in favour of that.

**Comment by GrimMaple** [comment]
> Well, ultimately the authoritative decision of what can get added to Phobos is done by @atilaneves.
> 
> I am not him, but I think the path forward here would be to discuss this with the community on the forum, maybe put this as a Dub package which extends std.json so people can try it out, and if there's community consensus that this is a good direction to go forward in then submit it for inclusion and review.

Realistically, if you exclude unittests and private convenience code, this is about a 100 LOC change. 100 LOCs don't feel worthy of having a discussion in the first place

> One suggestion might be to have serialisation UDAs be a generic thing separate to std.json, that way libraries can standardize on them a little

This would require designing `std.serialization`, which goes far beyound what my intentions are with this code, This considerably small change makes `std.json` a lot more usable for a little cost. Even if `std.serialization` comes to be, this code can be easily adjusted to use new UDAs, and these ones can be easily deprecated

**Comment by GrimMaple** [comment]
So what do I need to do from here? Community post? Extract this into `std.serialization`?

**Comment by CyberShadow** [comment]
> So what do I need to do from here? Community post?

Yes, a forum thread is a good way to get more feedback.

**Comment by CyberShadow** [comment]
> Realistically, if you exclude unittests and private convenience code, this is about a 100 LOC change. 100 LOCs don't feel worthy of having a discussion in the first place

On one extreme we have very large additions that need a lot of effort to be scrutinized from all sides. On the other extreme, we have proposals for trivial additions - one-liners, small helper functions, etc., these are also rejected on the basis of being too trivial.

> Even if `std.serialization` comes to be, this code can be easily adjusted to use new UDAs, and these ones can be easily deprecated

On the topic of why not just add things now and deprecate them later if they turn out to be suboptimal or a bad idea, this doesn't work in all cases. For a current example right in `std.json`, see https://forum.dlang.org/post/feudrhtxkaxxscwhhhff@forum.dlang.org. In this submission, I see e.g. that it would be difficult to deprecate the `@jsonField` UDA (and instead serialize everything like `ae.utils.json` / `vibe.data.json`) - it would have to be deprecated as a three-step process, first deprecating it and introducing something like `@jsonAll`, then removing `@jsonField` and deprecating `@jsonAll`, then finally removing `@jsonAll`.

**Comment by GrimMaple** [comment]
I think I will be closing this for now. I'll report to the forums once I rewrite this into `std.serialization`

**Pull request closed without merging**
