### PR TITLE
Add INoGcAllocator

### PR DESCRIPTION
**Pull request by atilaneves**

### CODE REVIEW

**Comment by JackStouffer** [comment]
This growth in the number of nessesary interfaces is why I don't think this is the right way to go with allocator code.

Far better to have the allocator type be in the template and have the attributes be inferred.

**Comment by radcapricorn** [comment]
Not necessarily the allocator type itself. See the (current) end of this [discussion](https://forum.dlang.org/post/pwrlcxbkonpwxczvdixw@forum.dlang.org). We could use a set of abstract "traits" as a parameter, and generate the appropriate interface based on that.

**Comment by MetaLang** [comment]
What's the status of this? Is there any intention to go ahead with it? Otherwise we should close it.

**Comment by JackStouffer** [comment]
I'm going to close. Feel free to ping me if there's an argument for this solution.

**Pull request closed without merging**
