### PR TITLE
Remove deprecated string methods from the book table

### PR DESCRIPTION
**Pull request by JackStouffer**
Once more

### CODE REVIEW

**Comment by JackStouffer** [comment]
I can't seem to git rid of those extra commits with `rebase -i`. Any ideas?

**Comment by quickfur** [comment]
````
git rebase -i  master
# inside editor: change "pick" to "squash" in all except the first line
git push -f origin
````

**Comment by JackStouffer** [comment]
@quickfur Rebase the branch onto master? But this is going on stable; I don't understand.

**Comment by quickfur** [comment]
Sorry, that was only meant as an example. Obviously, you want to rebase onto whatever branch you're targeting.  The main point is that you change `pick` to `squash` in the rebase dialog so that git will squash everything into a single commit.

**Comment by JackStouffer** [comment]
I think `git rebase origin/stable` did the trick

**Pull request merged**
