### PR TITLE
Fix issue 16432 - JSON incorrectly parses to string

### PR DESCRIPTION
**Pull request by wilzbach**
The entire `json` module seems to require a bit of love - though I am still hoping for [std.data.json](https://github.com/s-ludwig/std_data_json)

### CODE REVIEW

**Comment by wilzbach** [comment]
Great it seems that the floating point behavior on Win32_64 is different to all other machines and architectures (yep - even Win32). This could be due to a different C runtime which provides `snprintf` which is used by `formattedWrite` in `std.format`.
If someone has a 64-bit Windows machine, it would be great to know what the following yields:

```d
import std.format, std.stdio;
format("%.18g", 1e18 - 65).writeln;
format("%.18g", 1e18 - 64).writeln;
```

**Comment by WebDrake** [comment]
@wilzbach why not just add in a temporary patch which does the `writeln`s in the unittests, then check the auto-tester's console output? Or include the formatted string in the `assert` error message?

**Comment by BBasile** [comment]
The fix looks OK. You might be  interested to see that someone has hit the same problem precision in another [bug fix](https://github.com/dlang/phobos/pull/4345). So just choose better numbers for the unittests (i.e playing with minima/maxima here is a bad idea).

**Comment by BBasile** [comment]
This is why Grisu or RYU would be needed. These small differences due to different standard C library printf would be fixed for good.

**Comment by berni44** [comment]
> Great it seems that the floating point behavior on Win32_64 is different to all other machines and architectures (yep - even Win32). This could be due to a different C runtime which provides `snprintf` which is used by `formattedWrite` in `std.format`.
> If someone has a 64-bit Windows machine, it would be great to know what the following yields:
> 
> ```d
> import std.format, std.stdio;
> format("%.18g", 1e18 - 65).writeln;
> format("%.18g", 1e18 - 64).writeln;
> ```

Meanwhile `snprintf` is removed for `%g` (at least for `double` and `float`). Unfortunately this is exactly the gap between %e-like and %f-like output, which may still differ between different computers. The reason for this is the way D handles floating point math (internal promotion to real) and the fact, that floating point math might differ slightly, depending on the way the calculations are optimized by the compiler. To avoid this, a software floating point unit with predictable results would be needed, IMHO an overkill. See #7836 for more on this.

**Comment by RazvanN7** [comment]
Closing in favor of the newer PR.

**Pull request closed without merging**
