### PR TITLE
Update interfaces.d [rebased to stable]

### PR DESCRIPTION
**Pull request by wilzbach**
See https://github.com/dlang/phobos/pull/5901

CC @Dashster

### CODE REVIEW

**Comment by JackStouffer** [comment]
On my phone atm but the new version looks incorrect 
216b56af-4197-457d-8f38-f289a8299663

**Comment by Dashster** [comment]
Sorry, it looks like my requested change was incomplete. 

Line 46 in the original file, 47 in the changed file is:

"Convenience function for creating an $(D OutputRangeObject) with a base"

I believe it should have a "$(TD" prefixed:

"$(TD Convenience function for creating an $(D OutputRangeObject) with a base"

Also, line 58/59 

"$(TD Returns the interface type that best matches the range.)"

has a closing parentheses at the end that I think should be removed as there is one for that purpose as part of the next line.

**Comment by schveiguy** [comment]
@Dashster thx, added your suggestion. We'll see how it looks.

**Comment by schveiguy** [comment]
I see a stray closing parenthesis, will investigate...

**Comment by schveiguy** [comment]
> Also, line 58/59

oops, didn't see this at first, so your suggestions were complete after all :) Thanks @Dashster

**Pull request merged**
