### PR TITLE
[trivial] Fix imports in std.numeric

### PR DESCRIPTION
**Pull request by JackStouffer**

### CODE REVIEW

**Comment by 9il** [comment]
Auto-merge toggled on

**Comment by 9il** [comment]
Thanks!

**Comment by ZombineDev** [comment]
Why is `enforce` used, instead of `assert`? Most of the use cases seem like logic errors.

**Comment by 9il** [comment]
> Why is enforce used, instead of assert? Most of the use cases seem like logic errors.

Yes, and they can be easily checked by users. Asserst looks better for me too for std.numeric. @ZombineDev will you open the PR?

**Comment by ZombineDev** [comment]
Yes, I will. I was just checking if my understanding is correct.

**Comment by ZombineDev** [comment]
@9il see https://github.com/dlang/phobos/pull/4688

**Pull request merged**
