### PR TITLE
std.random enhancement: overload uniform to return array of elements

### PR DESCRIPTION
**Pull request by edi33416**
Overload uniform to return an array of elements of the given type.

For example, uniform!(int[])(10) will return an array of ten uniformly generated integers between int.min and int.max.

### CODE REVIEW

**Comment by yebblies** [comment]
Wouldn't it be better to expose a range of uniform random numbers, then the user can use the standard `.take.array` to turn it into an array?  That removes the implicit use of the GC and follows phobos policy better.

This also seems to be returning the wrong type for `wchar[]`.

**Comment by andralex** [comment]
@yebblies ok, a range seems a better option. What would be a good name for it?

**Comment by wilzbach** [comment]
> @yebblies ok, a range seems a better option. What would be a good name for it?

FWIW I like the `Range` adaptor in [`mir-random`](http://docs.random.dlang.io/latest/mir_random_algorithm.html):

```
#!/usr/bin/env dub
/+
dub.sdl:
name "mir_random_example"
dependency "mir-random" version="0.1.2"
+/

void main()
{
    import mir.random.algorithm : range;
    import mir.random.engine : Random;
    import mir.random.variable : UniformVariable;
    import std.range : take;
    import std.stdio : writeln;

    auto gen = Random(42);
    auto rv = UniformVariable!int(-10, 10);

    auto uniformRange = gen.range(rv);
    uniformRange.take(3).writeln; // [10, -2, -6]
}
```

**Comment by yebblies** [comment]
`uniformRange`?

**Comment by JackStouffer** [comment]
Ping @edi33416

**Comment by edi33416** [comment]
@JackStouffer, I will rework this, addressing the comments, in the next couple of days.
Currently I am working on some university projects that are due on Monday.

**Comment by MetaLang** [comment]
Looks like @edi33416 never got back to this so I'm going to close it. @edi33416 please comment if you want me to re-open this.

**Comment by andralex** [comment]
He's on internship for the summer and will be back at it.

**Comment by andralex** [comment]
So indeed we need a `uniformRange` that returns an infinite range of items. Then to obtain an array it suffices to pipe to `.take(n).array`. @edi33416 could you work on that, thx!

**Comment by MetaLang** [comment]
ping @edi33416

**Comment by wilzbach** [comment]
Ping @edi3346 ... Again :/

Looks like we should close this.

**Comment by JackStouffer** [comment]
I rethought this and I think the best solution here is to just add an example like this

    iota(100).map!(() => uniform(0, 100)).array;

I agree with Walter’s idea that anything that can be implemented in one line shouldn’t be broken out to its own function

**Comment by quickfur** [comment]
I agree, we should not add one-liners to Phobos just because we can, it will just make Phobos bloat into a mess of redundant functions.  The ideal scenario is to provide minimal, orthogonal primitives that user code can use to build whatever they want.

**Comment by wilzbach** [comment]
Absolutely agreed. We just need to make sure that all building blocks are there and easy to find :)

**Pull request closed without merging**
