### PR TITLE
Added some spaces (std.file documentation)

### PR DESCRIPTION
**Pull request by dmi7ry**
Few code formatting of the documentation's example, for more readable

### CODE REVIEW

**Comment by JackStouffer** [comment]
Squash the commits, then LGTM

**Comment by dmi7ry** [comment]
I don't know how I can squash it, bacause I did all changes using browser, I have no local copy of repository/fork, etc.

**Comment by burner** [comment]
clone your repo onto a machine, checkout the branch with the patch, squash, push changes to inet

**Comment by dmi7ry** [comment]
Done. And I hope I done it right.

**Comment by wilzbach** [comment]
Yes - you can just click on the commits tab here on github to see the list of commits in your pull request ;-)

**Comment by dmi7ry** [comment]
`auto-tester` shows errors. How it can be fixed? Need I worry about it (and to do something for fix)?

**Comment by JackStouffer** [comment]
Due to a [heisenbug](https://en.wikipedia.org/wiki/Heisenbug), std.allocator fails its tests sometimes. The failure has nothing to do with this PR.

**Comment by JackStouffer** [comment]
LGTM

**Comment by dmi7ry** [comment]
Ok, thank you.

**Comment by schveiguy** [comment]
Auto-merge toggled on

**Pull request merged**
