### PR TITLE
Simplify std.traits.isBoolean

### PR DESCRIPTION
**Pull request by n8sh**

### CODE REVIEW

**Comment by pbackus** [comment]
Buildkite failure is due to your branch missing the commits from #7678. Rebasing should fix it.

**Comment by ljmf00** [comment]
`BooleanTypeOf` check for `alias this` of type `bool`, can you do this with `T : bool` ?

```d
struct B
{
    bool val;
    alias val this;
}
struct S
{
    B b;
    alias b this;
}
```

**Comment by pbackus** [comment]
@ljmf00 This case is covered by the unit tests; take a look.

**Comment by pbackus** [comment]
Now the Buildkite failure is due to the new release of `dlang-requests` breaking the CI script.

PR here: https://github.com/dlang/ci/pull/436

**Comment by ljmf00** [comment]
> @ljmf00 This case is covered by the unit tests; take a look.

Yeah. Didn't know that `SubTypeOf` does that :+1:

**Review by ljmf00 — APPROVED** [review]

**Review by thewilsonator — APPROVED** [review]

**Pull request merged**
