### PR TITLE
Issue 15621 - std.file.rename does not allow moving files to a different drive

### PR DESCRIPTION
**Pull request by yebblies**
I don't think it's possible to unittest this without making excessive assumptions.

https://issues.dlang.org/show_bug.cgi?id=15621

### CODE REVIEW

**Comment by jmdavis** [comment]
FreeBSD (and presumably Linux, though I don't have a Linux box set up to test that on at he moment) have the same problem. When, I tried it, I got

    std.file.FileException@std/file.d(658): /home/jmdavis/foo.txt: Cross-device link

I don't know if we want to merge this without fixing that as well, since it would result in different behavior on different platforms. But aside from that issue, this looks fine to me.

**Comment by schuetzm** [comment]
Moving across drives (or filesystems on Unix) is a very different operation from a simple renaming (costs, atomicity). I'd rather not want `std.file.rename` doing this by default.

If we want to support this, it should be opt-in (a flag, or a separate function), and of course it should work on all platforms.

**Comment by yebblies** [comment]
I've never wanted rename to fail if the destination is on a different filesystem.  And it's not documented to do anything other than a full move.

**Comment by schuetzm** [comment]
It's not so much that people _want_ it to fail, but they may _expect_ it to, because they know that's how the underlying system calls work. We always use different functions if they have different runtime or memory complexities (e.g. `length` vs `walkLength`).

And if we make this change for UNIX platforms too, it would even be a breaking change, because it no longer guarantees atomicity. (That might also be true for Windows, but I don't know enough about that.)

**Comment by yebblies** [comment]
I expected something else, and the documentation doesn't specify.  These are meant to be high level file operations, so I don't see why matching a specific platform's syscalls should be a priority.

**Comment by jmdavis** [comment]
_I_ was certainly surprised when I found out that `rename` fails to move a file across file systems, and I considered it a bug the moment I found it. I just didn't take the time to report it like I should have. The documentation makes no guarantees of atomicity and says nothing about moving files across file systems. And since this a cross-platform operation, I don't know why anyone would expect it to necessarily act like a similar system function does. If you want that, then use `core` and use the actual system function.

I definitely think that `rename` should be fixed to move files across filesystems. The fact that it doesn't is easy to miss until you end up using it in production where someone happens to provide a destination directory that's on another filesystem, and *boom*. The operation fails due to an issue with the underlying implementation that the person using `rename` didn't know or care about - and certainly didn't test for, since it didn't even occur to them that it would be an issue.

**Comment by schuetzm** [comment]
Fine with me, then. But I feel the documentation should point out that it can copy, and it doesn't make guarantees about atomicity. (And it should also say what happens if you call it on a directory, or if that destination exists and is a directory, and so on.)

**Comment by jmdavis** [comment]
I would have thought that it was a given that it could copy if required. That's what happens with something like `mv`. It's really just the low-level system calls that don't work that way. As for atomicity, I confess that I don't know why anyone would expect atomicity from an operation like this.

But it's not like it hurts to make the documentation clearer. And clearly, some of us expect different behavior than others.

**Comment by yebblies** [comment]
Can anybody familiar with posix suggest an implementation that will fallback to copy?  I'll update the documentation to match.

**Comment by JakobOvrum** [comment]
I would expect atomicity. Copying has a number of caveats that renaming doesn't, which can be worked around in different ways, like whether or not to use a `.part` file and so on. `rename` as-is can probably also be expected to be fast, whether it succeeds or fails. Copying on the other hand can take a very long time.

IIRC, @andralex relies on the atomicity of `rename` in his examples of declarative programming that he uses in his talks.

How do other languages deal with copying?

I'm inclined to believe that we should leave `rename` as-is and add std.file.move which should behave like `mv`.

**Comment by jmdavis** [comment]
I'm fine with adding a `move` function (it's the more obvious name anyway) and leaving `rename` as-is so long as we're clear what `rename` does and we have a way to move files without worrying about what filesystem they're on. I confess that I have no idea how you even determine that two directories aren't no the same filesystem (at least on POSIX systems, since they don't have drive letters and allow you to mount a filesystem pretty much anywhere).

**Comment by yebblies** [comment]
I'm not keen on adding another conflicting named function to this module.

Windows is the same, since junction points can mount a drive in a directory.  There's probably some syscall to get the fs/device name for a directory.

**Comment by schuetzm** [comment]
On Posix, you'd just call `rename(2)` and if it returns `EXDEV`, you have to fallback to copying.

**Comment by 9il** [comment]
> I would expect atomicity.

+1

**Comment by wilzbach** [comment]
Can someone assign the decision to Andrei? Seems like we need a judge & final decision :/

**Comment by andralex** [comment]
Cool, I assume the Posix version already has the capability.

**Comment by braddr** [comment]
Removed the auto-merge tag since the presumption is false.
@andralex posix does not rename across disks, see the feb 2 comment from @schuetzm

**Comment by andralex** [comment]
Eh, in that case we need to get the Posix version done. An implementation with diverging capabilities on different OSs does more harm than good. @yebblies please reopen when up for it, thx!

**Comment by yebblies** [comment]
Ok, implementing the posix fallback should be easy since copy and delete are already part of this module.

**Comment by marler8997** [comment]
@yebblies 

I ran into this problem with http://github.com/marler8997/rund  It looks like you were going to modify this PR to also work on POSIX...are you able to do that and finish this PR?

**Comment by jmdavis** [comment]
> This isn't the case from what I can see. It appears that linux DOES support renaming files between filesystems/drives.

I don't have a Linux system to test this behavior at the moment, but I can guarantee that FreeBSD won't rename across filesystems, and I run into this problem fairly often. AFAIK, the only way to make this work in general is to try `rename`, and then if it fails, try to copy the file and then delete the original. But at this point, if we do something like that, I think that it should probably be a new function which is explicit about this behavior - particularly since the name `rename` carries with it certain expectations (particularly for those familiar with POSIX), and changing the current behavior could have unexpected consequences in existing code.

**Comment by jmdavis** [comment]
> Or a new flag e.g. rename!(CanCopy.Yes)(fileA, fileB)

Honestly, I'd rather have a new function, particularly since the behavior of `rename` carries with it the implication of `CanCopy.no`, and it's way more verbose to have to pass a flag for what is arguably the default behavior that many folks will want. The other nasty question here is what to do about directories. With `rename`, you can move a directory, and it's not a problem, but with a function designed to actually move a file and not just rename it, moving a directory could entail recursively copying the directory and the deleting the original. I'd be tempted to argue that we should punt on that and just add `moveFile` which only works on files and not directories.

**Comment by marler8997** [comment]
https://github.com/dlang/phobos/pull/6417

**Pull request closed without merging**
