### PR TITLE
std.digest.digest: Update deprecation comment

### PR DESCRIPTION
**Pull request by ibuclaw**

### CODE REVIEW

**Comment by MoonlightSentinel** [comment]
Already made a PR for `enforceEx`: #7283
It's currently blocked on a new vibe.d release.

**Comment by Geod24** [comment]
> It's currently blocked on a new vibe.d release.

Actually, I think it is actually blocked on a new `vibe-core` release (since Vibe.d v0.9.0 was released recently).
Will take care of that.

**Comment by Geod24** [comment]
Vibe-core release is done, so this should not be blocked anymore.

**Comment by ibuclaw** [comment]
Rebased, let's see...

**Comment by Geod24** [comment]
Oh well Vibe.d is fixed but now we need to update the dependencies of a bunch of programs

**Comment by Geod24** [comment]
```
Running DScanner
--
  | generated/dscanner-9364d6f15f4a610fda49a693dbc18608bfc701bb/dsc --config .dscanner.ini --styleCheck etc std -I.
  | posix.mak:562: recipe for target 'dscanner' failed
```

The style target is still failing, can you look into it ?
Everything else but `dub` has been fixed. I'll look into `dub` a bit later.

**Comment by Geod24** [comment]
`dub` PR has been merged, I just re-triggered Buildkite. Can you add a release note entry ?
Just a one liner is enough IMO.

**Comment by thewilsonator** [comment]
@ibuclaw CI seems stuck, can you please force push.

**Comment by Geod24** [comment]
And add the release not entry.

**Comment by ibuclaw** [comment]
> And add the release not entry.

What's the point when more than half of the functions originally in this PR have already been removed without note.

**Comment by ibuclaw** [comment]
@thewilsonator rebased.

**Comment by Geod24** [comment]
> What's the point when more than half of the functions originally in this PR have already been removed without note.

That's not an example to follow IMO.

**Comment by Geod24** [comment]
For reference, the point is to make it easier to search in release notes.

**Comment by ibuclaw** [comment]
> For reference, the point is to make it easier to search in release notes.

Well I think one of them was rndtol, but no idea what the others were by now.

**Comment by ibuclaw** [comment]
Rebased and Ping!

**Review by thewilsonator — APPROVED** [review]

**Comment by thewilsonator** [comment]
```
../.dub/packages/vibe-d-0.8.6/vibe-d/utils/vibe/internal/memory_legacy.d(9,8): Error: module `std.exception` import `enforceEx` not found, did you mean template `std.exception.enforce(E : Throwable = Exception) if (is(typeof(new E("", string.init, size_t.init)) : Throwable) || is(typeof(new E(string.init, size_t.init)) : Throwable))`?
```

**Comment by berni44** [comment]
@ibuclaw IMHO this one can be closed. All functions are meanwhile removed.

**Comment by ibuclaw** [comment]
Rebased, there's still a one-liner change remaining.

**Review by thewilsonator — APPROVED** [review]

**Pull request merged**
