### PR TITLE
Fix std.experimental.typecons omissions in Windows makefiles

### PR DESCRIPTION
**Pull request by CyberShadow**

### CODE REVIEW

**Comment by DmitryOlshansky** [comment]
Horrible windows makefiles... LGTM

**Comment by schveiguy** [comment]
Another sucky part is that we don't test windows docs. Oh well.

**Comment by schveiguy** [comment]
Auto-merge toggled on

**Comment by CyberShadow** [comment]
> Another sucky part is that we don't test windows docs. Oh well.

Working on it ;)

**Pull request merged**
