### PR TITLE
Replace `body` keyword with its replacement: `do`

### PR DESCRIPTION
**Pull request by wilzbach**
Automatic replacement with

    sed -i "s/^\([ ]*\)body/\1do/" -i **/*.d

Prompted by https://github.com/dlang/dlang.org/pull/1929:

> Even in phobos you still use body.

### CODE REVIEW

**Comment by ZombineDev** [comment]
@wilzbach we need to upgrade DScanner first.

**Comment by wilzbach** [comment]
>  we need to upgrade DScanner first.

Ok -> https://github.com/dlang/phobos/pull/5874

**Comment by ZombineDev** [comment]
@wilzbach I'm not sure, but I don't think DScanner has support for the `do` keyword (in place of `body`) yet.

**Comment by BBasile** [comment]
There's no emergency for the tools based on dparse. Once again, it's only a problem of communication. Specs have been update a too eagerly. Just updating the website should be okay, even if of course dparse needs an update too.

**Comment by wilzbach** [comment]
> @wilzbach I'm not sure, but I don't think DScanner has support for the do keyword (in place of body) yet.

Ah. I wrongly remembered seeing such a PR, but adding support for the do keyword shouldn't be too difficult and we have to do it anyways, so I gave it a quick shot:

-> https://github.com/dlang-community/libdparse/pull/180

**Comment by wilzbach** [comment]
As dlang-community/libdparse#180 was merged in light speed (thanks @BBasile !), I updated libdparse for the D-Scanner version used at Phobos (https://github.com/dlang-community/D-Scanner/pull/538) and now CircleCI is passing :tada: and this PR should be good to go :)

**Pull request merged**
