### PR TITLE
Move some deprecations along.

### PR DESCRIPTION
**Pull request by jmdavis**

### CODE REVIEW

**Comment by wilzbach** [comment]
Seems like another bug in dscanner/libdparse? The [line](https://github.com/jmdavis/phobos/blob/deprecations/std/bitmanip.d#L3660) looks fine to me..
Should we add `Expected : instead of ,` to the `travis.yml`?
Ping @Hackerpilot @CyberShadow

**Comment by quickfur** [comment]
LGTM. Why is travis ci failing?

**Comment by Hackerpilot** [comment]
I have no idea. That file parses just fine on my machine.

**Comment by Hackerpilot** [comment]
That version of dscanner that Travis uses was built with dub instead of make, so I don't have the commit hash.

**Comment by wilzbach** [comment]
> That version of dscanner that Travis uses was built with dub instead of make, so I don't have the commit hash.

I updated to 4cda805dc4a1b7725586165cdd00feb966ef2369 built with dmd.
The ldcbuild didn't work for me.
@Hackerpilot I have sent you an email with the credentials, but maybe we can get future milestone releases directly via github releases?

@jmdavis I have sent you a PR with the updated dscanner version.
https://github.com/jmdavis/phobos/pull/3

**Comment by Hackerpilot** [comment]
I grabbed a copy of this branch and the dscanner binary that Travis is using and I can't reproduce this failure.

**Comment by jmdavis** [comment]
I managed to munge my repo when trying to merge in Seb's PR to my repo with the travis changes, so I had to redo that and my changes for this - but they should be the same.

**Comment by wilzbach** [comment]
Seems like you got a typo in the version. Wasn't it 0.4-alpha?

**Comment by jmdavis** [comment]
@wilzbach It matches what you did in your PR: https://github.com/jmdavis/phobos/pull/3/files

But if it needs to be something else, I can change it.

**Comment by wilzbach** [comment]
> @wilzbach It matches what you did in your PR: https://github.com/jmdavis/phobos/pull/3/files
> But if it needs to be something else, I can change it.

Damn I shouldn't send PRs at 3am ... it's alpha_2_

-> `releases.dlang.io/dscanner/0.4.0-alpha2/dscanner`

Sorry for the inconvenience!

**Comment by jmdavis** [comment]
Okay. Updated.

**Comment by wilzbach** [comment]
Okay let's switch over and build Dscanner on Travis - doesn't take that long:

1) we need to replace the `wget release.` with

```
 - git clone https://github.com/Hackerpilot/Dscanner
 - (cd Dscanner && git checkout tags/v0.4.0-alpha2)
 - (cd Dscanner && git submodule update --init --recursive)
 - (cd Dscanner && make githash debug)
 - mv Dscanner/dsc .
 - rm -rf Dscanner
```

2) last line is `$(dsc`

[working again on my branch](https://travis-ci.org/wilzbach/phobos/builds/127808336)

entire file: https://github.com/wilzbach/phobos/blob/deprecations_travis/.travis.yml

@jmdavis Should I try again to send a proper PR?

**Comment by jmdavis** [comment]
Okay. Hopefully, I got the changes to the travis stuff right.

**Comment by wilzbach** [comment]
> I got the changes to the travis stuff right

Looks so. Thanks :)

**Comment by DmitryOlshansky** [comment]
Auto-merge toggled on

**Comment by Hackerpilot** [comment]
The debug build for D-Scanner is a really bad idea. It causes libdparse to include an insane amount of extra logging code.

**Pull request merged**
