### PR TITLE
reduce test template bloat

### PR DESCRIPTION
**Pull request by 9il**

### CODE REVIEW

**Comment by DmitryOlshansky** [comment]
How this reduces template bloat - it's only ever happening when unittesting?

**Comment by 9il** [comment]
> How this reduces template bloat - it's only ever happening when unittesting?

Yes, only for unittesting. 1 instance instead of ~40.

**Comment by DmitryOlshansky** [comment]
Okay LGTM if the unittesting was your intention

**Comment by DmitryOlshansky** [comment]
Auto-merge toggled on

**Pull request merged**
