### PR TITLE
Fix Issue 20159 - Make std.math.scalbn work in CTFE

### PR DESCRIPTION
**Pull request by n8sh**

### CODE REVIEW

**Comment by WalterBright** [comment]
Getting:
```
std\math.d(4566): Error: static assert:  `nanL == infL` is false
```
now in Azure pipelines (Windows_VisualD win32-ldc)

**Comment by WalterBright** [comment]
@n8sh please fix.

**Comment by n8sh** [comment]
That's the same problem I was seeing with FreeBSD. It seemed like CTFE didn't have 80 bit reals even though they existed at runtime. I'll try enabling the slow path for all platforms.

**Comment by n8sh** [comment]
@WalterBright PR #7155

**Pull request merged**
