### PR TITLE
treewide: rename index.d to index.dd

### PR DESCRIPTION
**Pull request by ljmf00**
Signed-off-by: Luís Ferreira <contact@lsferreira.net>

### CODE REVIEW

**Comment by RazvanN7** [comment]
Hmm, I wonder why it was called `index.d` in the first place. However, this seems to have upset the documentation tester. @CyberShadow any ideas why?

**Comment by CyberShadow** [comment]
@ljmf00 For all pull requests, it would be great if you could write a paragraph describing *why* you are making the change, and add it to the commit message.

https://www.google.com/search?q=good+commit+messages

**Comment by CyberShadow** [comment]
> @CyberShadow any ideas why?

I think this line needs to change too:
https://github.com/dlang/phobos/blob/baf6ede6de920f17df6c48aa5eac32b6ea30ca10/posix.mak#L519

**Review by thewilsonator — APPROVED** [review]

**Comment by RazvanN7** [comment]
@ljmf00 Please update this PR as suggested so that we can merge it.

**Comment by ljmf00** [comment]
> @ljmf00 Please update this PR as suggested so that we can merge it.

Done, although, it is a mess to touch those Makefile macros, so I'm not sure if I fixed it.

**Pull request merged**
