### PR TITLE
start making use of isAutodecodableString()

### PR DESCRIPTION
**Pull request by WalterBright**
I don't know why the `!isAggregate()` needs to be there, I suspect it is a mistake, but this is a refactoring not a redesign.

### CODE REVIEW

**Comment by thewilsonator** [comment]
It appears to be because https://github.com/dlang/phobos/blob/135f58080ef3126d378ce92de1e2f8c33ec3ab78/std/traits.d#L6681 a struct with an alias this to a string is considered autodecodeable.

**Comment by WalterBright** [comment]
> a struct with an alias this to a string is considered autodecodeable.

Right, but I reproduced this behavior exactly:
`autodecodeStrings && isNarrowString!R)` is identical to `isAutodecodableString!R && !isAggregateType!R`

**Comment by WalterBright** [comment]
Where is this file being generated?
```
generated/linux/debug/64/publictests/std_range_primitives.d(1108): Error: template instance `isAutodecodableString!R` template `isAutodecodableString` is not defined
```
and it should import `std.traits`

**Comment by WalterBright** [comment]
Yeah, but why does circleci fail and the other tests pass?

**Comment by thewilsonator** [comment]
I think those are the doc examples. Maybe it does doc testing?

**Comment by WalterBright** [comment]
Thanks, that's the clue I needed.

**Pull request merged**
