### PR TITLE
Revert "Sort imports in Phobos"

### PR DESCRIPTION
**Pull request by CyberShadow**
Reverts dlang/phobos#5478

Rationale:
- https://github.com/dlang/phobos/pull/5478#issuecomment-307707186
- https://github.com/dlang/phobos/pull/5478#issuecomment-307813481
- https://github.com/dlang/phobos/pull/5478#pullrequestreview-43473288

### CODE REVIEW

**Comment by CyberShadow** [comment]
I think it's fine if we enforce sorting of the module list only of top-level imports only.

**Comment by wilzbach** [comment]
> I think it's fine if we enforce sorting of the module list only of top-level imports only.

Then people would get confused as well ;-)
Why do I have to sort the top-level imports, but not within my `unittest`?

**Comment by CyberShadow** [comment]
> Then people would get confused as well ;-)
> Why do I have to sort the top-level imports, but not within my unittest?

I don't think anyone is going to be confused about not being forced to do something. Nothing is going to fail if the unittest imports *are* sorted.

**Comment by wilzbach** [comment]
> Nobody is going to be confused about not being forced to do something. Nothing is going to fail if the unittest imports are sorted.

The entire point of the normalization is that we don't need to spend time anymore on nitpicking the order of imports and we do nitpick on sorted imports.
So if we revert this, it will be a "human CI" doing the work instead of a binary/bot ...

**Comment by CyberShadow** [comment]
1. If you are "nitpicking the order of imports", then why are you not also nitpicking on the order of local variables (and other avenues of normalization)? Why are imports special?
2. Is this about order of modules or order of selective imports too?
3. It's fallacious to decide on and enforce one crappy standard which is worse than any suggestion that would make sense to a human.

**Comment by wilzbach** [comment]
> If you are "nitpicking the order of imports", then why are you not also nitpicking on the order of local variables (and other avenues of normalization)? Why are imports special?

You need to start somewhere ...

> Is this about order of modules or order of selective imports too?

Yes - didn't you check the diff / my comments to it?

>It's fallacious to decide on and enforce one crappy standard which is worse than any suggestion that would make sense to a human.

Because It makes sense in almost all cases and is thus easy to automate and is thus one thing less that drains a review.

**Comment by CyberShadow** [comment]
> You need to start somewhere ...

No. You need to STOP somewhere. Enforcing proper formatting and normalization at the cost of readability are on opposite sides of the line.

> Yes - didn't you check the diff / my comments to it?

That's not what I meant. Do you actually waste time nitpicking on the order of *selective* imports? That does seems like a waste of time, with the other obvious answer to not do it.

> Because It makes sense in almost all cases

[I don't think so](https://github.com/dlang/phobos/pull/5478#pullrequestreview-43473288).

**Comment by CyberShadow** [comment]
Superseded by https://github.com/dlang/phobos/pull/5481

**Pull request closed without merging**
