### PR TITLE
remove useless CT branch

### PR DESCRIPTION
**Pull request by 9il**

### CODE REVIEW

**Comment by wilzbach** [comment]
nice catch - shouldn't we call `save` if it's a ForwardRange? Or is this automatically done thanks to value-copying?

**Comment by 9il** [comment]
> nice catch - shouldn't we call save if it's a ForwardRange? Or is this automatically done thanks to value-copying?

No need. User can call save before `find` if he wants

**Comment by wilzbach** [comment]
> No need. User can call save before find if he wants

Alrighty, let's get rid of this then :)

**Comment by DmitryOlshansky** [comment]
To me this looks as some sort of optimization, so if it's not let's remove it

**Comment by 9il** [comment]
> To me this looks as some sort of optimization, so if it's not let's remove it

It definitely not an optimization

**Comment by wilzbach** [comment]
> It definitely not an optimization

I agree ;-)

**Comment by DmitryOlshansky** [comment]
Going to merge since the code never checked for a forward range to being with, and AFAIK it's the policy that saving a range is a user's task.

**Comment by DmitryOlshansky** [comment]
Auto-merge toggled on

**Comment by wilzbach** [comment]
autotester is yielding random errors:

```
****** FAIL release64 std.file
core.exception.AssertError@std/file.d(517): unittest failure
----------------
??:? _d_unittest [0x53b4624]
??:? void std.file.__unittest_fail(int) [0x400fa52]
??:? void std.file.__unittestL505_9() [0x3fd9d9a]
??:? void std.file.__modtest() [0x400f6bf]
??:? _init [0x40142d]
??:? runModuleUnitTests [0x53b5077]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x53e3f0a]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x53e3ea7]
??:? _d_run_main [0x53e3e0b]
??:? pure nothrow @nogc @safe long core.time.convert!("hnsecs", "msecs").convert(long) [0x401685]
??:? _init [0x40121d]
??:? ??? [0x533fff]
gmake[1]: *** [unittest/std/file.run] Error 1
gmake[1]: *** Waiting for unfinished jobs....
timelimit -t 60  generated/freebsd/debug/64/unittest/test_runner std.getopt
****** FAIL debug64 std.file
core.exception.AssertError@std/file.d(246): unittest failure
```

**Pull request merged**
