### PR TITLE
[BOOKTABLES]: Add BOOKTABLE to std.uni

### PR DESCRIPTION
**Pull request by wilzbach**
image

I am not really sure here what the best way to go is. The current documentation already contains a good introduction, which is pretty much destroyed by the quickIndex. 

### The current documentation looks like this:

image

https://dlang.org/phobos/std_uni.html

So we could also try to (a) include the missing functions in the "text-based" overview or (b) use the full-text information in a table overview as well.

Moreover for some symbols I wasn't entirely sure how to categorize them, e.g. `Grapheme` was a tough one.

### CODE REVIEW

**Comment by JackStouffer** [comment]
This is how the table appears on Chrome macOS

screen shot 2017-03-04 at 9 46 01 pm

The left column isn't wide enough for some reason

**Comment by wilzbach** [comment]
> The left column isn't wide enough for some reason

Indeed, that's really weird. On Linux with FF, Chrome/Chromium and Opera it looks as expected (and photographed above).

Does this only occur for these two PRs or the other `CHEATSHEET` table as well?
https://dlang.org/phobos-prerelease/

**Comment by JackStouffer** [comment]
I see this happening on std.ascii and std.path, but not on std.conv and std.regex

**Comment by quickfur** [comment]
How about changing "Lower/Upper-case" to "Casing"?

**Comment by quickfur** [comment]
Also, the heading "Functions" is misleading for some symbols like `NFC`, which are enum values.

**Comment by quickfur** [comment]
ping @wilzbach 

Let's get this PR cleaned up and merged, guys.  Doc improvements shouldn't be languishing in the queue for this long.

**Comment by wilzbach** [comment]
> How about changing "Lower/Upper-case" to "Casing"?

Good idea!

> Also, the heading "Functions" is misleading for some symbols like NFC, which are enum values.

"Functions" is currently somehow the default, how about using "Symbols"?

> Probably the enum values can be removed from the table, since the enum definition itself is already included. But still, "Functions" is misleading.

Yeah I included the enum values just for completeness, because they are part of the auto-generated documentation.

> Let's get this PR cleaned up and merged, guys. Doc improvements shouldn't be languishing in the queue for this long.

+1 - unfortunately I can't reproduce the UI issues on Linux, so it's a bit hard for me to push this forward.

**Comment by JackStouffer** [comment]
I think a change I asked for from Sönke on the website fixed the overlapping issue.

While the link color and squishing problem on ddox isn't perfect, it's better than the current situation.

**Pull request merged**
