### PR TITLE
Mark etc.c.odbc as deprecated

### PR DESCRIPTION
**Pull request by ibuclaw**
Publicly import core.sys.windows.sql instead.

Set removal date for one year in the future (February 2020).

### CODE REVIEW

**Comment by CyberShadow** [comment]
CC @andralex as the original author (https://github.com/dlang/phobos/pull/3398).

**Comment by John-Colvin** [comment]
Won’t this immediately break things for unixodbc or iodbc users on non-windows?

**Comment by ibuclaw** [comment]
All have `extern (Windows):` guards at the top of the modules. So non-windows are excluded anyway.

**Comment by wilzbach** [comment]
(rebased to master to fix the CIs)

**Comment by RazvanN7** [comment]
@ibuclaw Should we go on with this deprecation or remove it directly? Either way, can you update the deprecation comment so we can get this in?

**Comment by ibuclaw** [comment]
Bumped deprecation date to 2022, two years after the original remove date, _sigh_.

**Review by RazvanN7 — APPROVED** [review]

**Pull request merged**
