### PR TITLE
EASY: Companion to https://github.com/dlang/druntime/pull/3167/

### PR DESCRIPTION
**Pull request by andralex**
Propagate the changes in https://github.com/dlang/druntime/pull/3167 to phobos

### CODE REVIEW

**Comment by andralex** [comment]
One of this and https://github.com/dlang/druntime/pull/3167 must be force-merged because both are necessary to make the build work.

**Comment by Geod24** [comment]
@andralex : You don't have to break the build. You can just do an intermediate PR in DRuntime which exposes the templated interface, get this merged, then finish the druntime one.
Also please provide a proper commit title / message, something that can be understood without fetching additional context.

**Comment by andralex** [comment]
> @andralex : You don't have to break the build. You can just do an intermediate PR in DRuntime which exposes the templated interface, get this merged, then finish the druntime one.
> Also please provide a proper commit title / message, something that can be understood without fetching additional context.

Yah, crossed my mind too... think it's necessary?

**Comment by schveiguy** [comment]
> think it's necessary?

In fact, we may have to. I don't have the ability to merge with failing tests.

**Comment by andralex** [comment]
I'l force merge this and the other. Fingers crossed.

**Comment by Geod24** [comment]
> Yah, crossed my mind too... think it's necessary?

Yes.

**Comment by andralex** [comment]
@Geod24 let's see how this fares, if anything goes wrong I'll put in the extra overload temporarily.

**Comment by Geod24** [comment]
```
std/conv.d(5793): Error: template `core.internal.string.signedToTempString` cannot deduce function from argument types `!()(const(ulong), char[20], int)`, candidates are:
../druntime/import/core/internal/string.d(111):        `signedToTempString(uint radix = 10)(long value, return scope char[] buf)`
../druntime/import/core/internal/string.d(127):        `signedToTempString(uint radix = 10)(long value)`
std/conv.d(5798): Error: template `core.internal.string.unsignedToTempString` cannot deduce function from argument types `!()(const(ulong), char[20], int)`, candidates are:
../druntime/import/core/internal/string.d(31):        `unsignedToTempString(uint radix = 10)(ulong value, return scope char[] buf)`
../druntime/import/core/internal/string.d(77):        `unsignedToTempString(uint radix = 10)(ulong value)`
std/stdio.d(1559): Error: template instance `std.conv.toTextRange!(const(ulong), LockingTextWriter)` error instantiating
std/experimental/allocator/building_blocks/stats_collector.d(636):        instantiated from here: `write!(string, string, const(ulong), char)`
generated/linux/debug/64/publictests/std_experimental_allocator_building_blocks_stats_collector.d(773):        instantiated from here: `reportStatistics!(File)`
posix.mak:636: recipe for target 'std/experimental/allocator/building_blocks/stats_collector.publictests' failed
make: *** [std/experimental/allocator/building_blocks/stats_collector.publictests] Error 1
```

**Comment by andralex** [comment]
@Geod24 I'd expect the tests to restart once both the druntime and phobos PRs are in, right?

**Comment by Geod24** [comment]
Restarting the tests won't help, the failure is in `std.conv`, and as shown in the revert, this is still in master.

**Comment by schveiguy** [comment]
OK, we need a redo of this now.

**Comment by schveiguy** [comment]
Redo was #7568

**Pull request merged**
