### PR TITLE
Remove all package wide std.algorithm imports from Phobos

### PR DESCRIPTION
**Pull request by JackStouffer**
That's all of them!

I also added a style check to make sure we never add on more

### CODE REVIEW

**Comment by 9il** [comment]
Do you think we need separate commits?

**Comment by JackStouffer** [comment]
I don't know, just a personal preference. I can squish them if you want.

**Comment by 9il** [comment]
Yes please

**Comment by JackStouffer** [comment]
@9il done

**Comment by 9il** [comment]
Auto-merge toggled on

**Pull request merged**
