### PR TITLE
Add unittests for 100% coverage of CustomFloat

### PR DESCRIPTION
**Pull request by berni44**

### CODE REVIEW

**Comment by thewilsonator** [comment]
Any reason the unittests can't all be `@safe`?

**Comment by berni44** [comment]
> Any reason the unittests can't all be `@safe`?

`assertThrown` is `@system`. I could wrap it with `@trusted` though; would that be better?

**Comment by thewilsonator** [comment]
Ah never mind.

**Comment by thewilsonator** [comment]
Auto-merge toggled on

**Comment by thewilsonator** [comment]
Auto-merge toggled off

**Comment by thewilsonator** [comment]
Auto-merge toggled on

**Pull request merged**
