### PR TITLE
Issue 17127 - bad example code for std.concurrency.Generator

### PR DESCRIPTION
**Pull request by wilzbach**
Split-up of https://github.com/dlang/phobos/pull/5603 to see which test is failing for 32-bit on the auto-tester.

### CODE REVIEW

**Comment by edi33416** [comment]
Any updates on this? I strongly agree that we should have working examples in the docs.

**Comment by wilzbach** [comment]
Oh this example fails on 32-bit and my distro doesn't even support 32-bit anymore, so building a debug version of dmd, druntime and phobos is a bit of effort for which I hadn't had the time so far (and probably won't in the near future).
@edi33416 interested to dive into this?

**Comment by edi33416** [comment]
@wilzbach I'm going to spin-up a 32bit machine and give it a go

**Comment by wilzbach** [comment]
Cool! On a typical Linux distro, `gcc-multilib` is all you need, but be careful to use `AUTO_BOOTSTRAP=1` when building DMD.

**Comment by jercaianu** [comment]
@edi33416  @wilzbach 
This is failing because the test contains a subtle bug.
`receiveOnly` expects a `size_t`, but the `Generator` is generating `ints`, causing `receiveOnly` to silently throw a `MessageMismatch` exception.

Either catch the exception, or change the `Generator` type to `uint`.

**Pull request merged**
