### PR TITLE
Fix broken links

### PR DESCRIPTION
**Pull request by CyberShadow**
Needs https://github.com/dlang/dlang.org/pull/1802.

### CODE REVIEW

**Comment by RazvanN7** [comment]
There are some broken links also in std.algorithm.searching. The one's of seen:

-> minCount/maxCount
-> minPos/maxPos
-> minIndex/maxIndex

The link to isInputRange is broken. I looked on the sources and the links that work are identically declared as those that don't

**Comment by CyberShadow** [comment]
These only fix links to non-existing pages (404s). Links to non-existing anchors will come in a later PR

**Comment by CyberShadow** [comment]
Seems like this broke some DDox links (I forgot to define REF1, MREF1 etc. for std-ddox.ddoc).

**Comment by CyberShadow** [comment]
> Seems like this broke some DDox links

Oh, just the one link.

**Pull request merged**
