### PR TITLE
Fix issue 21000 - allow use of std{in,out,err} with -preview=noshared…

### PR DESCRIPTION
**Pull request by atilaneves**
…access

### CODE REVIEW

**Comment by atilaneves** [comment]
I don't know how to prove this works other than to say I tried it manually. I can't add the preview flag since this particular issue was covering up many more.

**Comment by CyberShadow** [comment]
There are some stand-alone tests in the `test` directory, maybe that would be a good place?

**Review by dkorpel — APPROVED** [review]

**Comment by RazvanN7** [comment]
ping @atilaneves

**Comment by RazvanN7** [comment]
There are 2 ways we can go about this:

(1) add a test in the tests directory and compile it with `-preview=nosharedaccess`; this seems like an unpopular path since there are only 3 tests in that directory.

(2) continue fixing this up and put this test in a unittest once we are able to compile phobos with -preview=nosharedaccess`; I am inclined to go down this route as long as you are pursuing it @atilaneves .

Let me know what you prefer.

**Comment by atilaneves** [comment]
For now I'd prefer to put it in the test directory, but I don't see anything in the Makefile that runs those except for explicitly running the betterC tests.

TBH I think that this is overkill given that this is necessary and I'd be in favour of merging as-is.

**Pull request merged**
