### PR TITLE
Move checkedint out of experimental

### PR DESCRIPTION
**Pull request by atilaneves**

### CODE REVIEW

**Review by wilzbach — CHANGES_REQUESTED** [review]
I don't think this module is ready. It has received very few improvements since it has been added.

See e.g. 
- https://issues.dlang.org/show_bug.cgi?id=21169
- https://issues.dlang.org/show_bug.cgi?id=21169
- https://issues.dlang.org/show_bug.cgi?id=18471


Here's my simple litmus test on whether it can be moved out of experimental:

```d
import std.experimental.checkedint;
void foo() @safe pure @nogc nothrow
{
   auto x = checked(5) + 7;
}
```

**Comment by n8sh** [comment]
> Here's my simple litmus test on whether it can be moved out of experimental:
> 
> ```d
> import std.experimental.checkedint;
> void foo() @safe pure @nogc nothrow
> {
>    auto x = checked(5) + 7;
> }
> ```

* `@safe`: [Fixed for 2.097.](https://issues.dlang.org/show_bug.cgi?id=18024).
* `pure`:  The default behavior on overflow is Abort which prints a message to stderr then assert(0). Purity could be achieved by changing the default hook from `Abort` to `Throw` (which would obviously preclude `nothrow`) or by changing `Abort` to instead of explicitly writing to stderr use `assert(0, message)`. IIRC some compilation settings might result in assertion messages being discarded.
* `@nogc`, `nothrow`: The basic problem is `std.stdio.File` throws an exception on failure to write. A more easily avoided problem is use of `std.format` to generate the error message.

I agree that checkedint by default should be usable in `@safe` code. It's less obvious to me that the default error-handling behavior needs to be `nothrow` and `@nogc`.

**Comment by wilzbach** [comment]
> It's less obvious to me that the default error-handling behavior needs to be nothrow and @nogc.

It was about the fact that you can.
Last time I checked you couldn't define a hook that is nothrow and @nogc (the attributes weren't forwarded).

**Comment by n8sh** [comment]
> Last time I checked you couldn't define a hook that is nothrow and `@nogc` (the attributes weren't forwarded).

If so then that specific problem has since been fixed. The following code compiles from 2.074.1 onward: https://run.dlang.io/is/aDx1Xs
```d
// Hook that ignores all problems.
struct Ignore
{
@nogc nothrow pure @safe static:
    Dst onBadCast(Dst, Src)(Src src) { return cast(Dst) src; }
    Lhs onLowerBound(Rhs, T)(Rhs rhs, T bound) { return cast(T) rhs; }
    T onUpperBound(Rhs, T)(Rhs rhs, T bound) { return cast(T) rhs; }
    bool hookOpEquals(Lhs, Rhs)(Lhs lhs, Rhs rhs) { return lhs == rhs; }
    int hookOpCmp(Lhs, Rhs)(Lhs lhs, Rhs rhs) { return (lhs > rhs) - (lhs < rhs); }
    typeof(~Lhs()) onOverflow(string x, Lhs)(ref Lhs lhs) { return mixin(x ~ "lhs"); }
    typeof(Lhs() + Rhs()) onOverflow(string x, Lhs, Rhs)(Lhs lhs, Rhs rhs)
    {
        static if (x == "/")
            return typeof(lhs / rhs).min;
        else
            return mixin("lhs" ~ x ~ "rhs");
    }
}

void main() @nogc nothrow pure @safe
{
    import std.experimental.checkedint;
    auto x = checked!Ignore(5) + 7;
}
```

**Comment by RazvanN7** [comment]
@atilaneves care for a rebase? If all tests pass, we can get this in.

**Comment by RazvanN7** [comment]
Buildkite is failing because there are style warnings:

```
std/checkedint.d(240:10)[warn]: Variable x is never modified and could have been declared const or immutable.
--
  | std/checkedint.d(241:10)[warn]: Variable y is never modified and could have been declared const or immutable.
  | std/checkedint.d(261:8)[warn]: Template parameters T isn't documented in the `Params` section.
  | std/checkedint.d(261:8)[warn]: Template parameters Hook isn't documented in the `Params` section.
  | std/checkedint.d(261:8)[warn]: Public declaration 'Checked' has no documented example.
  | std/checkedint.d(292:10)[warn]: A public function needs to contain a `Returns` section.
  | std/checkedint.d(296:14)[warn]: Variable x is never modified and could have been declared const or immutable.
  | std/checkedint.d(320:32)[warn]: Public declaration 'min' is undocumented.
  | std/checkedint.d(325:32)[warn]: Public declaration 'max' is undocumented.
  | std/checkedint.d(347:14)[warn]: Variable a is never modified and could have been declared const or immutable.
  | std/checkedint.d(349:14)[warn]: Variable b is never modified and could have been declared const or immutable.
  | std/checkedint.d(356:17)[warn]: Parameter rhs isn't documented in the `Params` section.
  | std/checkedint.d(356:17)[warn]: A public function needs to contain a `Returns` section.
  | std/checkedint.d(378:25)[warn]: Variable b is never modified and could have been declared const or immutable.
  | std/checkedint.d(432:7)[warn]: Methods 'opCmp', 'toHash', 'opEquals', 'opCast', and/or 'toString' are non-const.
  | std/checkedint.d(432:7)[warn]: Template parameters U isn't documented in the `Params` section.
  | std/checkedint.d(432:7)[warn]: Template parameters _ isn't documented in the `Params` section.
  | std/checkedint.d(432:7)[warn]: A public function needs to contain a `Returns` section.
  | std/checkedint.d(485:10)[warn]: Methods 'opCmp', 'toHash', 'opEquals', 'opCast', and/or 'toString' are non-const.
  | std/checkedint.d(485:10)[warn]: Parameter rhs isn't documented in the `Params` section.
  | std/checkedint.d(485:10)[warn]: Template parameters _ isn't documented in the `Params` section.
  | std/checkedint.d(485:10)[warn]: A public function needs to contain a `Returns` section.
  | std/checkedint.d(541:14)[warn]: Variable a is never modified and could have been declared const or immutable.
  | std/checkedint.d(568:12)[warn]: A public function needs to contain a `Returns` section.
  | std/checkedint.d(596:12)[warn]: Template parameters _ isn't documented in the `Params` section.
  | std/checkedint.d(643:10)[warn]: Template parameters Char isn't documented in the `Params` section.
  | std/checkedint.d(676:10)[warn]: Parameter rhs isn't documented in the `Params` section.
  | std/checkedint.d(676:10)[warn]: Template parameters _ isn't documented in the `Params` section.
  | std/checkedint.d(676:10)[warn]: A public function needs to contain a `Returns` section.
  | std/checkedint.d(701:10)[warn]: Parameter rhs isn't documented in the `Params` section.
  | std/checkedint.d(701:10)[warn]: Template parameters U isn't documented in the `Params` section.
  | std/checkedint.d(701:10)[warn]: Template parameters Hook1 isn't documented in the `Params` section.
  | std/checkedint.d(701:10)[warn]: Template parameters _ isn't documented in the `Params` section.
  | std/checkedint.d(751:14)[warn]: Variable a is never modified and could have been declared const or immutable.
  | std/checkedint.d(798:10)[warn]: Template parameters op isn't documented in the `Params` section.
  | std/checkedint.d(798:10)[warn]: Template parameters _ isn't documented in the `Params` section.
  | std/checkedint.d(798:10)[warn]: A public function needs to contain a `Returns` section.
  | std/checkedint.d(811:20)[warn]: An assert should have an explanatory message
  | std/checkedint.d(812:18)[warn]: Variable overflow is never modified and could have been declared const or immutable.
  | std/checkedint.d(823:17)[warn]: Template parameters op isn't documented in the `Params` section.
  | std/checkedint.d(862:14)[warn]: Variable a is never modified and could have been declared const or immutable.
  | std/checkedint.d(886:10)[warn]: Parameter rhs isn't documented in the `Params` section.
  | std/checkedint.d(886:10)[warn]: Template parameters op isn't documented in the `Params` section.
  | std/checkedint.d(886:10)[warn]: A public function needs to contain a `Returns` section.
  | std/checkedint.d(893:10)[warn]: Parameter rhs isn't documented in the `Params` section.
  | std/checkedint.d(893:10)[warn]: Template parameters op isn't documented in the `Params` section.
  | std/checkedint.d(902:16)[warn]: An assert should have an explanatory message
  | std/checkedint.d(921:18)[warn]: Variable overflow is never modified and could have been declared const or immutable.
  | std/checkedint.d(934:10)[warn]: Parameter rhs isn't documented in the `Params` section.
  | std/checkedint.d(934:10)[warn]: Template parameters op isn't documented in the `Params` section.
  | std/checkedint.d(934:10)[warn]: Template parameters U isn't documented in the `Params` section.
  | std/checkedint.d(934:10)[warn]: Template parameters Hook1 isn't documented in the `Params` section.
  | std/checkedint.d(940:10)[warn]: Parameter rhs isn't documented in the `Params` section.
  | std/checkedint.d(940:10)[warn]: Template parameters op isn't documented in the `Params` section.
  | std/checkedint.d(940:10)[warn]: Template parameters U isn't documented in the `Params` section.
  | std/checkedint.d(940:10)[warn]: Template parameters Hook1 isn't documented in the `Params` section.
  | std/checkedint.d(1013:10)[warn]: Parameter lhs isn't documented in the `Params` section.
  | std/checkedint.d(1013:10)[warn]: Template parameters op isn't documented in the `Params` section.
  | std/checkedint.d(1013:10)[warn]: A public function needs to contain a `Returns` section.
  | std/checkedint.d(1020:10)[warn]: Parameter lhs isn't documented in the `Params` section.
  | std/checkedint.d(1020:10)[warn]: Template parameters op isn't documented in the `Params` section.
  | std/checkedint.d(1048:18)[warn]: Variable overflow is never modified and could have been declared const or immutable.
  | std/checkedint.d(1116:16)[warn]: An assert should have an explanatory message
  | std/checkedint.d(1194:19)[warn]: Parameter value isn't documented in the `Params` section.
  | std/checkedint.d(1194:19)[warn]: Template parameters Hook isn't documented in the `Params` section.
  | std/checkedint.d(1194:19)[warn]: A public function needs to contain a `Returns` section.
  | std/checkedint.d(1240:8)[warn]: Public declaration 'Abort' has no documented example.
  | std/checkedint.d(1257:9)[warn]: Template parameters Dst isn't documented in the `Params` section.
  | std/checkedint.d(1260:9)[warn]: An assert should have an explanatory message
  | std/checkedint.d(1280:9)[warn]: An assert should have an explanatory message
  | std/checkedint.d(1286:9)[warn]: An assert should have an explanatory message
  | std/checkedint.d(1307:14)[warn]: Variable error is never modified and could have been declared const or immutable.
  | std/checkedint.d(1312:13)[warn]: An assert should have an explanatory message
  | std/checkedint.d(1339:14)[warn]: Variable error is never modified and could have been declared const or immutable.
  | std/checkedint.d(1344:13)[warn]: An assert should have an explanatory message
  | std/checkedint.d(1366:9)[warn]: An assert should have an explanatory message
  | std/checkedint.d(1372:9)[warn]: An assert should have an explanatory message
  | std/checkedint.d(1407:9)[warn]: Public declaration is undocumented.
  | std/checkedint.d(1428:16)[warn]: An instance of `CheckFailure` is thrown but not documented in the `Throws` section
  | std/checkedint.d(1428:16)[warn]: Template parameters Dst isn't documented in the `Params` section.
  | std/checkedint.d(1448:14)[warn]: An instance of `CheckFailure` is thrown but not documented in the `Throws` section
  | std/checkedint.d(1478:14)[warn]: Variable error is never modified and could have been declared const or immutable.
  | std/checkedint.d(1511:14)[warn]: Variable error is never modified and could have been declared const or immutable.
  | std/checkedint.d(1535:27)[warn]: An instance of `CheckFailure` is thrown but not documented in the `Throws` section
  | std/checkedint.d(1651:14)[warn]: Variable error is never modified and could have been declared const or immutable.
  | std/checkedint.d(1665:14)[warn]: Variable x is never modified and could have been declared const or immutable.
  | std/checkedint.d(1690:14)[warn]: Variable error is never modified and could have been declared const or immutable.
  | std/checkedint.d(1704:14)[warn]: Variable x is never modified and could have been declared const or immutable.
  | std/checkedint.d(1725:20)[warn]: Parameter lhs isn't documented in the `Params` section.
  | std/checkedint.d(1732:27)[warn]: Parameter lhs isn't documented in the `Params` section.
  | std/checkedint.d(1732:27)[warn]: Parameter rhs isn't documented in the `Params` section.
  | std/checkedint.d(1756:10)[warn]: Variable x is never modified and could have been declared const or immutable.
  | std/checkedint.d(1765:10)[warn]: Variable a is never modified and could have been declared const or immutable.
  | std/checkedint.d(1766:10)[warn]: Variable b is never modified and could have been declared const or immutable.
  | std/checkedint.d(1776:10)[warn]: Variable t is never modified and could have been declared const or immutable.
  | std/checkedint.d(1788:10)[warn]: Variable witness is never modified and could have been declared const or immutable.
  | std/checkedint.d(1789:10)[warn]: Variable expected is never modified and could have been declared const or immutable.
  | std/checkedint.d(1850:24)[warn]: An assert should have an explanatory message
  | std/checkedint.d(1859:18)[warn]: Variable error is never modified and could have been declared const or immutable.
  | std/checkedint.d(1904:24)[warn]: An assert should have an explanatory message
  | std/checkedint.d(1905:24)[warn]: An assert should have an explanatory message
  | std/checkedint.d(1950:10)[warn]: Variable x1 is never modified and could have been declared const or immutable.
  | std/checkedint.d(2128:24)[warn]: An assert should have an explanatory message
  | std/checkedint.d(2181:18)[warn]: Variable error is never modified and could have been declared const or immutable.
  | std/checkedint.d(2220:18)[warn]: Variable error is never modified and could have been declared const or immutable.
  | std/checkedint.d(2256:14)[warn]: Variable error is never modified and could have been declared const or immutable.
  | std/checkedint.d(2309:6)[warn]: Template parameters T isn't documented in the `Params` section.
  | std/checkedint.d(2329:14)[warn]: Variable x1 is never modified and could have been declared const or immutable.
  | std/checkedint.d(2337:14)[warn]: Variable x2 is never modified and could have been declared const or immutable.
  | std/checkedint.d(2377:10)[warn]: Variable x2 is never modified and could have been declared const or immutable.
  | std/checkedint.d(2408:7)[warn]: Parameter rhs isn't documented in the `Params` section.
  | std/checkedint.d(2408:32)[warn]: Parameter rhs is never used.
  | std/checkedint.d(2413:7)[warn]: Parameter rhs isn't documented in the `Params` section.
  | std/checkedint.d(2413:32)[warn]: Parameter rhs is never used.
  | std/checkedint.d(2450:10)[warn]: Parameter lhs isn't documented in the `Params` section.
  | std/checkedint.d(2450:40)[warn]: Parameter lhs is never used.
  | std/checkedint.d(2452:16)[warn]: An assert should have an explanatory message
  | std/checkedint.d(2456:27)[warn]: Parameter lhs isn't documented in the `Params` section.
  | std/checkedint.d(2456:27)[warn]: Parameter rhs isn't documented in the `Params` section.
  | std/checkedint.d(2473:20)[warn]: An assert should have an explanatory message
  | std/checkedint.d(2563:20)[warn]: An assert should have an explanatory message
  | std/checkedint.d(2564:20)[warn]: An assert should have an explanatory message
  | std/checkedint.d(2587:20)[warn]: An assert should have an explanatory message
  | std/checkedint.d(2588:20)[warn]: An assert should have an explanatory message
  | std/checkedint.d(2666:16)[warn]: An assert should have an explanatory message
  | std/checkedint.d(2667:16)[warn]: An assert should have an explanatory message
  | std/checkedint.d(2721:11)[warn]: An assert should have an explanatory message
  | std/checkedint.d(2730:10)[warn]: Variable overflow is never modified and could have been declared const or immutable.
  | std/checkedint.d(2741:10)[warn]: Variable overflow is never modified and could have been declared const or immutable.
  | std/checkedint.d(2750:10)[warn]: Variable overflow is never modified and could have been declared const or immutable.
  | std/checkedint.d(2825:5)[warn]: An assert should have an explanatory message
  | std/checkedint.d(2834:5)[warn]: An assert should have an explanatory message
  | std/checkedint.d(2902:39)[warn]: Parameter bound is never used.
  | std/checkedint.d(2907:39)[warn]: Parameter bound is never used.
  | std/checkedint.d(2926:10)[warn]: Variable x is never modified and could have been declared const or immutable.
  | std/checkedint.d(2926:45)[warn]: Variable y is never modified and could have been declared const or immutable.
  | std/checkedint.d(2957:10)[warn]: Variable x2 is never modified and could have been declared const or immutable.
  | std/checkedint.d(2961:10)[warn]: Variable x3 is never modified and could have been declared const or immutable.
  | std/checkedint.d(2996:10)[warn]: Variable x5 is never modified and could have been declared const or immutable.
  | std/checkedint.d(3009:10)[warn]: Variable x1 is never modified and could have been declared const or immutable.
  | std/checkedint.d(3013:10)[warn]: Variable x2 is never modified and could have been declared const or immutable.
  | std/checkedint.d(3087:10)[warn]: Variable y is never modified and could have been declared const or immutable.
  | std/checkedint.d(3114:10)[warn]: Variable x2 is never modified and could have been declared const or immutable.
  | std/checkedint.d(3137:10)[warn]: Variable x1 is never modified and could have been declared const or immutable.
  | std/checkedint.d(3179:25)[warn]: Variable x is never modified and could have been declared const or immutable.
  | std/checkedint.d(3200:10)[warn]: Variable x1 is never modified and could have been declared const or immutable.
  | std/checkedint.d(3221:10)[warn]: Variable x3 is never modified and could have been declared const or immutable.
  | std/checkedint.d(3252:10)[warn]: Variable x1 is never modified and could have been declared const or immutable.
  | std/checkedint.d(3311:12)[warn]: Variable _ushort is never modified and could have been declared const or immutable.
  | std/checkedint.d(3335:17)[warn]: Variable b is never modified and could have been declared const or immutable.
  | std/checkedint.d(3340:11)[warn]: Variable c is never modified and could have been declared const or immutable.
```

**Comment by RazvanN7** [comment]
Azure pipelines are failing with:

```
std\file.d(3395): Deprecation: module `std.experimental.checkedint` is deprecated
```

Which is caused by a reference to `std.experimental.checkedint` that is on a `version(Windows)` branch.

**Comment by atilaneves** [comment]
The style checks are more than odd given that it's exact same file with a different name.

**Comment by RazvanN7** [comment]
`std.experimental.checkedint.d` was excluded for some checks (one example is [1]). I don't know the exact reason, but I suspect, experimental is not seen as reliable code so contributors simply wanted to get the code in as fast as possible. The path of least resistance would be to simply alter `.dscanner.ini` to exclude `std.checkedint.d` from these checks, but I would rather go for fixing these warnings as most (if not all) are trivial. I can take a stab at it some time tomorrow.

[1] https://github.com/dlang/phobos/blob/master/.dscanner.ini#L170

**Comment by atilaneves** [comment]
> `std.experimental.checkedint.d` was excluded for some checks (one example is [1]). I don't know the exact reason, but I suspect experimental is not seen as reliable code, so contributors simply wanted to get the code in as fast as possible. The path of least resistance would be to simply alter `.dscanner.ini` to exclude `std.checkedint.d` from these checks, but I would rather go for fixing these warnings as most (if not all) are trivial. I can take a stab at it some time tomorrow.
> 
> [1] https://github.com/dlang/phobos/blob/master/.dscanner.ini#L170

I already started trying to fix them, but some are nonsensical. For instance, it's saying that `b` in: 

```d
///
    @safe unittest
    {
        Checked!long a, b;
        a = b = 3;
        assert(a == 3 && b == 3);
    }
```

Isn't modified and therefore should be const, which... wat?

It also complains that the template parameter `_` in `U opCast(U, this _)()` isn't documented, which again... wat.

**Comment by atilaneves** [comment]
After spending quite some time going through the dscanner warnings one by one, there's more false positives than I can shake a stick at.

**Comment by RazvanN7** [comment]
@atilaneves I have added some documentation and fixed most of the dscanner failures. However, I had to deactivate some of the checks because they were causing spurious failures as the one you mentioned (plus undocumented template `this _` parameters, unnamed parameters that have to be documented etc.)

**Comment by atilaneves** [comment]
The changelog entry is right there, so I don't know what the label is about.

**Comment by RazvanN7** [comment]
The label was put there in May last year. I removed it because you addressed it.

**Review by RazvanN7 — APPROVED** [review]

**Pull request merged**
