### PR TITLE
Issue 8166 - remove dead _backLength code in std.algorithm.splitter

### PR DESCRIPTION
**Pull request by wilzbach**
The implementation already was partially there.
Has anyone a memory why it wasn't enabled?

### CODE REVIEW

**Comment by jmdavis** [comment]
Making `splitter` a bidirectional range fundamentally broken - at least if the delimiter has more than one element. Think about something like

   auto result = "*******".splitter("**"); // odd number in the string being split, even number in the delimeter

The range is not going to have the same elements if it's iterated from the back. It will end up being split differently.

**Comment by wilzbach** [comment]
> Making splitter a bidirectional range fundamentally broken - at least if the delimiter has more than one element. Think about something like

Argh. I almost expected something like this, but couldn't think of it. Thanks!
I used this opportunity to remove the old, dead code then. No need to set and store `_backLength` if we never use it.

**Comment by JackStouffer** [comment]
You can still do it if `is(typeof(separator) == ElementType!Range)`

**Comment by wilzbach** [comment]
> You can still do it if is(typeof(separator) == ElementType!Range)

That's a separate overload, which already does so.

**Pull request merged**
