### PR TITLE
refact,digest, for core.bitops, use aliases instead of FQNs

### PR DESCRIPTION
**Pull request by NilsLankila**
Partially revert ddca869335a85d, because this is what should have been done initially.

### CODE REVIEW

**Comment by NilsLankila** [comment]
TF, @WalterBright, this is what i suggested earlier today. What's going on ?

**Comment by NilsLankila** [comment]
`toAlias()` is not called somewhere in DMD...

**Comment by NilsLankila** [comment]
just a guess, intrinsic detection is defeated by aliases.

**Comment by Geod24** [comment]
Now that the diff has been put in, is there any use in reverting ?

**Comment by NilsLankila** [comment]
Duplicate of #

**Pull request closed without merging**
