### PR TITLE
Add bookmark table to std.typecons

### PR DESCRIPTION
**Pull request by wilzbach**
Recreated https://github.com/dlang/phobos/pull/5639 due to the current CI blockage from GH (GH's hook don't work anymore on Phobos after a rebase).

-----

Before:

image

After:

image

Other interesting modules
- [std.process](https://dlang.org/phobos/std_process.html)
- [std.variant](https://dlang.org/phobos/std_variant.html)
- [std.uri](https://dlang.org/phobos/std_uri.html)
- [std.random](https://dlang.org/phobos/std_random.html)
- [std.parallelism](https://dlang.org/phobos/std_parallelism.html)
- [std.numeric](https://dlang.org/phobos/std_numeric.html)
- [std.mathspecial](https://dlang.org/phobos/std_mathspecial.html)
- [std.getopt](https://dlang.org/phobos/std_getopt.html)

### CODE REVIEW

**Comment by andralex** [comment]
Doc build is failing.

**Comment by wilzbach** [comment]
@CyberShadow - didn't we fix that one? Any way I can restart this without rebasing?

```
.generated/phobos-release @.generated/.release-files.txt
../dmd-2.075.0/src/ddmd/mars.d(47): Error: module objc is in file 'ddmd/objc.d' which cannot be read
```

**Comment by CyberShadow** [comment]
We fixed it on master, this is for stable IIRC.

**Comment by wilzbach** [comment]
But other PRs to stable passed already: https://github.com/dlang/phobos/pull/5641

**Comment by CyberShadow** [comment]
Don't know what to tell you. Stable itself has been failing for a while now:
http://dtest.dlang.io/history/stable

**Comment by wilzbach** [comment]
> Don't know what to tell you. Stable itself has been failing for a while now:

-> https://github.com/dlang/dlang.org/pull/1839

**Comment by wilzbach** [comment]
Argh sorry - something went wrong here, sorry for the noise. I have to open a new PR anyhow to the GH API bug :/

**Comment by wilzbach** [comment]
> something went wrong here, sorry for the noise

I accidentally rebased the PR against `master`, not `stable`.

> I have to open a new PR anyhow to the GH API bug

-> https://github.com/dlang/phobos/pull/5650

**Pull request closed without merging**
