### PR TITLE
formattedWrite: storing address of parameters is not @safe

### PR DESCRIPTION
**Pull request by WalterBright**
Fixed to pass more advanced @safe checks.

### CODE REVIEW

**Comment by schveiguy** [comment]
The difference here is that you are assigning a `const(void)` pointer from another `const(void)` pointer inside the trusted block vs. outside. I'm trying to understand why this is considered unsafe. I mean, the change looks like it's identical to the original code, so I have no beef there, but it's confusing me why the change is necessary.

**Comment by WalterBright** [comment]
Because it takes the address of a parameter and stores it in another variable. That is unsafe, as the compiler cannot keep track of it after doing that.

**Comment by schveiguy** [comment]
Not disagreeing that, but it does so inside a `@trusted` block.

The current rules say that if I have a `void *`, I can assign it to another `void *`. That is all the original code was doing. Are there new rules against this now?

**Comment by WalterBright** [comment]
> Are there new rules against this now?

That's not the issue. The issue is the complaint that it is not safe to escape the address of a parameter by storing it in another variable.

**Comment by schveiguy** [comment]
So are you saying that this is no longer allowed, even in trusted code?

```D
const(void) * foo(ref int i) @trusted { return cast(void) *&i; }
```

**Comment by schveiguy** [comment]
If someone else understands this, I don't have any objections to merging it. The code just seems identical either way, and should be fine with safe rules.

**Comment by WalterBright** [comment]
> The code just seems identical either way

It is not the same, the assignment was moved inside the trusted function.

**Comment by schveiguy** [comment]
@WalterBright I mean the code should generate identical instructions, and I still am unclear why the assignment is not allowed, since pointer assignment is fine in `@safe` code normally.

Again, all I'm saying is that my naive or ignorant understanding of why you are doing this shouldn't prevent someone else from merging if they feel it is necessary.

**Comment by jmdavis** [comment]
It's been the case that taking the address of a local variable is not `@safe`, but AFAIK, it's been `@safe` to assign `void*` to `void*`. And if that's true, then all that needed to be `@trusted` was the `&` and not the assignment. But if assigning `void*` to `void*` has become `@system` for some reason (or will soon), then the assignment would need to be `@trusted` as well. However, if that's not the case, then I don't understand how moving the assignment into `@trusted` matters any more than Steven does. The part flagged as `@system` is already `@trusted`.

Is the compiler now going to try and treat taking the address of a local variable as `@safe` and only treat it as `@system` depending on what you do with that address instead of just always treating taking the address of a local variable as `@system`? If that's the case, then this change would make sense.

**Comment by WalterBright** [comment]
Again, this change is because the taking of the address of a parameter and assigning it somewhere else makes it unsafe (it is caught by the improved safety checks that are not merged yet).

**Comment by jmdavis** [comment]
> Again, this change is because the taking of the address of a parameter and assigning it somewhere else makes it unsafe (it is caught by the improved safety checks that are not merged yet).

Does this mean that taking the address of a local variable is no longer going to always be treated as `@system` but rather will depend on what you do with the address?

**Comment by schveiguy** [comment]
To be clear, I thought the compiler could assume infinite lifetime for the return value from the lambda, because it's a bare pointer. Even with introspection, it can determine that the lifetime is tied to the parameter, which in the given call is at the same lifetime level as the array being assigned. I can't see how the original code should be flagged. Perhaps a more in depth explanation could illuminate what I'm not seeing.

**Comment by schveiguy** [comment]
Note: the fact that both Jonathan and I can't see why this is better may be an indication that the rules aren't clearly enough defined. It also could be that they are clearly defined, but we just aren't getting it. An example of how this rule would prevent a safety violation would go a long way I think.

**Comment by jmdavis** [comment]
I get that storing a pointer to a parameter is unsafe, but as it stands, that's already accounted for by the fact that taking the address of a local variable is flagged as `@system`. Once you have the pointer, I wouldn't have thought that assigning it to anything would be considered `@system`. And if it's the assignment that gets flagged as `@system`, then that implies that the compiler is then concerned with what you do with a pointer to a local variable and not that you took the address of a local variable, in which case, I wouldn't expect taking the address of a local variable to be flagged as `@system` anymore but rather that when something potentially unsafe is done with the resulting pointer, _that_ gets flagged as `@system`. But flagging the assignment when taking the address is already flagged doesn't make sense to me.

**Comment by WalterBright** [comment]
> what the changed rule is that applies here

Taking the address of a parameter and storing it in a local is unsafe per DIP1000. That makes the template this piece of code is in inferred to be unsafe, and causes failure to compile of @safe that calls it. It "worked" before because the address was taken inside a @trusted function and the assignment was not checked. Moving the assignment into the @trusted function makes it work.

**Comment by schveiguy** [comment]
Is there a way to output what the compiler infers on the lambda? Perhaps the inference is conveying the fact that the return value maps to the input parameter somehow.

**Comment by schveiguy** [comment]
Is there a way to mark a static array as pointing at local variables, such that the safety is not accidentally violated? Since pointer leaks out of the `@trusted` function, technically the whole function is unsafe. However, if there's a way to mark the static array such that none of its data can escape the function, then the whole thing would be `@safe`, you may not even need the trusted function at all.

**Comment by JackStouffer** [comment]
Ping @WalterBright

**Comment by WalterBright** [comment]
This has been superceded by -dip1000

**Pull request closed without merging**
