### PR TITLE
fix space between operators

### PR DESCRIPTION
**Pull request by wilzbach**
follow-up to #4239

### CODE REVIEW

**Comment by Hackerpilot** [comment]
:white_check_mark:

**Comment by JackStouffer** [comment]
Why can't we just use dfmt to do this automatically and all in one PR?

**Comment by wilzbach** [comment]
> Why can't we just use dfmt to do this automatically and all in one PR?

I think dfmt would even a lot more?
And just adding space already affects 3500 lines, s.t. it's impossible to review via the web interface (I tried).
In any case, I would love to put this style change into one PR ...

**Comment by JackStouffer** [comment]
I mean have dfmt do everything that it normally does and all in one PR. Assuming there are no bugs in dfmt, this should not be a problem. And even if there were, the auto-tester would catch them.

We would then be able to diff any PR with the dfmt output to stop style deviations.

**Comment by wilzbach** [comment]
> I mean have dfmt do everything that it normally does and all in one PR. Assuming there are no bugs in dfmt, this should not be a problem. And even if there were, the auto-tester would catch them.

```
169 files changed, 97926 insertions(+), 67498 deletions(-)
```

**Comment by JackStouffer** [comment]
> 169 files changed, 97926 insertions(+), 67498 deletions(-)

Better that than hundreds of separate PRs, which is what it would take to enforce all of dfmt's rules. And like I said, the auto-tester will catch any errors.

**Comment by Hackerpilot** [comment]
I thought that aligning trailing comments was a requirement for using dfmt?

**Comment by wilzbach** [comment]
> Better that than hundreds of separate PRs, which is what it would take to enforce all of dfmt's rules. And like I said, the auto-tester will catch any errors.

I just tried. `dfmt` destroys custom formatting and ddoc headers :/
-> Let's start simple & step by step? I will put all missing operator spaces in this pr.

**Comment by wilzbach** [comment]
> I will put all missing operator spaces in this pr.

done.

**Comment by JackStouffer** [comment]
If this was done automatically using sed, then LGTM

**Comment by Hackerpilot** [comment]
Auto-merge toggled on

**Comment by tsbockman** [comment]
@JackStouffer 
> the auto-tester will catch any errors.

That's very optimistic of you, for a ~100K line diff. It's not like we have 100% unit test coverage or anything...

**Comment by wilzbach** [comment]
Thanks :)

**Comment by Hackerpilot** [comment]
And now I wait for the yelling to start.

**Comment by wilzbach** [comment]
Yep you were quite brave - I didn't expect it to be merged that quickly, but it just touches single lines so I hope for the best!

**Comment by JackStouffer** [comment]
You avoided the bikeshedding quite skillfully

**Comment by yebblies** [comment]
> I thought that aligning trailing comments was a requirement for using dfmt?

That's for DMD.  I'm not sure anyone's really evaluated it for phobos yet - and phobos is not really internally consistent.

**Pull request merged**
