### PR TITLE
Fix issue #20260 - CustomFloat with 0 precision/exponentWidth

### PR DESCRIPTION
**Pull request by crocopaw**

### CODE REVIEW

**Comment by atilaneves** [comment]
How are there no changes to existing tests to accomodate this?

**Comment by crocopaw** [comment]
> How are there no changes to existing tests to accomodate this?

It's about compiler error messages:

Old:

```
numeric.d(322): Error: undefined identifier significand_max
numeric.d(330): Error: undefined identifier significand_max
numeric.d(517): Error: template instance `std.numeric.CustomFloat!(0u, 7u, cast(CustomFloatFlags)31, 63u).CustomFloat.fromNormalized!(ulong, long)` error in$
numeric.d(482):        instantiated from here: opAssign!double
numeric.d(627):        instantiated from here: __ctor!double
numeric.d(521): Error: undefined identifier significand_max
numeric.d(525): Error: cannot modify constant significand
numeric.d(386): Error: cannot modify manifest constant significand
numeric.d(398): Error: undefined identifier significand_max
numeric.d(430): Error: cannot modify manifest constant significand
numeric.d(456): Error: undefined identifier significand_max
numeric.d(467): Error: cannot modify manifest constant significand
numeric.d(521): Error: undefined identifier significand_max
numeric.d(525): Error: cannot modify constant significand
numeric.d(482): Error: template instance `std.numeric.CustomFloat!(0u, 7u, cast(CustomFloatFlags)31, 63u).CustomFloat.opAssign!float` error instantiating
numeric.d(477):        instantiated from here: __ctor!float
numeric.d(121):        instantiated from here: CustomFloat!(0u, 7u, cast(CustomFloatFlags)31, 63u)
numeric.d(627):        instantiated from here: CustomFloat!(0u, 7u, cast(CustomFloatFlags)31)
```

New:

```
numeric.d(121): Error: template std.numeric.CustomFloat does not match any template declaration
numeric.d(627): Error: template instance `std.numeric.CustomFloat!(0u, 7u, cast(CustomFloatFlags)31)` error instantiating 
```

Is there any way, to test this?

**Comment by atilaneves** [comment]
> Is there any way, to test this?

Yes. There are many tests that assert what the error messages should be, you can find many examples in the test suite.

**Comment by crocopaw** [comment]
> Yes. There are many tests that assert what the error messages should be, you can find many examples in the test suite.

I have to confess, that I'm lost a little bit. As far, as I know, phobos hasn't any test suite [1]. There are only unittests. I tried to search the website for something I miss, but did not find anything. The only thing I can imagine is to use "static assert" somehow, but did not manage to come up with something usefull. What I actually would need is "static assertThrown", but as far as I know, this doesn't exist...

[1] https://dlang.org/blog/2017/01/20/testing-in-the-d-standard-library/

**Comment by thewilsonator** [comment]
@atilaneves this is phobos not dmd, can't do that. Also phobos is banned in DMD test suites anyway.

**Comment by atilaneves** [comment]
I missed that it was Phobos, sorry. You could use a static assert on it failing to compile with `__traits(compiles)` though. 

Any change to production code without a corresponding change in tests is fishy.

**Comment by crocopaw** [comment]
I close this in favour of PR #7219.

**Pull request closed without merging**
