### PR TITLE
std.logger 32 bit unittest race condition fix

### PR DESCRIPTION
**Pull request by burner**
@WalterBright maybe this helps. From the errors I saw, there is a race somewhere on 32 bit.

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by burner** [comment]
thank you

**Comment by pbackus** [comment]
Same test is still failing for me in https://github.com/dlang/phobos/pull/8555

**Comment by pbackus** [comment]
Judging from the message I saw (`foo`), the race is between the test modified in this PR and [this test][1], which also accesses `sharedLog`.

[1]: https://github.com/dlang/phobos/blob/master/std/logger/core.d#L1534-L1571

**Comment by burner** [comment]
I think I understand the problem. The created thread executes code after the test is done. It has to be joined before the test is over. I'll create a PR.

**Pull request merged**
