### PR TITLE
Update std.array to use new REF macro

### PR DESCRIPTION
**Pull request by JakobOvrum**
Depends on D-Programming-Language/dlang.org/pull/1184.

Just an example to show how to use it for now.

### CODE REVIEW

**Comment by andralex** [comment]
rebase

**Comment by JakobOvrum** [comment]
Don't merge this until the dependency is merged.

**Comment by CyberShadow** [comment]
@JakobOvrum Time to rebase?

**Comment by JakobOvrum** [comment]
Rebased. The only real diff stems from the use of `ROOT_DIR`, which I'd say is a good sign that it works as a drop-in replacement.

The choice of std.array for this PR was fairly abitrary. I recently filed #3926 which applies `MREF` across all of Phobos. I'd like to convert this PR into one that similarly applies `REF` across all of Phobos (if we go ahead with that, it would help if #3926 was merged first, as it gets rid of many uses of `LINK2`). Thoughts?

Note that any macros in dlang.org.ddoc cannot be removed until they are verified to be unused across all three repositories.

**Comment by CyberShadow** [comment]
LGTM

**Comment by CyberShadow** [comment]
Auto-merge toggled on

**Comment by CyberShadow** [comment]
Thanks, hurray for relative links.

**Comment by JakobOvrum** [comment]
OK, I'll file future changes in a new PR then.

**Comment by CyberShadow** [comment]
Auto-merge toggled off

**Comment by CyberShadow** [comment]
Sorry, I somehow skipped over this paragraph:

> The choice of std.array for this PR was fairly abitrary. I recently filed #3926 which applies MREF across all of Phobos. I'd like to convert this PR into one that similarly applies REF across all of Phobos (if we go ahead with that, it would help if #3926 was merged first, as it gets rid of many uses of LINK2). Thoughts?

**Comment by greenify** [comment]
> OK, I'll file future changes in a new PR then.

AFAICT this was just a proposal, so it can be closed?

@JakobOvrum otherwise please rebase :)

**Comment by quickfur** [comment]
Now that https://github.com/D-Programming-Language/dlang.org/issues/1257 has merged, is this ready to go?

Also, merge conflict; please rebase.

**Comment by JakobOvrum** [comment]
If you'd like to help with this effort, please look at #3926.

**Comment by wilzbach** [comment]
Thanks to @aG0aep6G's [efforts](https://github.com/dlang/phobos/pull/4364) XREF got replaced with REF :)

Hence this is show case PR is not needed anymore.

**Pull request closed without merging**
