### PR TITLE
Simplify isSame

### PR DESCRIPTION
**Pull request by andralex**
Types can also be compared with the isSame trait. This saves a couple of seconds for the entire phobos unittest.

### CODE REVIEW

**Comment by PetarKirov** [comment]
This implementation also passes the tests:

```D
template isSame(alias a, alias b)
{
    static if (__traits(compiles, a == b) && !__traits(compiles, &a))
        enum isSame = a == b;
    else
        enum isSame = __traits(isSame, a, b);
}
```

I suggest using it as it looks cleaner. In case it's not an exact replacement, then we should amend the unit test in order to check the case(s) where it differs.

**Comment by andralex** [comment]
> This implementation also passes the tests:
> 
> ```d
> template isSame(alias a, alias b)
> {
>     static if (__traits(compiles, a == b) && !__traits(compiles, &a))
>         enum isSame = a == b;
>     else
>         enum isSame = __traits(isSame, a, b);
> }
> ```
> 
> I suggest using it as it looks cleaner. In case it's not an exact replacement, then we should amend the unit test in order to check the case(s) where it differs.

Awesome. Did so. Thank you!

**Comment by andralex** [comment]
@PetarKirov actually I added a couple of unitests that don't pass with your implementation. For now I reverted back to the previous implementation. Let me know if you work it out!

**Review by thewilsonator — APPROVED** [review]

**Comment by PetarKirov** [comment]
@andralex Thanks for the unit tests - I will check them out.

**Comment by PetarKirov** [comment]
Actually I see that you have use a hybrid approach that used the static if condition from the old code, but 2 alias parameters from my suggestion. This was my first iteration, but I wanted to see if I can simplify the condition, but for that the test coverage was not thorough enough, so thanks for improving it.

**Pull request merged**
