### PR TITLE
std.experimental.logger.filelogger: compile with -dip1000

### PR DESCRIPTION
**Pull request by WalterBright**
Completes the PRs for compiling Phobos with -dip1000.

### CODE REVIEW

**Comment by WalterBright** [comment]
ci/circleci failures are the usual linker error with undefined symbols in Phobos

**Comment by thewilsonator** [comment]
Yep. Merge after the rest are green.

**Comment by WalterBright** [comment]
Good. I want to get all the easy ones done first. All the dip1000 PRs are up now.

**Comment by thewilsonator** [comment]
All green except circle.

**Comment by wilzbach** [comment]
> ci/circleci failures are the usual linker error with undefined symbols in Phobos

Which you know everyone would get when trying to use Phobos with -dip1000...

**Pull request merged**
