### PR TITLE
Update D-scanner version

### PR DESCRIPTION
**Pull request by Basile-z**

### CODE REVIEW

**Comment by Basile-z** [comment]
It looks like it was not the right time for this because I see there's a kind of situation, as show by the CircleCI failure ?

**Comment by wilzbach** [comment]
Weird, master is passing: https://circleci.com/gh/dlang/phobos/9365

**Comment by thewilsonator** [comment]
I saw that on some other PR earlier.

**Comment by Basile-z** [comment]
Looks like the effect of #6890 after you force-pushed worked @wilzbach, ping for auto-merge.

**Comment by wilzbach** [comment]
Added

**Pull request merged**
