### PR TITLE
Move deprecations along

### PR DESCRIPTION
**Pull request by jmdavis**

### CODE REVIEW

**Comment by wilzbach** [comment]
@jmdavis I created a PR to fix Dscanner -> https://github.com/dlang-community/D-Scanner/pull/761
We can bump the dscanner hash in `posix.mak` once this has been merged and then this PR should pass.

**Comment by jmdavis** [comment]
@wilzbach Thanks!

**Comment by wilzbach** [comment]
Bumped DScanner to https://github.com/dlang-community/D-Scanner/commit/e5a73fa0ef0bf790a56fbcb34df407878454c965 which hopefully makes this PR pass.

**Comment by wilzbach** [comment]
Okay, so this three remaining projects fail:

- [ ] dlang-bot: https://github.com/dlang/dlang-bot/pull/230 - a bit tricky because upgrading to a newer vibe.d breaks the test suite
- [ ] dls (the problem is that it uses dub 1.15 and the original dub PR was against master. Hence, I cherry-picked it to stable in https://github.com/dlang/dub/pull/1710, s.t. the next point release contains this fix).
- [ ] ae (CC @CyberShadow)

```
sys/install/common.d(202,27): Error: module `digest` is in file 'std/digest/digest.d' which cannot be read
```

**Comment by MoonlightSentinel** [comment]
Most of these symbols were removed in other PRs.
The remaining `std.digest` is pending in #7281

**Comment by schveiguy** [comment]
Should we close this and then just focus on the remaining deprecation?

**Comment by MoonlightSentinel** [comment]
I think so as all other changes were merged already

**Pull request closed without merging**
