### PR TITLE
Fix issue 21253 - Can't compile Variant.visit!(...) with generic func…

### PR DESCRIPTION
**Pull request by Biotronic**
…tion

### CODE REVIEW

**Comment by Biotronic** [comment]
Turns out, the tests on lines 2433-2437 probably should have referred to `maybenumber` all along, and were testing for the wrong thing.

**Comment by pbackus** [comment]
The `nonmatch` check is a breaking change, because `visit` currently ignores handlers that don't match any types. Here's a unit test that passes on `master` but breaks with this PR:

```d
@system unittest
{
    Algebraic!(int, string) x = 123;
    assert(__traits(compiles,
        x.visit!(
            (int n) => "got int",
            (string s) => "got string",
            (char c) => "got char"
        )
    ));
}
```

**Comment by myCrack** [comment]
> breaking change, because visit currently ignores handlers that don't match any types.

https://dlang.org/phobos/std_variant.html#.visit:
> It is statically ensured that all held types of variant are handled across **_all_** handlers.

So, behavior from the master branch must be treated as a bug.

**Comment by pbackus** [comment]
I'm pretty sure that just means that you have to handle every type (which, indeed, is statically ensured on `master`), but the wording is certainly not as clear as it could be.

**Review by thewilsonator — APPROVED** [review]

**Pull request merged**
