### PR TITLE
Fix Issue 23940 - std.getopt does not assert with options that only d…

### PR DESCRIPTION
**Pull request by CyberShadow**
…iffer in case with config.caseInsensitive

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by ljmf00-wekaio** [comment]
@CyberShadow  This is a huge breaking change for `getopt` users! `getopt` with no `config` options whatsoever now asserts, ... at runtime.

This broke upgrades to recent compiler at Weka. CC @JohanEngelen (our traces instrumentor)

I can understand the breakage in a pedantic standpoint tho, as this is documented as such, although not entirely clear about short vs long options, but we should have announced this in the changelog, at bare minimum, and, imo, a better discussion.

A common valid use-case:
```
-d --debug
-D --directory
```
I would expect short options to be case insensitive here. This exact options now fail with this patch. Should we reconsider or/and document this better?

**Comment by CyberShadow** [comment]
Ahh, sorry about that :(

To be fair, this is one of those "thing that silently never worked in the first place is now correctly reported as an error" types of situations.

> I would expect short options to be case insensitive here.

I don't understand what you mean by this. How can they be case insensitive if you have two options that differ only in case?

**Comment by JohanEngelen** [comment]
@ljmf00-wekaio wouldn't this be fixed for weka by explicitly setting `config.caseSensitive` ?

**Comment by ljmf00-wekaio** [comment]
> @ljmf00-wekaio wouldn't this be fixed for weka by explicitly setting `config.caseSensitive` ?

It does, but given that was not the case, now only if it reaches the `getopt` call, it asserts at runtime. (given the nature of `getopt`, its not possible to catch it at compile-time). I think this can be a huge breakage since it may affect a lot of projects (and more silent breakage if they have multiple `getopt`, for subcommands).

I think, at bare minimum should have been in changelog.

**Comment by CyberShadow** [comment]
@thewilsonator Do we have any precedents for what to do in this situation?

More generally, what to do about breaking changes that can't be detected at compile-time? E.g. do we make built programs print a message to `stderr`? We could also do nothing and continue silently accepting wrong/self-contradictory parameters...

Should we document this breaking change retroactively by updating that version's changelog on dlang.org?

**Comment by ljmf00-wekaio** [comment]
> Should we document this breaking change retroactively by updating that version's changelog on dlang.org?

I agree with it.

Regarding the other suggestion, my opinion would be to ease that for `-d` and `-D` situations. I interpret the documentation as if you could do `--debug` or `--Debug` or `--DEBUG`, but if there's `d|debug` and `D|documentation`, `-d` and `-D` should have the possibility to be sensitive while the long option insensitive, but as far as I understand, there's no specific mention on short and long options, regarding the case sensitive option.

---

In anyway, this is something that I would really like to discuss. I also believe that, in the long term for Phobos v3, we should look at projects like https://github.com/andrey-zherikov/argparse from @andrey-zherikov. I generally agree with the design choices (some things I would change), and I'm sure Phobos folks would also generally agree with them. I think this being an adoption to Phobos would modernise our standard library.

In some projects I saw the necessity of using it because the Phobos `getopt` is simply not good/powerful enough.

**Comment by andrey-zherikov** [comment]
> (some things I would change)

Could you please create issue(s) with your thoughts so we can discuss? I'm living in my own bubble without feedback from others. This is a good time for new ideas because I'm working on new major version where I can accommodate as much breaking changes as possible.

**Pull request merged**
