### PR TITLE
fix issue 17780 -  Malformed DDOC links in std.range

### PR DESCRIPTION
**Pull request by BBasile**

### CODE REVIEW

**Comment by BBasile** [comment]
why not put in master and cherry pick in stable ?

**Comment by wilzbach** [comment]
> why not put in master and cherry pick in stable ?

Would be another PR which I can't do today

**Comment by ZombineDev** [comment]
As a general workflow we don't cherry pick, only merge stable into master.

**Comment by BBasile** [comment]
I didn't see the other commits yesterday. THe proper PR is #5708

**Pull request closed without merging**
