### PR TITLE
Run CircleCi coverage for 32-bit too

### PR DESCRIPTION
**Pull request by wilzbach**
See also: https://github.com/dlang/dmd/pull/7718

### CODE REVIEW

**Comment by wilzbach** [comment]
It looks like we need to figure that one out first - the `std.net.curl` tests run into a timeout on 32-bit on CircleCi:

```
T=`mktemp -d /tmp/.dmd-run-test.XXXXXX` &&                                                              \
  (                                                                                                     \
    ../dmd/generated/linux/debug/32/dmd -od$T -conf= -I../druntime/import  -w -de -dip25 -m32  -transition=complex -g -debug -main -unittest -version=StdUnittest generated/linux/debug/32/libphobos2.a -defaultlib= -debuglib= -L-ldl -cov -run etc/c/odbc/sql.d ;     \
    RET=$? ; rm -rf $T ; exit $RET                                                                   \
  )
DMD v2.078.1 DEBUG
posix.mak:395: recipe for target 'std/net/curl.test' failed
```

**Comment by kinke** [comment]
> the std.net.curl tests run into a timeout on 32-bit on CircleCi

Make sure the 32-bit curl libs are available - LDC installs the  `libcurl3:i386` package for the `ubuntu:14.04` docker image.

**Comment by JackStouffer** [comment]
Ping @wilzbach

**Comment by wilzbach** [comment]
We want to replace CircleCi with Buildkite (as its an attempt to unify all CIs) on the long run anyhow and I don't really now why installing the correct curl 32-bit package doesn't help here, so I'm closing this.

**Pull request closed without merging**
