### PR TITLE
Merge remote-tracking branch 'upstream/stable' into merge_stable

### PR DESCRIPTION
**Pull request by MartinNowak**

### CODE REVIEW

**Comment by wilzbach** [comment]
Travis fails because of the missing whitespace after `if`

```
/std/container/rbtree.d:    static if(is(typeof((){FormatSpec!(char) fmt; formatValue((const(char)[]) {}, ConstRange.init, fmt);})))
```

**Comment by andralex** [comment]
cc @MartinNowak for spacing

**Comment by andralex** [comment]
Auto-merge toggled on

**Comment by MartinNowak** [comment]
https://github.com/dlang/phobos/pull/4436

**Pull request merged**
