### PR TITLE
Fix Issue 23301 - Dlang website (doc) bug: std_experimental_checkedint.html

### PR DESCRIPTION
**Pull request by wolframw**

### CODE REVIEW

**Review by RazvanN7 — CHANGES_REQUESTED** [review]
This does not fix the issue. The master branch does not contain the problem, it's the [stable branch](https://github.com/dlang/phobos/blob/stable/std/experimental/checkedint.d) that has the problem.

**Comment by wolframw** [comment]
> This does not fix the issue. The master branch does not contain the problem, it's the stable branch that has the problem.

You're right, of course. It seemed like this change bizarrely fixes the issue locally. In reality, I was obviously on the wrong branch 🤦‍♂️

**Comment by RazvanN7** [comment]
It looks like this needs a rebase to lastest stable?

**Comment by wolframw** [comment]
> It looks like this needs a rebase to lastest stable?

Are you sure? `git rebase upstream/stable` tells me that my branch is up to date.

**Review by RazvanN7 — APPROVED** [review]

**Comment by RazvanN7** [comment]
This looks good. The failures might be related to the fact that stable is not yet a monorepo :-? .

**Comment by ibuclaw** [comment]
Master has been merged back into stable, so this is fixed.

**Pull request closed without merging**
