### PR TITLE
faster CRC32 implementation

### PR DESCRIPTION
**Pull request by MartinNowak**
- use slicing by 8 algorithm with bigger precomputed tables
- roughly 4x faster

### CODE REVIEW

**Comment by WalterWaldron** [comment]
According to [this](http://create.stephan-brumme.com/crc32/#endianness), this implementation is endian sensitive.
The link contains the endian aware modification and mentions that reordering the lookups could yield further performance improvement.

**Comment by MartinNowak** [comment]
Nope, the implementation also works for big endian, b/c it assembles the uint's from byte-wise reads instead of relying on unaligned hardware loads. Still did the reordering of the operations which indeed provided a noticeable speedup.

**Comment by WalterWaldron** [comment]
Ok, I hadn't digested that ```hasUnalignedReads``` was only to force that optimization in DMD rather than to provide a per-architecture switch.

LGTM on the basis of matching other slicing by 8 implementations.

**Comment by MartinNowak** [comment]
After your comment, I was actually a bit unsure whether genTables is endian correct, so I build a gdc cross-compiler and tested on my router. Will add a comment that the uint reads must be little endian.

**Comment by DmitryOlshansky** [comment]
LGTM, also love the CTFE construction of the table.

**Comment by UplinkCoder** [comment]
Auto-merge toggled on

**Comment by bgaff** [comment]
Dumb question here but why can't sse4 crc32 numonics be used when available? I apologize of the answer is obvious

**Comment by kubo39** [comment]
@bgaff SSE4.2 crc32 instruction is for castagnoli polynomial, not IEEE.

**Pull request merged**
