### PR TITLE
Optimize std.math.pow() for base = 2

### PR DESCRIPTION
**Pull request by kinke**
In order to speed-up `2.0 ^^ N` for bigger integral |N|, see http://forum.dlang.org/thread/vjftbmzikadoiqtvuaxu@forum.dlang.org. Pinging @nordlow.

### CODE REVIEW

**Comment by nordlow** [comment]
LGTM. I'm not very skilled in these low-level floating point matters, though.

**Comment by kinke** [comment]
The other alternative would be detecting a compile-time-constant base `2` and integral exponent in the compiler and remapping the runtime call from `std.math.pow(base, exponent)` to `std.math.ldexp(cast(T) 1, cast(int) exponent)`, in order to avoid the runtime cost in pow(). Optimizing for a non-compile-time-const base of 2 isn't worth it IMO.

**Comment by JackStouffer** [comment]
Performance numbers?

**Comment by kinke** [comment]
It should be clear that just setting the exponent (some integer ops) is way faster than the current loop for bigger absolute N, but I didn't perform any speed tests.
I'd rather drop this and add the optimization to the compiler, something like https://github.com/kinke/ldc/commit/dc01a338d73c2cdb843de6426f520f6c175640d3.

**Comment by JackStouffer** [comment]
> I'd rather drop this and add the optimization to the compiler

Then why not close this and do that?

**Comment by kinke** [comment]
So that I don't forget ;) - other priorities at the moment.

**Comment by wilzbach** [comment]
> I'd rather drop this and add the optimization to the compiler
> Then why not close this and do that?
> So that I don't forget ;) - other priorities at the moment.

As we aren't going to merge this,  I opened https://issues.dlang.org/show_bug.cgi?id=17662

**Comment by kinke** [comment]
Thanks.

**Pull request closed without merging**
