### PR TITLE
posix.mak: Add JSON target

### PR DESCRIPTION
**Pull request by CyberShadow**

### CODE REVIEW

**Comment by CyberShadow** [comment]
Druntime generates a JSON file by default. So does `win32.mak` (for Phobos and Druntime). Maybe this should be part of the default target for Phobos too?

**Comment by DmitryOlshansky** [comment]
> Druntime generates a JSON file by default. So does win32.mak (for Phobos and Druntime). Maybe this should be part of the default target for Phobos too?

Makes sense to do so

**Comment by CyberShadow** [comment]
> > Druntime generates a JSON file by default. So does win32.mak (for Phobos and Druntime). Maybe this should be part of the default target for Phobos too?
> 
> Makes sense to do so

Ah right, Phobos is built in pieces in posix.mak, so never mind...

**Comment by wilzbach** [comment]
> Ah right, Phobos is built in pieces in posix.mak, so never mind...

? 
Otherwise having the Json file sounds reasonable.

**Comment by CyberShadow** [comment]
> ?

`win32.mak` builds `phobos.lib` and `phobos.json` simultaneously, in one DMD invocation. `posix.mak`, however, builds Phobos in pieces (a few object files at a time, which are then linked together). This means that if you want a JSON file on Posix, you have to do one more compiler invocation. I assume most people don't want a JSON file, so it would be a pointless slowdown for the most part.

Which is why I've left it as a separate target.

**Comment by wilzbach** [comment]
> Which is why I've left it as a separate target.

Makes even more sense, thanks a lot for the explanation :)

**Comment by DmitryOlshansky** [comment]
Auto-merge toggled on

**Comment by andralex** [comment]
Is the json a single large json file for the entire library? @CyberShadow do you have plans with it? :)

**Comment by CyberShadow** [comment]
> Is the json a single large json file for the entire library? @CyberShadow do you have plans with it? :)

Yes, make Emacs automatically fix my imports [like my previous editor could](http://dump.thecybershadow.net/e91be687ebaeb0171d830025adf82848/autofix.gif). This one's completely selfish ;)

It was already done in `win32.mak` by default, whereas `posix.mak` didn't even have a target for it.

**Pull request merged**
