### PR TITLE
std.experimental.logger: Change LogLevel documentation

### PR DESCRIPTION
**Pull request by ljmf00**
Fix this issue on documentation:
image

### CODE REVIEW

**Comment by ZombineDev** [comment]
This actually seems like a bug in [dpl-docs](http://dpldocs.info/experimental-docs/std.experimental.logger.core.LogLevel.html)' ddoc-parsing engine. As per https://dlang.org/spec/ddoc#parsing:
> 1. [..] If the documentation comment appears on the same line to the right of a declaration, it applies to that.

I filed a bug: https://github.com/adamdruppe/adrdox/issues/30. Usually @adamdruppe I quite responsive, so I prefer to wait and see if this is something that could be easily fixed on his side, otherwise I would be fine with merging your PR as it doesn't negatively affect the other documentation engines and it would be could if documentation rendered correctly on dpl-docs too. My preference is for fixing this on the adrdox, as this bug probably affects other things too.

**Comment by adamdruppe** [comment]
On Fri, Aug 24, 2018 at 06:48:28PM +0000, Petar Kirov wrote:
> I filed a bug: https://github.com/adamdruppe/adrdox/issues/30. Usually @adamdruppe I quite responsive, so I prefer to wait and see if this is something that could be easily fixed on his side

Yes, this should be an easy fix for me when I am back from vacation,
I can do a fix on my end for the adrdox bug Monday or Tuesday.

**Comment by burner** [comment]
in the phobos docs it look corrent

**Comment by ljmf00** [comment]
> in the phobos docs it look corrent

Yeah, this is just happening in [dpldocs](http://dpldocs.info/experimental-docs/std.experimental.logger.core.LogLevel.html) .

**Comment by ljmf00** [comment]
According to D Documentation Generator specs, the documentation is well written. So I will close this issue

**Pull request closed without merging**
