### PR TITLE
Delete the CircleCI pipeline.

### PR DESCRIPTION
**Pull request by deadalnix**
It uses a busted compiler.

If it cannot be fixed in a timely manner, it needs to go. It can always be added back later once the compiler situation is figured out.

### CODE REVIEW

**Review by dkorpel — APPROVED** [review]

**Comment by maxhaton** [comment]
all the CIs using dmd are broken by this measure

**Comment by ibuclaw** [comment]
> It uses a busted compiler.

Evidence?

**Comment by maxhaton** [comment]
> > It uses a busted compiler.
> 
> Evidence?

Its in reference to the bitmanip PR, it's apparently too unbelievable that dmd would be getting these wrong

**Comment by ibuclaw** [comment]
> > > It uses a busted compiler.
> > 
> > 
> > Evidence?
> 
> Its in reference to the bitmanip PR, it's apparently too unbelievable that dmd would be getting these wrong versus a regression

I've looked, and Cirrus, Buildkite, et alii fail on line 570.

https://github.com/dlang/phobos/blob/327bae55a8e4930b7b7fca4887ed53fb8e11dd6b/std/bitmanip.d#L559-L572

Circle fails on line 909

https://github.com/dlang/phobos/blob/327bae55a8e4930b7b7fca4887ed53fb8e11dd6b/std/bitmanip.d#L897-L910

This difference can be explained away by Circle only running the _documented_ unittests.  The test at 570 isn't documented.

**Comment by deadalnix** [comment]
I maintain my stance. The point of CI is the help build software harder, better, faster, stronger, whether you are a pair of French DJ robots or not.

If it doesn't do that, then it's not working. If it is not working it needs to either be fixed, or go if it cannot be fixed in a timely manner. It can always be readded once fixed. It's all in source control.

**Comment by deadalnix** [comment]
@maxhaton I'm going after Circle because I know for a fact that it is busted. I'm not sure why other are failing yet, but if it turns out they are busted too, then the same reasoning applies: they need to be either fixed in a timely manner, or go untill they are fixed.

**Comment by ibuclaw** [comment]
Stop with these outrageous lies now.

Mainline is passing all CircleCI tests: https://app.circleci.com/pipelines/github/dlang/phobos/6448/workflows/a67b4008-a745-46ae-ae54-6ad1ead90e42/jobs/15984
Stable is passing all CircleCI tests: https://app.circleci.com/pipelines/github/dlang/phobos/6424/workflows/d351f4c3-6e79-49e8-9b2a-1a96ede6883e/jobs/15951 

If your PR breaks pipelines, then it is your PR that is broken, not the CI.

**Comment by John-Colvin** [comment]
> Stop with these outrageous lies now.
> 
> 
> 
> Mainline is passing all CircleCI tests: https://app.circleci.com/pipelines/github/dlang/phobos/6448/workflows/a67b4008-a745-46ae-ae54-6ad1ead90e42/jobs/15984
> 
> Stable is passing all CircleCI tests: https://app.circleci.com/pipelines/github/dlang/phobos/6424/workflows/d351f4c3-6e79-49e8-9b2a-1a96ede6883e/jobs/15951 
> 
> 
> 
> If your PR breaks pipelines, then it is your PR that is broken, not the CI.

This is an overly dogmatic take imo. If a change surfaces a weird bug in a test then it could well be the right thing to just disable the test and let people get on with changes while the test is fixed (or not).

**Comment by ibuclaw** [comment]
> This is an overly dogmatic take imo. If a change surfaces a weird bug in a test then it could well be the right thing to just disable the test and let people get on with changes while the test is fixed (or not).

It's not a weird bug, it's simply how shifting works. ;-)

**Comment by deadalnix** [comment]
I cannot assert the PR doesn't break anything. I can assert the compiler is wrong on the tests for which is broken. The PR uses the `>>` operator purposefully, as sign extension for signed integer is expected. The CI pipeline breaks because the compiler used by the CI pipeline does sign extension for UNSIGNED integrals, which is definitively should not. I cannot assert that, if the compiler were to do the right thing with signed shifts, the PR wouldn't break something else. But there is just no way to know at this stage.

There are 2 course of action here:
1. The pipeline is updated to use a decent compiler in a timely manner.
2. The pipeline is removed, and possibly added back in later if someone fixes it.

I will not let this issue go, Everything being broken all the time is just a workable environment. Change has to happen one way or another.

**Comment by deadalnix** [comment]
> Stop with these outrageous lies now.
> 
> Mainline is passing all CircleCI tests: https://app.circleci.com/pipelines/github/dlang/phobos/6448/workflows/a67b4008-a745-46ae-ae54-6ad1ead90e42/jobs/15984 Stable is passing all CircleCI tests: https://app.circleci.com/pipelines/github/dlang/phobos/6424/workflows/d351f4c3-6e79-49e8-9b2a-1a96ede6883e/jobs/15951
> 
> If your PR breaks pipelines, then it is your PR that is broken, not the CI.

The fact that no code in mainline trigger the erroneous behavior is by no mean a proof that no such erroneous behavior exists. It is simply proof, that, in addition of the pipeline being busted, the test suite is lacking. Shooting the messenger doesn't reflect positively on you and I have to say I'm very disappointed because I have otherwise a very high opinion of you. I would prefer not to have to revise that judgement.

**Review by ibuclaw — CHANGES_REQUESTED** [review]
Well I hope you'll come to your senses soon enough.

**Comment by deadalnix** [comment]
Now that CircleCI runs a non busted compiler, this can be closed.

**Pull request closed without merging**
