### PR TITLE
Fix Issue 16006 - Investigate adding fork() to std.process

### PR DESCRIPTION
**Pull request by CyberShadow**
https://issues.dlang.org/show_bug.cgi?id=16006

Needs https://github.com/dlang/druntime/pull/1569

CC @MartinNowak @schveiguy

### CODE REVIEW

**Comment by schveiguy** [comment]
I think this is not a good idea. You are not supposed to use anything in the forked process because you have no idea the state of any of the libraries. The OS pulls a bunch of rugs out from under a lot of things. In particular, I'm not sure removing all the non-running threads from the global array is a good idea. For example, this couldn't be used to implement Sociomantic's forking GC, since it needs the thread stacks of the other threads to scan them, and your call removes all that metadata!

On Mac OSX, the man page for fork includes this warning:

```
     There are limits to what you can do in the child process.  To be totally safe you should restrict
     yourself to only executing async-signal safe operations until such time as one of the exec functions
     is called.  All APIs, including global data symbols, in any framework or library should be assumed to
     be unsafe after a fork() unless explicitly documented to be safe or async-signal safe.  If you need to
     use these frameworks in the child process, you must exec.  In this situation it is reasonable to exec
     yourself.
```

Really, the point of calling fork is to do some setup, and then call exec. Anything else is very dangerous to provide as a phobos-level call. Given that we have something that already does that, do we need to provide another way to do it? What is the use case here? What do we get beyond calling the posix system call?

Note, I'd rather see GC.runLocked be exposed than a direct lock/unlock call. Also note, if a deadlock can occur if you don't do it the right way, are we doing it the right way in our existing calls to fork? Is that a bug reported anywhere?

**Comment by CyberShadow** [comment]
> You are not supposed to use anything in the forked process because you have no idea the state of any of the libraries.

Not sure what you mean here.

> In particular, I'm not sure removing all the non-running threads from the global array is a good idea. For example, this couldn't be used to implement Sociomantic's forking GC, since it needs the thread stacks of the other threads to scan them, and your call removes all that metadata!

That's OK. Such low-level usage is not the target consumer for this function. The GC is in the runtime anyway, and can't call this Phobos function.

> On Mac OSX, the man page for fork includes this warning:

I don't understand. Is `fork` so broken on OS X that it is unusable to be used the way it's intended to be used?

> Really, the point of calling fork is to do some setup, and then call exec.

Why is that?

> Anything else is very dangerous to provide as a phobos-level call.

That's OK. This function is dangerous, but can be used correctly. It is not the intent to provide a completely safe function, but a nicer wrapper around `fork` which makes it reasonably safe provided it is used correctly.

**Comment by CyberShadow** [comment]
> Given that we have something that already does that, do we need to provide another way to do it?

What do we have? Do you mean the C `fork` call? This does some things in addition to that.

> What is the use case here?

Forking, in a way that doesn't break the GC / Druntime.

> Also note, if a deadlock can occur if you don't do it the right way, are we doing it the right way in our existing calls to fork?

We should be fine as long as we don't allocate between `fork` and `exec`.

There are actually some OS X `fork`/`exec` bugs reported, but I don't have an OS X machine set up currently.

**Comment by CyberShadow** [comment]
In either case, `fork` should be completely safe when used in single-threaded applications, and there is no reason we should not support that use case at least. Currently, this is too onerous, one reason being is that you cannot construct a `Pid` yourself, and thus can't use the Phobos `wait` / `tryWait` functions.

Looking around a bit more regarding `fork` on OS X:

http://stackoverflow.com/questions/18854708/why-is-it-prohivited-to-use-fork-without-exec-in-mac

It seems that the emphasis is on the "to be completely safe" However, the entire thing is incredibly vague. File handles and sockets are duplicated, so there should be no dangling file descriptor issues. All memory is duplicated, so there should be no issues with memory safety. We could upgrade the warning on the documentation and advise against combining `fork` with threads completely, or hell even throw if the application has more than one thread, but this all smells a bit like FUD to me right now. What exactly will break???

I've read this article before submitting the PR:

http://www.linuxprogrammingblog.com/threads-and-fork-think-twice-before-using-them

It seems we cover all cases here (either via documenting them or otherwise). Additionally, as I mentioned in the Druntime PR, I believe glibc's fork will take care of the `malloc` lock too.

**Comment by schveiguy** [comment]
> We should be fine as long as we don't allocate between fork and exec.

The code should probably be marked `@nogc`.

**Comment by CyberShadow** [comment]
> The code should probably be marked @nogc.

Good idea. I'll send a PR. In fact, I already found a bug.

**Comment by CyberShadow** [comment]
https://github.com/dlang/phobos/pull/4298

**Comment by schveiguy** [comment]
I'm not really saying that we necessarily cannot provide a mechanism to do this, in fact, I think it should be at least *possible* to do this (whereas without the exposure of the GC lock, it's not possible). I think providing a way to call fork that returns a Pid is helpful because you have other functions that deal with this (on the parent process side). I just don't know that we need to put too much machinery in it. If there's any way we can just give the tools to do this without assuming too much about the caller, then we should go for that.

**Comment by CyberShadow** [comment]
Well, the main issue with handing this off to the user is that the user may not know what exactly they have to do to "get it right". Acquiring the GC lock is certainly not obvious, and in fact dangerous because it may look like it "works" in a naive test. In the future, we may want to add more machinery to Druntime which needs to be fork-aware, at which point we can neatly integrate it into our nice `fork` wrapper.

I agree that a Phobos `fork` only makes sense if typical D programs can use this function more-or-less safely, and this seems to be true at least for single-threaded programs, possibly also multi-threaded programs which do not use external C libraries or unusual OS facilities.

**Comment by schveiguy** [comment]
If you do fork and then exec (without calling GC), then it is actually correct. One may still want Pid niceties in the parent, while doing their own custom setup of the subprocess, without having to lock the GC.

Things are so hairy here, that it's difficult to explain how to do this "correctly" :)

**Comment by CyberShadow** [comment]
For `fork`+`exec`, we have the `spawnProcess` et al. The intent of this function's usage is for all other uses of `fork`, i.e. those which are *not* followed by `exec`, i.e. the classical UNIX multi-tasking model (without threads).

My particular use case is adding multi-threading to DustMite. Although I could rewrite the program to use threads / run multiple processes directly / etc., a much easier way would be to fork off, run a "what-if" simulation, and report the result to the parent. CoW-ing the entire memory is the crucial `fork` feature that's not provided by other facilities.

**Comment by schveiguy** [comment]
Right, but my quesiton is, if you could lock the GC (e.g. if dlang/druntime#1569 goes through), do we need this too?

**Comment by CyberShadow** [comment]
Yes, I think so, but maybe I don't fully understand your question because I thought I already answered it [here](https://github.com/dlang/phobos/pull/4294#issuecomment-218213562). However, we will not be adding a GC.lock primitive, since as it has been pointed out it leeks too much implementation detail. What I will most likely do (after sorting out the [nothrow mess](http://forum.dlang.org/post/ikustnbyaonhbacjvrdq@forum.dlang.org)) is move most of the code into Druntime, and only leave the `Pid` wrapping in Phobos. This allows leaving the GC locking and such as a Druntime implementation detail.

**Comment by schveiguy** [comment]
I think having a GC-friendly wrapper in druntime is a good compromise.

**Comment by d-random-contributor** [comment]
I'd say it should be clarified in documentation that it's meant to be used in a unix-style application simply preserving druntime infrastructure.

**Comment by MetaLang** [comment]
@CyberShadow what's the status of this? Can it be closed in lieu of a Druntime PR instead, or do you still have plans for this?

**Comment by CyberShadow** [comment]
> Can it be closed in lieu of a Druntime PR instead,

Yep, let's close this for now.

**Pull request closed without merging**
