### PR TITLE
Write functions should handle invalid bool values properly

### PR DESCRIPTION
**Pull request by Bolpat**

### CODE REVIEW

**Comment by dkorpel** [comment]
I don't think this is the right place. `format` is not a compiler intrinsic, it is a library function that should be able to assume that its argument's type invariants hold. You wouldn't expect `format` to debug dangling pointers either. This PR is essentially unittesting undefined behavior. It's also using `__bool(0xFF)` syntax which is not supported by the language or `std.format.read`.

I'd say the issue is WONTFIX.

**Review by thewilsonator — APPROVED** [review]

**Comment by thewilsonator** [comment]
`std/format/internal/write.d(50:34)[warn]: An assert should have an explanatory message`

**Review by Geod24 — CHANGES_REQUESTED** [review]
If we can't rely on `bool` being either `true` or `false` we've lost.

**Comment by ntrel** [comment]
> If we can't rely on bool being either true or false we've lost.

Only in `@safe` code. How about we throw an `Error` showing the byte value? (no need for hex IMO).

**Comment by Geod24** [comment]
> How about we throw an `Error` showing the byte value? (no need for hex IMO).

We have tried that idea with signaling NaN a long time ago. Didn't work.

**Comment by Bolpat** [comment]
@dkorpel wrote:
> You wouldn't expect `format` to debug dangling pointers either.

Well, it can’t, or can it? There’s a difference if something isn’t done because it can’t be done or if it’s not done although it can be done.

@dkorpel wrote:
> This PR is essentially unittesting undefined behavior.

You’re mistaken on what is undefined here. Creating an invalid `bool` isn’t undefined, _reading_ an invalid `bool` as a boolean is undefined. In a union which overlaps a `bool` and a `ubyte`, writing the `ubyte` is even `@safe`, although it creates an invalid `bool`. `@safe` only won’t let you access any `bool` that might not be 0 or 1. 

@Geod24, in `@system` code, a `bool` that’s not 0 or 1 simply can happen, usually by accident, or because someone wants to see what happens (which is how I got to this).

I’d rather still have `std.format.write` write an invalid `bool` as anything but `false` and `true` than writing them as either of them, for the simple reason that both `true` or `false` would be a lie, even if `std.format.read` returns any non-zero value as `true`. Writing it an invalid bool as if it’s a `ubyte` is better, but still subobtimal, as it could be conflated with a valid integer value. If you see `__bool(0x02)` in your output, you know something is off. You can suggest something different, I just picked something that would stand out.

If we want to argue technically, well, _technically_ UB also permits write-formatting an invalid `bool` as anything we like, so why not choose something helpful? As for the asymmetry of reading and writing, of course, `std.format.read` shouldn’t create invalid `bool` values from any input because those reading functions would then have to be `@system`. This means that invalid `bool` values don’t round-trip, which is perfectly okay as that requires reading them and that is UB. (Apart from that, not even in `@safe` functions do all built-in values round-trip, e.g. NaN values with payload.) I’d consider the fact that invalid `bool` values don’t round-tip as a win, actually.

**Comment by Geod24** [comment]
Remind me, why do we have invalid bool in the first place ? Why is `true` defined as `0x01` and not "anything but `0x01`" ?

**Comment by Bolpat** [comment]
There is no easy way to create invalid `bool` values.
Instead of <code>__bool(*hexValue*)</code>, we could print just the unsigned value. Printing <code>{ ubyte b = *hexValue*; return \*cast(bool\*) &b; }()</code> is a non-starter IMO.

**Comment by thewilsonator** [comment]
> Why is true defined as 0x01 and not "anything but 0x01" ?

Surely you mean "anything but `0x00`"

**Comment by Geod24** [comment]
@Bolpat : That doesn't answer the question. Why do we entertain `bool` having more state than `true` or `false` ?

**Comment by dkorpel** [comment]
> You’re mistaken on what is undefined here.

Your unittest asserts that `(cast(byte) __bool(0x03)) == 3`. This happens to work, but if the compiler changes its implementation of `cast`,  suddenly Phobos' test suite breaks. I've had the 'pleasure' of deleting such unittests relying on unspecified behavior  before, I don't want more of them.

**Comment by dkorpel** [comment]
I don't think this is worth a long discussion, perhaps @atilaneves can make an executive decision and we'll leave it at that?

**Comment by Bolpat** [comment]
> Remind me, why do we have invalid bool in the first place ? Why is `true` defined as `0x01` and not "anything but `0x01`" ?

We _have_ invalid `bool` values due to `@system` code. How we _treat_ them is a different story.

First things first, I tried to get an invalid `bool` at CTFE and it didn’t work; apparently, at CTFE, `bool` values behave exactly like you suggest and most people intuitively assume they do. At run-time, it’s more complicated.

At the moment, `true` isn’t simply defined as `0x01`. It’s unfortunately weirder. For most cases, `true` is basically defined as _is odd._ I could identify three cases:
1. Converting a non-`bool` value to `bool` is an *equals-zero* test. (Indeed, for floating-point data, `-0.0` is `false`.)
2. Copying a `bool` to a `bool` or an 8-bit integer type (`byte` or `ubyte`) is an exact bit-copy.
3. In all other cases, when reading a `bool`, it is masked for the last bit, i.e. it has `x => x & 0x01` applied. This includes:
    * converting a `bool` to a non-`bool` of size > 8 bit (e.g. `int`) explicitly through a `cast` or implicitly including using arithmetic on it
    * `if`/`while`/`switch` testing, and
    * comparing `bool` values.

While 1. and 2. can be explained because it’s a no-op, why 3.?

Of course, the cheapest treatment of `bool` would be to treat it like `ubyte` in essentially all cases except for assignment as in 1. above, and IIRC, this actually is how it was. Unfortunately, that makes invalid `bool` values break value-range propagation and some other things, which lead to `@safe` code not actually being UB-free. The most correct solution, as you say, is to apply <code>… !*is* 0</code>¹ when a `bool` value is read. IIRC, Walter took issue with that because he deemed it too expensive, I guess both to run it in the generated binary and to implement optimizations that track a `bool` value’s origin so that the test can be optimized away in most cases.

A middle ground was found (not to say agreed upon) in that `bool` values should be masked with `0x01` when used, instead of being zero-tested.

A concrete situation where the difference shows would be when comparing two `bool` values: By your suggestion, `a == b` would, essentially, become <code>(a !*is* 0) is (b !*is* 0)</code>¹ because any two non-zero `bool` values should compare equal. Every <code>!*is* 0</code>¹ (in x86 assembly) is two instructions: a test (`test` or `cmp`) and a conditional set (`setne`). Walter made it be `(a & 0x01) is (b & 0x01)`. That is more expensive than <code>a *is* b</code>,¹ but ticks the box of `bool` values being in-range as far as value-range propagation is concerned.

There are three ways for `a == b` to be implemented:
* As <code>a *is* b</code>¹, in assembly: (load―load―)compare
* As `(a & 0x01) is (b & 0x01)`, in assembly: (load―)mask―(load―)mask―compare² or (load―load―)xor―not―and³
* As <code>(a !*is* 0) is (b !*is* 0)</code>¹, in assembly: compare―set―compare―set―compare⁴

The number of instructions is quite different.

I don’t know why Walter doesn’t leave optimizing the comparison to the optimizer or the programmer and have correct code be generated.

You asked for why, and to the best of my knowledge, this is why. If someone knows better, let me know. Nothing of this is my opinion, by the way. I just recognize that we _have_ invalid `bool` values in the language semantics and this PR just tries to help programmers to deal with them.

¹ This is not how `is` works for `bool` at the moment, you need to insert `cast(ubyte)` before every `bool`. Those `is` instances are italic: *`is`*
² `and a,0x01`―`and b,0x01`―`cmp a,b` – this is the obvious variant
³ `xor a,b`―`not a`―`and a,0x01` – this is what GCC does on O3
⁴ this is both the obvious variant *and* what GCC does on O3

**Comment by atilaneves** [comment]
I second @dkorpel

**Comment by Geod24** [comment]
> You asked for why, and to the best of my knowledge, this is why.

Thanks, that was both comprehensive and easy to read. The conclusion I draw here is that we should have a discussion with Walter, because performance should not trump correctness.

**Comment by ntrel** [comment]
> > How about we throw an `Error` showing the byte value? (no need for hex IMO).
> 
> We have tried/explored that idea with signaling NaN a long time ago. Didn't work.

I don't mean on every read of an invalid bool. I mean throw when calling `write` on the bool.

**Pull request closed without merging**
