### PR TITLE
Fix Issue 18760 - theAllocator dangling reference bug

### PR DESCRIPTION
**Pull request by edi33416**
This fixes the following bug

```
    import std.experimental.allocator.mallocator : Mallocator;

    auto a = sharedAllocatorObject(Mallocator.instance);
    auto buf = theAllocator.allocate(42);
    processAllocator = a;
    theAllocator.deallocate(buf);
```

### CODE REVIEW

**Comment by JackStouffer** [comment]
This should have a bug report.

**Comment by edi33416** [comment]
> This should have a bug report.

I'll file one and then link this to it

**Comment by n8sh** [comment]
The auto-tester failure appears unrelated.

**Comment by edi33416** [comment]
@CyberShadow any idea why `DAutoTest` is failing?

**Comment by edi33416** [comment]
Got it. Apparently it's kicking quite a few PRs lately.

**Comment by jercaianu** [comment]
@edi33416 can you rebase please?

**Comment by andralex** [comment]
@CyberShadow can you please take a look at the failure?

**Comment by CyberShadow** [comment]
> @CyberShadow can you please take a look at the failure?

It looks like compilation or execution of `changed.d` failed, but there is nothing in the log to indicate why. Possibly the process died because of a signal, e.g. due to running out of memory.

**Pull request merged**
