### PR TITLE
Fix Issue 16587 - split("", "x") should be ""

### PR DESCRIPTION
**Pull request by CyberShadow**
This reverts commit b438bf5a0653b616ef6debe2a0dfe247d8fc5928.

https://issues.dlang.org/show_bug.cgi?id=16587

### CODE REVIEW

**Comment by CyberShadow** [comment]
I seriously cannot comprehend how all the reviewers of #4030 thought that breaking elementary code willy-nilly like this is OK at the point where we are today. D is no longer a toy language, please stop treating it like one!

**Comment by dcarp** [comment]
First this is inconsistent with the documentation:
```
If the empty range is given, the result is a range with one empty element. If a range with one separator is given, the result is a range with two empty elements. 
```

On the other hand with this PR these are not consistent:
```dlang
split(",,", ",")     => ["", "", ""]
split(",", ",")     => ["", ""]
split("", ",")     => []

split("ab", ",")     => ["ab"]
split("a", ",")     => ["a"]
split("", ",")     => []
```

I think that the original problem is that under the same name, the first three overloads keep empty string parts, but the forth overload filters them out.
In other languages, Python uses the same trick and Qt spends an extra parameter for this.

I propose to not merge this PR and in your code fix it by simply adding `.filter!(a => !a.empty)` as documented.

**Comment by CyberShadow** [comment]
> First this is inconsistent with the documentation:

Then fix the documentation.

> I think that the original problem is that under the same name, the first three overloads keep empty string parts, but the forth overload filters them out.

The argument of which one is more correct is irrelevant because we are not designing a new function, but changing the behavior of one that's been around for a decade.

> I propose to not merge this PR and in your code fix it by simply adding .filter!(a => !a.empty) as documented.

I propose that everyone involved take a stronger stance against breaking code arbitrarily. This is not just about my or your code, but everyone's using D. This is silent breakage, these should not be tolerated.

CC @andralex

**Comment by dcarp** [comment]
We can argue whether the code was not already broken by not following the documentation.

I think that there are more people writing code using the documentation of the library, that the ones knowing the actual implementation. Actually the former was the case when I found this inconsistency in my company's code base.

Moreover, the part documenting that and empty range returns a range containing an empty range dates to 2010 and at that time the implementation was as documentation. In 2014 (2.066.1) the implementation was still consistent (https://github.com/dlang/phobos/blob/v2.066.1/std/algorithm.d#L2731). Afterwards the unittest was removed and the implementation changed. So we are talking about silent breakage that happened two years ago.

**Comment by dcarp** [comment]
We can argue whether the code was not already broken by not following the documentation.

I think that there are more people writing code using the documentation of the library, that the ones knowing the actual implementation. Actually the former was the case when I found this inconsistency in my company's code base.

Moreover, the part documenting that and empty range returns a range containing an empty range dates to 2010 and at that time the implementation was as documentation. In 2013 (2.064) the implementation was still consistent (https://github.com/dlang/phobos/blob/v2.064/std/algorithm.d#L2372). So we are talking about silent breakage that happened three years ago.

**Comment by CyberShadow** [comment]
> We can argue whether the code was not already broken by not following the documentation.

No. No, you can't. The documentation is complementary, the real contract is dictated by the unit tests foremost (which you've decided to disregard) and how the code is used in the real world second.

> I think that there are more people writing code using the documentation of the library, that the ones knowing the actual implementation. Actually the former was the case when I found this inconsistency in my company's code base.

This is irrelevant. Just because your codebase contained a bug that was caused by wrong documentation is nowhere near an excuse of breaking the code for everyone else.

> Moreover, the part documenting that and empty range returns a range containing an empty range dates to 2010 and at that time the implementation was as documentation. In 2013 (2.064) the implementation was still consistent (https://github.com/dlang/phobos/blob/v2.064/std/algorithm.d#L2372). So we are talking about silent breakage that happened three years ago.

Is there perhaps a misunderstanding of what "breakage" actually means here? Wrong documentation is not "breakage"! Silently breaking existing working, debugged programs *is* breakage!

`split("", ",")` returned `[]` since the earliest downloadable D version (0.50). You wanting to change that *is* the breakage.

**Comment by dcarp** [comment]
> split("",  ",") returned [] since the earliest downloadable D version (0.50). ....

Why is this then passing in 2.064?

```dlang
a = null;
assert(equal(splitter(a, 0), [ (int[]).init ][]));
```

https://github.com/dlang/phobos/blob/v2.064/std/algorithm.d#L2372

**Comment by CyberShadow** [comment]
Hmm, no idea. My concern is mainly about `split` specifically (not `splitter`). Perhaps the trouble started when `split` was reimplemented on top of `splitter`. Once this revert is in, I suppose we could look for a solution that doesn't break `splitter`, but this doesn't change everything I've already said.

**Comment by CyberShadow** [comment]
> Why is this then passing in 2.064?

Found it.

2.064's `splitter` was inconsistent depending on the type:

```
	assert("".splitter(",").walkLength == 0); // OK
	assert((int[]).init.splitter(0).walkLength == 0); // Assertion failure
```

It was fixed in this PR: https://github.com/dlang/phobos/pull/1502

**Comment by andralex** [comment]
The basic idea with splitter's definition is to generally not lose information, i.e. be able to join back a split range from its split form. If the given range is empty, it may be split two ways in such a way that the original is restored. So I'd say we're fine and the simplest way to go is change the documentation.

**Comment by jmdavis** [comment]
I never liked the idea that `splitter` was changed so that splitting an empty range could actually result in a non-empty range. That just seems totally illogical to me. So, it sure doesn't hurt my feelings any to see the old behavior restored.

**Comment by jondegenhardt** [comment]
PR #4030 was better in at least one common splitter use case - line-by-line processing typified by delimited files. In these files there is a table of rows and columns. Rows delimited by newline, columns by a separator character. If there are N columns, there are N-1 delimiters per line. Entries are typically allowed to be empty, this is designated by a consecutive separators or a separator at the beginning or end of a line. Example, using comma:
```
a,b,c
a,,c
,,
```
Running splitter on each line yields a range of three elements. The elements may be an empty string. However, there is a nasty special case, that of a 1-column file. For example:
```
a

c
```
This is also a three line file, but the second line is empty. Meaning, it should represent the empty element. However, running the pre PR #4030 split/splitter yields ranges that are either 0 or 1 element. This is an easy to miss difference from the 2+ column case, where the ranges are all the same length.

This sort of inconsistency is exactly what all the comments in PR #4030 are referring to. The PR ensures consistent behavior along these lines. I've used strings in the above example, but the same thing happens with other data types. However, the string case is the common case, and splitting on delimiters is a common use case.

Conceptually - The pre PR #4030 code was dropping valid content, zero length ranges, and dropping them in an inconsistent way, as it was dropping it them only if there is a single range.

@jmdavis - Note that splitter creates a range of ranges. The outer range holds the component ranges, this includes empty ranges. So, creating a range which holds a single element that is itself an empty range is not a case of creating something out of nothing. It's simply wrapping the original empty range in another.

Naturally, the reason I know about this is that I've had to test for this case specially in my programs. I would prefer to see the PR #4030 restored. Another possibility would be to add another option that determines whether to retain empty ranges. However, that's also problematic, because being consistent and dropping all empty ranges would be inconsistent with the previous behavior as well.

**Comment by andralex** [comment]
@jondegenhardt that's good evidence, though that's arguably less important than preserving existing behavior. Code that needs to handle things the other way may just insert an `if`.

@dcarp can you please submit a PR for the documentation and then mark https://issues.dlang.org/show_bug.cgi?id=15735 as closed? Thanks!

**Comment by CyberShadow** [comment]
@jondegenhardt All good points, but this still ends up being a choice between:

- Improving one function or overload at the expense of inconsistence with similar functions (see https://issues.dlang.org/show_bug.cgi?id=16587)
- Changing even more functions and risk breaking even more code
- Leaving things as they are and documenting the corner case.

If we were designing a new function or language, it would be a much easier choice; however, as I mentioned, `split` has been around for over a decade, and this change is very likely to affect code out there (see https://issues.dlang.org/show_bug.cgi?id=16587#c1).

Besides, if the code expects a `split`'d array to have at least 1 element and attempts to access it, it will crash with a range violation, which is much easier to debug than if the change had been made in the other direction.

**Comment by jondegenhardt** [comment]
@andralex @CyberShadow - Agreed, it's a tradeoff between preserving behavior of existing code vs avoiding unexpected behavior for new users. It's a judgement call. In this case it's even a bit trickier call, as the change may affect existing code with undetected bugs. e.g. a fragment like:
```
size_t c = 0;
foreach(line; stdin.byLine) line.splitter(',').each!(delegate(x) { c++; });
```
intended to count the number of fields in the input, contains a subtle bug that might never get detected by the author. Whether it's preferable to "fix" these cases in existing code, largely unannounced, is itself judgement call. For what's it's worth, I do appreciate that time has been taken to examine both sides in making a choice.

**Comment by MartinNowak** [comment]
Just to balance the sides here.

Plenty of us have heavy investments in D code and would be unable to maintain it if we returned to pre 2.060 bitrotting rates.
The example @CyberShadow gave `environment.get("LIBPATH", null).splitter(":")` is fairly convincing, even though it incorrectly handles `::` in LIBPATH. We also had similar tricky discussions about `if (array)` testing for null `.ptr` instead of zero `.length`.

OTOH working with splitter has many complex corner cases that make it error prone. Much like a for-loop w/ it's possible off-by-one errors, splitting/joining isn't such a simple tool as it might first appear.
Personally always get surprised by the empty trailing part a regex splitter can return https://github.com/MartinNowak/dlang-bot/commit/fe0707714a72b95c3b858d9a00e05bfced70f71f, where `"a,".split(",")` obviously contains 2 csv columns ;).

> I think any code that processes splitter has to handle the case that there is an empty element anyway.

I couldn't have come up w/ such a good counterexample as Vladimir's myself, but this sentence should've raised an eye for being [motivated reasoning](https://en.wikipedia.org/wiki/Motivated_reasoning). This is normal human behavior and often can't be seen by the reasoning person.
Recommended (short) talk on the topic [Julia Galef: Why you think you're right -- even if you're wrong](https://www.ted.com/talks/julia_galef_why_you_think_you_re_right_even_if_you_re_wrong).

Any variation of "code that's broken by this was already incorrect" should raise a red flag.
We should probably program a bot to detect it ;).

**Comment by dcarp** [comment]
> @jondegenhardt that's good evidence, though that's arguably less important than preserving existing behavior. Code that needs to handle things the other way may just insert an if.

... then let's insert the `if` in the implementation of `split`. @CyberShadow complained about `split`, and not about `splitter`. With the time `split` will be probably used less and less.

> @dcarp can you please submit a PR for the documentation and then mark https://issues.dlang.org/show_bug.cgi?id=15735 as closed? Thanks!

If this @PR stays like this, I'm ok with that, but don't expect me to document the choice that I don't like.

**Pull request merged**
