### PR TITLE
Generator implements InputRange interface

### PR DESCRIPTION
**Pull request by dukc**
Reboot of https://github.com/dlang/phobos/pull/5194

### CODE REVIEW

**Comment by dukc** [comment]
ping @wilzbach

**Comment by dukc** [comment]
ping @JackStouffer

**Comment by dukc** [comment]
Ignored, so I close. Perhaps i'll try again some day.

**Comment by JackStouffer** [comment]
Sorry about this. I am currently juggling work and school so I only have time to review trivial PRs.

Please understand that if a PR is in the queue and there are no blocking issues, it will get reviewed eventually.

**Comment by dukc** [comment]
Well, it ain't ignored anymore, so I can reopen...

It does not matter per se, i'm not in a hurry to get this in. I just don't want it to become one of those dead pr-s littering the queue.

**Comment by dukc** [comment]
I have long since stopped checking this back often enough. If somebody made a comment on this it could well take weeks for me to notice. I close this, for now.

**Comment by MetaLang** [comment]
@dukc if you still want to go ahead with this, I don't have merge privileges but I will review it and try to help push it through. If not, I will re-submit it on your behalf.

**Comment by quickfur** [comment]
@MetaLang  I agree this should be resubmitted.  I think it's worthwhile pursuing; I feel sorry that nobody had the time to review it. If only I had more free time...

**Comment by dukc** [comment]
Reopened here: #5515 

this time i'll notify on the forums before closing it, I promise.

**Comment by WalterBright** [comment]
Please don't close good work.

**Pull request closed without merging**
