### PR TITLE
Fix Issue 16413 - multiSort doesn't work with @system comparison function

### PR DESCRIPTION
**Pull request by John-Colvin**
Title says it all, I think

### CODE REVIEW

**Comment by wilzbach** [comment]
The CircleCi failure is unrelated (see #4748 for a fix).

@John-Colvin 
1) Would you be so kind to add a unittest for both cases to prevent regressions? 
2) Can you quickly file an issue, s.t. the dlang-bot recognizes this and shows it in the bugfix changelog?

Otherwise LGTM, of course.

**Comment by John-Colvin** [comment]
done

**Comment by andralex** [comment]
Auto-merge toggled on

**Comment by wilzbach** [comment]
> Can you quickly file an issue, s.t. the dlang-bot recognizes this and shows it in the bugfix changelog?

For the future: the commit message needs to contain the reference to the issue, the title is not parsed at the moment.

**Comment by lodo1995** [comment]
@John-Colvin The autotester doesn't like this PR. The unittest added in the second commit does not compile. Can you have a look at this again?

**Comment by John-Colvin** [comment]
I think that is caused by https://issues.dlang.org/show_bug.cgi?id=16179

**Comment by John-Colvin** [comment]
I can't get phobos to pass tests even without this pull...

**Comment by lodo1995** [comment]
> I think that is caused by https://issues.dlang.org/show_bug.cgi?id=16179

I see. @wilzbach can you have a look?

> I can't get phobos to pass tests even without this pull...

And... that's strange...

**Comment by John-Colvin** [comment]
Ok so `make -f posix.mak unittest` works but `make -f posix.mak std/algorithm.test` or `make -f posix.mak std/algorithm/sorting.test` fails at `std/algorithm/sorting(2265)`. This is without this pull though, so looks like it's an unrelated bug.

**Comment by wilzbach** [comment]
> Ok so make -f posix.mak unittest works but make -f posix.mak std/algorithm.test or make -f posix.mak std/algorithm/sorting.test fails at std/algorithm/sorting(2265). This is without this pull though.

Yep that's a well known issue, even though I can only find the older issue with std.numeric at the moment:

https://issues.dlang.org/show_bug.cgi?id=16227

(it fails due to some weird behavior/compiler bug of the entropy function)

**Comment by wilzbach** [comment]
> I think that is caused by https://issues.dlang.org/show_bug.cgi?id=16179

@John-Colvin the fix is in master, could you please rebase? :)

**Comment by John-Colvin** [comment]
https://github.com/dlang/phobos/issues/4740 fixed the bug, this is just the test now. Should be good to go.

**Comment by wilzbach** [comment]
> #4740 fixed the bug, this is just the test now. Should be good to go.

It has already been on auto-merge on, so it will be merged soon ;-)

image

**Pull request merged**
