### PR TITLE
compile Phobos with -dip1000

### PR DESCRIPTION
**Pull request by WalterBright**
Here to gauge progress in getting Phobos to work with -dip1000

### CODE REVIEW

**Comment by andralex** [comment]
Auto-merge toggled on

**Comment by JackStouffer** [comment]
Auto-merge toggled off

**Comment by JackStouffer** [comment]
No need to prioritize this in the auto tester just yet.

**Comment by nordlow** [comment]
@klickverbot https://github.com/dlang/DIPs/blob/master/DIPs/DIP1000.md#mangling

**Comment by nordlow** [comment]
You mean if the same D source code compiled into two objects files, one with -dip1000 and one without are replaceable? I'm guessing the `M`-qualifier is added to the mangling of parameters that have their scope inferred in the `-dip1000`-version but not in the other.

**Comment by MartinNowak** [comment]
Yes, they are ABI compatible.

We recently fixed a related issue caused by return inference ([Issue 17123 – [REG 2.073] Issues with return @safe inference](https://issues.dlang.org/show_bug.cgi?id=17123)).
The solution to the ABI change is straightforward, always _infer_ return, but _only enforce_ it when using `-dip1000`.

**Comment by MetaLang** [comment]
@WalterBright what's the status of this?

**Comment by JackStouffer** [comment]
See the discussion here on why this isn't viable at this point: https://github.com/dlang/phobos/pull/5915

**Pull request closed without merging**
