### PR TITLE
[std.regex] Disable Bit-NFA in CTFE

### PR DESCRIPTION
**Pull request by DmitryOlshansky**
Should fix out of memory problems with ctRegex.

### CODE REVIEW

**Comment by MartinNowak** [comment]
thx

**Comment by MartinNowak** [comment]
Mmh, seems like this didn't fully resolve the problem.
Just tested with the latest [nightly](https://nightlies.dlang.org/dmd-master-2016-10-30/).
```d
import std.regex;
enum notAlnum = ctRegex!(`[^0-9|a-z|A-Z]`, "g");
```
Unfortunately have no time to debug this further atm.

**Comment by MartinNowak** [comment]
Ping @DmitryOlshansky, still fails and we soon want to branch 2.073. Please resolve or we'll have to revert it for now.

**Comment by DmitryOlshansky** [comment]
Can't guarantee much time during the next week, if need branching away new version in this time frame then do the revert.

**Pull request merged**
