### PR TITLE
std.math: Fix log coefficiants for 128-bit implementation

### PR DESCRIPTION
**Pull request by ibuclaw**
- logCoeffsR is upside down.
- logCoeffsS has a `,` bug (and subsequently the wrong size).

Tested on aarch64-linux-gnu, no std.math tests are failing after applying this.

### CODE REVIEW

**Comment by ibuclaw** [comment]
FYI @kinke

**Comment by kinke** [comment]
[LDC uses LLVM intrinsics for the log family IIRC, most likely just calling C `logl`.]

**Review by dnadlinger — APPROVED** [review]

**Comment by dnadlinger** [comment]
Huh, I thought I tested these on AArch64 a few years ago, but clearly that can't be the case – perhaps we had a bug in the unit test runner back then making this invisible… I haven't checked this on LDC, but merging anyway as I trust your GDC results.

**Comment by ibuclaw** [comment]
Auto-merge toggled on

**Comment by ibuclaw** [comment]
Auto-merge toggled off

**Comment by ibuclaw** [comment]
Restarting auto-testers, as the network on one of the boxes is being flaky.

**Pull request merged**
