### PR TITLE
Fix Issue 13572: etc.c.zlib must be nothrow

### PR DESCRIPTION
**Pull request by JackStouffer**

### CODE REVIEW

**Comment by ZombineDev** [comment]
Yay, more attributes! LGTM

**Comment by d-random-contributor** [comment]
AIU, zalloc and zfree are used by zlib to initialize the stream state. Now they can't allocate from GC?

**Comment by schveiguy** [comment]
@d-random-contributor `nothrow` is not `@nogc`

**Comment by schveiguy** [comment]
Auto-merge toggled on

**Pull request merged**
