### PR TITLE
std.net.curl: RFC link at HTTP client docs is broken

### PR DESCRIPTION
**Pull request by zaydek**
Please update link so it's clickable

### CODE REVIEW

**Comment by CyberShadow** [comment]
Fixed that for you!

**Comment by wilzbach** [comment]
> continuous-integration/jenkins/pr-merge — This commit cannot be built

Hmm ...

Btw, while not intended as a proper solution, the Dlang-Bot might [soon](https://github.com/dlang-bots/dlang-bot/pull/109) understand commands like:
- please squash this PR ("bot-squash")
- please rebase this PR ("bot-rebase")

Especially the later is unfortunately currently commonly needed on PRs.

**Comment by wilzbach** [comment]
(rebased to rekick Jenkins and used this opportunity to rebase the PR to `stable` and squash the commits, i.e. drop the comment).

**Comment by wilzbach** [comment]
Rebased again. @CyberShadow imho either @MartinNowak agrees to temporarily disable DUB + Vibe.d tests or we set disable set the Jenkins project-tester to non required again. It's not really fun to rebase a PR 3-4 times just to get it to pass at the project-tester ....

**Comment by wilzbach** [comment]
> imho either @MartinNowak agrees to temporarily disable DUB + Vibe.d tests or we set disable set the Jenkins project-tester to non required again. It's not really fun to rebase a PR 3-4 times just to get it to pass at the project-tester ....

image

CC @CyberShadow 

Also it seems that there's something wrong with the auto-tester - it doesn't detect this PR (it's not even listed).

**Comment by CyberShadow** [comment]
Could you email Martin and CC me? I think we need to do something about this *today*, but Martin isn't responsive to GitHub mentions.

**Comment by wilzbach** [comment]
> Could you email Martin and CC me? I think we need to do something about this today, but Martin isn't responsive to GitHub mentions.

Done.

**Comment by wilzbach** [comment]
> Also it seems that there's something wrong with the auto-tester - it doesn't detect this PR (it's not even listed).

Ping @CyberShadow @braddr - should we simply create a new PR?

**Comment by wilzbach** [comment]
This has been superseded by https://github.com/dlang/phobos/pull/5526

@zaydek thanks again for submitting this fix. I hope you weren't that frustrated by our temporary CI problems. We are looking forward to your next contribution ;-)

**Comment by braddr** [comment]
I don't see anything in the auto-tester logs to point to something going wrong, other than the lack of any attempts to build this pull request.  I see the record of it's existence and the edits to switch branches, update the head commit a few times, and add the merge label.  But no builds happened.  Next time you see this happen, let me know and I'll dig deeper.

**Pull request closed without merging**
