### PR TITLE
Changed zip and lockstep of std.range to assert same length

### PR DESCRIPTION
**Pull request by dukc**
…instead of enforcing. This is of course controversal since it's breaking but I decided it's worth a discussion. Isn't it after all clearly a bug if zipped ranges with `StoppingPolicy.RequireSameLength` have different lengths?

I made the same change for enforcement of `!stoppingPolicy != StoppingPolicy.Longest` for `LockStep` and enforcement of default-initializable elemets.

The advantages are that functions can be faster in production code and, in case of `zip`, `nothrow` can be inferred.

### CODE REVIEW

**Comment by dukc** [comment]
Such code is doubtlessly bug-prone since the length property does not check for all ranges, resulting in overflow sooner or later. But that makes the code no less existent...

**Comment by JackStouffer** [comment]
I can tell you from experience that Andrei will reject this due to its breaking nature, and I'd have to agree with him.

I would refactor this to add a new `StoppingPolicy` which gives this behavior.

**Comment by dukc** [comment]
Good idea, I think. Does not let us infer `nothrow`, though.

Already 3 to be considered against. Enough to convince me off.

**Comment by wilzbach** [comment]
FWIW [DIP1008](https://github.com/dlang/dmd/pull/6681) has been merged two days ago. So while you might not get `nothrow`, inference of `@nogc` due to Exceptions being `@nogc` might happen very soon ;-)

**Pull request closed without merging**
