### PR TITLE
path.d and uni.d: fix -dip1000 errors

### PR DESCRIPTION
**Pull request by WalterBright**
A start, anyway.

### CODE REVIEW

**Comment by WalterBright** [comment]
Hold off on this for a moment. I think I see a problem...

**Comment by MetaLang** [comment]
@WalterBright what's the status of this?

**Comment by MetaLang** [comment]
@WalterBright ping

**Comment by JackStouffer** [comment]
Closing due to inaction.

**Comment by quickfur** [comment]
What, why? Isn't pushing -dip1000 a priority?

ping @WalterBright

**Comment by JackStouffer** [comment]
For the record, there are other PRs on adding dip1000 to std.uni, one of which is Walter's, so I assumed that he forgot about this one.

**Comment by carblue** [comment]
The part "std/path.d" is not covered currently, whereas
the part "std.uni.d" is included in merged https://github.com/dlang/phobos/pull/6041

**Comment by wilzbach** [comment]
Closing as std.uni has been fixed in another PR and std.pathis addressed by https://github.com/dlang/phobos/pull/6357 and then it's `relativePath` left (which isn't addressed by this PR)

**Pull request closed without merging**
