### PR TITLE
Merge remote-tracking branch 'upstream/stable' into merge_stable

### PR DESCRIPTION
**Pull request by wilzbach**
https://github.com/dlang/phobos/pull/6017 back to `master`

See also: https://github.com/wilzbach/git-tools

### CODE REVIEW

**Comment by wilzbach** [comment]
This is required before we can improve `std.array.replace` to allow single elements.

See: https://github.com/dlang/phobos/pull/6017#issuecomment-356361420

**Comment by wilzbach** [comment]
Should I make `dlang-bot` auto-approve and auto-merge these merge PRs? (only if there weren't any conflicts, of course).

**Comment by quickfur** [comment]
Might be a good idea.  Let's see what @andralex thinks.

**Comment by wilzbach** [comment]
> Let's see what @andralex thinks.

I think we should better ask @MartinNowak who is our release tzar and also doing these merge back into `master` PRs.

**Comment by andralex** [comment]
I think it's a good idea, @MartinNowak should decide.

**Pull request merged**
