### PR TITLE
Revert #4273 + add tests

### PR DESCRIPTION
**Pull request by CyberShadow**
https://github.com/dlang/phobos/pull/4273

https://issues.dlang.org/show_bug.cgi?id=16514

### CODE REVIEW

**Comment by CyberShadow** [comment]
D'oh, wrong branch.

**Comment by wilzbach** [comment]
> D'oh, wrong branch

Since a couple of weeks it's possible to change the target branch ;-)

**Comment by CyberShadow** [comment]
Really?? Thanks, that's awesome

**Comment by wilzbach** [comment]
See: https://github.com/blog/2224-change-the-base-branch-of-a-pull-request

**Comment by schveiguy** [comment]
Does it rebase though? I've switched locally targeting a different branch, but it pulls in all kinds of unrelated commits. Usually, you have to do a rebase onto the new branch in order to get the right result.

**Comment by CyberShadow** [comment]
I'd rather rebase manually than have the web service rewrite my branch though. Not having to create a new PR and update all links in shame is much bigger though.

**Pull request closed without merging**
