### PR TITLE
std.math: deprecate backwards compatibility with Phobos1

### PR DESCRIPTION
**Pull request by 9il**
is____ functions in std.math

Depends on https://github.com/D-Programming-Language/dmd/pull/4090

### CODE REVIEW

**Comment by WalterBright** [comment]
These name changes have to stop. They're the poster boy for churn giving an "illusion of progress".

**Comment by WalterBright** [comment]
> Never underestimate learning curve damage of inconsistent naming.

I don't buy that. There's nothing "intuitive" or "consistent" with isNaN instead of isnan. (Googling it shows that isnan, isNaN, ISNAN, is-nan are common spellings in various languages.) There is, however, considerable ongoing damage with "my working code from 1 year ago  won't compile anymore because of gratuitous incompatible changes."

We ought to be working on things that matter, like making the documentation for isnan better, than just more wretched bikeshedding and breaking.

**Comment by yebblies** [comment]
> I don't buy that. There's nothing "intuitive" or "consistent" with isNaN instead of isnan.

Of course there is, because we have a naming style and `isnan` doesn't follow it.

**Comment by WalterBright** [comment]
> Of course there is, because we have a naming style and  isnan  doesn't follow it.

Then it should have been `isNan`. In any case, it's been `isnan` for 14 years. Breaking long standing, working, correct code like this for no good reason just annoys people. It wastes our time and every user's time. It must stop. I'd be shocked if isnan confused anybody.

**Pull request merged**
