### PR TITLE
Fix issue 17482: Fix Nullable!Variant equality checks.

### PR DESCRIPTION
**Pull request by jmdavis**

### CODE REVIEW

**Comment by jmdavis** [comment]
The circleci stuff seems to be complaining about something in std.json which wasn't even touched by this PR.

**Comment by RazvanN7** [comment]
I suggest adding a unittest which tests opEquals for other value types: structs and fixed length arrays.

**Comment by CyberShadow** [comment]
> The circleci stuff seems to be complaining about something in std.json which wasn't even touched by this PR.

Oops, that looks like my fault.

**Comment by wilzbach** [comment]
>> The circleci stuff seems to be complaining about something in std.json which wasn't even touched by this PR.
>Oops, that looks like my fault.

->  https://github.com/dlang/phobos/pull/5560

**Pull request merged**
