### PR TITLE
Move unit test so it makes it into the docs

### PR DESCRIPTION
**Pull request by schveiguy**
Followup to #4460

### CODE REVIEW

**Comment by schveiguy** [comment]
Don't pull. The docs aren't getting in yet. Going to fix that.

**Comment by schveiguy** [comment]
Auto-merge toggled on

**Comment by schveiguy** [comment]
Yay, now see the example text.

**Comment by schveiguy** [comment]
Auto-merge toggled off

**Comment by schveiguy** [comment]
OK, so editing with github puts in extra spacing. Going to fix. Grr....

**Comment by schveiguy** [comment]
Stupid github. I don't know how to squash this.

**Comment by Geod24** [comment]
> OK, so editing with github puts in extra spacing. Going to fix. Grr....

It also creates the P.R. branch in the upstream repo instead of your fork, so IMHO should be avoided anyway.

**Comment by schveiguy** [comment]
Yes, but only for repository contributors. For external people, it just creates a fork in their own account (I just realized this when I was doing this PR). That is really dumb IMO.

The nice thing about github editing for simple fixes is that you are done quickly. I'll probably still use it for doc changes.

**Pull request closed without merging**
