### PR TITLE
Fix Issue 20440 - Associative arrays of BigInt does not support require or get function

### PR DESCRIPTION
**Pull request by GoaLitiuM**

### CODE REVIEW

**Comment by Biotronic** [comment]
While this PR does fix the specific issue as described in the bug report, the underlying problem is in `require()`, as it will fail to compile for any type with an overloaded `opAssign` that doesn't return ref. D's own [operator overloading page](https://dlang.org/spec/operatoroverloading.html) uses `void` return type, so we obviously cannot expect `opAssign` to return ref.

In short: the proposed changes to `object.require()` also need to be done.

**Comment by GoaLitiuM** [comment]
I'll make the changes, but the new unittest is causing invariant to fail in `BigUint`.

**Comment by n8sh** [comment]
I agree with @Biotronic:
>The fix in PR 7312 only fixes this for BigInt specifically. If we are not going to require that opAssign return ref for every type, this should be fixed in druntime instead.
>In other words: this is a bug in require(), not in BigInt.

As such I'm proposing as an alternative https://github.com/dlang/druntime/pull/2869

**Comment by GoaLitiuM** [comment]
Closing for dlang/druntime#2869

**Pull request closed without merging**
