### PR TITLE
Remove unnecessary boolean from template for DirIterator

### PR DESCRIPTION
**Pull request by schveiguy**
I think this whole boolean is not necessary. I don't see how it helps. Going to see if this passes CI.

### CODE REVIEW

**Comment by pbackus** [comment]
> `generated/linux/release/64/../../../../../phobos/std/algorithm/iteration.d:1313: error: undefined reference to '_D3std4file__T12_DirIteratorZQp15__fieldPostblitMFNaNbNiNlZv'`
> `generated/linux/release/64/../../../../../phobos/std/algorithm/iteration.d:1311: error: undefined reference to '_D3std4file__T12_DirIteratorZQp11__fieldDtorMFZv'`


Looks like it was necessary.

**Comment by Geod24** [comment]
Git blame: https://github.com/dlang/phobos/pull/8368

**Comment by schveiguy** [comment]
It does not... but.. I'm very confused why it passes with the boolean and doesn't pass without.

**Comment by schveiguy** [comment]
@Geod24 I am aware of the origin. I'm trying to figure out how it works. Do you know? As far as I can tell, the boolean is not used anywhere, so I don't see why it matters.

**Comment by schveiguy** [comment]
A simple local test fails to link as well, even with the boolean in place.

**Comment by Geod24** [comment]
Most likely it is because Phobos is distributed compiled. So it includes a `dirEntry` symbol that has the non-DIP1000 ABI, because DIP1000 is not yet enabled. But as soon as you compile your code with `-dip1000`, the compiler expect a certain ABI, but the binary includes another, leading to linker error. Or at least that's the issue I remember with DIP1000 & Phobos.

**Comment by schveiguy** [comment]
Yes, it's a linker error. But the compiler invocation does not see the boolean in terms of how phobos is compiled, it sees it in terms of how the local module is compiled.

So why does it work? What special thing about this boolean makes it decide "aha! I need to emit something extra here"?

**Comment by schveiguy** [comment]
To me this looks like a compiler bug, with a weird workaround. But I don't have time to chase it. I was mostly just curious what the error was it is "fixing".

**Comment by Geod24** [comment]
Locally I have:
```
0000000000000000 W @trusted void std.file._DirIterator!(true)._DirIterator.__fieldDtor()
0000000000000000 W pure nothrow @nogc scope @trusted void std.file._DirIterator!(true)._DirIterator.__fieldPostblit()
```

A.k.a:
```
0000000000000000 W _D3std4file__T12_DirIteratorVbi1ZQt11__fieldDtorMFNeZv
0000000000000000 W _D3std4file__T12_DirIteratorVbi1ZQt15__fieldPostblitMFNaNbNiNlNeZv
```

Missing symbols:
```
_D3std4file__T12_DirIteratorZQp15__fieldPostblitMFNaNbNiNlZv
_D3std4file__T12_DirIteratorZQp11__fieldDtorMFZv
```

A.k.a:
```
pure nothrow @nogc scope void std.file._DirIterator!()._DirIterator.__fieldPostblit()
void std.file._DirIterator!()._DirIterator.__fieldDtor()
```

So it looks like an attribute mismatch ?

**Comment by pbackus** [comment]
The attribute mismatch is expected. What we don't understand is, why does the boolean fix it?

**Comment by dukc** [comment]
> The attribute mismatch is expected. What we don't understand is, why does the boolean fix it?

@pbackus @schveiguy I happened to stumble upon your related Discord discussion now, and consequently found this. I can explain. Steven's example:

```D
For context, this is my file: ```d
module lib;

private auto dip1000Test(int x) {return *&x;}

enum dip1000Enabled
    = is(typeof(&dip1000Test) : int function(int) @safe);

auto fun(bool useDIP1000 = dip1000Enabled)(int arg)
{
    pragma(msg, useDIP1000);
    int n = arg;
    scope int *p = &n;
    return *p;
}

alias realFun = fun!();
```

Assuming you tested this with call to `realFun` from the client code, you have instantiated the template in the library, with whatever DIP1000 flag the library compilation had. However, if you call `fun` from client code (or equally `dirEntries`) the template instantiation happens at the client code, along with it's `useDIP1000` setting.

I also saw the idea floated around that `fun` could simply be a template with NO parameters. This can in fact work, and was how I originally did it, but I felt the solution was too fragile. Quoting my comment from `useDIP1000` flag:

```D
// We don't use isSafe, because betterC client code needs to instantiate
// core.internal.array.comparison.__cmp in the client side. isSafe uses
// __cmp of two strings, so using it would instantate that here instead. That
// won't do because betterC compilations do not link the Phobos binary in.
package(std) enum dip1000Enabled
    = is(typeof(&dip1000Test) : int function(int) @safe);
```

I submit it sucks to avoid instantiating templates like this. If `dirEntries` template had no parameters, all other code in Phobos would have to avoid instantiating it like the Plague, or else get extremely cryptic linker failures in the test suite. The boolean template parameter makes this a non-issue.

**Comment by schveiguy** [comment]
The boolean doesn't matter. What matters is that it causes the compiler to emit the template instantiation from client code instead of assuming the library has already generated the code for it.

Why does it omit it when the boolean is missing? If you say it's because the compiler sees that the library has already instantiated it, well, that's the same thing as with the boolean! The client code sees what it *thinks* the library was built with based on the current command line flags. It can't know that the library was built with different flags.

Honestly, I wonder if you just replaced the boolean default value with a `true`, if it would work.

I suggest this whole thing is very fragile and probably based on a compiler bug.

**Comment by dukc** [comment]
> Why does it omit it when the boolean is missing? If you say it's because the compiler sees that the library has already instantiated it, well, that's the same thing as with the boolean! The client code sees what it thinks the library was built with based on the current command line flags. It can't know that the library was built with different flags.

I don't know for fact how it works, but I'd imagine the compiler simply keeps tracks of template attribute sets for each template that it has instantiated, and also stores that information to intermediate object files. Imagine:

```D
DFunctionAST[[string]][DSymbol[]] instancedTemplates;
```

Now, when the compiler looks at `phobos.a`, if the compiler ended up instancing `dirEntries` when precompiling it, it will find `instanceTemplates[["std", "file", "dirEntries"]][[DSymbol(true)]]`inside the binary. When compiling client code, the compiler will look for either that or `instancedTemplates[["std", "file", "dirEntries"]][[DSymbol(false)]]`, depending on the client code DIP1000 setting. If it doesn't match that of the precompiled binary, the template instances do not match and therefore the compiler correctly deems a new instance is needed.

The compiler doesn't know per se what settings Phobos was compiled with, but it (assuming my mental picture) knows what parameters the preinstantiated templates have used so it doesn't have to.

**Pull request closed without merging**
