### PR TITLE
[Issue 16170] Partial Fix for Broken std.algorithm.sorting.partition

### PR DESCRIPTION
**Pull request by JackStouffer**
Separate the various implementations of `std.algorithm.sorting.partition` into overloads.

In addition to this making the code more readable, this partially fixes issue 16170 by fixing bad constraints that were too permissive for some of the implementations. Also fixes going past the ends of ranges.

Unfortunately, the results partition gives for ranges are wrong, and I don't have the know-how to fix it. 

Example:

```
import std.stdio;
import std.internal.test.dummyrange;

static bool even(int a) { return (a & 1) == 0; }

auto data = new ReferenceBidirectionalRange!int([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]);
auto r = partition!(even)(data);
r.writeln;
```

prints

```
[6, 7, 8, 9, 10]
```

### CODE REVIEW

**Comment by JackStouffer** [comment]
Ping

**Comment by ntrel** [comment]
Please could you make PR titles more descriptive, it helps when browsing the PR queue. Thanks!

**Comment by 9il** [comment]
Please do not mix style fixes to bug fixes PRs

**Comment by JackStouffer** [comment]
@9il this is now only the style change. This will help the next step of fixing this.

**Comment by JackStouffer** [comment]
Now passing

**Comment by wilzbach** [comment]
> @9il this is now only the style change. This will help the next step of fixing this.

I remember that @andralex was making a point on hiding overloads from the user, but in this case it looks quite cleaner. What do you think @9il?

**Comment by 9il** [comment]
> I remember that @andralex was making a point on hiding overloads from the user, but in this case it looks quite cleaner. What do you think @9il?
>  Hide all checks

No idea

**Comment by andralex** [comment]
So what we have here is:

```d
Range partition(alias predicate, SwapStrategy ss, Range)(Range r)
    if (ss == SwapStrategy.stable && isRandomAccessRange!(Range) && hasLength!Range && hasSlicing!Range);
Range partition(alias predicate, SwapStrategy ss, Range)(Range r)
    if (ss == SwapStrategy.semistable && isInputRange!Range && hasSwappableElements!Range);
Range partition(alias predicate, SwapStrategy ss = SwapStrategy.unstable, Range)(Range r)
    if (ss == SwapStrategy.unstable && isInputRange!Range && hasSwappableElements!Range);
```

The question is which of these pertain to things the user cares about vs. matters pertaining to the implementation. From what I can tell the user has no interest in the fact that the implementation is different for semistable vs. unstable. User does care, however, that the restrictions for stable partitioning are more stringent. So how about we unify things like this:

```d
Range partition(alias predicate, SwapStrategy ss, Range)(Range r)
    if (ss == SwapStrategy.stable && isRandomAccessRange!Range && hasLength!Range && hasSlicing!Range);
Range partition(alias predicate, SwapStrategy ss, Range)(Range r)
    if (ss != SwapStrategy.stable && isInputRange!Range && hasSwappableElements!Range);
```

Nice?

**Comment by ZombineDev** [comment]
I suggest a single overload that uses ststic ifs internally to dispatch to the right implementation and static asserts to provide good error messages when incompatible template arguments are supplied.

**Comment by andralex** [comment]
@ZombineDev the "politically correct" way is to have the signature reflect the capability. It's how we do it everywhere in the library. Unless we make it a policy decision to use imprecise signatures and static assert, we should stay the course.

**Comment by JackStouffer** [comment]
@andralex Fixed

**Comment by andralex** [comment]
Auto-merge toggled on

**Pull request merged**
