### PR TITLE
std.logger default example does not work

### PR DESCRIPTION
**Pull request by MikeShah**
Example does not compile as provided. I believe you want 'logf' to otherwise have 'printf' style logging.

If this is accepted, I'll update the documentation below to reflect this is writing to stdout intead of stderr.

### CODE REVIEW

**Review by thewilsonator — CHANGES_REQUESTED** [review]
The example compiles for me, but does not print in either case. N.B the that the documentation is wrong, c.f. https://github.com/dlang/phobos/issues/10520

I was trying to figure out what I needed to set the global logLevel to in order to get the "no lo level" overload to actually print, but lost that train of though.

Also please adjust the PR title and commit messages to something more descriptive, and if it fixes that issue, say that.

**Comment by 0xEAB** [comment]
> I was trying to figure out what I needed to set the global logLevel to in order to get the "no lo level" overload to actually print, but lost that train of though.

The default logger used by `log` is an `StdForwardLogger` with a `LogLevel` of `all`.
<https://github.com/dlang/phobos/blob/9e7d2f37cfd36f42b7f2376ad07814297e40809f/std/logger/core.d#L1513>

This one forwards to `sharedLog` which defaults to a `FileLogger` with `LogLevel.info`.
<https://github.com/dlang/phobos/blob/9e7d2f37cfd36f42b7f2376ad07814297e40809f/std/logger/core.d#L1425>

**Review by 0xEAB — CHANGES_REQUESTED** [review]
I don’t see which issue is fixed by this change.
Neither version prints log message to the terminal in a default configuration.

**Comment by MikeShah** [comment]
It seems I still cannot get 'log' to write to standard error.

**Test program**
```
import std.logger;                                                                                                      
                                                                                                                        
void main() {                                                                                                           
// This is the trouble case, everything else seems fine.
log("Testing will never appear");       

                                                                                                  
logf("Logging to the sharedLog with its default LogLevel");                                                             
error("Logging to the sharedLog with its error LogLevel");                                                              
errorf("Logging %s the sharedLog %s its error LogLevel", "to", "with");                                                 
critical("Logging to the"," sharedLog with its error LogLevel");                                                        
fatal("Logging to the sharedLog with its fatal LogLevel");                                                              
}
```

Tried running and capturing standard error with the following.
`dmd logger.d && ./logger 2> err.log`

**Comment by 0xEAB** [comment]
> It seems I still cannot get 'log' to write to standard error.

That’s because your code does not change the log level of the logging backend. This defaults to `info` and therefore discards your `log()` and `logf()` messages which are logged with a level of `all`.

**Comment by 0xEAB** [comment]
```sh
$ cat test.d 
import std.logger;

void main() {
	(cast(Logger) sharedLog).logLevel = LogLevel.all;	
	log("log");
	logf("logf");
}
```
```sh
$ /opt/ldc2-1.39.0/bin/ldc2 -run test.d >/dev/null
2024-12-07T00:21:16.095 [all] test.d:5:main log
2024-12-07T00:21:16.095 [all] test.d:6:main logf
```
```sh
$ /opt/ldc2-1.39.0/bin/ldc2 -run test.d 2>/dev/null
```

**Comment by 0xEAB** [comment]
IMHO `log()` defaulting to `LogLevel.all` is atrocious.
But this PR does not address this issue and instead rewrites the out-of-date example (that  stems from a time when the default backend was configured to level `all`, I’ve been told) with a similar one.

Personally, I’d suggest to…
- Replace `log()` with `info()` in the “hello world” example.
- Or rework `log()` to be equivalent to `info()`. (Probably a task for Phobos 3?)

Not sure what others think about this topic, though.

**Comment by MikeShah** [comment]
I think changing the hello world example to your minimal hello world and also exposing the shared Logger would be a good idea.

Anyone wanting to use std.logger should be less surprised as I had been then :)

**Comment by atilaneves** [comment]
> Replace log() with info() in the “hello world” example.

This is what I would suggest.

**Comment by 0xEAB** [comment]
> > Replace log() with info() in the “hello world” example.
> 
> This is what I would suggest.

Implemented by #10582.

**Comment by LightBender** [comment]
I am closing this PR as it appears to be resolved by https://github.com/dlang/phobos/pull/10582

**Pull request closed without merging**
