### PR TITLE
Fix Issue 23922 - Fix broken links in std.socket

### PR DESCRIPTION
**Pull request by RazvanN7**

### CODE REVIEW

**Review by CyberShadow — APPROVED** [review]
OK but why not fix the macros?

**Comment by CyberShadow** [comment]
It's in dlang.org: https://github.com/search?q=repo%3Adlang%2Fdlang.org%20SAMPLESRC&type=code

**Comment by RazvanN7** [comment]
That's quite unexpected.

**Comment by CyberShadow** [comment]
Then you may be surprised to learn that `LINK2` is defined there as well :)

**Comment by RazvanN7** [comment]
I assumed that everything is defined in one place, I just used something that I know works. Anyway, better fix link then.

**Pull request closed without merging**
