### PR TITLE
Bugfix for "undefined identifier _min" in SharedFreeList.

### PR DESCRIPTION
**Pull request by chadjoan**
When instantiating SharedFreeList with a 0 minSize and a
chooseAtRuntime maxSize, it will give an error like so:

  std/experimental/allocator/building_blocks/free_list.d(822): Error: undefined identifier _min, did you mean alias min?

This commit resolves the error message by using 'min' instead
of '_min', because '_min' is only available when
(minSize == chooseAtRuntime).

### CODE REVIEW

**Comment by chadjoan** [comment]
Roger.  Hope that does it.

**Comment by RazvanN7** [comment]
You should try to rebase [1] . Hopefully that will get rid of the CyberShadow failure (you probably have an older version of phobos and the tools that come with it.)

[1] https://wiki.dlang.org/Starting_as_a_Contributor#Rebasing

**Comment by wilzbach** [comment]
> You should try to rebase 

Thanks to the CircleCi magic at https://github.com/dlang/phobos/pull/5559, simply restarting CircleCi should be enough (I just did this)

**Comment by CyberShadow** [comment]
> Hopefully that will get rid of the CyberShadow failure (you probably have an older version of phobos and the tools that come with it.)

I don't think that should cause the documentation tester to fail.

Please ping me if everything but the documentation tester is failing, and you think it shouldn't.

**Comment by chadjoan** [comment]
I squashed/rebased and added a test for min being chooseAtRuntime while maxSize is chosen at compile time.

**Comment by wilzbach** [comment]
> I squashed/rebased and added a test for min being chooseAtRuntime while maxSize is chosen at compile time.

Thanks. I also added `deallocateAll` on exit as, even if the sizes are small, it's a good practice to cleanup the "global state" one messed with after each tests.

**Pull request merged**
