### PR TITLE
Do not count if it is not necessary

### PR DESCRIPTION
**Pull request by kubo39**

### CODE REVIEW

**Comment by maxhaton** [comment]
Is there any point in doing this? If the function is told not to count, the count will never be returned and is thus eliminated by the optimizer. 

https://d.godbolt.org/z/8YKaTq9YW

**Comment by ljmf00** [comment]
> Is there any point in doing this? If the function is told not to count, the count will never be returned and is thus eliminated by the optimizer.
> 
> [d.godbolt.org/z/8YKaTq9YW](https://d.godbolt.org/z/8YKaTq9YW)

That doesn't generate naturally optimized code and this seems to be used just for debugging purposes, so I don't see the reason for the optimized take action on a clearly not used variable. I would rather suggest adding a `debug` block instead of `static if`, as it increases readability on explicitly marking it as `debug` code.

**Comment by maxhaton** [comment]
> > Is there any point in doing this? If the function is told not to count, the count will never be returned and is thus eliminated by the optimizer.
> > [d.godbolt.org/z/8YKaTq9YW](https://d.godbolt.org/z/8YKaTq9YW)
> 
> That doesn't generate naturally optimized code and this seems to be used just for debugging purposes, so I don't see the reason for the optimized take action on a clearly not used variable. I would rather suggest adding a `debug` block instead of `static if`, as it increases readability on explicitly marking it as `debug` code.

What is "that"? There is no way for the counter to be returned and it can therefore can be and is elided.

**Comment by ljmf00** [comment]
> > > Is there any point in doing this? If the function is told not to count, the count will never be returned and is thus eliminated by the optimizer.
> > > [d.godbolt.org/z/8YKaTq9YW](https://d.godbolt.org/z/8YKaTq9YW)
> > 
> > 
> > That doesn't generate naturally optimized code and this seems to be used just for debugging purposes, so I don't see the reason for the optimized take action on a clearly not used variable. I would rather suggest adding a `debug` block instead of `static if`, as it increases readability on explicitly marking it as `debug` code.
> 
> What is "that"? There is no way for the counter to be returned and it can therefore can be and is elided.

I meant the previous code. If you compile it without optimizations, the compiler will generate those calls. The right way to do it, mainly for readability reasons, is to explicitly mark those code blocks as `debug` blocks because they only assist for debugging purposes.

**Comment by ljmf00** [comment]
I missed the fact that there was a `doCount` flag there. This seems fine then.

**Comment by RazvanN7** [comment]
From my perspective, the fact that the code is much uglier by adding `static if`s outweighs the potential benefit one would get for non-optimized code. On that note, this PR should prove the benefits of adding those `static if`s. My expectation is that there is not benefit since the instruction is probably ran in parallel with other more time consuming instructions. However, the fact that non-optimized code still performs the increment on `count` is a weak motivator for this PR. I think that we should focus on optimizations that the optimizer cannot do.

**Comment by kubo39** [comment]
Hmm, I don't think this is so ugly.. My motivation is that the standard libraries should be optimized as possible, but it's not so strong. Feel free to close if you would like to. @RazvanN7

**Comment by RazvanN7** [comment]
Thanks @kubo39 !

**Pull request closed without merging**
