### PR TITLE
ci: circleci: bump host compiler used for bootstrapping

### PR DESCRIPTION
**Pull request by ljmf00**
Signed-off-by: Luís Ferreira <contact@lsferreira.net>

### CODE REVIEW

**Comment by ibuclaw** [comment]
Any specific reason for bumping the baseline compiler?

**Comment by ljmf00** [comment]
> Any specific reason for bumping the baseline compiler?

CI is failing on every new PR. See https://github.com/dlang/phobos/pull/8204 and https://github.com/dlang/phobos/pull/8203 . Completely unrelated.

**Comment by maxhaton** [comment]
These CI failures seem quite specific, so it would  be good to work out exactly what is going wrong before bumping (should we decide to do so) in case there's a deeper problem.

**Comment by ljmf00** [comment]
> These CI failures seem quite specific, so it would be good to work out exactly what is going wrong before bumping (should we decide to do so) in case there's a deeper problem.

Marked as a draft again.

**Comment by ibuclaw** [comment]
```
src/dmd/backend/dt.d(226): Error: `@safe` function `dmd.backend.dt.DtBuilder.print` cannot call `@system` function `core.stdc.stdio.printf`
```

The `print` method was added by dlang/dmd#13000

**Comment by pbackus** [comment]
I'm getting a different error building DMD in https://github.com/dlang/phobos/pull/8208:

```
Command: /home/circleci/dlang/dmd-2.079.1/linux/bin64/dmd -of/home/circleci/dmd/generated/linux/debug/64/dmd -vtls -J/home/circleci/dmd/src/dmd/res -version=MARS -w -de -fPIC -m64 -J/home/circleci/dmd/generated/linux/debug/64 -I/home/circleci/dmd/src -dip25 -g -color=on src/dmd/dinifile.d src/dmd/gluelayer.d src/dmd/lib.d src/dmd/libelf.d src/dmd/libmach.d src/dmd/libmscoff.d src/dmd/libomf.d src/dmd/link.d src/dmd/mars.d src/dmd/scanelf.d src/dmd/scanmach.d src/dmd/scanmscoff.d src/dmd/scanomf.d src/dmd/vsoptions.d src/dmd/access.d src/dmd/aggregate.d src/dmd/aliasthis.d src/dmd/apply.d src/dmd/argtypes_x86.d src/dmd/argtypes_sysv_x64.d src/dmd/argtypes_aarch64.d src/dmd/arrayop.d src/dmd/arraytypes.d src/dmd/astenums.d src/dmd/ast_node.d src/dmd/astcodegen.d src/dmd/asttypename.d src/dmd/attrib.d src/dmd/blockexit.d src/dmd/builtin.d src/dmd/canthrow.d src/dmd/chkformat.d src/dmd/cli.d src/dmd/clone.d src/dmd/compiler.d src/dmd/complex.d src/dmd/cond.d src/dmd/constfold.d src/dmd/cppmangle.d src/dmd/cppmanglewin.d src/dmd/ctfeexpr.d src/dmd/ctorflow.d src/dmd/dcast.d src/dmd/dclass.d src/dmd/declaration.d src/dmd/delegatize.d src/dmd/denum.d src/dmd/dimport.d src/dmd/dinterpret.d src/dmd/dmacro.d src/dmd/dmangle.d src/dmd/dmodule.d src/dmd/doc.d src/dmd/dscope.d src/dmd/dstruct.d src/dmd/dsymbol.d src/dmd/dsymbolsem.d src/dmd/dtemplate.d src/dmd/dtoh.d src/dmd/dversion.d src/dmd/env.d src/dmd/escape.d src/dmd/expression.d src/dmd/expressionsem.d src/dmd/func.d src/dmd/hdrgen.d src/dmd/impcnvtab.d src/dmd/imphint.d src/dmd/init.d src/dmd/initsem.d src/dmd/inline.d src/dmd/inlinecost.d src/dmd/intrange.d src/dmd/json.d src/dmd/lambdacomp.d src/dmd/mtype.d src/dmd/nogc.d src/dmd/nspace.d src/dmd/ob.d src/dmd/objc.d src/dmd/opover.d src/dmd/optimize.d src/dmd/parse.d src/dmd/parsetimevisitor.d src/dmd/permissivevisitor.d src/dmd/printast.d src/dmd/safe.d src/dmd/sapply.d src/dmd/semantic2.d src/dmd/semantic3.d src/dmd/sideeffect.d src/dmd/statement.d src/dmd/statement_rewrite_walker.d src/dmd/statementsem.d src/dmd/staticassert.d src/dmd/staticcond.d src/dmd/stmtstate.d src/dmd/target.d src/dmd/templateparamsem.d src/dmd/traits.d src/dmd/transitivevisitor.d src/dmd/typesem.d src/dmd/typinf.d src/dmd/utils.d src/dmd/visitor.d src/dmd/foreachvar.d src/dmd/cparse.d src/dmd/dmsc.d src/dmd/e2ir.d src/dmd/eh.d src/dmd/iasm.d src/dmd/iasmdmd.d src/dmd/iasmgcc.d src/dmd/glue.d src/dmd/objc_glue.d src/dmd/s2ir.d src/dmd/tocsym.d src/dmd/toctype.d src/dmd/tocvdebug.d src/dmd/todt.d src/dmd/toir.d src/dmd/toobj.d src/dmd/backend/cc.d src/dmd/backend/cdef.d src/dmd/backend/cgcv.d src/dmd/backend/code.d src/dmd/backend/cv4.d src/dmd/backend/dt.d src/dmd/backend/el.d src/dmd/backend/global.d src/dmd/backend/obj.d src/dmd/backend/oper.d src/dmd/backend/outbuf.d src/dmd/backend/rtlsym.d src/dmd/backend/code_x86.d src/dmd/backend/iasm.d src/dmd/backend/codebuilder.d src/dmd/backend/ty.d src/dmd/backend/type.d src/dmd/backend/exh.d src/dmd/backend/mach.d src/dmd/backend/mscoff.d src/dmd/backend/dwarf.d src/dmd/backend/dwarf2.d src/dmd/backend/xmm.d src/dmd/backend/dlist.d src/dmd/backend/melf.d src/dmd/root/aav.d src/dmd/root/longdouble.d src/dmd/root/man.d src/dmd/root/response.d src/dmd/root/speller.d src/dmd/root/string.d src/dmd/root/strtold.d generated/linux/debug/64/lexer.o generated/linux/debug/64/backend.o

-----------------------------------------------------------
/home/circleci/dlang/dmd-2.079.1/linux/bin64/../../src/druntime/import/core/exception.d(686): _store is thread local
generated/linux/debug/64/backend.o: In function `cdeq(CodeBuilder&, elem*, unsigned int*)':
/home/circleci/dmd/src/dmd/backend/cod4.d:708: undefined reference to `_D3dmd7backend4code7findregFNbNekiAyaZh'
/home/circleci/dmd/src/dmd/backend/cod4.d:762: undefined reference to `_D3dmd7backend4code7findregFNbNekiAyaZh'
/home/circleci/dmd/src/dmd/backend/cod4.d:788: undefined reference to `_D3dmd7backend4code7findregFNbNekiAyaZh'
/home/circleci/dmd/src/dmd/backend/cod4.d:822: undefined reference to `_D3dmd7backend4code7findregFNbNekiAyaZh'
generated/linux/debug/64/backend.o: In function `cdaddass(CodeBuilder&, elem*, unsigned int*)':
/home/circleci/dmd/src/dmd/backend/cod4.d:1243: undefined reference to `_D3dmd7backend4code7findregFNbNekiAyaZh'
generated/linux/debug/64/backend.o:/home/circleci/dmd/src/dmd/backend/cod4.d:1588: more undefined references to `_D3dmd7backend4code7findregFNbNekiAyaZh' follow
collect2: error: ld returned 1 exit status
Error: linker exited with status 1
```

**Comment by ibuclaw** [comment]
@pbackus scroll up and scroll up some more.  The last message in the CI terminal is a red herring.

**Comment by ibuclaw** [comment]
> I'm getting a different error building DMD in #8208:

It's the same error: https://app.circleci.com/pipelines/github/dlang/phobos/4632/workflows/df73d216-9e48-4d44-bae6-f93a852d0187/jobs/14177?invite=true#step-103-289

**Comment by ljmf00** [comment]
@ibuclaw The compiler is using a new feature from `2.082`. See https://dlang.org/changelog/2.082.0.html#debug-unsafe

```d
void main(){
    void print() @safe
    {
        import core.stdc.stdio : printf;
        debug printf("foobar\n");
    }
}
```

Running a regression test:

```
Up to      2.060  : Failure with output: onlineapp.d(5): Error: safe function 'print' cannot call system function 'printf'
2.061   to 2.071.2: Failure with output: onlineapp.d(5): Error: safe function 'onlineapp.main.print' cannot call system function 'core.stdc.stdio.printf'
2.072.2 to 2.078.1: Failure with output: onlineapp.d(5): Error: @safe function 'onlineapp.main.print' cannot call @system function 'core.stdc.stdio.printf'
2.079.1 to 2.081.2: Failure with output: onlineapp.d(5): Error: `@safe` function `onlineapp.main.print` cannot call `@system` function `core.stdc.stdio.printf`
Since      2.082.1: Success and no output
```

**Comment by ibuclaw** [comment]
> @ibuclaw The compiler is using a new feature from `2.082`. See https://dlang.org/changelog/2.082.0.html#debug-unsafe

I don't see that as a rationale to bump the baseline compiler version.  The requirement is to be compilable from 2.076 and up still.

**Comment by ljmf00** [comment]
> > @ibuclaw The compiler is using a new feature from `2.082`. See [dlang.org/changelog/2.082.0.html#debug-unsafe](https://dlang.org/changelog/2.082.0.html#debug-unsafe)
> 
> I don't see that as a rationale to bump the baseline compiler version. The requirement is to be compilable from 2.076(-ish) and up still.

So we should eradicate that `printf` to make it `@safe` or make it `@system`.

**Comment by pbackus** [comment]
> So we should eradicate that `printf` to make it `@safe` or make it `@system`.

Looks like it can be `@trusted` since it's only using `%p`, which is guaranteed to have defined behavior for all pointer values. (Source: <http://port70.net/~nsz/c/c99/n1256.html#7.19.6.1>)

**Comment by ljmf00** [comment]
Resolved with https://github.com/dlang/dmd/pull/13008 .

**Pull request closed without merging**
