### PR TITLE
Remove ref from the Slice.this parameters

### PR DESCRIPTION
**Pull request by ZombineDev**
This allows passing rvalues directly.

@9il

### CODE REVIEW

**Comment by ZombineDev** [comment]
[Docs](http://dtest.thecybershadow.net/artifact/website-8ce16a564dd1bc29d79059b29e58df330c7b6e6b-df30e482216b655dd362499aca9cadb5/web/phobos-prerelease/std_experimental_ndslice_slice.html#.Slice.this)

**Comment by 9il** [comment]
Auto-merge toggled on

**Comment by 9il** [comment]
Auto-merge toggled off

**Comment by 9il** [comment]
It fails

**Comment by ZombineDev** [comment]
Sorry, should be fixed now.

**Comment by ZombineDev** [comment]
I decided to amend the example so that it show that depending on the stride, changes to the original array may not be visible.

**Comment by ZombineDev** [comment]
I'm not sure what's failing on [Linux_64_64](https://auto-tester.puremagic.com/show-run.ghtml?projectid=1&runid=2051599&isPull=true), but it seems unrelated.

**Comment by 9il** [comment]
Auto-merge toggled on

**Comment by ZombineDev** [comment]
Thanks!

**Comment by schuetzm** [comment]
Does this have performance implications? If so, should use `auto ref`?

**Comment by 9il** [comment]
> Does this have performance implications? If so, should use auto ref?

No, this would be inlined anyway

**Comment by ZombineDev** [comment]
Also the size of the paramters is constant and relatively small - e.g. 20*size_t.sizeof if you have a 10-dimensional Slice. Which would be quite rare, IMO.

**Pull request merged**
