### PR TITLE
use WindowsException for errors from windows api

### PR DESCRIPTION
**Pull request by John-Colvin**
In accordance with https://github.com/dlang/phobos/pull/4938#discussion_r91655136 and https://github.com/dlang/phobos/pull/4938#discussion_r91655158

### CODE REVIEW

**Comment by John-Colvin** [comment]
ping @CyberShadow this addresses your post-merge comments on https://github.com/dlang/phobos/pull/4938

**Comment by CyberShadow** [comment]
How weird that the documentation tester is failing to build the compiler:
```
dstruct.d(762): Error: constructor ddmd.dstruct.StructDeclaration.this (Loc loc, Identifier id, bool inObject) is not callable using argument types (Loc, Identifier)
```
I don't know what could cause this. Other PRs don't seem to have this problem, and master seems to have built successfully.

**Comment by John-Colvin** [comment]
everything seems to have passed now

**Comment by John-Colvin** [comment]
merge time?

**Comment by CyberShadow** [comment]
Auto-merge toggled on

**Pull request merged**
