### PR TITLE
Fix Issue 24215 - isBasicType!Enum should be false

### PR DESCRIPTION
**Pull request by pbackus**

### CODE REVIEW

**Comment by pbackus** [comment]
Dub build failure is caused by this change somehow; time to investigate...

**Review by thewilsonator — APPROVED** [review]

**Comment by thewilsonator** [comment]
Dependant PR merged.

**Review by atilaneves — APPROVED** [review]

**Comment by dkorpel** [comment]
Considering it broke a project on buildkite, it probably warrants a change log entry

**Comment by n8sh** [comment]
Hang on a minute! The way std.traits classifies types doesn't always line up with the language specification and nothing says it has to. For example as far as the D language is concerned char and bool are unsigned integer types but std.traits.isUnsigned and std.traits.isIntegral present a view of the world that draws a distinction between characters, boolean values, and numbers. Breaking changes to std.traits are particularly bad given how foundational it is. Even D programmers who use little else of Phobos rely on it.

Is there some common coding pattern using isBasicType that runs into problems if the programmer doesn't explicitly consider enums and exclude them? That would be a decent reason to consider changing it.

**Comment by pbackus** [comment]
I wanted this version of `isBasicType` for my safe allocators project, but I ended up finding a different solution to the same problem. So at this point it's just a UX issue.

If consensus is that this is too risky, I'm fine with reverting it. We can revisit for Phobos v2, if and when that ever happens.

@atilaneves, thoughts?

**Comment by atilaneves** [comment]
If there are issues and you have a workaround, I say it's better/easier to revert.

**Pull request merged**
