### PR TITLE
std.traits: fix return ref

### PR DESCRIPTION
**Pull request by WalterBright**
This is blocking https://github.com/dlang/dmd/pull/5901

### CODE REVIEW

**Comment by WalterBright** [comment]
Please don't delay pulling this.

**Comment by JackStouffer** [comment]
> Please don't delay pulling this.

It's 4th of July weekend, not many are going to be at their computers.

**Comment by WalterBright** [comment]
There are lots of no-US people here!

**Comment by ZombineDev** [comment]
LGTM, but I don't have the privileges to pull.

**Comment by andralex** [comment]
nice

**Pull request merged**
