### PR TITLE
Use alias assignment in Filter

### PR DESCRIPTION
**Pull request by andralex**
Code is greatly simplified, memory consumed is reduced.

### CODE REVIEW

**Comment by n8sh** [comment]
```console
generated/dscanner-9364d6f15f4a610fda49a693dbc18608bfc701bb/dsc --config .dscanner.ini --styleCheck etc std -I.
---
  | std/meta.d(885:20)[error]: no identifier for declarator
  | std/meta.d(885:44)[warn]: Empty declaration
  | posix.mak:577: recipe for target 'dscanner' failed
```

The style checker seems not to like this idiom.

**Review by n8sh — APPROVED** [review]

**Review by dukc — CHANGES_REQUESTED** [review]
Wait a minute. Isn't alias assigment currently an experimental feature? If it is rejected or changed later on, we will have problems.

**Comment by dukc** [comment]
Oh I see that you explained using experimental features in #8033. I assume you have discussed with Walter and/or Atila about the issue?

**Comment by andralex** [comment]
> Oh I see that you explained using experimental features in #8033. I assume you have discussed with Walter and/or Atila about the issue?

Yes, @WalterBright and @atilaneves are in the loop. Essentially we can't get an estimate on how well the feature could fare outside the stdlib because the stdlib would be its primary beneficiary (which would then improve the life of client code).

The PRs are intentionally bite-sized so we can easily dustmite and pinpoint performance problems back to them.

**Comment by adamdruppe** [comment]
Worst case you could always revert the specific commits that use this if the feature were removed too. Probably best to keep a list of them just in case.

**Comment by adamdruppe** [comment]
It took me a sec to realize what the recursive AliasSeq assignment was with the eponymous alias but I get it now and indeed this is really quite decent. Cool.

**Comment by wilzbach** [comment]
Someone would need to upgrade/improve/fix dscanner before this can be used.

**Comment by nordlow** [comment]
> Someone would need to upgrade/improve/fix dscanner before this can be used.

That has been fixed. :)

**Pull request merged**
