### PR TITLE
Streamline std.traits.BuiltinTypeOf & IntegralTypeOf

### PR DESCRIPTION
**Pull request by n8sh**
This incidentally fixes a 'TODO' in `BuiltinTypeOf`: `ifloat`/`idouble`/`ireal` and `cfloat`/`cdouble`/`creal` were being collapsed to `ireal` and `creal` and their qualifiers were being discarded.

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by thewilsonator** [comment]
cc @9il mir algorithm fails this PR, not sure why.

**Comment by 9il** [comment]
The bug is somewhere in Phobos, either this MR or `std.format`.
```d
    // back to text
    import std.format;
    import mir.ndslice;
    Slice!(int*, 2) matrix;
    auto text = format("%(%(%s %)\n%)\n", matrix);
```

**Comment by n8sh** [comment]
The problem was in this PR. `BuiltinTypeOf!(Slice!(int*, 2))` was resolving to `void` instead of failing to instantiate.

**Comment by thewilsonator** [comment]
Thanks!

**Pull request merged**
