### PR TITLE
Prepare for long line checks in travis

### PR DESCRIPTION
**Pull request by JackStouffer**
This should be one of the easier ones to enable and then fix, so let's see how this breaks.

### CODE REVIEW

**Comment by BBasile** [comment]
Close this. Dscanner checks was a premature decision. I don't know why the hell Alexandrescu tolds to wilzback that it was a good idea. It needs some work. For example [this PR](https://github.com/Hackerpilot/Dscanner/pull/340). I've made it mostly for my IDE but I think it could help you with the travis thing since everybody get on thinking that a Dscanner check is usefull. :see_no_evil:

**Comment by JackStouffer** [comment]
There's no reason to not get rid of lines longer than 120 characters, even if they are inside of unittest blocks.

And I'm of the opinion that automated style checking is a very good idea.

**Comment by BBasile** [comment]
In 6 monthes I'll ask you for a list of people who've found this check usefull. You don't even realize the problem. For example this: https://github.com/dlang/phobos/blob/master/std/typecons.d#L4498.

I'm no especailly againt **this** PR. I just say that Dscaning now is premature and not well implemented. I've told it before but since it may detect a lot of old issues the check should be a diff between the old source and the new source.

**Comment by JackStouffer** [comment]
> I just say that Dscaning now is premature and not well implemented

This is just a natural part of [dogfooding](https://en.wikipedia.org/wiki/Eating_your_own_dog_food). Eventually, we want dscanner and dfmt to become official tools, but if even the D contributors aren't using/testing it, then why should anyone else.

**Comment by BBasile** [comment]
@JackStouffer : common, just look at the results of the CI-dscanner checkings for **this PR**...
> the check should be a diff between the old source and the new source.   

Your PR fails because what are the constraints of today were not applied yesterday.

**Comment by JackStouffer** [comment]
> Your PR fails because what are the constraints of today were not applied yesterday.

Yes, and I expected it to break, and in many places. That's the whole point of this: to fix these style deviations and make it so they cannot happen again.

**Comment by wilzbach** [comment]
> And I'm of the opinion that automated style checking is a very good idea.

Yep I totally agree with @JackStouffer. Thanks a lot for pushing this ;-)

> Eventually, we want dscanner and dfmt to become official tools, but if even the D contributors aren't using/testing it, then why should anyone else.

Well you say "that Dscaning now is premature and not well implemented.", but how is it going to be mature if no one uses or tests it?
Yes we had a couple of issues with Dscanner once we integrated it to Phobos, but those should be fixed now and thus it is easier for other people to use dscanner in their projects. 

> That's the whole point of this: to fix these style deviations and make it so they cannot happen again.

That's exactly why Andrei liked the idea btw!

**Comment by BBasile** [comment]
The Travis-CI based dscanner check will never help anyone to make a better pull request. never ever.
It's a complete extravaganza. I'm sorry @JackStouffer if I've used this PR to make my propaganda. End of storry.

**Comment by wilzbach** [comment]
> The Travis-CI based dscanner check will never help anyone to make a better pull request. never ever.
It's a complete extravaganza.

Basically it's an automated enforcement of the [D Style](http://dlang.org/dstyle.html):

> We are not necessarily recommending that all code follow these rules. They're likely to be controversial in any discussion on coding standards. However, they are required in submissions to Phobos and other official D source code.

**Comment by BBasile** [comment]
Wilzback, to use dscanner here is not a good idea. I've banned you because of this. I've also banned Alexandrescu because he trusted you. To use Dscanner right now to check pull requests is totally useless and is a waste of resource. it's completly stupid. Dumb.

**Comment by JackStouffer** [comment]
> Wilzback, to use dscanner here is not a good idea. I've banned you because of this. I've also banned Alexandrescu because he trusted you. To use Dscanner right now to check pull requests is totally useless and is a waste of resource. it's completly stupid. Dumb.

Please back up assertions with evidence.

As we have already mentioned, dscanner has bugs, but that's why we're dogfooding it. That's not a reason to throw out the idea wholesale.

**Comment by BBasile** [comment]
> Please back up assertions with evidence.

By __ban__ I mean __block__, in my own social system.

bully

**Comment by wilzbach** [comment]
> To use Dscanner right now to check pull requests is totally useless and is a waste of resource. it's completly stupid. Dumb.
> Please back up assertions with evidence.

I think it's a waste of resources to have this discussion.
Thanks a lot @JackStouffer for investing the time & fixing this simple constraint!

**Comment by CyberShadow** [comment]
:+1:

Don't mind @BBasile, I think he's just a bit too liquored up at the moment :)

Making the error messages nicer would be a point of improvement going forward.

BTW, @JackStouffer, it seems your git email address is not associated with your GitHub account.

**Comment by JackStouffer** [comment]
@wilzbach @CyberShadow That's everything.

**Comment by CyberShadow** [comment]
Hmm, why is the doc build failing? Is it this?
```
string expected, not '"It will be removed from Phobos in October 2016. " ~ "If you still need it, go to https://github.com/DigitalMars/undeaD"'
```

**Comment by CyberShadow** [comment]
The internal Unicode tables look like they might be machine-generated, thus they may break again if regenerated. @DmitryOlshansky ?

**Comment by JackStouffer** [comment]
@CyberShadow hmm, deprecation messages are now supposed to work with enum messages, so if I change it to this:

```
enum deprecated_message = "It will be removed from Phobos in October 2016. "
    ~"If you still need it, go to https://github.com/DigitalMars/undeaD";
deprecated(deprecated_message) module std.stream;
```

I get

```
std/stream.d(30): Error: declaration expected, not 'module'
```

**Comment by JackStouffer** [comment]
@CyberShadow for the unicode tables, I just ran them though dfmt. So if they need to be regenerated later, then dfmt can just be rerun.

**Comment by CyberShadow** [comment]
> @CyberShadow hmm, deprecation messages are now supposed to work with enum messages, so if I change it to this:

Might be a use case for the implicit string concatenation thing (unless that's enabled in Travis already?)

**Comment by Hackerpilot** [comment]
Putting the `enum` above a deprecated module won't work because the grammar doesn't allow anything before the module declaration.

I'm pretty sure that concatenating strings in deprecated messages is allowed as of dmd 2.071.

**Comment by JackStouffer** [comment]
> I'm pretty sure that concatenating strings in deprecated messages is allowed as of dmd 2.071.

I thought so too, but it seems to not work.

**Comment by Hackerpilot** [comment]
It's right there in the changelog: http://dlang.org/changelog/2.071.0.html#extended-deprecated

**Comment by JackStouffer** [comment]
> It's right there in the changelog: http://dlang.org/changelog/2.071.0.html#extended-deprecated

I don't know what to tell you man. It **doesn't work**.

**Comment by JackStouffer** [comment]
https://issues.dlang.org/show_bug.cgi?id=16014

**Comment by CyberShadow** [comment]
Omit the `~` in the mean time?

**Comment by JackStouffer** [comment]
Can't, the line is too long.

**Comment by CyberShadow** [comment]
I mean this stupid trick (same as in C++):

```
writeln("abc" "def");
```

It should be deprecated and removed, but IIRC it should work.

**Comment by JackStouffer** [comment]
@CyberShadow fixed.

**Comment by JackStouffer** [comment]
> but IIRC it should still work for the moment

Welp, I guess travis answered that question.

**Comment by CyberShadow** [comment]
D'oh.

> (unless that's enabled in Travis already?)

**Comment by CyberShadow** [comment]
Perhaps the travis.yml change should be dropped from the commit until the compiler bug is fixed, and the rest (actual fixes) merged quickly to avoid conflicts.

**Comment by JackStouffer** [comment]
@CyberShadow Done.

**Comment by CyberShadow** [comment]
Auto-merge toggled on

**Comment by wilzbach** [comment]
@JackStouffer what stopped you from enabling the long line check?
Since May a couple of new violations were checked in.

```
std/format.d(5191:12)[warn]: Line is longer than 120 characters
std/stream.d(26:12)[warn]: Line is longer than 120 characters
std/socketstream.d(37:12)[warn]: Line is longer than 120 characters
std/socket.d(1070:116)[warn]: Line is longer than 120 characters
std/experimental/ndslice/selection.d(1436:118)[warn]: Line is longer than 120 characters
std/experimental/ndslice/selection.d(1529:106)[warn]: Line is longer than 120 characters
std/math.d(7787:119)[warn]: Line is longer than 120 characters
```

> I don't know what to tell you man. It doesn't work.

Be creative. It's just one occurrence in socketstream that will be removed anyhows, e.g. just removing "from Phobos" in the message already gets you below 120 ;-)

**Comment by JackStouffer** [comment]
> what stopped you from enabling the long line check?

The unwillingness of the compiler maintainers to admit that 16014 is a bug.

**Comment by wilzbach** [comment]
> The unwillingness of the compiler maintainers to admit that 16014 is a bug.

Yeah I know, but as said it's easy to workaround and there's only one occurrence - the following just uses 115 chars ;-)

```d
deprecated("It will be removed in October 2016. If you still need it, go to https://github.com/DigitalMars/undeaD")
module std.socketstream;
```

**Comment by wilzbach** [comment]
Btw in the [bug](https://issues.dlang.org/show_bug.cgi?id=16014) another workaround was suggested:

```
pragma(msg, __FILE__,"(",__LINE__,"): this module is deprecated");
```

Imho just pick one workaround and enable the check before more violations are merged in, `socketstream` will be removed anyway in two months :)

**Pull request merged**
