### PR TITLE
Issue 17127 - bad example code for std.concurrency.Generator

### PR DESCRIPTION
**Pull request by wilzbach**
The only way we can ensure that an example works is by actually executing it!

### CODE REVIEW

**Comment by MetaLang** [comment]
Ping @wilzbach

**Comment by WalterBright** [comment]
This is consistently failing the autotester, seems to be a timeout issue.

**Comment by WalterBright** [comment]
Removed auto-merge until it passes the tests, otherwise it plugs up the autotest queue.

**Comment by JackStouffer** [comment]
@wilzbach As best I can tell from the failure messages, these tests push `std.concurrency` past its test time limit. 

If possible, I would increase the time limit for 32 bit environments and see if that fixes it.

**Comment by wilzbach** [comment]
Okay I tried to split this PR up into a PR for each modified test: #5870, #5871, #5872, #5873 - hopefully only one of these fails ...

**Comment by JackStouffer** [comment]
It's https://github.com/dlang/phobos/pull/5873

**Comment by wilzbach** [comment]
> It's #5873 

Alrighty :)
How about merging the other passing ones (they are already out anyways), so that we can focus solely on #5873?
(The Jenkins failures are unrelated and due to it running out of space)

**Pull request closed without merging**
