### PR TITLE
[trivial] Remove some package wide std.algorithm imports

### PR DESCRIPTION
**Pull request by JackStouffer**

### CODE REVIEW

**Comment by andralex** [comment]
Auto-merge toggled on

**Comment by andralex** [comment]
push again for the autotester (freebsd box seems to have timed out)

**Comment by schveiguy** [comment]
> push again for the autotester

As a contributor, you can deprecate a test to have it rerun if you think it was a one-off error. Click on the test run id on the auto tester, and then there is a "deprecate" link if it's not already been deleted.

**Comment by wilzbach** [comment]
> As a contributor...

Everyone that has at least once opened a PR and is thus approved can do
that. Or the other way around: the auto-tester only runs of the user has
been approved ;-)

**Pull request merged**
