### PR TITLE
Move logger out of experimental

### PR DESCRIPTION
**Pull request by atilaneves**

### CODE REVIEW

**Comment by atilaneves** [comment]
> I think allocator should move out of experimental first

It can't yet, but logger can, so hence the PR. Rest assured, the plan is to get allocator out of experimental as well, but some work needs to be done first.

**Comment by Herringway** [comment]
Maybe this should be added to std/package.d as well?

**Review by ibuclaw — CHANGES_REQUESTED** [review]
> Maybe this should be added to std/package.d as well?

Yes

**Comment by ibuclaw** [comment]
> > I think allocator should move out of experimental first
> 
> It can't yet, but logger can, so hence the PR. Rest assured, the plan is to get allocator out of experimental as well, but some work needs to be done first.

I still have some outstanding fixes to get it working on OSX too (current implementation assumes posix_memalign exists IIRC).

**Review by aG0aep6G — CHANGES_REQUESTED** [review]
I strongly suggest fixing [issue 16232](https://issues.dlang.org/show_bug.cgi?id=16232) ("std.experimental.logger.core.sharedLog isn't thread-safe") before going ahead with this. It's a safety hole that likely needs an API change to fix. That kind of issue is why std.experimental exists in the first place.

**Comment by burner** [comment]
> I strongly suggest fixing [issue 16232](https://issues.dlang.org/show_bug.cgi?id=16232) ("std.experimental.logger.core.sharedLog isn't thread-safe") before going ahead with this. It's a safety hole that likely needs an API change to fix. That kind of issue is why std.experimental exists in the first place.

How do you suggest fixing it?

**Comment by PetarKirov** [comment]
@burner As mentioned by @aG0aep6G in the issue:

> I see two ways out:
> 1) Make sharedLog `@system`.
> 2) Return a `shared` Logger.

I vote for 2) as it is the right thing™ to do.

**Review by RazvanN7 — APPROVED** [review]

**Comment by RazvanN7** [comment]
@atilaneves is this still a draft? Once #8489 is in, I see no reason not to pull this.

**Comment by RazvanN7** [comment]
@atilaneves #8489 is in, so please rebase this so that we can merge it.

**Comment by atilaneves** [comment]
Rebased and green.

**Comment by WalterBright** [comment]
@RazvanN7 @atilaneves this code keeps randomly crashing when the test suite is run.

https://issues.dlang.org/show_bug.cgi?id=23286

Please fix or put it back in experimental.

**Pull request merged**
