### PR TITLE
Update ThreadInfo.cleanup() to unregister itself instead of the local thread's

### PR DESCRIPTION
**Pull request by look-at-me**

### CODE REVIEW

**Comment by thewilsonator** [comment]
Does this have a bugzilla number?

**Comment by Geod24** [comment]
@look-at-me : Now that you found the case, could you craft a test case for it, and create a bugzilla issue so that it shows up in the changelog ?
@thewilsonator : Not yet. It is one of the bounties that we are sponsoring. I didn't have a small test case to reproduce it, but it looks like  @look-at-me found the root cause (see https://github.com/Geod24/localrest/pull/5 )

**Comment by look-at-me** [comment]
Not sure if it's worth adding a unittest over. Not exactly an issue that will likely be repeated.

**Comment by AndrejMitrovic** [comment]
> Not sure if it's worth adding a unittest over. Not exactly an issue that will likely be repeated.

Someone in the future might tag along and think "huh, why is this code here, let's see what happens if I delete it? Hey look, the tests still pass. Great."

**Comment by look-at-me** [comment]
There's tests that check the functionality. Just not the edge case that caused this error. This edge case isn't worth testing as it is unlikely to happen again in the future.

**Pull request closed without merging**
