### PR TITLE
Use the generated VERSION file instead of the outdated ../dmd/VERSION

### PR DESCRIPTION
**Pull request by wilzbach**
The generated `VERSION` file is the source of truth - it's a dependency for `dmd`, so it's guaranteed to be there.

CC @CyberShadow @MartinNowak 

Before:

```
ln -sf libphobos2.so.0.74.0 generated/linux/release/64/libphobos2.so.0.74
ln -sf libphobos2.so.0.74.0 generated/linux/release/64/libphobos2.so
```

(due to the outdated `VERSION` file)

After:

```
ln -sf libphobos2.so.0.75.0 generated/linux/release/64/libphobos2.so.0.75
ln -sf libphobos2.so.0.75.0 generated/linux/release/64/libphobos2.so
```

And of course, future git tags will propagates automatically :)

### CODE REVIEW

**Comment by wilzbach** [comment]
Rebased.
@CyberShadow do you feel comfortable enough merging this or should we wait for Martin?

**Comment by CyberShadow** [comment]
Definitely wait for Martin. He seems to have enough trouble with VERSIONs lately.

**Comment by wilzbach** [comment]
> Definitely wait for Martin.

https://trello.com/c/f7NayGyf/329-using-the-generated-version-file-at-dlang-phobos

> It's about using dmd's generated/.../VERSION file? Sounds reasonable.

> Maybe add a fallback to not tie phobos too much to ../dmd being build beforehand.

-> done (even though I think that DMD and Phobos are intertwined anyways)

**Comment by wilzbach** [comment]
> https://trello.com/c/f7NayGyf/329-using-the-generated-version-file-at-dlang-phobos

@CyberShadow Martin approved this, so anything else blocking this? (except for our current CI problem)

**Comment by CyberShadow** [comment]
It looks like you added `slide.d` by accident.

**Comment by wilzbach** [comment]
> It looks like you added slide.d by accident.

Oh sorry. Should I squash the two commits?

**Comment by CyberShadow** [comment]
OK, so

- DMD's VERSION file in /generated/ is generated from the git tags?
- This makefile already requires DMD to be built? Because it if attemps to build DMD like the dlang.org one, it will try to read the file before it's there.

Generally as this is more Martin's area than mine I would rather leave the merge to him.

**Comment by wilzbach** [comment]
> DMD's VERSION file in /generated/ is generated from the git tags?

Yes.

> This makefile already requires DMD to be built? Because it if attemps to build DMD like the dlang.org one, it will try to read the file before it's there.

No it's not required, but we just use the `dmd` binary.
In any case there's a fallback to the current behavior of using the manually bumped `VERSION`.

> Generally as this is more Martin's area than mine I would rather leave the merge to him.

Fair enough. Let's wait then.

**Comment by MartinNowak** [comment]
Why is it outdated? They should no longer be out of sync since we switched dmd's VERSION bumping to match `git describe` with 2.075.0 (https://gist.github.com/MartinNowak/a471fe7ddbfeef205cdf04c93a94c6d0/revisions#diff-e55bb7573f1110c8b2a6922fe8cccf48).
Also doing sth. different based on the state of a directory that's not dependency of the build (you can build phobos with any dmd) asks for trouble.
Might be smarter to give phobos it's own VERSION file as the SONAME mostly depends on phobos (except for ABI differences between compiler versions). For now, as we release dmd and phobos in lock-step, it should be mostly fine as is though.

**Comment by wilzbach** [comment]
> They should no longer be out of sync since we switched dmd's VERSION bumping to match git describe with 2.075.0 

Fair enough.

**Pull request closed without merging**
