### PR TITLE
WIP: Add @nogc to relevant std.algorithm.iteration.map unittests

### PR DESCRIPTION
**Pull request by atilaneves**
Only exists to trigger the autotester.

### CODE REVIEW

**Comment by wilzbach** [comment]
This was the first visible public example of the function. It is now vastly less legible for beginners (i.e. the kind of people who would read this example in the first place).

**Comment by atilaneves** [comment]
It was WIP and not meant to be merged, I was going to add @nogc to more tests.

**Comment by atilaneves** [comment]
> This was the first visible public example of the function. It is now vastly less legible for beginners (i.e. the kind of people who would read this example in the first place).

Because of the use of `only`?

**Comment by atilaneves** [comment]
I used `staticArray` in a different PR and hit an assertion in the backend for Windows. I'm not sure that was the cause, so I did a very small change here with `only` to see if it passed CI. I didn't mean for it to get merged.

Would this have looked better?

```d
auto rng1 = only(1, 2, 3, 4);
auto rng2 = only(5, 6);
auto squares = map!(a => a* a)(chain(rng1, rng2));
```

It's less of a change. I'm not sure how much harder it is for beginners given that the original example had `chain` instead of `~`.

I'm open to suggestions.

**Pull request merged**
