### PR TITLE
Finish work on checking of too broad local imports outside of unit tests

### PR DESCRIPTION
**Pull request by JackStouffer**
That's all of them.

Will enable the check once this and https://github.com/dlang/phobos/pull/4513 are pulled.

### CODE REVIEW

**Comment by WalterBright** [comment]
Auto-merge toggled on

**Comment by wilzbach** [comment]
Windows is failing :/

**Comment by JackStouffer** [comment]
Not surprised; one sec

**Comment by JackStouffer** [comment]
Should be good now

**Pull request merged**
