### PR TITLE
[DEMO][DONOTPULL] Partially converted imports to static imports

### PR DESCRIPTION
**Pull request by andralex**
This shows a partial attempt at converting `import`s to `static import`s in std.array. Attempting to do this further results in increasing difficulties.

### CODE REVIEW

**Comment by wilzbach** [comment]
I guess as we don't plan to pull it, I can go ahead and close it. Please ping if you intended otherwise.

**Comment by andralex** [comment]
@wilzbach yah, didn't think of the resources consumed. In the future I'll close such experiments immediately.

**Comment by wilzbach** [comment]
> @wilzbach yah, didn't think of the resources consumed. In the future I'll close such experiments immediately.

It's not about resources at all. The `auto-tester` doesn't build older PRs and the other CI services only build a PR once (at least for now). My main motivation is the clogged PR queue - we are close to the magical 100 :O

**Comment by andralex** [comment]
Well, "resources" includes human resources. Urgh, that didn't come out well :).

**Pull request closed without merging**
