### PR TITLE
Fix issue 16331 - std.container.array should allow uncomparable values

### PR DESCRIPTION
**Pull request by wilzbach**
Working with `std.container` is a huge pain as one bumps into bugs all the time :/

Are there any plan yet to rewrite this module?, e.g.  [emsi's container](https://github.com/economicmodeling/containers) could be a a good start.

### CODE REVIEW

**Comment by JackStouffer** [comment]
Andrei is working on it.

**Comment by JackStouffer** [comment]
This is a trivial change that allows a valid use case, and the tests are passing, so LGTM

**Comment by schveiguy** [comment]
Agree. Also, the check to see if we are inserting things properly that *are* comparable are covered by other unit tests.

**Comment by schveiguy** [comment]
Auto-merge toggled on

**Pull request merged**
