### PR TITLE
adds assert messages to std.container.package

### PR DESCRIPTION
**Pull request by burner**

### CODE REVIEW

**Comment by thewilsonator** [comment]
Given that the types that contain those asserts are intended to not be instantiated, much less used, i.e. Doc only, I think there is not much value in doing this. 

Making those types conditionally defined as `version(StdDoc)` (or whatever it is) is a better idea.

**Comment by burner** [comment]
yeah I had the same feeling. It might only be a bit out of the scope of this project.

**Review by RazvanN7 — APPROVED** [review]

**Comment by RazvanN7** [comment]
I see no harm in adding those messages.

**Comment by burner** [comment]
@RazvanN7 thank you

**Comment by RazvanN7** [comment]
@burner You're welcome! Thanks for your patience!

**Comment by burner** [comment]
> @burner You're welcome! Thanks for your patience!

to be honest, I forgot that I had this ;-)

**Pull request merged**
