### PR TITLE
std.math: Use DOUBLEPAIR_MSB/LSB for accessing high/low parts of ibmExtended format

### PR DESCRIPTION
**Pull request by ibuclaw**
A continuation of #5822 (or a prelude, works both ways).

When running the unittests for PPC64/LE, found many failures due to it checking the wrong part (`MANTISSA_MSB` value is the least significant index on `LittleEndian`).

Fixed places where Big/Little endian would otherwise differ, but actually should do the same thing.

### CODE REVIEW

**Comment by ibuclaw** [comment]
Maybe its time to resurrect  #4336

**Comment by redstar** [comment]
Very nice - I found this, too. I will have a closer look this evening. One point: you are enabling doubledouble support on little endian. This should also be reflected in the version check at the beginning of the file (https://github.com/dlang/phobos/blob/master/std/math.d#L233).

**Comment by ibuclaw** [comment]
@redstar, oh and there's also #5825 which fixes this using an entirely different approach.

**Comment by redstar** [comment]
Ok, this is the simple approach. :-) Looks good to me. There are no overlooked instance, so it should work out of the box.

**Comment by ibuclaw** [comment]
Rebased.

**Pull request merged**
