### PR TITLE
fix Issue 15215 - Erroneous error messages in to!IntegralType conversions 

### PR DESCRIPTION
**Pull request by CyberShadow**
https://issues.dlang.org/show_bug.cgi?id=15215

### CODE REVIEW

**Comment by CyberShadow** [comment]
By necessity, the second commit removes a template de-bloating optimization for small integers. It's probably fine.

**Comment by DmitryOlshansky** [comment]
> It's probably fine.

Personally I can leave with error message not specifying which _exact_ type is converted to which, having generic message such as "string to integer" is perfectly fine.

**Comment by JackStouffer** [comment]
LGTM

**Comment by quickfur** [comment]
Just realized that #4008 is a total duplicate of this PR (except worse :-P). Since it's checked in now, is there anything left to do here? perhaps check in the better unittests? Or should we just close this?

**Comment by DmitryOlshansky** [comment]
Ping @CyberShadow

**Comment by CyberShadow** [comment]
Well, I don't know. How should I feel about this? I submit a PR, it sits for a few months, then another PR is submitted which addresses the same thing to a lesser degree, and that one gets merged in two days.

It wasn't my itch to scratch, so I think I'm just going to stop caring about this.

**Pull request closed without merging**
