### PR TITLE
fix issue 16192 - std.conv.toChars() opSlice wrong for radix other th…

### PR DESCRIPTION
**Pull request by aG0aep6G**
…an 10

https://issues.dlang.org/show_bug.cgi?id=16192

Targeting the stable branch here, but I'm not sure if all bug fixes should go to stable or only regression fixes.

### CODE REVIEW

**Comment by smolt** [comment]
would be good to add some more opSlice unittests too.

**Comment by joakim-noah** [comment]
LGTM

**Comment by aG0aep6G** [comment]
> would be good to add some more opSlice unittests too.

Have anything specific in mind?

**Comment by smolt** [comment]
> Have anything specific in mind?

Maybe something like this for a little better coverage of happy path:
```D
        r = toChars!(16)(0x12345678u);
        assert(r[0..8].array == "12345678");
        assert(r[0..8].length == 8);
        assert(r[1..7].array == "234567");
        assert(r[1..7].length == 6);
        assert(r[2..6].array == "3456");
        assert(r[2..6].length == 4);
        assert(r[3..5].array == "45");
        assert(r[3..5].length == 2);
        assert(r[4..4].length == 0);
```

**Comment by aG0aep6G** [comment]
> Maybe something like this for a little better coverage of happy path:
> 
>         r = toChars!(16)(0x12345678u);
>         assert(r[0..8].array == "12345678");
>         assert(r[0..8].length == 8);

Checking length seems superfluous to me. Other tests should verify that a Result's length works properly. How about verifying that slicing produces the same results as popFront/popBack calls?

For example:
```d
auto original = toChars!2(0b101100);
auto r = original.save;
assert(original[0 .. 6] is r);
r.popFront();
assert(original[1 .. 6] is r);
r.popFront();
assert(original[2 .. 6] is r);
/* ... etc ... */
```

**Comment by aG0aep6G** [comment]
The auto-tester fails with "core.exception.AssertError@std\datetime.d(27285): TZName which is missing: Aleutian Standard Time". Is the stable branch broken?

**Comment by schveiguy** [comment]
Yes, need to cherry pick this: https://github.com/dlang/phobos/commit/9f97025940dc335e6736bb38605d936db30da295#diff-abc63c8931bdb5d94304fc154ab68539

I don't know how to do it.

**Comment by JackStouffer** [comment]
I would just target master. Stable is typically only for regressions.

**Comment by smolt** [comment]
I'm good with any additional unit testing that covers opSlice.  It does not have to include what I suggested.

**Comment by aG0aep6G** [comment]
New PR against master with more extensive tests: #4489.

**Pull request closed without merging**
