### PR TITLE
fix issue 16184 - allocator.dispose allows to dispose C++ interfaces

### PR DESCRIPTION
**Pull request by BBasile**

### CODE REVIEW

**Comment by JackStouffer** [comment]
Seems reasonable. I don't know C++ though, so I don't know if some corner cases aren't being handled.

**Comment by BBasile** [comment]
Neither do I. A few monthes ago there was a fix for the COM interfaces. At this time I knew that the same problem existed for the C++ interfaces but I haven't found yet the trick to detect them.

https://github.com/dlang/phobos/pull/4022

**Comment by BBasile** [comment]
There's an obvious corner case actually. I think it's the only:

```D
interface Foo
{
    extern(C++) void foo1;
    extern(C++) void foo2;
}
```

will be seen as

```D
extern(C++) interface Foo
{
    void foo1;
    void foo2;
}
```

by the trait code. But I don't see why someone would do this if the interface is not really coming from a C++ library. Theorically only 1 method check would be enough. Each one is checked to handle another corner case:

```D
 interface Foo
{
    void foo1;
    extern(C++) void foo2;
}
```

By the way "rumbu" can be credited for the trick which was found here: https://forum.dlang.org/post/wlrewwryycuitesecbob@forum.dlang.org

**Comment by BBasile** [comment]
ping, this one is almost trivial. Either the trait code is good or bad. There is no hundreds of way to detect a C++ interface.

**Comment by schveiguy** [comment]
I ran a test, if you have a C++ interface, you cannot cast to Object, but if you have a D class that implements a C++ interface, it can cast to Object. This is something I thought was not possible (I thought the vtable layout for a D class that implements a C++ interface was different, and therefore wouldn't work for Object). I thought it was the same as COM (where your D class does not derive from Object).

So it's difficult to say whether this is right or wrong, because I'm not sure what is supposed to happen...

**Comment by schveiguy** [comment]
Meh, nevermind. I see where my understanding is incorrect. We can't cast IUnknown derived *interfaces* to Object, you can cast the D objects that implement them to Object however.

LGTM.

**Comment by BBasile** [comment]
The PR is actually more motivated by the specifications that say that _a c++ interface can't be the argument of a deleteExpression_. Actually I don't even know if they are castable or not to Object.

**Comment by schveiguy** [comment]
> Actually I don't even know if they are castable or not to Object.

I tested. It is not. Returns `null`, which would cause a segfault or memory corruption. This is why the COM exception above your code was added in the first place.

**Comment by BBasile** [comment]
> This is why the COM exception above your code was added in the first place.  

lol, yes, i remember because actually [i know very well the guy who added this protection...](https://github.com/BBasile/phobos/commit/211c10aff2b2cdfd9280f159cab7825b8a323c80)

**Comment by BBasile** [comment]
ping

**Pull request closed without merging**
