### PR TITLE
Typified an always throwing method as `noreturn`

### PR DESCRIPTION
**Pull request by dukc**

### CODE REVIEW

**Comment by dukc** [comment]
autotester errors: `std.exception.bailOut!(OutOfMemoryError).bailOut` without side effects discards return value of type `noreturn`; prepend a `cast(void)` if intentional.

Isn't discarding `noreturn` supposed to be ok?

**Comment by RazvanN7** [comment]
This looks like a bug to me, however, the implementation of `noreturn` is incomplete at the moment so I would wait before actually using it. cc @WalterBright

**Comment by n8sh** [comment]
https://github.com/dlang/dmd/pull/12430 fixes this.

**Comment by RazvanN7** [comment]
dlang/dmd#12430 was merged, however this is still failing.

**Comment by dukc** [comment]
Error message is still the same as last time. Perhaps the test just have not been redone since the DMD pr. I try an empty commit,

**Comment by dukc** [comment]
Still failing, but seems to be something unrelated this time.

**Comment by dukc** [comment]
Rebased. Let's see what happens this time.

**Review by thewilsonator — APPROVED** [review]

**Comment by Geod24** [comment]
This pull request introduced a (minor) regression:
https://issues.dlang.org/show_bug.cgi?id=22235

**Comment by dukc** [comment]
Aww, I wonder if I should wait a few releases before applying a new feature in Phobos next time? It could have been something more serious.

**Pull request merged**
