### PR TITLE
Add std.traits.isQualifierConvertible

### PR DESCRIPTION
**Pull request by pbackus**
Complements the existing `isImplicitlyConvertible`. From discussion in #8819 and #8827, it seems like we might want to include this so that users don't have to invent their own versions.

### CODE REVIEW

**Comment by atilaneves** [comment]
The only issue I have is that I don't think this is usable in `isInputRange` for some reason.

**Comment by pbackus** [comment]
Tested in a local branch and it appears to work if the two-argument form is split into a separate overload. Is that an acceptable workaround?

**Comment by atilaneves** [comment]
> Tested in a local branch and it appears to work if the two-argument form is split into a separate overload. Is that an acceptable workaround?

Yeah, that works.

**Review by atilaneves — APPROVED** [review]

**Comment by pbackus** [comment]
Changes to `isInputRange` pushed to pbackus/phobos@fcbca57a6; will submit PR once this is merged.

**Pull request merged**
