### PR TITLE
Markdownify std.algorithm

### PR DESCRIPTION
**Pull request by wilzbach**
Done with: https://github.com/wilzbach/dscanner-fix/blob/master/d_code_markdown.d

Revival of https://github.com/dlang/phobos/pull/5801 for `std.algorithm`

### CODE REVIEW

**Comment by wilzbach** [comment]
We can also do this file by file if that's easier.

**Comment by wilzbach** [comment]
> Because this was done via program and not by hand you can infer the correct-ness by looking at a few examples of the output (

Not that there are still some cases in which DDoc auto-highlights a token, compare e.g.

Old: http://dtest.dlang.io/artifact/website-d4a3e415e1933b1bf95375258832afc0fa2d38d9-cf0b6d829835d57b259c20e7d81ed874/web/library-prerelease/std/algorithm/sorting/top_n.html
New: http://dtest.dlang.io/artifact/website-d4a3e415e1933b1bf95375258832afc0fa2d38d9-dd7fe723dce5f3ab6d81d0f7a8671d92/web/library-prerelease/std/algorithm/sorting/top_n.html

and look at "r.length" after "satisfy".

Though AFAICT these changes look benign as the auto-highlighting actually does make sense in these spots.

**Comment by JackStouffer** [comment]
Let's get on with this.

**Comment by d-random-contributor** [comment]
First change: backticks don't nest.

**Pull request merged**
