### PR TITLE
Fix 404.

### PR DESCRIPTION
**Pull request by veelo**

### CODE REVIEW

**Comment by wilzbach** [comment]
Nice catch! How about a bot that automatizes such 404 link checking?

**Comment by CyberShadow** [comment]
Auto-merge toggled on

**Comment by veelo** [comment]
> How about a bot that automatises such 404 link checking?

I used http://www.brokenlinkcheck.com but the free version stops at 3000 pages and does not allow scanning just a sub-tree. If I am not mistaken, [Google webmaster tools](https://www.google.com/webmasters/tools/home?hl=en) does full link checking, but only for owners of the site.

A bot on Travis would be nice, but it should not block a commit when an external link stops working. To check these, a generic link checker is still necessary. It would also put a high strain on Travis, methinks.

Ideally, ddoc or ddox should just refuse to create erroneous internal links, like Doxygen does.

So as a working minimum, I would advice to check out [Google webmaster tools](https://www.google.com/webmasters/tools/home?hl=en).

**Comment by veelo** [comment]
> How about a bot that automatizes such 404 link checking?

Relevant thread: http://forum.dlang.org/post/nerbnn$2i2j$1@digitalmars.com

**Comment by atilaneves** [comment]
LGTM

**Pull request merged**
