### PR TITLE
XREF purge: CXREF, ECXREF, std/string.d, changelog.dd

### PR DESCRIPTION
**Pull request by aG0aep6G**
Caution: This removes all ref macros from changelog.dd, making it more complicated to get a preview of the changelog. With the planned upgrades to the changelog process (one file per entry, preview via doc tester), this should not be a problem in the far future. If it's a problem in the near future, I can duplicate the different `REF` variants, of course.

### CODE REVIEW

**Comment by aG0aep6G** [comment]
The first `sed` here is bad; writes "std" when it should be "core". Going to amend.

**Comment by aG0aep6G** [comment]
> The first sed here is bad; writes "std" when it should be "core". Going to amend.

Fixed.

**Comment by aG0aep6G** [comment]
This should be last of these for phobos, by the way.

**Comment by aG0aep6G** [comment]
Related pull requests for druntime and dmd:
* https://github.com/dlang/druntime/issues/1584
* https://github.com/dlang/dmd/issues/5843

**Comment by wilzbach** [comment]
> Caution: This removes all ref macros from changelog.dd, making it more complicated to get a preview of the changelog. With the planned upgrades to the changelog process (one file per entry, preview via doc tester), this should not be a problem in the far future. 

I doubt it will be a problem and if we can still reflect this during the changelog process. Also as you mentioned we will have @CyberShadow's preview for the changelog, so imho we are all good here.

> This should be last of these for phobos, by the way.

Someone any last "famous" words? ;-)

**Comment by CyberShadow** [comment]
CC @MartinNowak

**Comment by wilzbach** [comment]
@aG0aep6G tada - you've got a merge conflict :S

**Comment by aG0aep6G** [comment]
> @aG0aep6G tada - you've got a merge conflict :S

:) Resolved manually. One little typo had been fixed in the meantime.

**Comment by CyberShadow** [comment]
Auto-merge toggled on

**Pull request merged**
