### PR TITLE
Issue 17161 - [REG 2.072.2] Massive Regex Slowdown

### PR DESCRIPTION
**Pull request by JackStouffer**
This PR reverts all changes to the regex code from 2.072.2 onwards.

See the discussion [here](https://issues.dlang.org/show_bug.cgi?id=17161) and [here](https://github.com/dlang/phobos/pull/4995).

It's not fair of me to ask for regex development to be frozen until the new CTFE engine is done. However, it's unfair to our users to ask them to deal with a huge performance drop until the new CTFE engine is done.

Regex development can continue in a separate branch, and be merged into master when the CTFE is done.

CC @MartinNowak @DmitryOlshansky

### CODE REVIEW

**Comment by DmitryOlshansky** [comment]
Has some strange test failures on win32.

**Comment by JackStouffer** [comment]
I think I fixed the Windows errors.

One of the Phobos admins needs to merge this because the doc builder is still error-ing.

**Comment by JackStouffer** [comment]
Auto-merge toggled on

**Comment by MartinNowak** [comment]
Can you double-check my merge pls? https://github.com/dlang/phobos/pull/5122

**Comment by DmitryOlshansky** [comment]
Should have been more careful. Now I realize that this rollbacks way too much - we've lost BitNFA that was proudly described on the D blog:
https://dlang.org/blog/2016/11/07/big-performance-improvement-for-std-regex/

**Pull request merged**
