### PR TITLE
Eliminate shared this from std/net/curl.d

### PR DESCRIPTION
**Pull request by andralex**
Using atexit upon initialization.

### CODE REVIEW

**Comment by andralex** [comment]
cc @jcd @MartinNowak @RazvanN7 @wilzbach @JackStouffer @jpf91

**Comment by schveiguy** [comment]
I wonder if we shouldn't create a general D mechanism for `atexit` that uses a malloc'd stack of functions to run, to avoid having D consume all the entries in `atexit` (max is 32 I believe). You could do it with just one `atexit` registration.

**Comment by andralex** [comment]
@schveiguy the 32 limit is an ancient posix 1.0 requirement. I just checked and glibc uses malloc so it's essentially unbounded.

**Comment by CyberShadow** [comment]
What about DM and MS libc?

**Comment by andralex** [comment]
@CyberShadow I really think reaching the limits of atexit is not something to preoccupy ourselves with.

**Comment by CyberShadow** [comment]
> @CyberShadow I really think reaching the limits of atexit is not something to preoccupy ourselves with.

Well... Intel and AMD are releasing consumer 16+-core CPUs, that makes 32+ threads. I don't know if the limit is per process or per thread, but if it's per-process, calling just one thing using `atexit` in a `parallel` loop will hit that limit.

I think it is something we must look into, at least?

**Comment by andralex** [comment]
>I think it is something we must look into, at least?

This is "rational but not sensible". The limit is of historical relevance at best, much like the 509 character limit in printf (which was later raised to an equally insufficient 4095). Feel free to investigate, but as a matter of course it seems the kind of bureaucracy that we can't afford to spend time on.

**Comment by CyberShadow** [comment]
> Feel free to investigate,

OK, I did a quick check.

The DigitalMars C runtime has a limit of 64 functions. The limit is per process (not per thread).

Moving forward with this requires a change in the DM C runtime or a different approach.

**Comment by andralex** [comment]
@CyberShadow actually if worse comes to worst WSACleanup is not called, but the process cleanup will take care of that anyway. We're good.

**Comment by CyberShadow** [comment]
Why not provide a Phobos-specific centralized atexit implementation? Not only would that fix the atexit limit problems, but it would also allow C users to explicitly control when Phobos is deinitialized.

**Comment by andralex** [comment]
@CyberShadow it seems a very low-impact time expenditure. Definitely not necessary for this - the only reason we still call WSACleanup here is out of political correctness. Feel free to work on that after this gets pushed, but I wouldn't advise spending time on it.

**Comment by CyberShadow** [comment]
I really don't feel comfortable signing off on this one - I feel like we're hand-waving a lot of hard questions such as not only the atexit limitations, but also the difference in semantics. (E.g. what if Phobos is not used in the main program thread? atexit will call registered functions in the main thread, which Phobos never saw until then). So I'll let someone else merge this and the remaining ones.

**Comment by CyberShadow** [comment]
> Definitely not necessary for this - the only reason we still call WSACleanup here is out of political correctness.

Yes but this might eat into the limit and displace / leave no room for functions that actually really need to be called at exit.

**Comment by WalterBright** [comment]
DMC++'s limit needs to be improved, but curl doesn't work with DMC++ anyway, so I believe this PR is good to go.

**Comment by CyberShadow** [comment]
> but curl doesn't work with DMC++ anyway

Sure it does. We even ship an OPTLINK-compatible import library (and DLL) with Windows builds of DMD, do we not?

**Comment by WalterBright** [comment]
> Sure it does.

Guess I'm wrong. Anyhow, I'll fix the limit in DMC++'s library, so we're still good to go.

**Comment by WalterBright** [comment]
Auto-merge toggled on

**Comment by adamdruppe** [comment]
> I wonder if we shouldn't create a general D mechanism for atexit

I thought `share static ~this()` WAS the general D mechanism for atexit. This seems like a bizarre sideways move, what's the end goal of removing those module destructors?

**Comment by WalterBright** [comment]
Generally, the less dependencies there are in the runtime library, the more modular it is. Also, if these have no actual order dependencies, it relieves the burden on the programmer of removing non-existing import destruction cycles.

**Comment by WalterBright** [comment]
@klickverbot atexit() should not run after shared library unloads.

"Since glibc 2.2.3, atexit() (and on_exit(3)) can be used within a shared library to establish functions that are called when the shared library is unloaded."

http://man7.org/linux/man-pages/man3/atexit.3.html

**Comment by WalterBright** [comment]
"Each time a new process attempts to use the DLL, the operating system creates a separate copy of the DLL's data: this is called process attach. The run-time library code for the DLL calls the constructors for all of the global objects, if any, and then calls the DllMain function with process attach selected. The opposite situation is process detach: the run-time library code calls DllMain with process detach selected and then calls a list of termination functions, including atexit functions, destructors for the global objects, and destructors for the static objects. Note that the order of events in process attach is the reverse of that in process detach."

https://msdn.microsoft.com/en-us/library/988ye33t.aspx

**Pull request merged**
