### PR TITLE
Add fast power modulus `powmod()` for BigInt operands.

### PR DESCRIPTION
**Pull request by shove70**

### CODE REVIEW

**Comment by n8sh** [comment]
Does this function accept negative operands?

**Comment by shove70** [comment]
> Does this function accept negative operands?

Yes, it supports negative operands.

**Comment by thewilsonator** [comment]
@shove70 this PR is from your master branch, are you sure you want to do that? I'll Add 72h->merge to this.

**Comment by n8sh** [comment]
The corresponding function in `std.math` is called `powmod` (no capital "M").

**Comment by shove70** [comment]
> @shove70 this PR is from your master branch, are you sure you want to do that? I'll Add 72h->merge to this.

Yes, sure. Thank you.

**Comment by thewilsonator** [comment]
OK, please change the name to match `std.math` and rebase this so that it has no merge commits in it and this can be merged.

**Comment by thewilsonator** [comment]
You've still got the merge commits there. You can run `git diff` and save the diff to apply after resetting your master branch if you're having trouble with git.

**Pull request closed without merging**
