### PR TITLE
Simplified overloads of std.range.cycle.

### PR DESCRIPTION
**Pull request by dukc**
Well, this is breaking since it disallows cycling infinite ranges which are not forward ranges. But since cycle is intended for forward ranges only, I don't think it should compile with others even when it would just alias itself away.

### CODE REVIEW

**Comment by dukc** [comment]
I think there is: doing that is most likely a coding mistake. And because it does nothing, making the compiler complain about that helps to reduce bugs.

Trough, it could be a better option to give an explicit error message about that, so maintainers of breaking code don't get confused. Opinions?

**Comment by wilzbach** [comment]
Unfortunately I can't +1 @quickfur's review, but I fully agree with him that using `static if` within a function is the way to go! 
As Walter continues to repeat himself, it's very important to have clean APIs towards the user and being able to error with a better error message is yet another advantage.

**Comment by quickfur** [comment]
@dukc  It should be allowed.  Consider the case of a generic algorithm that uses `cycle` as part of its implementation, and that can also handle infinite ranges. If an infinite range causes a compile error in `cycle`, the algorithm will have to special-case infinite ranges, which makes the code needlessly complex.

In general, we should try to avoid special cases whenever possible, especially in generic tools like range primitives that can be used in unforeseen ways in the future. Imposing arbitrary restrictions on it will only limit its future applications, and that for no good reason.

**Comment by dukc** [comment]
Changed to behave as Quickfur requested. I don't know if it passes tests, since locally linker did not like me right now.

**Comment by quickfur** [comment]
The CI failure seems unrelated to the code changes in this PR (timeout while testing std.concurrency)?

**Pull request merged**
