### PR TITLE
Fix issue 15917 - std.concurrency module destructor causes useless cr…

### PR DESCRIPTION
**Pull request by yazd**
…eation of new MessageBox.

### CODE REVIEW

**Comment by yazd** [comment]
To help in reviewing the code, what happens is that the module destructor calls `TheadInfo.cleanup` which in turn calls `unregisterMe` which, in order to do its job, requires the current thread's `Tid`. So it calls [`thisTid`](https://github.com/dlang/phobos/blob/cf48dc32e220c80bd93e469d427e9bce8d2a26fb/std/concurrency.d#L979), but [`thisTid`](https://github.com/dlang/phobos/blob/cf48dc32e220c80bd93e469d427e9bce8d2a26fb/std/concurrency.d#L357) constructs a `Tid` lazily when first called and so it creates a new `MessageBox` which in turns creates a load of [unnecessary stuff](https://github.com/dlang/phobos/blob/cf48dc32e220c80bd93e469d427e9bce8d2a26fb/std/concurrency.d#L1790-L1805).
The solution in this PR is to, instead of using `thisTid` in `unregisterMe`, directly check the existence of the `Tid` using `thisInfo.ident` (which is used in `thisTid`).

This bug is indirectly causing this [issue](https://github.com/rejectedsoftware/vibe.d/issues/1462) in vibe.d. Its [fix](https://github.com/rejectedsoftware/vibe.d/pull/1472) requires this fix in Phobos.

**Comment by schveiguy** [comment]
LGTM. Auto tester seems to be having hiccups with timeouts on freebsd.

**Comment by DmitryOlshansky** [comment]
LGTM

**Comment by DmitryOlshansky** [comment]
Auto-merge toggled on

**Pull request merged**
