### PR TITLE
[Refactor] Generalize kickstart engines, in preparation for more to come

### PR DESCRIPTION
**Pull request by DmitryOlshansky**
This makes Kickstart engine an interface that an upcoming new engine will implement.

### CODE REVIEW

**Comment by DmitryOlshansky** [comment]
No idea about win32 failures.

**Comment by 9il** [comment]
Do we really need OOP here? Why not to use structural type system?

**Comment by DmitryOlshansky** [comment]
The exact type of kickstart (many types in future) depends on the contents of a pattern which is run-time entity.

**Comment by 9il** [comment]
OK, we will be able to use refcounting or/and allocators in the future.

**Comment by 9il** [comment]
Auto-merge toggled on

**Comment by DmitryOlshansky** [comment]
Auto-merge toggled off

**Comment by DmitryOlshansky** [comment]
Please do not merge untill Win32 failures are resolved

**Comment by 9il** [comment]
sorry, my bad

**Comment by 9il** [comment]
needs rebase

**Comment by DmitryOlshansky** [comment]
> Please do not merge untill Win32 failures are resolved

Looks like a compiler bug - tests pass without -O but fail with -O.

**Comment by AndrejMitrovic** [comment]
> Please do not merge untill Win32 failures are resolved

AFAIK the auto-tester won't merge the PR until it's green either way. ;)

**Comment by DmitryOlshansky** [comment]
Superseded by https://github.com/dlang/phobos/pull/4286

**Pull request closed without merging**
