### PR TITLE
Add missing SharedConstInoutOf and refactor QualifierOf

### PR DESCRIPTION
**Pull request by andralex**
Not sure how useful those XxxOf are, but added this one for completeness.

Also refactored QualifierOf into something that probably the compiler would have an easier time going through.

### CODE REVIEW

**Comment by thewilsonator** [comment]
```
generated/linux/debug/64/publictests/std_traits.d(488): Error: undefined identifier `MutableOf`
generated/linux/debug/64/publictests/std_traits.d(488):        while evaluating: `static assert(__traits(isSame, QualifierOf!int, MutableOf))`
```

**Comment by RazvanN7** [comment]
Can't we just deprecate them all together?

**Comment by RazvanN7** [comment]
@andralex Should we really add these for completeness? Wouldn't it be better to deprecate the existing one?

**Review by RazvanN7 — APPROVED** [review]
I'll just merge this and deprecate them altogether later if we reach that conclusion.

**Comment by andralex** [comment]
@RazvanN7 Thanks. I think we should have a better procedure for deciding on deprecation, e.g. search github.com and code.dlang.org to assess the level of use of facilities, etc.

**Pull request merged**
