### PR TITLE
[trivial] Fix formatting to appease travis

### PR DESCRIPTION
**Pull request by schveiguy**
Do not pull until travis likes.

### CODE REVIEW

**Comment by schveiguy** [comment]
OK, someone please merge this. All Travis builds will fail until this is done.

**Comment by wilzbach** [comment]
Thanks :)
We should really force the AutoTester to check the Travis status on auto-merge ...

**Comment by schveiguy** [comment]
@wilzbach the problem I see is that travis doesn't rerun when the base branch is fixed. So if we did this, we would have to manually ping every failed travis build in the event an "error" gets into master.

**Comment by wilzbach** [comment]
>@wilzbach the problem I see is that travis doesn't rerun when the base
>branch is fixed. So if we did this, we would have to manually ping
>every failed travis build in the event an "error" gets into master.

I am not sure whether I understand this correctly. Travis behaves similarly to DAutoTest and runs every to time you push to a branch (for both force-push and new commits) regardless of previous build results.

**Comment by schveiguy** [comment]
When something is merged into main-line, then travis does not rebuild all the PRs. So the build/check the bot would rely on would be stale.

D autotester clears out all results when the main line is modified, and rebuilds.

**Pull request merged**
