### PR TITLE
[BOOKTABLES]: Add BOOKTABLE to std.encoding

### PR DESCRIPTION
**Pull request by wilzbach**
image

"Booktablified" yet another module :)

### CODE REVIEW

**Comment by JackStouffer** [comment]
Same squishing problem I noted on the other PR is here as well.

Also, on the ddox version of this page, the styling is off

screen shot 2017-03-04 at 9 50 21 pm

**Comment by quickfur** [comment]
Why is "EncodingSchemes" one word? It could be split into two words, which may help with the squishing problem.

**Comment by quickfur** [comment]
ping @wilzbach 
Can we can an update please? This PR has been rotting in the queue for way too long.

**Comment by JackStouffer** [comment]
Merging as perfect is the enemy of the good, and this is an improvement

**Pull request merged**
