### PR TITLE
std.uri Cleanup

### PR DESCRIPTION
**Pull request by JackStouffer**
* removed most global imports
* removed commented out code
* made some declarations private

### CODE REVIEW

**Comment by JackStouffer** [comment]
Ok, so apparently this broke something the project tester, but I can't find anything that tells me why something broke.

**Comment by ZombineDev** [comment]
1. Click on Project Tester -> https://ci.dawg.eu/job/phobos_trigger/198/
2. Click on Subproject Builds: `DPL` Failed <build num> (e.g. #*1013*) -> https://ci.dawg.eu/job/DPL/1013/
3. Click on Subproject Builds `projects` Failed <build num> (e.g. #*874*) -> https://ci.dawg.eu/job/projects/874/
4. Look for red projects (in this case vibe.d) -> https://ci.dawg.eu/job/projects/874/REPO=rejectedsoftware%2Fvibe.d/
5. Go to Console Output (it's on the left) to see the output log and error messages -> https://ci.dawg.eu/job/projects/874/REPO=rejectedsoftware%2Fvibe.d/console
6. At the bottom you should see a segfault in one of vibe.d's tests, configuration libasync.

**Comment by JackStouffer** [comment]
Hmm, doesn't seem related.

**Comment by UplinkCoder** [comment]
You cannot just make things private.
This is begging for breakage.

**Comment by JackStouffer** [comment]
These are undocumented. The only way someone could be using these is if they read the source, in which case they should know better.

**Comment by JackStouffer** [comment]
Auto-merge toggled on

**Comment by UplinkCoder** [comment]
@JackStouffer you just broke vibe.d.

**Comment by JackStouffer** [comment]
Are you sure? Vibe was failing to compile with some druntime pulls.

**Comment by UplinkCoder** [comment]
looks that way to me.
seemed to work before this pull.

**Comment by JackStouffer** [comment]
Can you post an error message?

**Comment by UplinkCoder** [comment]
@JackStouffer looks like you introduced an import cycle

**Comment by UplinkCoder** [comment]
it segfaults somewhere in libasync

**Comment by UplinkCoder** [comment]
could be that it is really unrelated.
But please pay more attention to these kinds of failiures.
@ZombineDev it looks like your annotations pr in druntime did something unintended.

**Comment by ZombineDev** [comment]
Yes, it's my fault. See https://issues.dlang.org/show_bug.cgi?id=17130.

**Pull request merged**
