### PR TITLE
fix issue 16249 - std.signals: disconnect() is unsafe during emit() 

### PR DESCRIPTION
**Pull request by nmtigor**
[https://issues.dlang.org/show_bug.cgi?id=16249](https://issues.dlang.org/show_bug.cgi?id=16249)

### CODE REVIEW

**Comment by BBasile** [comment]
You should rebase your PR so that it forms a single commit. Additionally you should edit the message of the first commit to remove the bar between `issue` and `16249`. This allows the dlang bot to link the PR to the bugzilla issue so that  it can be closed automatically.

Rebasing will not fail otherwise a merge conflict would be displayed here. I you don't know what I'm talking about you can follow the procedure described [here](http://blog.steveklabnik.com/posts/2012-11-08-how-to-squash-commits-in-a-github-pull-request), except that you can replace the `pick` by `fixup` (instead of quash like said in the article) (in the lines 2 to N). For the first line change the message (as explained upper) but not the verb (pick).

**Comment by BBasile** [comment]
Ok, unless someone has plans to replace this old-fashioned D1-styled module I suggest to take the bug fix.

**Comment by andralex** [comment]
Auto-merge toggled on

**Comment by wilzbach** [comment]
Auto-merge toggled off

**Comment by wilzbach** [comment]
@nmtigor you should rebase to the latest branch, not merge. I toggled it (temporarily) off as I am pretty sure we want to avoid committing 250+ commits into master ;-)
(btw that's a good reason why the auto-tester should automatically toggle itself off when new push events happen, see https://github.com/braddr/d-tester/issues/49)

**Comment by nmtigor** [comment]
What's the problem with auto-tester?

**Comment by andralex** [comment]
The free list allocator is failing on one machine (not enough RAM?) and the parallelism fails on another. You may want to re-push to restart the autotester.

**Comment by DmitryOlshansky** [comment]
Auto-merge toggled on

**Pull request merged**
