### PR TITLE
Fix issue 17340 - isNumeric!bool should not be true

### PR DESCRIPTION
**Pull request by tsbockman**
https://issues.dlang.org/show_bug.cgi?id=17340

### CODE REVIEW

**Comment by JackStouffer** [comment]
Regression fixes should go onto stable so they get included in the next point release.

Please use the Github UI (the button next to the PR title) to change the base branch and then manually rebase the changes onto the right commit.

**Comment by tsbockman** [comment]
> Please use the Github UI (the button next to the PR title) to change the base branch

Done...

> manually rebase the changes onto the right commit.

What is "*the right commit*"? How do I do this?

**Comment by schveiguy** [comment]
@tsbockman I generally have to look up the directions when doing this: https://wiki.dlang.org/Starting_as_a_Contributor#Stable_Branch

**Comment by schveiguy** [comment]
The changes seem quite simple, maybe just checkout the stable branch and recreate it might take less time.

**Comment by schveiguy** [comment]
ping @wilzbach dlang bot seems to have erred here. I think when the branch was targeting stable, but included all the fixes from master, it confused the hell out of the bot and it put some unrelated bug links. But it hasn't put the correct link here (fix 17340). I'm concerned about merging this might post to wrong bug report.

**Comment by schveiguy** [comment]
Hm... auto tester I think doesn't like that the PR moved from master to stable (https://auto-tester.puremagic.com/pull-history.ghtml?projectid=1&repoid=3&pullid=5343). Something's not right. @braddr?

**Comment by JackStouffer** [comment]
@schveiguy The bug report the bot says it will close is already closed, so it should be fine.

Also, I had the same issue with another PR that I switched to stable. After I added the auto merge tag and the auto tester prioritized it, it was tested eventually.

**Comment by schveiguy** [comment]
@JackStouffer What's odd is that the auto tester is testing against master. And they are new runs, so it hasn't picked up that it needs to test against stable since the retargeting occurred. I don't know if it will switch automatically.

**Comment by quickfur** [comment]
Autotester seems completely confused. I'm gonna try closing and reopening this PR to see if that helps. Apologies in advance if that screws things up.

**Comment by quickfur** [comment]
Auto-merge toggled on

**Comment by quickfur** [comment]
OK, that seems to have kicked some sense into the autotester. Let's hope it goes through this time.

**Comment by schveiguy** [comment]
hah! dlang bot edited its comment when you reopened, very slick.

**Comment by schveiguy** [comment]
Removed the auto merge label since the auto tester is going to merge it.

**Comment by tsbockman** [comment]
> Auto-merge toggled on

Great. Thanks!

**Pull request merged**
