### PR TITLE
Test coverage for 32-bit too

### PR DESCRIPTION
**Pull request by wilzbach**
in reference to #4639

### CODE REVIEW

**Comment by 9il** [comment]
@wilzbach where the GSoC plan? 👿

**Comment by JackStouffer** [comment]
Why? Travis is not for testing Phobos. We have the auto tester for that.

**Comment by wilzbach** [comment]
> Why? Travis is not for testing Phobos. 

Jobs are run parallel at Travis and the idea of adding the 32-bit job is that we go through all 32-bits paths at least once and don't have misleading coverage reports.

> We have the auto tester for that.

The main reason for Travis is that it's a lot easier to modify - if you want to integrate coverage statistic with AutoTester (e.g. with [codecov-bash](https://github.com/codecov/codecov-bash)) that would be very nice too :)

**Comment by wilzbach** [comment]
Superseded by #4719

**Pull request closed without merging**
