### PR TITLE
style fix: add space after 'for' operator

### PR DESCRIPTION
**Pull request by wilzbach**
It turns out that I forgot to sed for `for` and there was an double occurrence of `foreach` in `std/encoding.d`.
I am terribly sorry for the spam.

### CODE REVIEW

**Comment by JackStouffer** [comment]
LGTM

**Comment by DmitryOlshansky** [comment]
Auto-merge toggled on

**Comment by trikko** [comment]
It adds spaces after "for" key, but what about:

```d
for ( auto x; elements )
```
vs

```d
for (auto x; elements)
```

?

**Comment by DmitryOlshansky** [comment]
Never seen the first style in Phobos, so the latter is prefered I guess.

**Comment by trikko** [comment]
I see it. For example on changed files for this pull request:

std/concurrency.d 1989, 2133, ...

I think it can fix this too.

**Comment by wilzbach** [comment]
> I think it can fix this too.

@trikko do you mean "I"?
Don't forget to add a regex to check for this in the future to the `.travis.yml` then ;-)

**Comment by trikko** [comment]
Whoops I mean "fixes" :+1: eheh.

**Comment by trikko** [comment]
Yes, I wrote "I think" :+1: eheh.

**Pull request merged**
