### PR TITLE
Improve isAlphaNum

### PR DESCRIPTION
**Pull request by deadalnix**
Using recent version of LDC, here are the codegen I get:
```
        lea     eax, [rdi - 48]
        cmp     eax, 74
        ja      .LBB2_1
        lea     ecx, [rdi - 97]
        mov     al, 1
        cmp     ecx, -39
        jb      .LBB2_4
        add     edi, -65
        cmp     edi, 26
        setb    al
.LBB2_4:
        ret
.LBB2_1:
        xor     eax, eax
        ret
```

And now:
```
        lea     eax, [rdi - 48]
        cmp     eax, 9
        setb    cl
        or      edi, 32
        add     edi, -97
        cmp     edi, 26
        setb    al
        or      al, cl
        ret
```

Which is much better all around: less instructions, no branches, etc...

I will note that doing `isDigit(c) || isAlpha(c)` also gives me good codegen using LDC, but I chose against it as DMD fails to inline properly and the end result is pretty bad.

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by deadalnix** [comment]
What is required to unblock this?

**Review by ljmf00 — APPROVED** [review]

**Comment by thewilsonator** [comment]
>What is required to unblock this?

Try rebasing.

**Comment by deadalnix** [comment]
@thewilsonator this is on top of master already.

**Comment by thewilsonator** [comment]
then just force-push to restart the CIs

**Pull request merged**
