### PR TITLE
[trivial] [large diff] Update uses of Flag to use the Yes/No structs.

### PR DESCRIPTION
**Pull request by e-y-e**
Apologies for the large diff. This is a find/replace job to update uses of Flag types of the form `Option.no`, `Option.yes` to `No.option` and `Yes.option`.

### CODE REVIEW

**Comment by UplinkCoder** [comment]
What value does it provide over the previous way of doing it?

**Comment by e-y-e** [comment]
I would say it paves the way for getting rid of the alias declarations as mentioned here: https://github.com/dlang/phobos/pull/4812#issuecomment-249151241, which I am not necessarily in favor of, but also when used in examples or default parameters it makes it clear that the Flag is a Flag and not an enum. It's also the style used in the codebase in other places and it makes sense to either use one or the other.

**Comment by UplinkCoder** [comment]
I would have been against #4812 
However since it already merged. 
We might continue on that path.
using Flag instead of enums  is worse in every way.
it forces template-instanciations and is worse for auto-completion.

**Comment by e-y-e** [comment]
These PRs were mainly about consistency, because in some cases a Flag was expected and in others an enum was expected when they both did the same job.

**Comment by jmdavis** [comment]
Personally, I've never liked `Flag`, and I like `{Yes,No}.name`. And I definitely think that `Name.{yes,no}` is better than changing everything over to `{Yes,No}.name`. This just seems like needless code churn to me. And for a number of these we still need an alias even if we change them to `Flag`s, because the enums have real documentation on them explaining what they mean. So, moving towards replacing all of these enums with `Flag`s - especially with no alias - just seems like a terrible idea to me.

**Comment by e-y-e** [comment]
I'm getting some mixed messages on this front. Seems some don't want Flag to be used at all, whereas others seem to want everything to be a Flag, and then to remove the aliases. Both approaches would break existing code and leave the other party very unhappy, whereas these changes aim to make the codebase, the interfaces and the docs more consistent and less context heavy.

@andralex @JackStouffer Anything to add? Seems this may be a more long term discussion that needs to happen on the use of `Flag` vs `enum`.

Anyway, all make valid points, its an interesting discussion.

**Comment by UplinkCoder** [comment]
Explicit enums are the way to go here.
The Flag templates are cheap but enums are cheaper. 
And even if we don't even talk about perf enums are also more readable

**Comment by andralex** [comment]
@e-y-e no worries, whatever happens there's going to be folks for it and folks against it. We have one idiomatic way in D to do existential flags, and that's `Flag`. It caught one as the solution of choice because it is self-descriptive and has no need for a separate definition. Peppering the standard library with various non-idiomatic flags is undesirable when we have the (almost miraculous) chance to fix it without breaking anything.

Here's how this should go:

* Leave the module-level aliases be, but never use them. Use `Flag"xxx"` in the signatures. We'll probably undocument the aliases later.

* The parameter itself does not need a descriptive name. Consider e.g.:

```d
bool isPermutation(Flag!"allocateGC" allocate_gc, Range1, Range2)
(Range1 r1, Range2 r2);
```

There is stuttering - two equivalent yet annoyingly different names for the same thing. The type name carries all that's needed (which is the beauty of the scheme). Just use `f` as the parameter name, or `f1` etc if there's two or more. So the above becomes:

```d
bool isPermutation(Flag!"allocateGC" f, Range1, Range2)
(Range1 r1, Range2 r2);
```

and that's the canonical form.

* You have descriptions such as

```d
allocate_gc = Yes/No.allocateGC
```

This slight colloquialism is fine but please use code font e.g.

```d
allocate_gc = `Yes`/`No.allocateGC`
```

(I do reckon it was in the previous text, but now since you touched these lines, they're yours :o))

**Comment by e-y-e** [comment]
I personally agree with this (still unsure about readability of e.g `Flag!"allocateGC f"` vs `AllocateGC allocateGC` but you make a good point about the type name carrying all the necessary information). I will be busy for the next <1 week but those changes look good for a few PRs.

Here's my first thoughts on what to do:

- Touch up this PR (check docs..)

- New PR: add documentation for the `Flag` to the function/etc declaration where missing.

- New PR: change uses of aliases in declarations to explicit `Flag` types.

- New PR: change parameter names to reduce redundancy.

- New PR: remove docs on aliases.

The reason so many PRs are necessary is because I think each will be met with a different set of grievances.

**Comment by andralex** [comment]
I'm okay with one PR for the whole thing (as each will spawn another discussion), but as you wish.

**Comment by e-y-e** [comment]
Amended with description changes.

**Comment by jmdavis** [comment]
I would point out that some of these flags actually need documentation. Not all such enums are one-offs used with one function, which is what `Flag` was created for in the first place, and they're not all entirely self-descriptive. `std.datetime.AllowDayOverflow` is an example of this. It's used by quite a few functions, and it has documentation to describe what it does without needing to duplicate that explanation every place that it's used. Removing such documentation would make our documentation objectively worse. So, regardless of whether any of these enums are converted to `Flag`, some of those aliases really should exist and continue to be documented.

**Comment by andralex** [comment]
Auto-merge toggled on

**Pull request merged**
