### PR TITLE
Fix issue 4509 - XML parser in std.xml throws TagException if the attr value is put in apostrophes.

### PR DESCRIPTION
**Pull request by aG0aep6G**
This is a resubmission of #4064 which @coderabhishek wasn't able to finish. I've added the requested asserts in a separate commit. CC @quickfur.

If this gets merged, #4064 can be closed.

### CODE REVIEW

**Comment by Hackerpilot** [comment]
:white_check_mark:

**Comment by aG0aep6G** [comment]
Added a commit to actually do the parsing so that the asserts are actually run :S

**Comment by aG0aep6G** [comment]
I don't get the Travis CI failure. It says:

> std/internal/phobosinit.d(26:12)[warn]: Local imports should specify the symbols being imported to avoid hiding local symbols.

std.internal.phobosinit has been added in #4493, but Travis CI has been green there. And it's green on other PRs.

**Comment by schveiguy** [comment]
Not only that, but the warning is inaccurate. That is the *perfect* place to do a wholesale import of another module. Why was that warning added as a requirement?

**Comment by quickfur** [comment]
Probably need to rebase on HEAD to get the `phobosinit` fix included in this PR.

Other than that, LGTM.

**Comment by aG0aep6G** [comment]
Triggered a re-run of Travis CI. Is green now.

**Comment by quickfur** [comment]
Auto-merge toggled on

**Pull request merged**
