### PR TITLE
[DOC] Minor update to minElement example

### PR DESCRIPTION
**Pull request by growlercab**
Removes ambiguity between min element value and index of min element value.

### CODE REVIEW

**Comment by wilzbach** [comment]
Rebased your PR to `stable`, s.t. it will be deployed to dlang.org soon.

**Comment by MartinNowak** [comment]
> CyberShadow/DAutoTest

That one really needs a rerun button @CyberShadow.

**Comment by wilzbach** [comment]
> That one really needs a rerun button @CyberShadow.

FYI: The failure is due to the DUB registry being unreachable. 
Should I cherry-pick the fix from `master` to `stable`? https://github.com/dlang/dlang.org/pull/1926

**Comment by MartinNowak** [comment]
> Should I cherry-pick the fix from master to stable? dlang/dlang.org#1926 and dlang/dlang.org#1891

Sure

**Comment by wilzbach** [comment]
> Should I cherry-pick the fix from master to stable? dlang/dlang.org#1926 and dlang/dlang.org#1891

https://github.com/dlang/dlang.org/pull/2089

**Pull request merged**
