### PR TITLE
Test compiling Phobos with `-boundscheck=off` in CI

### PR DESCRIPTION
**Pull request by ljmf00**
Signed-off-by: Luís Ferreira <contact@lsferreira.net>

### CODE REVIEW

**Comment by ljmf00** [comment]
By merging #8222 and #8220 this should compile.

**Comment by RazvanN7** [comment]
What is the rationale for doing this?

**Comment by CyberShadow** [comment]
We should not do this. It removes `@safe` guarantees.

Situations where maximum speed is preferred over integrity / correctness / safety exist, but they are relatively rare, and such a thing needs to be very very opt-in (the compile-your-own-standard-library kind of opt-in).

Fixes to make Phobos work with `-noboundscheck` are welcome, but we should not change the default.

**Comment by CyberShadow** [comment]
I misread the pull request. This does not change the default, but adds a CI pass to test building Phobos without bounds checking.

**Review by RazvanN7 — APPROVED** [review]

**Pull request merged**
