### PR TITLE
Update D-Scanner to alpha 8.

### PR DESCRIPTION
**Pull request by Hackerpilot**
Should un-block https://github.com/dlang/phobos/pull/4668

### CODE REVIEW

**Comment by wilzbach** [comment]
@Hackerpilot did you change anything in alpha7? Travis is failing due to linking errors :/

**Comment by Hackerpilot** [comment]
Working on it.

**Comment by Hackerpilot** [comment]
Ready to go.

**Comment by wilzbach** [comment]
Btw these messages are not a CodeCov bug, it's on our side.

```
 Hits          65471      65473     +2   
+ Misses         8356       8354     -2   
```

It comes from `std.parallelism` and `std.concurrency`:

```
 std/parallelism.d -1   +1
634	
            throw exception;
```

```
std/concurrency.d -1   +1
1346	
        return ThreadInfo.thisInfo;
2134	
                    thisInfo.owner = Tid.init;
2337	
                m_last = n;
```

**Comment by 9il** [comment]
Auto-merge toggled on

**Pull request merged**
