### PR TITLE
Adding const to all ref FormatSpec parameters.

### PR DESCRIPTION
**Pull request by japplegame**
Because this should compile:
```d
void foo() {
    ...
    static immutable spec = singleSpec("%s");
    formatValue(writer, value, spec);
    ...
}
```

### CODE REVIEW

**Comment by japplegame** [comment]
Because this should compile:
```d
void foo() {
    static immutable spec = singleSpec("%s");
    formatValue(writer, value, spec);
}
```

**Comment by japplegame** [comment]
Also I suppose `Writer` parameter of `formatValue` and `formattedWrite` should be `auto ref`. What do you think?

**Comment by JackStouffer** [comment]
Please target master. Only regressions go into stable

**Comment by aG0aep6G** [comment]
> Please target master. Only regressions go into stable

@wilzbach told me previously:

> @aG0aep6G to iterate what Martin is trying to say for the last year:
>>  All bug fixes should go into stable

Which one is it now? "Only regressions" or "all bug fixes"?

**Comment by japplegame** [comment]
Sorry. I messed up my branch. So created new PR  #5263

**Pull request closed without merging**
