### PR TITLE
Add @system and @safe to std.datetime unit tests

### PR DESCRIPTION
**Pull request by atilaneves**

### CODE REVIEW

**Comment by JackStouffer** [comment]
Could you break this into multiple PR's or commits? The diff is too large to show on Github.

**Comment by atilaneves** [comment]
Breaking it is possible but not easy... I'd have to undo the commit then git add -p at random points.

**Comment by WalterBright** [comment]
Why not just close this, then open two new ones, one with the first half and the other with the second half?

**Comment by atilaneves** [comment]
Who knows if half would be small enough, so I broke the commit into several which can be viewed here separately

**Comment by WalterBright** [comment]
Thanks!

**Pull request merged**
