### PR TITLE
std/file.d: Don't check for OS-dependent error message in unittest

### PR DESCRIPTION
**Pull request by the-horo**

### CODE REVIEW

**Review by CyberShadow — APPROVED** [review]

**Review by thewilsonator — APPROVED** [review]

**Comment by CyberShadow** [comment]
@the-horo Out of curiosity, what motivated this? I see the check is already in a `version (linux)` block.

**Comment by the-horo** [comment]
I though the comment was referring to the error message being possibly different across linux distributions. The purpose of the PR is to fix the tests on Gentoo, where the error message is:
```
core.exception.AssertError@std/file.d(1094): Failed to remove file (null): Bad address

```

**Comment by CyberShadow** [comment]
Thanks. But isn't the error message string you posted exactly what the test used to check for?

**Comment by the-horo** [comment]
Right. I severely lack in reading comprehension skills apparently. If I run the unittest as a normal user they pass normally. If run through Gentoo's package manager I get:
```
core.exception.AssertError@std/file.d(1093): Failed to remove file (null): Invalid argument
```

**Comment by CyberShadow** [comment]
Thanks (and, interesting!)

**Pull request merged**
