### PR TITLE
Enable -preview=dtorfields for phobos

### PR DESCRIPTION
**Pull request by MoonlightSentinel**
Let's see what breaks.

### CODE REVIEW

**Review by wilzbach — APPROVED** [review]

**Comment by Geod24** [comment]
@MoonlightSentinel : So there's no risk of ABI mismatch if the client doesn't use this switch ?

**Comment by MoonlightSentinel** [comment]
Don't think so, `-preview=dtorfields` just adds additional code in the constructor to destroy the instance which was previously  ignored when throwing an exception.
Unless I'm missing something(?)

**Comment by UplinkCoder** [comment]
This appears to have broken something ?
https://issues.dlang.org/show_bug.cgi?id=21250

**Comment by UplinkCoder** [comment]
@MoonlightSentinel please revert.
on stable.
@MartinNowak We need a patch release.

**Comment by UplinkCoder** [comment]
This is a timebomb.
Regardless of whether you fix that instance in phobos.
We don't know what else it breaks.
Defer to next release!

**Comment by wilzbach** [comment]
It's already released.

**Comment by UplinkCoder** [comment]
Yes indeed.
We need a patch release asap.

**Pull request merged**
