### PR TITLE
Updated posix.mak makefile to use ../tools/checkwhitespace.d

### PR DESCRIPTION
**Pull request by RazvanN7**
I noticed that the windows makefiles don't have a checkwhitespace rule. Is that ok?

### CODE REVIEW

**Comment by wilzbach** [comment]
> I noticed that the windows makefiles don't have a checkwhitespace rule. Is that ok?

Yeah whitespace checks only need to be run on _one_ CI and at the moment the auto-tester runs this on nearly all machines and CircleCi runs this as well.

**Comment by wilzbach** [comment]
Btw I think I mentioned it once before, but we do check for trailing whitespace already on the `style` target

```
grep -nr '[[:blank:]]$$' etc std ; test $$? -eq 1
```

https://github.com/dlang/phobos/blob/master/posix.mak#L497

So an easy way would be to make `checkwhitespace` a no-op, and just add a check for tabs to the `style` target, like e.g.:

```
grep -nr $'\t' --include='*.d'  ; test $$? -eq 1
```

**Comment by RazvanN7** [comment]
@wilzbach I will let the makefile use the checkwhitespace.d for now to preserve consistency with the dmd makefile

**Comment by RazvanN7** [comment]
@wilzbach Applied!

**Comment by andralex** [comment]
@wilzbach we good?

**Comment by wilzbach** [comment]
> @wilzbach we good?

Well, there's nothing different to this PR than to the one at DMD (and the same discussion applies). 
However, as this target optional and only used by the auto-tester, I don't want to bikeshed this further.

**Pull request merged**
