### PR TITLE
llroundl is available on windows, so why not use it?

### PR DESCRIPTION
**Pull request by John-Colvin**
I suspect this PR will fall foul of some platforms/runtimes... let's see :)

### CODE REVIEW

**Comment by John-Colvin** [comment]
So... Windows 32 has llroundl declared but not actually present in the C runtime by the looks of things.

Is the autotester Win_32 working with DigitalMars or Microsoft C runtime?

**Comment by thewilsonator** [comment]
Digital Mars.

**Comment by John-Colvin** [comment]
What system tests with the 32 bit Microsoft runtime?

**Comment by ZombineDev** [comment]
> What system tests with the 32 bit Microsoft runtime?

Look for the the `Win_32` rows on the `auto-tester`.

**Comment by ZombineDev** [comment]
If you want to test with `-m32mscoff`, the best would be to setup Azure Pipelines, similarly to how it's done for dmd:

* https://github.com/dlang/dmd/blob/master/azure-pipelines.yml
* https://github.com/dlang/dmd/blob/f5069353042e50ea566f8ed28f6eb5d19a78cc9b/.azure-pipelines/windows.sh#L67

**Comment by RazvanN7** [comment]
`std/math.d` no longer exists; it has been refactored into multiple files. Right now the functions touched by this PR no longer call `core.stdc.math.llroundl` only for Posix. It has been refactored to assert if `version=CRuntime_DigitalMars`, which is correct.

Closing this.

**Pull request closed without merging**
