### PR TITLE
Add example to std.string.toStringz

### PR DESCRIPTION
**Pull request by JackStouffer**
Also removed commented out code

### CODE REVIEW

**Comment by wilzbach** [comment]
Looks good!

**Comment by wilzbach** [comment]
this is a trivial PR that went under the radar, can someone have a look & pull? Thanks!

**Comment by DmitryOlshansky** [comment]
LGTM

**Comment by DmitryOlshansky** [comment]
Auto-merge toggled on

**Comment by JackStouffer** [comment]
Thanks!

**Pull request merged**
