### PR TITLE
[std.regex] Use ref-counting for Captures struct

### PR DESCRIPTION
**Pull request by DmitryOlshansky**
Should improve cases where a lot of temporary captures allocated with big number of submatches.

### CODE REVIEW

**Comment by JackStouffer** [comment]
Benchmark?

**Comment by DmitryOlshansky** [comment]
> Benchmark?

Need to create one for this I guess.

**Comment by 9il** [comment]
rebase please

**Comment by DmitryOlshansky** [comment]
> Benchmark?

Doesn't show any difference on things I tried. This pull however unties matching from GC usage so we may have `@nogc` one day.

**Comment by 9il** [comment]
Auto-merge toggled on

**Comment by schuetzm** [comment]
It seems this introduced a regression:
https://issues.dlang.org/show_bug.cgi?id=16698

**Comment by 9il** [comment]
Ping @DmitryOlshansky

**Comment by DmitryOlshansky** [comment]
I'm on it

**Comment by quickfur** [comment]
Apparently it's caused by interaction with a compiler bug: [issue 16699](https://issues.dlang.org/show_bug.cgi?id=16699).

**Pull request merged**
