### PR TITLE
Fix issue 16352 - dead-lock in std.allocator.free_list unittest

### PR DESCRIPTION
**Pull request by WalterWaldron**
https://issues.dlang.org/show_bug.cgi?id=16352

Also fixes ```deallocateAll``` not updating free list count and dereferencing after free which were found in the process.

### CODE REVIEW

**Comment by WalterWaldron** [comment]
@andralex Supposedly its addressed in this PR: https://github.com/dlang/phobos/pull/4955#issuecomment-268853079

**Comment by andralex** [comment]
@WalterWaldron push again

**Comment by wilzbach** [comment]
> @WalterWaldron push again

Unfortunately before this PR we did not merge into the target branch at CircleCi (it's not supported there out of the box), so you need to rebase :/

**Comment by WalterWaldron** [comment]
> so you need to rebase :/

I squashed the last two commits for the added benefit of not having broken unit tests while bisecting.

**Comment by wilzbach** [comment]
> I squashed the last two commits for the added benefit of not having broken unit tests while bisecting.

As the error was happening in the `circleci.sh` script & it didn't do merges to master before, you really need to run:

```
git rebase upstream/master
```

**Comment by WalterWaldron** [comment]
>  As the error was happening in the circleci.sh script & it didn't do merges to master before, you really need to run:

I'm not familiar with circleci workings, anyway, I've rebased as instructed.

**Comment by andralex** [comment]
Auto-merge toggled on

**Comment by andralex** [comment]
Thanks @WalterWaldron!

**Pull request merged**
