### PR TITLE
std.stdio: remove redundant version declarations

### PR DESCRIPTION
**Pull request by WalterBright**
These just confuse things.

### CODE REVIEW

**Comment by CyberShadow** [comment]
I see you didn't remove `GENERIC_IO`, I guess that's still needed? If so, that seems to indicate that these version definitions are still useful?

**Comment by WalterBright** [comment]
I haven't determined what the right solution for GENERIC_IO is, but I do know that renaming A=B just for the heck of it is not the best idea.

**Comment by WalterBright** [comment]
Phobos in general seems to have an excessive number of version declarations.

**Comment by WalterBright** [comment]
Check out this:
```
else version (GENERIC_IO)
{
    nothrow:
    @nogc:

    extern (C) private
    {
        static import core.stdc.wchar_;

        pragma(mangle, fputc.mangleof) int _FPUTC(int c, _iobuf* fp);
        pragma(mangle, core.stdc.wchar_.fputwc.mangleof) int _FPUTWC(wchar_t c, _iobuf* fp);
        pragma(mangle, fgetc.mangleof) int _FGETC(_iobuf* fp);
        pragma(mangle, core.stdc.wchar_.fgetwc.mangleof) int _FGETWC(_iobuf* fp);
    }

    version (Posix)
    {
        private alias _FLOCK = core.sys.posix.stdio.flockfile;
        private alias _FUNLOCK = core.sys.posix.stdio.funlockfile;
    }
    else
    {
        static assert(0, "don't know how to lock files on GENERIC_IO");
    }
```
meaning that GENERIC_IO just means Posix, because otherwise std.stdio will not compile.

**Comment by WalterBright** [comment]
@CyberShadow see also related https://github.com/dlang/phobos/pull/8803

**Comment by CyberShadow** [comment]
> meaning that GENERIC_IO just means Posix

"POSIX but not GNU libc" though, right?

I think I wrote that `version (Posix)` block and the check is entirely redundant there.

**Comment by CyberShadow** [comment]
Deferring to @ibuclaw.

**Review by dkorpel — APPROVED** [review]

**Pull request merged**
