### PR TITLE
Fix issue 4957 - std.concurrency rejects structs with Tid

### PR DESCRIPTION
**Pull request by Geod24**
```
In addition to the fix which makes it recurse in struct,
the instantiation was changed to not use recursive template instantiation,
exception for struct's tupleof.
```

### CODE REVIEW

**Comment by bithavoc** [comment]
I hope this gets merged, this and https://issues.dlang.org/show_bug.cgi?id=5570 made me feel that Dlang was not stable enough a few years back. I've seen more activity in these bug reports these days, I'm feeling tempted to try Dlang again ☕️ .

**Comment by andrej-mitrovic** [comment]
> the instantiation was changed to not use recursive template instantiation

But doesn't the old code short-circuit, and yours does not? Then again maybe the performance is ultimately better because of a lack of recursive template instantiations.. ¯\_(ツ)_/¯

**Comment by n8sh** [comment]
>Is there a way to short-circuit without recursive instantiation ?

In my experience you can write `doesIt |= ...; if (doesIt) return true;` without triggering an unreachable code check.

**Comment by Geod24** [comment]
Don't think this has much influence, because by the time the code is run at CTFE all we have is `doesIt |= [true|false]` so we're just assigning from a constant. Evaluating the template is what we should really short-circuit, but we can't do that with CTFE.

**Comment by n8sh** [comment]
For the benefit of dlang-bot I edited the commit message to start "Fix Issue 4957" instead of "Fix 4957", but that's been clobbered. Please make that change.

**Comment by Geod24** [comment]
I did already, but dlang-bot doesn't seem to realize this.

**Comment by Geod24** [comment]
@n8sh : Ah, commit message, not PR title. Sorry. Thanks for the fix!

**Comment by wilzbach** [comment]
Yep that's needed to aggregate the changelog entries over commit messages

**Pull request merged**
