### PR TITLE
Fix issue 17894 - std.regex.internal.ir.Bytecode.length is defined as uint

### PR DESCRIPTION
**Pull request by ZombineDev**
See https://github.com/dlang/phobos/pull/5726#issuecomment-335768162 for more context.

### CODE REVIEW

**Comment by ZombineDev** [comment]
Nevermind @dlang-bot - we need this fix only master.

**Comment by DmitryOlshansky** [comment]
@ZombineDev Please don't Bytecode isn't a range and never ment to be one. Length is uint is perfectly fine.

**Comment by ZombineDev** [comment]
> Bytecode isn't a range and never meant to be one

I agree 100%. My intention is **not** to make `Bytecode` pass `isInputRange`, but instead to allow it fail *gracefully* without emitting warning that break the build.

**Comment by DmitryOlshansky** [comment]
> I agree 100%. My intention is not to make Bytecode pass isInputRange, but instead to allow it fail gracefully without emitting any warnings that break the build.

This is patently wrong. If *unrelated field* called length breaks some build check *that build check is wrong*.

**Comment by ZombineDev** [comment]
So which course of action do you propose? Removing the check for warnings or to removing the warning?

**Comment by DmitryOlshansky** [comment]
Remove the check if there are false positives.
Do no mutilate code to fit some poorly designed check obviously.

**Comment by ZombineDev** [comment]
Without this check input ranges with whose `.length` field is not defined as `size_t` will unconditionally fail the `isInputRange` check. So you propose breaking the code of all Phobos users? :D

**Comment by DmitryOlshansky** [comment]
> Without this check input ranges with whose .length field is not defined as size_t will unconditionally fail the isInputRange check. So you propose breaking the code of all Phobos users, whose input ranges are not using size_t? :D

Something is seriously damaged if that is the case. A single unrelated struct needs to be reworked because some check for Ranges somewhere else won't pass otherwise for user-defined structs. Am I mad thinking this is sheer idiocy?

**Comment by DmitryOlshansky** [comment]
> So you propose breaking the code of all Phobos users, whose input ranges are not using size_t? :D

So don't. Why std.regex.Bytecode is the victim of poorly devised checks in std.range?

**Comment by ZombineDev** [comment]
> Am I mad thinking this is sheer idiocy?

Hah. Initially the commit message for the PR was named "Workaround stupid bug", however the more I investigated the less certain I was that there is a clear answer here. If you examine carefully all the code in that stack, you'll find that every single one is doing the right thing in isolation, it's just when we integrate everything it all falls apart.

**Comment by ZombineDev** [comment]
> A single unrelated struct needs to be reworked because some check for Ranges somewhere else won't pass otherwise for user-defined structs.

If there's someone to put to the blame, it's the probably the template constraint in `std.array.insertInPlace(T, U...)(ref T[] array, size_t pos, U stuff)`, which `std.regex.internal.parser.optimize` internally uses.

**Comment by DmitryOlshansky** [comment]
> But still, I don't see a clear way forward, save for the workaround proposed by this pull request.

You do understand that some innocent user-defined object may have defined length to be something other then size_t and it may have called insertInPlace

**Comment by DmitryOlshansky** [comment]
> If there's someone to put to the blame, it's the probably the template constraint in std.array.insertInPlace(T, U...)(ref T[] array, size_t pos, U stuff), which std.regex.internal.parser.optimize internally calls. But still, I don't see a clear way forward, save for the workaround proposed by this pull request.

Obviously we need somehow to first check is smth is a range and then issue a warning or whatever if the length is not size_t. Bytecode is not a range hence no warning.

**Comment by ZombineDev** [comment]
> Obviously we need somehow to first check is smth is a range and then issue a warning or whatever if the length is not size_t. Bytecode is not a range hence no warning.

The code goes the other way around. In order to check if `R` is an input range, it checks if `R` defines `empty`. If `empty` is not defined, the compiler implicitly uses via UFCS the version of `empty` defined in `std.range.primitives`, which calls `hasLength`.

**Comment by ZombineDev** [comment]
> You do understand that some innocent user-defined object may have defined length to be something other then size_t and it may have called insertInPlace

This is not problem though. Their build system is unlikely to fail if the compiler emits a `pragma(msg, ...)`, while the phobos build system will.

**Comment by DmitryOlshansky** [comment]
> while the phobos build system will.

Why do we need this?

**Comment by ZombineDev** [comment]
To ensure that users of Phobos won't get unrelated warnings. That way it forces authors of PRs to fix warnings, before they reach the end-users.

**Comment by ZombineDev** [comment]
Fine, let's see how this goes.

**Pull request closed without merging**
