### PR TITLE
std.math.IeeeFlags: make getters const

### PR DESCRIPTION
**Pull request by aG0aep6G**
As [requested](https://github.com/dlang/phobos/pull/5240#discussion_r104324767).

Not sure if this qualifies for stable or if it should go into master.

### CODE REVIEW

**Comment by wilzbach** [comment]
> Not sure if this qualifies for stable or if it should go into master.

I don't know either. It's not really a "bug fix" more an "enhancement", so I would have targetted `master`, but I doubt it matters in this case.

**Comment by wilzbach** [comment]
It looks like the stable branch has been "broken" by other changes:

```
executing out/std_regex_package.d
out/std_regex_package.d(43): Error: undefined identifier 'popFrontN'
out/std_regex_package.d(150): Error: undefined identifier 'Yes.keepSeparators'
out/std_regex_package.d(154): Error: undefined identifier 'Yes.keepSeparators'
make: *** [publictests] Error 1
```

DAutoTest complains as well :/

**Comment by JackStouffer** [comment]
Mind the failures @aG0aep6G

**Comment by aG0aep6G** [comment]
> Mind the failures @aG0aep6G

As far as I can tell, the failures of DAutoTest and circleci are not related to my changes.

**Comment by JackStouffer** [comment]
@aG0aep6G Ah, it's because you're on stable.

There was a dmd bug with dlang.org that was fixed in master. Try changing the base branch to master.

**Comment by aG0aep6G** [comment]
> There was a dmd bug with dlang.org that was fixed in master. Try changing the base branch to master.

Changed to master. Aside: Does this mean we just cannot get anything into stable now?

**Comment by JackStouffer** [comment]
Not unless either Andrei or Walter merges it who as far as I'm aware are the only people who can still merge with failing tests.

**Pull request merged**
