### PR TITLE
Make Mallocator betterC friendly

### PR DESCRIPTION
**Pull request by RUSShyTwo**
Ideally allocators should be betterC compatible

A good candidate for a ``core`` package, let's try and remove the imports to std

### CODE REVIEW

**Comment by Herringway** [comment]
Wouldn't moving allocators to core actually prevent them from being used in betterC, given that core is part of druntime?

**Comment by RUSShyTwo** [comment]
> Wouldn't moving allocators to core actually prevent them from being used in betterC, given that core is part of druntime?

That would help isolate the module, also i'm pretty use some part of ``core`` are accessible in betterC?

**Comment by ljmf00** [comment]
core has `max` and `min` functions in internal module, see https://github.com/dlang/druntime/blob/master/src/core/internal/util/math.d . I think this change makes the code more unreadable and the transition is easy to do anyway. I propose adding a FIXME comment explaining why if this is going forward.

**Comment by RUSShyTwo** [comment]
> core has `max` and `min` functions in internal module, see https://github.com/dlang/druntime/blob/master/src/core/internal/util/math.d . I think this change makes the code more unreadable and the transition is easy to do anyway. I propose adding a FIXME comment explaining why if this is going forward.

The motive is to make the module not need any external imports, so it's a perfect candidate for a betterC compatible module

If the one liner is harder to read, i can make it a package function like i did for ``isPowerOfTwo``

**Comment by radcapricorn** [comment]
I think this is not the way to move forward. The way, IMO, is to recognize `min` and `max` as fundamental algorithms and (at least) require them publicly defined in core or (better) be builtins and not require **any** imports.

**Comment by RUSShyTwo** [comment]
> I think this is not the way to move forward. The way, IMO, is to recognize `min` and `max` as fundamental algorithms and (at least) require them publicly defined in core or (better) be builtins and not require **any** imports.

I agree with that, that would be ideal

**Comment by ljmf00** [comment]
> Ideally allocators should be betterC compatible

But `max` from `std.algorithm` is not betterC ready?

**Comment by PetarKirov** [comment]
> The motive is to make the module not need any external imports [..]

This has nothing to do with BetterC. BetterC simply about the compiler not implicitly linking the DRuntime / Phobos libraries and (perhaps too) eagerly producing errors when the user attempts to use features that depend on druntime being linked (e.g. TypeInfo / ModuleInfo, GC, exceptions, etc.).

In BetterC mode you can freely use template functions (such as `min` and `max`) defined in any library (including DRuntime and Phobos) as long as they also call only template functions that don't depend on the features mentioned above (basically like header-only libraries in C++ that only include other header-only libraries).

**Review by PetarKirov — CHANGES_REQUESTED** [review]
While I agree that the allocator package should be BetterC compatible and that it should probably live under `core.*`, the changes in this PR don't help with BetterC compatibility. The right way to permanently improve BetterC compatibility is to add a `@betterC` unittest that guarantees that a given function is usable in BetterC mode.


If a `@betterC unittest` passes with and without a set of changes, it is a good indicator that those changes are not necessary and should be reverted.

For example, see:
* https://github.com/dlang/druntime/blob/v2.098.1/src/core/lifetime.d#L3 (search for `@betterC` unit tests below)
* https://github.com/dlang/phobos/blob/v2.098.1/posix.mak#L651-L669
* https://github.com/dlang/phobos/blob/v2.098.1/std/algorithm/comparison.d#L119
* https://github.com/dlang/phobos/blob/v2.098.1/std/typecons.d#L77 (search for `@betterC` unit tests below)
* https://github.com/dlang/phobos/blob/v2.098.1/std/internal/memory.d

**Comment by atilaneves** [comment]
I second what @PetarKirov said.

**Comment by RazvanN7** [comment]
@RUSShyTwo What are your plans with this PR?

**Comment by RUSShyTwo** [comment]
@RazvanN7 there is no sign of ``std.experimental.allocator`` leaving experimental, so i don't want to put in effort if it goes to the trashbin, so i'll close this and re-evaluate the effort maybe next year or in 10 years, depending on progress

**Pull request closed without merging**
