### PR TITLE
Add a changelog entry for the performance improvement of std.algorithmm.iteration.joiner

### PR DESCRIPTION
**Pull request by wilzbach**
Follow-up to https://github.com/dlang/phobos/pull/6492

Preview:

image

### CODE REVIEW

**Comment by ZombineDev** [comment]
@wilzbach feel free to force merge as Jenkins is still marked as required.

**Comment by Geod24** [comment]
Can we make that gist live under the `dlang` organisation, instead of your personal account ?

**Comment by wilzbach** [comment]
I'm not sure there's an easy way to do so :/
We could create a special benchmark repository, but I'm not sure it's worth the effort. 
If you are worried about the link being dead in the future, we could link to the respective PR instead (though of course you never know what will happen to GitHub in the MS-age).

**Comment by Geod24** [comment]
> (though of course you never know what will happen to GitHub in the MS-age)

Well... Doesn't that reasoning applies to `gist` as well ? :)
Do you see any way to add it [here](https://gist.github.com/dlang/) ?

**Pull request merged**
