### PR TITLE
Fix Issue 16281 – std.format.formattedRead should use ref instead of requiring pointers

### PR DESCRIPTION
**Pull request by RazvanN7**
This is a reopening of @Bolpat 's branch. For more information see #5247

Credits go to @Bolpat . This commit does the exact same thing except for deprecating the pointer versions.

### CODE REVIEW

**Comment by JackStouffer** [comment]
I'm confused, the orginal PR is open and Andrei still seems against the change

**Comment by Bolpat** [comment]
@JackStouffer, see https://github.com/dlang/phobos/pull/5247#issuecomment-293320167.

**Comment by burner** [comment]
I agree with @andralex comment, the api should stay as is.

**Comment by andralex** [comment]
The idea is to allow references and also pointers.

**Pull request closed without merging**
