### PR TITLE
std.variant: Make visit, tryVisit pass file, line to VariantException

### PR DESCRIPTION
**Pull request by ntrel**
Also fix `Handlers` capitalization (see commit).

### CODE REVIEW

**Comment by JackStouffer** [comment]
@WalterBright is against such additions, pinging for his opinion

**Comment by ntrel** [comment]
@JackStouffer Added tests (and another minor fix).

**Comment by JackStouffer** [comment]
Ping @WalterBright  or @andralex

**Comment by andralex** [comment]
No, sorry, this is too much overhead. One major attraction of visitiation it doesn't have a large performance hit, and this chews into that.

**Comment by ntrel** [comment]
@andralex Maybe I could rework this so release mode is unaffected?

**Comment by andralex** [comment]
@ntrel a good idea. But overall is the complication worth it? The question is how many clients would be helped, and by how much, by adding file and line. I hypothesize that not too many.

**Pull request closed without merging**
