### PR TITLE
Remove all Replace definitions except for alias

### PR DESCRIPTION
**Pull request by andralex**
Unittests pass so I'm putting this up for review. If there was a reason for all, we'll see soon enough.

### CODE REVIEW

**Comment by andralex** [comment]
> Best get rid of GenericReplace and move that into Replace. See also ReplaceAll

Right, that's the grand plan. Per Chesterton's fence rule, I'm waiting for comments from the folks who introduced the code to make sure I'm not tripping any wires.

**Comment by andralex** [comment]
> See also ReplaceAll

See also a third of this module :)

**Comment by thewilsonator** [comment]
Touché.

**Comment by andralex** [comment]
I'll be back with a more substantive rework.

**Comment by dnadlinger** [comment]
This would have been because basic types used to be incompatible with alias parameters.

**Pull request closed without merging**
