### PR TITLE
Regex. Numbers of begin and end symbol of match in input data.

### PR DESCRIPTION
**Pull request by DarkRiDDeR**
Numbers of begin and end symbol of match in input data.
Application examole:
```
	alias matchType = Tuple!(string, "text", int, "position");
	matchType[] results;
	auto matches = matchAll(subject, regex(pattern, regex_flags));
	while (!matches.empty) {
		matchType result;
		result.text = matches.front.hit;
		result.position = captures.numBegin;
		results ~= result;
		matches.popFront();
	}
```

### CODE REVIEW

**Comment by DmitryOlshansky-google** [comment]
To be honest the API is ugly. Secondly the same applies to submatches, you might want indices for these too. Lastly all of this is possible today with pointers:
```d
alias matchType = Tuple!(string, "text", int, "position");
	matchType[] results;
	auto matches = matchAll(subject, regex(pattern, regex_flags));
	while (!matches.empty) {
		matchType result;
		result.text = matches.front.hit;
		result.position = result.text.ptr - subject.ptr;
		results ~= result;
		matches.popFront();
	}
```

**Comment by DmitryOlshansky** [comment]
To be honest the API is ugly. Secondly the same applies to submatches, you might want indices for these too. Lastly all of this is possible today with pointers:
```d
alias matchType = Tuple!(string, "text", int, "position");
	matchType[] results;
	auto matches = matchAll(subject, regex(pattern, regex_flags));
	while (!matches.empty) {
		matchType result;
		result.text = matches.front.hit;
		result.position = result.text.ptr - subject.ptr;
		results ~= result;
		matches.popFront();
	}
```

**Comment by DarkRiDDeR** [comment]
Thank you!!! But works correctly only for char. How to be with wchar? Using a codeLength is not suitable
`import std.regex;
	import std.utf: codeLength;
	alias matchType = Tuple!(string, "text", int, "position");
	matchType[] results;
	auto subject = `полоса two three`;
	auto matches = matchAll(subject, regex(pattern, regex_flags));
	int subjectLen = codeLength!wchar(subject);
	while (!matches.empty) {
		matchType result;
		result.text = matches.front.hit;
		result.position = codeLength!wchar(result.text);
		results ~= result;
		matches.popFront();
	}
	writeln(results[0].position); //6
	writeln(results[1].position); //3
	writeln(results[2].position); //5`

**Comment by DarkRiDDeR** [comment]
Probably, it is possible to take a line from memory by means of pointers and already to process it codeLength

**Comment by DmitryOlshansky** [comment]
> How to be with wchar? Using a codeLength is not suitable

I don't get what you are trying to do. It works perfectly fine for wchar - what you get is offset that can slice with.

**Comment by DarkRiDDeR** [comment]
I figured it out. Thank you again

```
	import std.utf: codeLength;
	alias matchType = Tuple!(string, "text", int, "position");
	matchType[] results;
	auto matches = matchAll(subject, regex(pattern, regex_flags));
	while (!matches.empty) {
		matchType result;
		result.text = matches.front.hit;
		result.position = codeLength!wchar(subject[0..(result.text.ptr - subject.ptr)]);
		results ~= result;
		matches.popFront();
	}
```

**Comment by DmitryOlshansky** [comment]
So you match on utf-8 string but then convert position of the match as if it was wstring... 
Do you know that you can match on wstring as well?

**Comment by DarkRiDDeR** [comment]
I looked in the documentation, but did not find how to do it. Maybe I was searching bad. Could you tell?

**Comment by DmitryOlshansky** [comment]
Hm could be missing from thea docs.
Basically you need your pattern to be wstring.
auto r = regex(w"some pattern")
for( m : text.matchAll(r)){
wstring hit = m.hit;
}

**Pull request closed without merging**
