### PR TITLE
Fix issue 24549 - std.process.environment.get(null) segfaults

### PR DESCRIPTION
**Pull request by schveiguy**
The true fix I think would b to make it so tempCString never returns null (it doesn't make a lot of sense). But the code was clearly intended to work this way, and was set up because of a long ago regression.

Even if that problem is eventually fixed, this fix is not invalidated.

### CODE REVIEW

**Comment by CyberShadow** [comment]
Would it more correct to do something like `if (!name) name = "";` ?

**Comment by schveiguy** [comment]
> Would it more correct to do something like `if (!name) name = "";` ?

I think in this case, it doesn't matter -- I don't think an empty string is a valid environment name.

**Comment by Geod24** [comment]
> I don't think an empty string is a valid environment variable name.

Yes, but the distinction between empty string and `null` is a common gotcha.

**Comment by schveiguy** [comment]
There are many ways to solve this. I think if we are going to do a check for null anyway, we might as well circumvent the entire process. Why call an opaque C function when we know it's going to return "variable not found"?

**Comment by schveiguy** [comment]
All green now. Would be nice to get this in the next release...

**Review by CyberShadow — APPROVED** [review]

**Pull request merged**
