### PR TITLE
Support std.typecons.Tuple expansion in 'any' and 'all'

### PR DESCRIPTION
**Pull request by FeepingCreature**
It would be convenient if ranges that iterated over typecons Tuples could be used with predicates that took multiple parameters. This PR adds tests and implementation for 'all' and 'any' to start, by changing 'find' to try Tuple expansion and 'any' and 'all' to check more relaxedly.

### CODE REVIEW

**Comment by MetaLang** [comment]
I dunno about this... auto-expansion for tuples in `foreach` loops is considered to have been a mistake; I don't know if we want to codify it in Phobos as well.

**Comment by FeepingCreature** [comment]
Personally I feel it's something that seems like it _should_ work if viewed intuitively. If I'm looking at a range of tuples, I'm rarely interested in the tuples as values, but usually in their individual members.

**Comment by wilzbach** [comment]
> Personally I feel it's something that seems like it should work if viewed intuitively. 

Well, yes `10.iota.enumerate.find!(e => e.value == 7)` isn't as powerful as `10.iota.enumerate.find!((idx, val) => val == 7)`, but note that with the extra braces needed you actually don't save keystrokes - especially if you consider that you could write `10.iota.enumerate.find!(e => e[1] == 7)` too.

Anyhow, the biggest problem with this is that once we start doing this for a few ranges, a user would expect it to work for all ranges. Even if we say we do this for Phobos, there are functions that accept a `pred` that could be unary or binary as well, so we might run into problems there.

**Comment by FeepingCreature** [comment]
I'd been trying to see if there was some way to support this within unaryPred, but I couldn't figure it out. There doesn't seem to be a way to, depending on arguments, either define a function or an alias, in a way that still works with ifti.

**Comment by andralex** [comment]
This seems to add a special case that needs more explanation than just following the simpler rules. I suggsest closing.

**Pull request closed without merging**
