### PR TITLE
faster front

### PR DESCRIPTION
**Pull request by UplinkCoder**
On ascii input a simple cast is enough.
No need to call decode..

### CODE REVIEW

**Comment by UplinkCoder** [comment]
@andralex could you review this ?

**Comment by andralex** [comment]
Could you please post some numbers you get with the code below? First run the baseline and write then the numbers. Then replace myFront with your version and run again and write those as well. Thanks!

```d
import std.range;

alias myPopFront = std.range.popFront;
alias myFront = std.range.front;

void main(string[] args) {
    import std.algorithm, std.array, std.stdio;
    char[] line = "0123456789".dup.repeat(50_000_000).join;
    ulong checksum;
    if (args.length == 1)
    {
        while (line.length) {
            version(autodecode)
            {
                checksum += line.myFront;
                line.myPopFront;
            }
            else
            {
                checksum += line[0];
                line = line[1 .. $];
            }
        }
        version(autodecode)
            writeln("autodecode ", checksum);
        else
            writeln("bytes ", checksum);
    }
    else
        writeln("overhead");
}
```

**Comment by andralex** [comment]
(use optimized build)

**Comment by UplinkCoder** [comment]
Using the above code I get a 24% speed increase with dmd.
and a 5% decrease using ldc.

**Comment by UplinkCoder** [comment]
I suspect preventing decodeImpl from being in-lined would help matters.

**Comment by UplinkCoder** [comment]
The only change in the resulting code is in code-layout, not in the instructions generated.

**Comment by andralex** [comment]
That must mean ldc already inlines decodeImpl and dmd doesn't. Ideally we'd have a solution working nicely for all.

**Comment by UplinkCoder** [comment]
I think inlining decodeImpl is not beneficial, since it pulls in rarely used code. Do we have a portable `neverinline` ?

**Comment by 9il** [comment]
> I think inlining decodeImpl is not beneficial, since it pulls in rarely used code. Do we have a portable neverinline ?

`pragma(inline, false)`

**Comment by 9il** [comment]
> I think inlining decodeImpl is not beneficial, since it pulls in rarely used code.

I don't think so. When you parse Russian or Chines `decodeImpl` will be called almost each time.

**Comment by 9il** [comment]
> Using the above code I get a 24% speed increase with dmd.
> and a 5% decrease using ldc.

I don't think this is good optimization. `decode` already has it:
```d
    if (str[index] < codeUnitLimit!S)
        return str[index++];
...
```
This can be added for DMD only. LDC does not need it because it is just a code duplication to help DMD

**Comment by andralex** [comment]
Yah, I was thinking the same as @9il. One good thing to do here is go inside the decode() implementation and make it smaller. If smaller, its inlined version will do better.

**Comment by UplinkCoder** [comment]
decode does unnecessary work.
by increment the index and requires an unnecessary variable to be created.
Writing the UTF8-decoding inline here will give us a speedup no doubt.

**Comment by 9il** [comment]
> decode does unnecessary work.
> by increment the index and requires an unnecessary variable to be created.
> Writing the UTF8-decoding inline here will give us a speedup no doubt.

This will be reduced by LDC.

**Comment by UplinkCoder** [comment]
mov qword ptr [rsp], 0
right there.

**Comment by UplinkCoder** [comment]
@klickverbot 
I don't see why we should relay on complicated back-end optimization when 10 lines of code can make it a sure deal ?
Fixing DMD's inliner seems to be rather involved.

**Comment by UplinkCoder** [comment]
I have just tested a it on the test @andralex provided above.
A front that is written inline is 9% faster.

**Comment by 9il** [comment]
I am closing this PR. The reason is that this is not solution for current problem, and a proper solution can be found. Feel free to open a new PR with clean solution. The question is open, and this thread is still open for discussion.

**Comment by 9il** [comment]
Please also test 2 bytes and 4 bytes based text too for new PR
.

**Comment by UplinkCoder** [comment]
@9il The point of this was to improve performance on ASCII only code.

**Comment by 9il** [comment]
> @9il The point of this was to improve performance on ASCII only code.

But we should be sure that this would not reduce performance for other encodings.

**Comment by andralex** [comment]
It doesn't seem we have a solid attack here. One way would be to not throw from front which would make the function smaller and faster, but that would break compatibility.

**Comment by 9il** [comment]
`decodeImpl` can be (I hope so) inlined for LDC using `version(LDC) pragma(inline, true);` `decodeImpl` contains loops, it is weird.

> One way would be to not throw from front which would make the function smaller and faster

+1

**Comment by UplinkCoder** [comment]
I just ran a benchmark using a chapter from Alis book in Turkish .
This is the result for ldc -O3 :
```
my_popFront and my_front took: 89usecs
popFront and front took: 93usecs
```

This is the result for dmd -release -O
```
my_popFront and my_front took: 161usecs
popFront and front took: 245usecs
```
And this is the result for ldc2 -Os -release
```
my_popFront and my_front took: 106usecs
popFront and front took: 176usecs
```

**Comment by UplinkCoder** [comment]
On the blns.txt testcase
ldc -release -O3 does
```
my_popFront and my_front took: 67usecs
popFront and front took: 80usecs
```

**Comment by andralex** [comment]
Which my_popFront would that be? The one in this diff?

**Comment by UplinkCoder** [comment]
The one I merged. With branch_hints.

**Comment by UplinkCoder** [comment]
My Front looks like this : 
```
dchar myFront(ref char[] str) pure
{
    dchar c = cast(dchar) str.ptr[0];
    if (c & 128)
    {
        if (c & 64)
        {
            auto l = charWidthTab.ptr[c - 192];
            if (str.length < l)
                goto Linvalid;

            final switch (l)
            {
            case 2:
                c = ((c & ~(64 | 128)) << 6);
                c |= (str.ptr[1] & ~0x80);
                break;
            case 3:
                c = ((c & ~(32 | 64 | 128)) << 12);
                c |= ((str.ptr[1] & ~0x80) << 6);
                c |= ((str.ptr[2] & ~0x80));
                break;
            case 4:
                c = ((c & ~(16 | 32 | 64 | 128)) << 18);
                c |= ((str.ptr[1] & ~0x80) << 12);
                c |= ((str.ptr[1] & ~0x80) << 6);
                c |= ((str.ptr[3] & ~0x80));
                break;
            case 5, 6, 1:
                goto Linvalid;
            }
        }
        else
    Linvalid : throw new Exception("yadayada");

    }
    return c;
}
```

**Comment by andralex** [comment]
Oh, yes, meant to ask about my_front. That looks tight, how about discussing that instead of the current content of this PR?

**Comment by UplinkCoder** [comment]
For ldc -O3 this does not make too big of a difference. 
I measured a few times and the speed-up is in the noise.
However If one builds with -Os or -Oz
or if one uses dmd this is quite the improvment.

**Comment by andralex** [comment]
I'd say paste the new front in and reopen but let's put a conclusion to this soon - thanks!

**Comment by UplinkCoder** [comment]
It does not pass phobos unitests.
oh well.

**Comment by wilzbach** [comment]
@UplinkCoder please don't create branches for such small work at upstream. The upstream repository should only be used for releases and reverts as we all get notifications of you push to them!! 
(and it creates a lot of noise) 

E. g. https://forum.dlang.org/post/580176d2226ca_33d43fab72cf5140806fa@hookshot-fe3-cp1-prd.iad.github.net.mail

**Comment by UplinkCoder** [comment]
@wilzbach I didn't mean to do that.
It pushed to the wrong repo

**Pull request closed without merging**
