### PR TITLE
Ensure that Variant.visit only accepts handlers that handle allowed types

### PR DESCRIPTION
**Pull request by MetaLang**
This is a simplified reworking of https://github.com/dlang/phobos/pull/4894

### CODE REVIEW

**Comment by MetaLang** [comment]
And this is why you test a PR on your local system before committing.

**Comment by BBasile** [comment]
Yeah and just `dmd theModule.d -unittest -main && ./theModule` is usually enough when only 1 module is involved.

**Comment by andralex** [comment]
lgtm, but what's with the autotester failure?

**Comment by MetaLang** [comment]
Unfortunately I think I'll have to close this PR as it breaks some of the `Algebraic` unit tests.

**Comment by ntrel** [comment]
The failing code is:
```
 static assert( __traits(compiles, number.visit!((string x) => x ~ "a", x => x + 1)));
```
This is just after the declaration of `maybenumber`, which is unused. I think these tests are erroneously using `number` instead of `maybenumber`. Fixing that then causes an error that `x => x + 1` cannot be instantiated with `string` (one of `maybenumber.AllowedTypes`). This bug was not hit before as each of `number.AllowedTypes` can instantiate the generic lambda.

**Comment by MetaLang** [comment]
Yes, I've already gone down this rabbit hole and came to the conclusion that this functionality can't be implemented without breaking `Algebraic`. I can't remember what the exact issue was, though, so I will go over it again to double check. However, in general, we're going from more permissive to less permissive, so it's more or less a given that some code will break. It all depends on whether we _want_ to break code that uses `Algebraic` or not.

**Comment by ntrel** [comment]
There seems to be a problem with my setup, so I can't run tests ATM. But, the `maybenumber` test needs to be fixed, and is fairly straightforward using `to!string`: https://github.com/ntrel/phobos/commit/d5c5dbb69948c0d6c5ec7e2725ade703ea076849

**Pull request closed without merging**
