### PR TITLE
Fixed wrong variable name in embedded doc

### PR DESCRIPTION
**Pull request by mtrenkmann**

### CODE REVIEW

**Comment by wilzbach** [comment]
Thanks - LGTM :)

**Comment by schveiguy** [comment]
Auto-merge toggled on

**Comment by schveiguy** [comment]
@wilzbach what's up with the report that this will decrease coverage? Makes no sense.

**Comment by wilzbach** [comment]
> @wilzbach what's up with the report that this will decrease coverage? Makes no sense.

It comes from std.concurrency and std.parallelism. Due to undeterministic behavior with multithreading some lines get covered in a specific build and sometimes not. I am not an expert in these modules, so if you know how we could ensure that these lines always get covered, please go ahead. You can browse these lines on the codecov file output. 

Btw Codecov provides two measures (1) patch (only counts modified coverage in the diff - as expected this  didn't change here), and (2) project (overall coverage).

**Pull request merged**
