### PR TITLE
Avoid use of EnumMembers in enum specialization of formatValueImpl

### PR DESCRIPTION
**Pull request by nordlow**
Also see https://github.com/dlang/phobos/pull/8591.

### CODE REVIEW

**Comment by nordlow** [comment]
Looks at the definition of EnumMembers. It makes n+1 template instances where n is the number of members of the enum.

**Comment by pbackus** [comment]
`EnumMembers` only creates 1 template instance since PR #8262 was merged last year—a PR which you yourself submitted!

If we want to get rid of the second `__traits(allMembers)`, the correct solution IMO is to replace it with `__traits(identifier)`, which in addition to any performance benefits will also make the meaning of the code clearer to future readers.

**Comment by schveiguy** [comment]
regardless of whether this is needed (which I don't think it is), I can't see a reason to store the members as a static immutable.

**Comment by nordlow** [comment]
> regardless of whether this is needed (which I don't think it is), I can't see a reason to store the members as a static immutable.

Should we store it as an enum instead?

**Comment by schveiguy** [comment]
> Should we store it as an enum instead?

I see nothing wrong with
```d
foreach(member; __traits(allMembers, T))
```

**Comment by pbackus** [comment]
From the other PR thread, @nordlow's benchmark showing a reduction in memory usage by replacing `EnumMembers` with `__traits(allMembers)`: https://github.com/dlang/phobos/pull/8591#discussion_r993022406

**Comment by atilaneves** [comment]
What is the supposed benefit?

**Review by RazvanN7 — APPROVED** [review]

**Comment by RazvanN7** [comment]
@atilaneves for the benchmark presented in https://github.com/dlang/phobos/pull/8591#discussion_r993022406 , the reduction was 4%.

@nordlow please fix the conflict.

**Comment by nordlow** [comment]
> @nordlow please fix the conflict.

Done.

**Pull request merged**
