### PR TITLE
Fix issue 15530: multiSort forbids any SwapStrategy different from un…

### PR DESCRIPTION
**Pull request by jamesragray**
…stable.

### CODE REVIEW

**Comment by jamesragray** [comment]
Can't help but wonder if multiSort shouldn't always forward to sort.
```d
import std;
import std.datetime.stopwatch;


alias P = Tuple!(int,int);

bool multiSortPredFun(T, funs...)(T a, T b)
{
    foreach (f; funs)
    {
        alias lessFun = binaryFun!(f);
        if (lessFun(a, b)) return true;
        if (lessFun(b, a)) return false;
    }
    return false;
}

void main() {
   auto points = [P(1,3),P(5,4),P(2,7),P(0,9),P(1,2)].cycle.take(10000).array;
    benchmark!(()=>points.sort!(multiSortPredFun!(P,(a,b)=>a[0]<b[0],(a,b)=>a[1]<b[1])))(10000).writeln;
    benchmark!(()=>points.multiSort!((a,b)=>a[0]<b[0],(a,b)=>a[1]<b[1]))(10000).writeln;
}
```
[5 secs, 821 ms, 922 μs, and 7 hnsecs]
[7 secs, 566 ms, 474 μs, and 2 hnsecs]

**Comment by RazvanN7** [comment]
Hi @jamesragray ! Thanks for your pull request. Unfortunately, I don't think this is the right solution. The underlying issue is that `partition3` does not support the stable swapping strategy. I suggest fixing `partition3` to accept the stable swap strategy.

**Comment by jamesragray** [comment]
> Hi @jamesragray ! Thanks for your pull request. Unfortunately, I don't think this is the right solution. The underlying issue is that `partition3` does not support the stable swapping strategy. I suggest fixing `partition3` to accept the stable swap strategy.

I agree that what I did isn't ideal, but (a) it produces a stable multi sort (b) it is better in my opinion than keeping the broken state (for more than six years). Wouldn't it be better to accept this trivial change and then open a new issue (saying multisort stable is too slow if it really is)?

**Comment by pbackus** [comment]
Won't this give the wrong answer when the elements in the input range are not already correctly ordered by the 2nd comparison function?

For example, in the new unit test, what happens if you swap `Point(1, 1)` and `Points(1, 2)` in `pts1`?

**Comment by jamesragray** [comment]
You are correct, line 1582 should be:
```d
sort!(multiSortPredFun!(Range,funs), ss)(r);
```
I will fix it later today.

**Comment by RazvanN7** [comment]
> @RazvanN7 I agree that what I did isn't ideal, but (a) it produces a stable multi sort (b) it is better in my opinion than keeping the broken state (for more than six years). Wouldn't it be better to accept this trivial change and then open a new issue (saying multisort stable is too slow if it really is)?

@jamesragray The fact that this is an old issue isn't a motivation to accept a hacky fix. The problem is that if we accept small fixes like this one day we will end up with tons of such cases that will ultimately add to the burden of maintaining the code. As Walter has said in the past "the small crabs that accumulate will eventually sink the ship". So, I, personally, don't agree with this addition. However, I will not block its addition if others accept it.

**Comment by jamesragray** [comment]
Hi I agree putting bad code into phobos just to fix an issue is wrong. I guess what we don't agree about is that although this is simple change I don't consider it to be hacky.  It simply forwards multisort stable to sort stable with the approriate predicate. On the other hand I have implemented a stable version of partion3 here: https://github.com/dlang/phobos/pull/8583. So when I have time I will benchmark this forwarding approach against using the stable partition3 via the current implementation of multisort.

**Pull request closed without merging**
