### PR TITLE
Fix 17416 - Add REUSEPORT to std.socket

### PR DESCRIPTION
**Pull request by 0xEAB**
#8389 plus a reference link as requested by @CyberShadow.
Text has been adjusted to provide further explanations.

Further reading: <https://stackoverflow.com/a/14388707>

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]
Please retitle the _commit message_ "Fix bugzilla issue 17416 - Add REUSEPORT to std.socket"

**Comment by pinskia** [comment]
See https://github.com/dlang/dmd/issues/20688

**Comment by ibuclaw** [comment]
I think this would have also caused a build regression on Solaris if I'm reading the change correctly.

**Comment by 0xEAB** [comment]
Yeah, the introduction of a regression was clearly unfortunate.
Glad you’ve discovered it in time – thanks for that, much appreciated!

(I think we should keep in mind though that the original PR (#8389) was already 32 months old when this slight adaption finally got merged – given nobody noticed during that period, one could almost say, the regression was bound to happen.)

**Pull request merged**
