### PR TITLE
std.file: delete is not @safe

### PR DESCRIPTION
**Pull request by WalterBright**
This is blocking https://github.com/dlang/dmd/pull/5887

### CODE REVIEW

**Comment by ZombineDev** [comment]
LGTM

**Comment by schveiguy** [comment]
Wow, this function is a nightmare. Not even close to `@safe`.

This is fixing at the wrong level, but the fix doesn't leave the function any worse off than before, and allows a much more important update to `@safe` than the scope of this function. So...

**Comment by schveiguy** [comment]
Auto-merge toggled on

**Comment by schveiguy** [comment]
https://issues.dlang.org/show_bug.cgi?id=16218

**Pull request merged**
