### PR TITLE
[scope] add annotations to std.datetime

### PR DESCRIPTION
**Pull request by WalterBright**

### CODE REVIEW

**Comment by jmdavis** [comment]
Does this relate to a recent DIP? I wasn't even aware that `scope` was legal on return types, and I don't have any idea what it would mean on a return type. I thought that the whole point of `scope` was to prevent references from escaping, and that's exactly what happens with a `ref` return type. It's whole purpose is to have the reference escape.

**Comment by WalterBright** [comment]
It's to support DIP1000, which adds semantics for `scope` and `scope ref`.

**Comment by WalterBright** [comment]
Looks like dscanner for ci/circleci needs updating:
```
../dscanner/dsc --config .dscanner.ini --styleCheck $(find etc std -type f -name '*.d' | grep -vE 'std/traits.d|std/typecons.d') -I.
std/datetime.d(905:39)[error]: 'in', 'out', 'body', or block statement expected
std/datetime.d(908:19)[error]: Declaration expected
std/datetime.d(910:9)[error]: Declaration expected
std/datetime.d(9290:1)[error]: Declaration expected
make: *** [style] Error 1
```

**Comment by wilzbach** [comment]
> Looks like dscanner for ci/circleci needs updating:

I guess it's libdparse -  CC @Hackerpilot

**Comment by andralex** [comment]
Auto-merge toggled on

**Pull request merged**
