### PR TITLE
chore(allocator): make AlignedMallocator pure

### PR DESCRIPTION
**Pull request by ljmf00**
Signed-off-by: Luís Ferreira <contact@lsferreira.net>

---

Requires https://github.com/dlang/dmd/pull/14456 to compile successfully.

### CODE REVIEW

**Comment by RazvanN7** [comment]
This looks like it requires a rebase.

**Review by RazvanN7 — CHANGES_REQUESTED** [review]
Please also annotate the unittests as pure so that we have this covered.

**Comment by RazvanN7** [comment]
ping @ljmf00

**Comment by RazvanN7** [comment]
You're welcome! Looks like on windows the allocator is not pure.

**Comment by ljmf00** [comment]
For some reason, Windows OMF is failing.

**Review by thewilsonator — APPROVED** [review]

**Pull request merged**
