### PR TITLE
Switched package-wide datetime imports to new sub-packages

### PR DESCRIPTION
**Pull request by JackStouffer**
Should have faster compile times.

### CODE REVIEW

**Comment by JackStouffer** [comment]
Now that's an interesting failure for Win32. Maybe someone can correct me on this, but it looks like a Win32 specific lookup error.

**Comment by CyberShadow** [comment]
> Now that's an interesting failure for Win32. Maybe someone can correct me on this, but it looks like a Win32 specific lookup error.

No, it's breaking because FILETIMEToSysTime is no longer in scope.

I think `static assert(__traits(compiles, ...))` is an anti-pattern, it could be replaced with `if (false) {...}`. Then the error message would be obvious.

**Comment by JackStouffer** [comment]
Should be fixed now

**Comment by CyberShadow** [comment]
FILETIMEToSysTime is Windows only :)

**Comment by JackStouffer** [comment]
I should really setup vagrant at some point

**Comment by wilzbach** [comment]
@JackStouffer mind the current failure on Windows:

```
std\file.d(1239): Error: undefined identifier `SysTimeToFILETIME`
std\file.d(1240): Error: undefined identifier `SysTimeToFILETIME`
std\file.d(1309): Error: template instance std.file.setTimes!string error instantiating
std\file.d(1315):        instantiated from here: setTimes!(TestAliasedString)
```

**Comment by JackStouffer** [comment]
Phobos was successfully built on the windows platforms so this looks good to go @wilzbach @CyberShadow

**Comment by CyberShadow** [comment]
LGTM, thanks!

**Pull request merged**
