### PR TITLE
make assertThrown return the caught Exception

### PR DESCRIPTION
**Pull request by burner**
* returning the exception also it to be inspected this is not possible otherwise

### CODE REVIEW

**Comment by ZombineDev** [comment]
This may be a breaking change, because `assertThrown` may be inferred as `pure`, in which case existing users will get a compiler warning because they're discarding the result of a call to a `pure` function, which with dub leads to compilation error by default.

**Comment by burner** [comment]
s**t, I didn't think of that. IMO a function like this is still valuable. Ideas?

**Comment by DmitryOlshansky** [comment]
> s**t, I didn't think of that. IMO a function like this is still valuable. Ideas?
> 
> Update: what are the inference rules for lazy expression?

collectAssert ?

**Comment by ZombineDev** [comment]
> Update: what are the inference rules for lazy expression?

If the function is not templated, it should as if you're calling a delegate with no attributes.

On the other hand w.r.t. function templates, my understanding is that the current implementation treats them the same, but that may (should IMO) change in the future. See: https://issues.dlang.org/show_bug.cgi?id=12647

**Comment by jmdavis** [comment]
> collectAssert ?

Well, we already have `collectException`, which would work perfectly fine for this. It's just that it would require that you then assert that the result is non-null rather than it throwing an `AssertError` for you in the case where nothing was thrown.

**Comment by burner** [comment]
I didn't know about collectException, but that is not what I want.

I want collectException + assertThrown

**Comment by wilzbach** [comment]
> I want collectException + assertThrown

You get that with collectException too. While a jup pointer isn't nice, it's a failure in the test suite and will prevent it from passing.
Of course, it's also not that difficult to check that collectException didn't return `null`, if people feel that this is too much manual work, it could be a flag to collectException..

**Comment by burner** [comment]
I'm too lazy to check for null. A flag is better, but it will not be turned on by default (I guess)!?

How about a function called catchAndReturn?

**Comment by jmdavis** [comment]
> How about a function called catchAndReturn?

That just sounds like `collectException`. If you're adding a function, something like `collectAndAssertException` would make more sense, though that's getting a bit long.

Though honestly, while I'm not opposed to adding this sort of functionality, I do question that it's needed often enough to make sense to add it to the standard library when `collectionException` already does what you need. It just requires an extra assertion. So, we're talking about adding only a slight variation on what's already there, which is the sort of thing that Andrei tends to veto. If we do anything, I think that it makes the most sense to figure out a clean way to adjust `collectionException` so that you can optionally tell it to throw an `AssertError` if the return value is `null`. Certainly, adding a new function seems like overkill, much as I can see wanting to avoid the extra assertions for non-`null`.

**Comment by burner** [comment]
I think @jmdavis is right, I'm closing this.

**Pull request closed without merging**
