### PR TITLE
Remove deprecated std.c package

### PR DESCRIPTION
**Pull request by JinShil**
According to the `@@@DEPRECATED_2017-06@@@` header comment, this is overdue for removal.  Mostly this is just house-cleaning, but somewhat motivated by discussion at https://github.com/dlang/druntime/pull/2179

### CODE REVIEW

**Comment by jmdavis** [comment]
Yeah. These need to go. Their removal was delayed, because vibe.d depended on some stuff in here that hadn't made it into druntime, but that was fixed several months ago.

**Comment by jmdavis** [comment]
> Seems like std(x).allocator needs to be fixed as well.

Yeah, though it appears to be a Windows-only problem.

    ../dmd/generated/windows/release/32/dmd.exe -lib -ofphobos.lib -Xfphobos.json -conf= -O -release -w -de -dip25 -I..\druntime\import std\stdio.d  std\string.d  std\format.d  std\file.d  std\array.d  std\functional.d  std\path.d  std\outbuffer.d  std\utf.d  std\csv.d  std\math.d  std\complex.d  std\numeric.d  std\bigint.d  std\bitmanip.d  std\typecons.d  std\uni.d  std\base64.d  std\ascii.d  std\demangle.d  std\uri.d  std\mmfile.d  std\getopt.d  std\signals.d  std\meta.d  std\typetuple.d  std\traits.d  std\encoding.d  std\xml.d  std\random.d  std\exception.d  std\compiler.d  std\system.d  std\concurrency.d  std\uuid.d  std\variant.d  std\zlib.d  std\socket.d  std\conv.d  std\zip.d  std\stdint.d  std\json.d  std\parallelism.d  std\mathspecial.d  std\process.d  std\algorithm\package.d  std\algorithm\comparison.d  std\algorithm\iteration.d  std\algorithm\mutation.d  std\algorithm\searching.d  std\algorithm\setops.d  std\algorithm\sorting.d  std\algorithm\internal.d  std\container\array.d  std\container\binaryheap.d  std\container\dlist.d  std\container\rbtree.d  std\container\slist.d  std\container\util.d  std\container\package.d  std\datetime\date.d  std\datetime\interval.d  std\datetime\package.d  std\datetime\stopwatch.d  std\datetime\systime.d  std\datetime\timezone.d  std\digest\crc.d  std\digest\sha.d  std\digest\md.d  std\digest\ripemd.d  std\digest\digest.d  std\digest\hmac.d  std\digest\murmurhash.d  std\digest\package.d  std\net\isemail.d  std\net\curl.d  std\range\package.d  std\range\primitives.d  std\range\interfaces.d  std\regex\internal\ir.d  std\regex\package.d  std\regex\internal\parser.d  std\regex\internal\tests.d  std\regex\internal\tests2.d  std\regex\internal\backtracking.d  std\regex\internal\thompson.d  std\regex\internal\kickstart.d  std\regex\internal\generator.d    std\windows\registry.d  std\windows\syserror.d  std\windows\charset.d    std\internal\cstring.d  std\internal\unicode_tables.d  std\internal\unicode_comp.d  std\internal\unicode_decomp.d  std\internal\unicode_grapheme.d  std\internal\unicode_norm.d  std\internal\scopebuffer.d  std\internal\test\dummyrange.d  std\internal\test\range.d  std\internal\digest\sha_SSSE3.d  std\internal\math\biguintcore.d  std\internal\math\biguintnoasm.d  std\internal\math\biguintx86.d  std\internal\math\gammafunction.d  std\internal\math\errorfunction.d  std\internal\windows\advapi32.d  std\experimental\all.d std\experimental\checkedint.d std\experimental\typecons.d  std\experimental\allocator\common.d  std\experimental\allocator\gc_allocator.d  std\experimental\allocator\mallocator.d  std\experimental\allocator\mmap_allocator.d  std\experimental\allocator\showcase.d  std\experimental\allocator\typed.d  std\experimental\allocator\package.d  std\experimental\allocator\building_blocks\affix_allocator.d  std\experimental\allocator\building_blocks\aligned_block_list.d  std\experimental\allocator\building_blocks\allocator_list.d  std\experimental\allocator\building_blocks\ascending_page_allocator.d  std\experimental\allocator\building_blocks\bitmapped_block.d  std\experimental\allocator\building_blocks\bucketizer.d  std\experimental\allocator\building_blocks\fallback_allocator.d  std\experimental\allocator\building_blocks\free_list.d  std\experimental\allocator\building_blocks\free_tree.d  std\experimental\allocator\building_blocks\kernighan_ritchie.d  std\experimental\allocator\building_blocks\null_allocator.d  std\experimental\allocator\building_blocks\quantizer.d  std\experimental\allocator\building_blocks\region.d  std\experimental\allocator\building_blocks\scoped_allocator.d  std\experimental\allocator\building_blocks\segregator.d  std\experimental\allocator\building_blocks\stats_collector.d  std\experimental\allocator\building_blocks\package.d  std\experimental\logger\core.d  std\experimental\logger\filelogger.d  std\experimental\logger\multilogger.d  std\experimental\logger\nulllogger.d  std\experimental\logger\package.d    etc\c\zlib.d  etc\c\curl.d  etc\c\sqlite3.d  etc\c\odbc\sql.d  etc\c\odbc\sqlext.d  etc\c\odbc\sqltypes.d  etc\c\odbc\sqlucode.d  etc\c\zlib\zlib.lib ..\druntime\lib\druntime.lib
    std\experimental\allocator\mallocator.d(165): Error: module `stdlib` is in file 'std\c\stdlib.d' which cannot be read
    import path[0] = ..\druntime\import

**Comment by wilzbach** [comment]
Looking at Jenkins, it seems that Vibe.d is still depending on it :/

**Comment by JinShil** [comment]
Jenkins is now passing (Thank you @wilzbach, @BBasile, @atilaneves, and  stefan-koch-sociomantic for your support)

@wilzbach, circleci is now failing.  Can you please help me troubleshoot?

**Comment by wilzbach** [comment]
Oh it looks like just the DScanner hash here at Phobos isn't up-to-date

https://github.com/dlang/phobos/pull/6529

edit: we need to update the git submodules too, e.g. https://github.com/dlang-community/containers/pull/113 and https://github.com/dlang-community/D-Scanner/pull/642

**Comment by JinShil** [comment]
Grrr. Circle CI is still failing.  The latest DScanner is now reporting an error for this code:

```D
static if (is(T == const U, U)
        || is(T == immutable U, U)
        || is(T == shared U, U)
        || is(T == const shared U, U))
    {
```
`std/typecons.d(2440:9)[warn]: Left side of logical or is identical to right side.`

Looks like it might be a bug in dscanner as the code looks fine to me.

**Comment by BBasile** [comment]
Yes it's a D-Scanner bug : see https://github.com/dlang-community/D-Scanner/issues/593. Unfortunately nobody manages to reproduce it.

**Comment by wilzbach** [comment]
The CircleCi failure appears randomly with ~10% chance, so a restart often helps ;-)

**Pull request merged**
