### PR TITLE
Fix style (space between a .. b) in std/json.d

### PR DESCRIPTION
**Pull request by wilzbach**
See also: https://github.com/dlang/phobos/pull/5541#issuecomment-313282541

CC @CyberShadow 

(will investigate how it managed to get through Circle)

### CODE REVIEW

**Comment by wilzbach** [comment]
I cherry-picked the commit from https://github.com/dlang/phobos/pull/5547#issuecomment-313247317

**Comment by wilzbach** [comment]
> (will investigate how it managed to get through Circle)

https://github.com/dlang/phobos/pull/5511 was never green on CircleCi:

image

It's simply not required: 

image

**Comment by CyberShadow** [comment]
Thanks :)

**Comment by wilzbach** [comment]
Regarding https://github.com/dlang/phobos/pull/5547#issuecomment-313851985

> maybe because everyone ignores CircleCI, since it fails quite often

@MartinNowak No AFAICt it simply has never been enforced.
Btw regarding failures - I am not so sure whether this is true anymore. Here are the build statistics for the last month:

image

Phobos builds over the last month in details:

image

There were only four failures in the last thirty days and half of them were our fault:

- https://circleci.com/gh/dlang/phobos/3368 -> our fault (old, unrebased PR)
- https://circleci.com/gh/dlang/phobos/3253 -> CodeCov outage
- https://circleci.com/gh/dlang/phobos/3206 -> DUB registry outage
- https://circleci.com/gh/dlang/phobos/3067 -> our fault (old, unrebased PR)

> takes ages to load logs.

That might even be an temporary error on the CircleCi side - I have never experienced this (except when being on my phone).


@CyberShadow @MartinNowak can we require CircleCi to pass for the `stable` branch as well?

**Comment by CyberShadow** [comment]
> @CyberShadow @MartinNowak can we require CircleCi to pass for the stable branch as well?

Sounds good to me but it's ultimately up to Martin.

> takes ages to load logs.

The UI is clunky and it does take a bunch of scrolling and several clicks to open the relevant section for no apparent reason.

**Comment by MartinNowak** [comment]
I'd rather not do that. We want people to be able to merge even with small coverage decreases. Might as well adjust the limits, but I'd rather leave that to common sense.
What needs to be fixed is https://github.com/dlang-bots/dlang-bot/issues/69 instead.

**Comment by wilzbach** [comment]
> I'd rather not do that. We want people to be able to merge even with small coverage decreases. Might as well adjust the limits, but I'd rather leave that to common sense.

How is this related? CircleCi is about the linting, public tests etc. - it doesn't fail if the coverage decreases. That's CodeCov to which CircleCi sends the coverage files.

**Comment by MartinNowak** [comment]
> How is this related? CircleCi is about the linting, public tests etc. - it doesn't fail if the coverage decreases. That's CodeCov to which CircleCi sends the coverage files.

I see, only meant the latter, indeed makes sense for Linting. Any plans to work on https://github.com/dlang-bots/dlang-bot/issues/69 regardless.

**Comment by wilzbach** [comment]
> indeed makes sense for Linting. 

Enabled then :)

> Any plans to work on dlang-bots/dlang-bot#69 regardless.

It's not on my main priority list, I might get to it on the next bot hacking session in August, but no promises.

**Pull request merged**
