### PR TITLE
Fix 22838 - BitArray.count reads beyond data

### PR DESCRIPTION
**Pull request by JohanEngelen**
This fixes issue 22838
https://issues.dlang.org/show_bug.cgi?id=22838

All hail AddressSanitizer! ;-)

### CODE REVIEW

**Comment by thewilsonator** [comment]
Please include the test case

**Comment by JohanEngelen** [comment]
> Please include the test case

The test case is already there :) The bug is triggered by a unittest (see bug report). The invalid memory access is of course only found when enabling ASan.

**Comment by CyberShadow** [comment]
The test is already there. The failure is visible only when running with AddressSanitizer, which we don't do as part of our unit tests, so there is nothing to add.

Is it possible to write a unit test which purposefully clobbers respective memory so that the failure is visible outside AddressSanitizer, though?

**Review by thewilsonator — APPROVED** [review]

**Review by CyberShadow — APPROVED** [review]
I think that was the only case where `_ptr[fullWords]` was accessed before checking that `endBits` is non-zero.

**Comment by CyberShadow** [comment]
Reopening the PR with the same branch as another confused the CI I think.

**Comment by JohanEngelen** [comment]
> Is it possible to write a unit test which purposefully clobbers respective memory so that the failure is visible outside AddressSanitizer, though?

No. It is an invalid read, but the calculation of bit count still works, because of the masking with endMask.

**Comment by maxhaton** [comment]
> All hail AddressSanitizer!

I started implementing it in dmd during the Christmas holiday but then I realized it was supposed to be a holiday and stopped.

**Comment by JohanEngelen** [comment]
CI errors are not due to this PR

**Comment by kinke** [comment]
[AFAIK, CI doesn't like direct branches on the upstream repo. That's mainly intended for bigger features targeting `master`, e.g., where druntime and compiler both need to be patched, and where one can use same-named branches for both original repos.]

**Pull request merged**
