### PR TITLE
Merge remote-tracking branch 'upstream/stable' into merge_stable

### PR DESCRIPTION
**Pull request by MartinNowak**
Conflicts:
        std/traits.d

### CODE REVIEW

**Comment by MartinNowak** [comment]
Why is this stuck?

**Comment by schveiguy** [comment]
@MartinNowak Looks fine, what does the "conflicts" comment at the top mean?

**Comment by MartinNowak** [comment]
> @MartinNowak Looks fine, what does the "conflicts" comment at the top mean?

If you merge on the command line, that's the commit message git creates when merge conflicts occur.
In this case I had to resolve a merge conflict in std.traits, where ParameterDefaults was changed in stable #4864 and master #4862.

**Comment by andralex** [comment]
@MartinNowak so what do we do here? Should I just merge?

**Comment by MartinNowak** [comment]
Yes, I'll just merge it.

The resolution of the merge conflict is part of the merge commit (as always), the conflict comment is just a git remark for the history.

**Comment by MartinNowak** [comment]
Auto-merge toggled on

**Pull request merged**
