### PR TITLE
std.getopt: two little features to aid rdmd

### PR DESCRIPTION
**Pull request by ghost**
As outlined in https://github.com/D-Programming-Language/tools/pull/140 which aims to fix https://issues.dlang.org/show_bug.cgi?id=13290:
- `endOfOptionsPred`: stop processing on a predicate (rdmd: stop on source and executable file names)
- `GetoptResult.stoppedAt`: distinguishing unrecognized options from non-options (rdmd: dmd args vs program args)

### CODE REVIEW

**Comment by MartinNowak** [comment]
> handles the argument, of course;
> can signal if the argument is to be removed from the array; and
> can stop argument processing right there.

That sounds almost like a foreach loop, how about this.

```d
foreach (arg, ref keep; getopt(args, "v|verbose", &verbose))
{
    if (arg == "--") break;
    keep = false;
}
```

**Comment by MartinNowak** [comment]
Another problem with getopt is that it doesn't support help text.
Something like this might work.
```d
getopt(args,
    opt("v|verbose", &verbose, "print verbose output")
);
```

Then getopt could be used to generate a help menu.

**Comment by NilsBossung** [comment]
> That sounds almost like a foreach loop, how about this.

I had thought that way too:

[NilsBossung commented on 3 Sep 2014](https://github.com/D-Programming-Language/tools/pull/140#issuecomment-54233299):
> It would be possible to expand on the idea of getOneOpt, separating the option specificiation from the popping, maybe turn it into a range. But it would still be out of line with the rest of getopt which works with callbacks.

**Comment by NilsBossung** [comment]
> Another problem with getopt is that it doesn't support help text.

It does actually.

**Comment by MartinNowak** [comment]
How is that? Looks like you still need to duplicate each option in the usage message by hand.

**Comment by NilsBossung** [comment]
> How is that? Looks like you still need to duplicate each option in the usage message by hand.

```d
import std.getopt;
void main(string[] args)
{
    bool verbose;
    auto r = getopt(args, "v|verbose", "print verbose output", &verbose);
    if(r.helpWanted) defaultGetoptPrinter("foo", r.options);
}
```

Run it with `--help` and it prints:

```
foo
-v --verbose print verbose output
-h    --help This help information.
```

See also: 'Synopsis' of http://dlang.org/phobos-prerelease/std_getopt#.getopt

**Pull request closed without merging**
