### PR TITLE
Fix CommonType template to no longer assume typeof(type) == _error_

### PR DESCRIPTION
**Pull request by UplinkCoder**
This enables us to introduce a type of types in the future

### CODE REVIEW

**Comment by UplinkCoder** [comment]
@andralex you might be interested in this one.

**Comment by UplinkCoder** [comment]
The build seems to fail because of template emission bugs ...

**Comment by thewilsonator** [comment]
A fix should come with a test case, I cannot tell from the context why the clause that follows does not already cover the case added.

**Comment by atilaneves** [comment]
What @thewilsonator said.

**Comment by UplinkCoder** [comment]
There can't be a testcase unless typefunctions are in a preview switch

**Comment by atilaneves** [comment]
Then there's no reason for this to exist right now.

**Comment by UplinkCoder** [comment]
It'd be nicer to fix it for the case before.
Because that makes it more general

**Comment by Geod24** [comment]
> There can't be a testcase unless typefunctions are in a preview switch

Then raise a PR with a functioning preview switch for it.
It's impossible for someone to review a change based on a bug they haven't see, or a feature they don't know about.
On the other hand, it's very easy to envision that things will work one way, and realize at the end that they didn't.

If you raise small and intermediate PRs, that's only useful if they have intrinsic values, or if they implement a small part of a much larger feature that is already visible to the reviewer.

**Pull request closed without merging**
