### PR TITLE
std.socket - tired of heisenbug failures in test suite

### PR DESCRIPTION
**Pull request by WalterBright**

### CODE REVIEW

**Review by CyberShadow — APPROVED** [review]

**Comment by 0xEAB** [comment]
Do we have some way to *log* that reverse DNS lookup wasn’t actually tested?
I feel like we might want to point out to the person running the testsuite that the test had to be skipped unfortunately.

**Comment by CyberShadow** [comment]
There is `softUnittest`, it could be used here.

**Comment by CyberShadow** [comment]
@WalterBright If you have a link to the failure, that would be good to have as a reference for the future.

**Comment by WalterBright** [comment]
like to the failure:

 https://github.com/dlang/dmd/pull/14869#issuecomment-1426954124

**Comment by WalterBright** [comment]
Isn't it ironic that this PR is failing the test suite because of MORE heisenbugs. Sigh. We have a plague of them.

**Comment by ibuclaw** [comment]
I don't see a heisenbug, only a clear change where the segfault started occurring.

https://github.com/dlang/phobos/commits/master

**Review by RazvanN7 — APPROVED** [review]

**Comment by RazvanN7** [comment]
@ibuclaw I find it hard to believe that some tests for BinaryHeap can cause a socket failure ;)

**Comment by ibuclaw** [comment]
???
```
>>> TARGET FAILED: `unit` tests
FAILED targets:
- `unit` tests
make: *** [Makefile:215: run_all_tests] Error 1
make: Leaving directory '/tmp/dmd/compiler/test'

Exit status: 2
```
Failed consistently 4 times on the trot on FreeBSD.

**Comment by CyberShadow** [comment]
This change is fine regardless, I don't think we should be doing network activity in our test suite at the scale we are today.

Maybe what would make a bit more sense is disabling tests like these in CI only, so that they're still ran on local checkouts. Yeah, annoying for the random contributor who gets to deal with the regression, but it still guarantees that it will be caught.

**Comment by RazvanN7** [comment]
> Failed consistently 4 times on the trot on FreeBSD.

Most likely it was because of a rebase failure. The CI is green for some time and the changes were not undo-ed

**Pull request merged**
