### PR TITLE
fix 14478: support non-copyable elements in many range algorithms

### PR DESCRIPTION
**Pull request by WebFreak001**
same as #8714

code not fully covered

### CODE REVIEW

**Comment by RazvanN7** [comment]
@WebFreak001 the testers are failing. Are you willing to push this to the finish line?

**Comment by WebFreak001** [comment]
thanks!

**Comment by RazvanN7** [comment]
Thank you!

**Comment by JohanEngelen** [comment]
This PR results in issues at Weka with `retro` for a struct that has `void opAssign()(auto ref const(typeof(this)) that) const` defined, i.e. a struct that allows `const` assignment. The problem is that *assignment* is allowed, but *move* is not (because it would be a memcpy to const memory).

The cause of the problem: `retro` checks for `hasAssignableElements`, but then does a move rather than an assignment.
https://github.com/dlang/phobos/pull/8721/files#diff-705ed5d9f4ea4f9dadcb07d7116df8dc8397e851639a28538dc0b1d6fa446f56L312-R318

Testcase:
```d
import std.range;

struct Handle { 
    int[5] entries;
    void opAssign()(auto ref const(typeof(this)) that) const { }
}

const(Handle)[100] arr;
auto foo() {
    return arr[0..5].retro;
}
```

the problem is fixed by reverting the lines for retro.

**Comment by jmdavis** [comment]
> This PR results in issues at Weka with `retro` for a struct that has `void opAssign()(auto ref const(typeof(this)) that) const` defined, i.e. a struct that allows `const` assignment. The problem is that _assignment_ is allowed, but _move_ is not (because it would be a memcpy to const memory).

Aside from anything to do with the specific changes here, what does a `const` `opAssign` even do? Conceptually, that seems like it would be illegal, because mutating `const` violates the type system (though without the compiler having extra checks to prevent it, it makes sense that `opAssign` would be treated like any other function in its ability to be `const`). Is this `opAssign` casting away `const` to mutate anyway? Or is it just mutating something outside the object instead of the object itself? Or is not actually doing any kind of assignment?

**Comment by JohanEngelen** [comment]
> Aside from anything to do with the specific changes here, what does a `const` `opAssign` even do? 

It's used to enable assigning to a const(Handle!Block) as if it is a Handle!(const(Block)), and it's indeed writing to something outside the object. There could be better solutions, but "it worked" before...

**Comment by jmdavis** [comment]
> > Aside from anything to do with the specific changes here, what does a `const` `opAssign` even do?
> 
> It's used to enable assigning to a const(Handle!Block) as if it is a Handle!(const(Block)), and it's indeed writing to something outside the object. There could be better solutions, but "it worked" before...

I'm not trying to argue against changing the Phobos code. I'm just trying to understand why anyone would be doing anything with a `const` `opAssign`, since at a glance, it seems like something that's violating the type system.

Regardless of the details of your code, you've clearly shown that `retro`'s template constraint is wrong, because it checks for one operation and then does another instead.

**Comment by WebFreak001** [comment]
The `hasAssignableElements` is used in most of the range operations I touched in this PR, should all of them be changed as well?

**Comment by jmdavis** [comment]
I'll have a PR for this in a bit.

**Comment by jmdavis** [comment]
https://github.com/dlang/phobos/pull/8969

**Comment by JohanEngelen** [comment]
> #8969

thank you!

**Pull request merged**
