### PR TITLE
Let safety of cartesianProduct.Result.popFront be inferred

### PR DESCRIPTION
**Pull request by John-Colvin**
I don't believe https://github.com/dlang/phobos/pull/7440/ was the correct thing to do. @Geod24

### CODE REVIEW

**Comment by PetarKirov** [comment]
Is there a `@safe` unit test to verify that this can be used from `@safe` code? If yes, than I'm fine with merging, though I wonder if you hit some problem in practice which prompted you to propose this change.

**Comment by Geod24** [comment]
Indeed, #7440 was only applying a pre-existing comment, but on second look, that comment was wrong. There are plenty of `@safe unittest`, but no `@system` one. Could you add one @John-Colvin ? From what I see, having a `@system` `popFront` would do it.

**Comment by John-Colvin** [comment]
> Indeed, #7440 was only applying a pre-existing comment, but on second look, that comment was wrong. There are plenty of `@safe unittest`, but no `@system` one. Could you add one @John-Colvin ? From what I see, having a `@system` `popFront` would do it.

done

Also re-targeted to stable because it's a regression

**Comment by Geod24** [comment]
Style check failed:
```

generated/dscanner-9364d6f15f4a610fda49a693dbc18608bfc701bb/dsc --config .dscanner.ini --styleCheck etc std -I.
--
  | std/algorithm/setops.d(557:1)[warn]: A unittest should be annotated with at least @safe or @system
  | std/algorithm/setops.d(566:13)[warn]: Zero-parameter '@property' function should be marked 'const', 'inout', or 'immutable'.
  | std/algorithm/setops.d(571:14)[warn]: Zero-parameter '@property' function should be marked 'const', 'inout', or 'immutable'.


```

**Comment by John-Colvin** [comment]
> Style check failed:
> 
> ```
> 
> generated/dscanner-9364d6f15f4a610fda49a693dbc18608bfc701bb/dsc --config .dscanner.ini --styleCheck etc std -I.
> --
>   | std/algorithm/setops.d(557:1)[warn]: A unittest should be annotated with at least @safe or @system
>   | std/algorithm/setops.d(566:13)[warn]: Zero-parameter '@property' function should be marked 'const', 'inout', or 'immutable'.
>   | std/algorithm/setops.d(571:14)[warn]: Zero-parameter '@property' function should be marked 'const', 'inout', or 'immutable'.
> ```

The first one seems fair enough.

The fact that the second 2 apply to unittests is madness, because it means phobos can't test functions like them!

**Comment by Geod24** [comment]
True, but why would you use `@property` in the first place ?

**Comment by John-Colvin** [comment]
> True, but why would you use `@property` in the first place ?

That's a reasonable question, but even if we assume one shouldn't use it, it's all over people's code for historical reasons or because of misunderstanding. You can't easily remove it because it affects `typeof` and `__traits(compiles, ...)`.

**Comment by Geod24** [comment]
> it's all over people's code

Yeah, maybe we should add a check that no new usage is introduced.

> You can't easily remove it

Is there any code in Phobos that **requires** the usage of `@property` ? I know of the minor difference it introduces, but I'd imagine any reasonable generic utility would not depend on `@property`. Perhaps I am being too hopeful.

**Comment by n8sh** [comment]
>Is there any code in Phobos that **requires** the usage of `@property`? I 

[There was at least some code that didn't work unless `front` was `@property`](https://github.com/dlang/phobos/pull/6987).

**Pull request merged**
