### PR TITLE
Fix 23132 - Avoid ranges copy when compared for equality

### PR DESCRIPTION
**Pull request by tchaloupka**
With this change, at least my code compiles again successfully.

### CODE REVIEW

**Comment by ljmf00** [comment]
> With this change, at least my code compiles again successfully.

Regressions should target `stable` branch. Also, this seems to be rather a regression on the compiler. I can't confirm right now tho.

**Comment by tchaloupka** [comment]
Ok, I've switched it (with a bit of a struggle) to the stable branch.
I also thing that the main problem is somewhere in the compiler, but at least this is some workaround as the bisected PR's refactor makes this come up?

Unfortunately I haven't found any simplified test case for this.

**Comment by pbackus** [comment]
Can probably just be plain `ref`, since it's a `private` function that's only ever called with lvalue arguments.

**Comment by tchaloupka** [comment]
> Can probably just be plain `ref`, since it's a `private` function that's only ever called with lvalue arguments.

Right, changed

**Review by dkorpel — APPROVED** [review]

**Pull request merged**
