### PR TITLE
Use a common Makefile for win{32,64}.mak

### PR DESCRIPTION
**Pull request by wilzbach**
Gets rid off of a huge chunk of redundancy by simply moving common variables to a shared file.

### CODE REVIEW

**Comment by wilzbach** [comment]
I'm a bit worried about auto-tester's patching here:
https://github.com/braddr/at-client/blob/master/src/diff-phobos-win64.diff

**Comment by andralex** [comment]
This is cool, cuts a lot of fat.

**Comment by wilzbach** [comment]
Well, it's blocked on the auto-tester still doing it's magic patching which would have been addressed by https://github.com/braddr/at-client/pull/8 ...

**Comment by wilzbach** [comment]
Doesn't look like this is ever going to pass :/

**Pull request closed without merging**
