### PR TITLE
std.conv.octal: simplify implementation

### PR DESCRIPTION
**Pull request by WalterBright**
A much simpler and more efficient implementation using a recursive function.

### CODE REVIEW

**Comment by dkorpel** [comment]
If this would replace the string overload, it would be simpler. This just adds more lines of code. 

Is it measurably faster?

**Comment by WalterBright** [comment]
> Is it measurably faster?

It replaces something like 10 layers of templates with a trivial function that does the same thing but without the voyage around the horn making/parsing a string.

> This just adds more lines of code.

And removing a dependency and inscrutable layers of bloat.

> If this would replace the string overload, it would be simpler

If you can make the string overload simpler too, I'll approve it.

**Review by thewilsonator — CHANGES_REQUESTED** [review]
Needs unit tests
Also this would appear to be incapable of expressing "large" octals whose decimal representation is larger than `T.max`,  I suspect that is why the original used strings.

**Comment by WalterBright** [comment]
> Needs unit tests

Already has them, as this is a replacement of an existing template that has unit tests.

> Also this would appear to be incapable of expressing "large" octals whose decimal representation is larger than T.max, I suspect that is why the original used strings.

You are correct about the limitation, which is why `octal!123` and `octal!"123"` are different templates before and after this PR. This PR replaces the implementation of `octal!123`.

**Pull request merged**
