### PR TITLE
fix Issue 16383 - 'Algebraic visit does not match const'

### PR DESCRIPTION
**Pull request by Cauterite**

### CODE REVIEW

**Comment by aG0aep6G** [comment]
Change looks like a step in the right direction. The new condition, `is(Params[0] == T)`, is obviously ok. It's not so clear for the existing one, `is(Unqual!(Params[0]) == T)`.

There are some related cases that should probably be made to work:

```d
{
    /* since the same works with Algebraic!Object */
    alias T = Algebraic!(immutable Object);
    T.init.visit!(
        (const Object x) => 0,
        () => 0,
    );
}
{
    /* similarly */
    alias T = Algebraic!(Object, immutable Object);
    T.init.visit!(
        (const Object x) => 0,
        () => 0,
    );
}
{
    /* This one should obviously work, but fails because of Unqual. */
    alias T = Algebraic!(Object, immutable Object);
    T.init.visit!(
        (Object x) => 0,
        (immutable Object x) => 0,
        () => 0,
    );
}
{
    /* Not sure about this one. */
    alias T = Algebraic!(Object, const Object);
    T.init.visit!(
        (Object x) => 0,
        (const Object x) => 0,
        () => 0,
    );
}
```

If you'd like to tackle these too, @Cauterite, that would be great. But they fail already, they wouldn't be introduced by this PR. So we can just file them and leave them for later.

Please add a `unittest` for the fixed issue.

**Comment by andralex** [comment]
Could you please add a unittest that your code makes work?

**Comment by Cauterite** [comment]
I'll consider revisiting this to deal with those other cases, but for now I don't consider it a priority.

**Comment by Cauterite** [comment]
This should be all green by the way; the build failures don't appear to have anything to do with this patch.

**Comment by schveiguy** [comment]
@Cauterite the auto tester looks like it had some recent issues with space. But that seems to have cleared up, and the test in question has been deprecated anyhow.

@aG0aep6G yeah, I think the way this should work is that if any items are *callable* with the stored type, then it should work. If two or more items match, and one is a better match (defined by D overload rules), then the better match should work.

Probably needs a good design examination, I don't think it's a quick fix.

LGTM. I assume that the other comments are approvals sans unit test that is now added?

**Comment by schveiguy** [comment]
Auto-merge toggled on

**Pull request merged**
