### PR TITLE
Remove stream from phobos

### PR DESCRIPTION
**Pull request by burner**
did went through the deprecation cycle and is scheduled to be remove Oct 2016

### CODE REVIEW

**Comment by JackStouffer** [comment]
We still have ten days to go

**Comment by burner** [comment]
I doubt that there will be a 2.072 release in the next 10 days. I can also wait ten days for this to be merged ;-)

**Comment by JackStouffer** [comment]
Martin wants to branch off the 2.072 beta "soon", so here's hoping.

**Comment by burner** [comment]
if 72 gets release in > Oct and this is in, IMO everything is ok. I still doubt that the release of 72 will be in Sep 2016.

**Comment by 9il** [comment]
> if 72 gets release in > Oct and this is in, IMO everything is ok. I still doubt that the release of 72 will be in Sep 2016.

Yep, first we will have beta

**Comment by 9il** [comment]
@burner Looks like you need to fix Win32 file

**Comment by burner** [comment]
@9il I know I don't have a win32 machine to test so the rundtrip takes quite long ;-)

**Comment by andralex** [comment]
@MartinNowak could you please take a look

**Comment by MartinNowak** [comment]
> fixup win64.mak for gone unittest6j.obj

Nice, I just fixed the win64 test, first time using github's new push the PR branches feature.
[Improving collaboration with forks](https://github.com/blog/2247-improving-collaboration-with-forks)

**Comment by MartinNowak** [comment]
Auto-merge toggled on

**Comment by burner** [comment]
thanks

**Pull request merged**
