### PR TITLE
Remove need for Unqual in EndianSwapper

### PR DESCRIPTION
**Pull request by nordlow**

### CODE REVIEW

**Comment by RazvanN7** [comment]
What is the point of this change? `Unqual` is much more expressive than the misleading use of `immutable`.

**Comment by nordlow** [comment]
> What is the point of this change? `Unqual` is much more expressive than the misleading use of `immutable`.

Reducing calls to Unqual is always preferred.

**Comment by nordlow** [comment]
I just realized we can reduce number of template instances by making Unqual a true alias to druntime. For details see https://github.com/dlang/phobos/pull/8227.

**Comment by andralex** [comment]
Yah, the safer and more restrictive immutable is to be preferred, all else being equal. [Principle of Least Effort](https://en.wikipedia.org/wiki/Principle_of_least_effort) and all that.

**Comment by nordlow** [comment]
> Yah, the safer and more restrictive immutable is to be preferred, all else being equal. [Principle of Least Effort](https://en.wikipedia.org/wiki/Principle_of_least_effort) and all that.

Auto-merge, @RazvanN7? :)

**Comment by andralex** [comment]
I see @nordlow simplified the code at best. Thanks!

**Review by andralex — APPROVED** [review]

**Pull request merged**
