### PR TITLE
[style] remove several useless usages of "final"

### PR DESCRIPTION
**Pull request by BBasile**
After this phobos PR and [this Dscanner PR](https://github.com/Hackerpilot/Dscanner/pull/398) the check for final _"could"_ be enabled in dscanner.ini

### CODE REVIEW

**Comment by JackStouffer** [comment]
Auto-merge toggled on

**Comment by JackStouffer** [comment]
According to http://dtest.thecybershadow.net/history/master, my pulling of this somehow broke the doc builder.

**Comment by BBasile** [comment]
But this PR didn't change anything to the doc. The problem must be more subtle.

**Comment by JackStouffer** [comment]
I will create a revert PR to test

**Pull request merged**
