### PR TITLE
Makefiles: Enable -checkaction-context for unittest builds

### PR DESCRIPTION
**Pull request by MoonlightSentinel**
See dlang/druntime#2836.

Blocked by
- [x] dlang/dmd#10535
- [x] dlang/dmd#10550
- [ ] dlang/dmd#10677
- [x] dlang/dmd#12258

### CODE REVIEW

**Comment by MoonlightSentinel** [comment]
Some more DIP1000 issues in `std.range`:

```
void main() @safe
{
    int[5] a = [ 1, 2, 3, 4, 5 ];
    assert(retro(a[]).source is a[]);
}

auto retro(return scope int[] s) @safe
{
    static struct R
    {
        int[] source;
    }
    return R(s);
}
```
```
safe.d(6): Error: address of variable a assigned to __assertOp4 with longer lifetime
```

**Review by PetarKirov — APPROVED** [review]

**Comment by RazvanN7** [comment]
@MoonlightSentinel This seems to pass all the tests now. Does this still depend on https://github.com/dlang/dmd/pull/10677 ?

**Review by RazvanN7 — APPROVED** [review]

**Comment by MoonlightSentinel** [comment]
Not ATM, but there could be new problems if another deprecated type is used in an `assert`.

Also there is still a potential for linker errors due to missing template instances (because Druntime and Phobos are compiled without -checkaction=context). That's why `-checkaction=D` is currently required for the `publictest` target.

**Comment by RazvanN7** [comment]
How should we move forward? Should we merge this or should we first merge dlang/dmd#10677 and compile druntime and dmd with checkaction=context ?

**Comment by MoonlightSentinel** [comment]
I'll close this PR for now, it has caught all remaining issues with `-checkaction=context` in Phobos.

We can gradually enable `-checkaction=context` for druntime/phobos once it get around to finish dlang/dmd#10677.

**Pull request closed without merging**
