### PR TITLE
fix Issue 18023 - remove std.net.isemail until license issues are resolved

### PR DESCRIPTION
**Pull request by WalterBright**
We cannot copy other peoples' code, translate it to D, and change the license on it. This module must be removed ASAP until we get permission from the copyright holder to change the license.

Note that the BSD license is incompatible with Boost because it requires binary attributeion, which is why we do not use it.

https://github.com/dominicsayers/isemail/blob/master/license.md

### CODE REVIEW

**Comment by andralex** [comment]
No need for this. The email from Dominic Sayers on Tue, 22 Feb 2011 12:36:59 +0000 has sent you a zip file containing the code licensed under Boost. That was the basis of the current code.

**Comment by WalterBright** [comment]
Phew! Dodged a bullet there!

**Comment by jmh530** [comment]
It probably couldn't hurt to put a notice to this effect in the relevant files.

**Comment by quickfur** [comment]
Walter already did this: https://github.com/dlang/phobos/pull/5898

**Comment by jmh530** [comment]
@quickfur Ah, good.

**Pull request closed without merging**
