### PR TITLE
Do not call async-signal-safe library function between fork-exec

### PR DESCRIPTION
**Pull request by kubo39**
malloc() is not async-singal-safe function, so stop call between fork-exec.

### CODE REVIEW

**Comment by kubo39** [comment]
hmm,, I'm not sure why removed code needed.., Anyway only glibc malloc can be used here because it releases the locks at pthread_atfork.
I think alloca has same problem. At least, FreeBSD has closefrom(2) system call, this could be useful.

**Comment by CyberShadow** [comment]
> hmm,, I'm not sure why removed code needed..,

A good way to discover the answer to such questions is to use "git blame". It will point you to the relevant commit. If the commit message is not enough, you can find the corresponding pull request, and Bugzilla issue number, which should have an explanation and some discussion.

**Comment by kubo39** [comment]
@CyberShadow I checked https://github.com/dlang/phobos/pull/4114, (is this right?)

If perfromance is required as a requrement, it's ok for me. However I think it's better to supplement with comments.

**Comment by CyberShadow** [comment]
> @CyberShadow I checked #4114, (is this right?)

No; actually, looking at it, this code was there from the very beginning.

The problem is that we need to make sure child processes do not inherit any file descriptors they shouldn't. In theory, all such file descriptors should have been opened with the `CLOEXEC` flag, but in practice I think that's not realistic, as all code (incl. in libraries) must remember to use that flag.

**Comment by kubo39** [comment]
So, I just remove the code using malloc(), still closes all fds except forkPipeOut.

**Comment by CyberShadow** [comment]
Oh, right, the `poll` code removed here was introduced in #4114.

> Anyway only glibc malloc can be used here because it releases the locks at pthread_atfork.

`malloc` here is the libc `malloc`, so, is there still a problem?

**Comment by kubo39** [comment]
The problem is that it depends on implementation. I'm not sure whether jemalloc/tcmalloc/bionic-libc works like glibc does.

**Comment by kubo39** [comment]
circle ci failed, but I suppose it is spurious.

**Comment by wilzbach** [comment]
Yes it's due to the recent dub registry outage :/

**Comment by kubo39** [comment]
rebased.

**Comment by n8sh** [comment]
>glibc malloc can be used here because it releases the locks at pthread_atfork.

Can we use `version (CRuntime_Glibc)`?

**Comment by kubo39** [comment]
I'm not sure that it is safe when LD_PRELOAD is used. If we need a faster implementation, it would be better  to port cpython's `_close_open_fds_safe` function.

**Comment by kubo39** [comment]
I checked cpython's subprocess `_close_open_fds_maybe_unsafe` and commented,

> f these, the one most likely to ever cause a problem is opendir() as it performs an internal
> malloc().  Practically this should not be a problem.  The Java VM makes the
> same calls between fork and exec in its own UNIXProcess_md.c implementation.

I'm not sure still this should not be a problem, but jemalloc seems work well.
So I close this.

**Pull request closed without merging**
