### PR TITLE
Windows is supported; docs said otherwise

### PR DESCRIPTION
**Pull request by Cauterite**

### CODE REVIEW

**Comment by 9il** [comment]
The code is here. But it is specialised system code, so we need resolution from @andralex or review from core contributors.

**Comment by BBasile** [comment]
https://github.com/andralex/phobos/pull/17, there's a note about the DDOC... :innocent:

**Comment by BBasile** [comment]
Also get rid of the low level technical details:

```
MmapAllocator is usually intended for allocating large pools to be managed 
by fine-granular allocators.
Under Posix, the allocator is based on $(D $(LUCKY mmap)), $D( $(LUCKY munmap)). 
Under Windows, $(D $(LUCKY VirtualAlloc)), $(D $(LUCKY VirtualFree)) are used.
```

Finally It may also be worth explaining why these OS functions are used: lazy allocation (actual physical alloc happens on commitment, not limited by the amount of physical memory available, etc).

**Comment by BBasile** [comment]
@klickverbot : you' ve just made an error. The ddoc comment is bad. See my last review comment.

**Pull request merged**
