### PR TITLE
fix Issue 6106 - Keep track of changes during replace function

### PR DESCRIPTION
**Pull request by gizmomogwai**

### CODE REVIEW

**Comment by gizmomogwai** [comment]
> local development environment setup

Thank @ibuclaw, I still try to setup my local dev environment. Working on an M1 Mac does not make it simpler, as most instructions just do not work out of the box (e.g. `dub run digger -- build "master + phobos#8694"` does not work).
I think I will resolve to a linux vm or docker image to get a local build first and then continue to work on this issue.

**Comment by gizmomogwai** [comment]
But the github pipelines are a great help, as they at least point out what all is wrong (e.g. examples and so on) ... there will be more...

**Comment by gizmomogwai** [comment]
Anything else I can do here?

**Review by thewilsonator — APPROVED** [review]

**Comment by gizmomogwai** [comment]
With this merged I think we can close the associated github bootcamp issue:
https://github.com/orgs/dlang/projects/12/views/1?pane=issue&itemId=9602400

**Comment by PetarKirov** [comment]
Thanks for the reminder @gizmomogwai! I just did.

**Pull request merged**
