### PR TITLE
Add @system and @safe to std.path unit tests

### PR DESCRIPTION
**Pull request by atilaneves**

### CODE REVIEW

**Comment by DmitryOlshansky** [comment]
LGTM any idea thy the system tests have to be system?

**Comment by JackStouffer** [comment]
@DmitryOlshansky I think the idea behind it is

1. Contributors know that a template is `@system` without looking at the code
2. `grep`-ability

**Comment by atilaneves** [comment]
At this point I'm not incredibly interested in finding out why, just annotate them so in a later phase we can go through all the `@system` unit tests and figure out why and make phobos `@safe`

**Comment by schveiguy** [comment]
@JackStouffer I think the question was more, why can't those unit tests be marked `@safe`, as they sure don't seem to be violating safety.

@atilaneves I agree, no need to fix the issues in such a PR.

**Comment by schveiguy** [comment]
Auto-merge toggled on

**Pull request merged**
