### PR TITLE
Remove deprecated doFormat

### PR DESCRIPTION
**Pull request by wilzbach**
Apparently we missed the deprecation cleanup on this one.

It's part of undeaD:

https://github.com/dlang/undeaD/blob/master/src/undead/doformat.d

### CODE REVIEW

**Comment by sprinkle131313** [comment]
Looks like a test in DMD still uses doFormat:

https://github.com/dlang/dmd/blob/master/test/runnable/imports/argufile.d#L21

**Comment by wilzbach** [comment]
> Looks like a test in DMD still uses doFormat:

-> https://github.com/dlang/dmd/pull/6346

**Comment by wilzbach** [comment]
> -> dlang/dmd#6346

This is in now - so we can go ahead :)

**Comment by JackStouffer** [comment]
What's up with the CI failure?

**Comment by wilzbach** [comment]
> What's up with the CI failure?

This has to do with the new public unittest tester: to [avoid random failures](https://github.com/dlang/phobos/pull/4943#discussion_r92733728) a specific git version of the tools repo is checked out.
The problem is that we do a `git clone` with `--depth 1` by default and just recently a new commit got into the `tools` repo, s.t. the checked out version isn't fetched anymore due.

-> https://github.com/dlang/phobos/pull/4955

**Comment by wilzbach** [comment]
> What's up with the CI failure?

The CircleCi fix is in & now it's green again :)

**Comment by JackStouffer** [comment]
Auto-merge toggled on

**Pull request merged**
