### PR TITLE
fix, prevent a few traits to hijack the "i" identifier

### PR DESCRIPTION
**Pull request by BBasile**
from IRC, discovered with this paste https://dpaste.dzfl.pl/8d46ad513fbe, by "mitch_"

### CODE REVIEW

**Comment by BBasile** [comment]
No, "i" was just a poorly chosen identifier. I have already encountered the same issue with a custom template. People have to take care to the identifiers they use in things that get mixed or that are templates.

**Comment by BBasile** [comment]
this fix is pragmatic.

**Comment by jmdavis** [comment]
If the name is leaking, it's a compiler bug and needs to be fixed. Picking a different name just changes what conflicts. And while `__i` is less likely to conflict, it's also using double underscores, which as I understand it is supposed to only be used by the compiler, and using it in a variable name is asking for trouble.

**Comment by BBasile** [comment]
In the meantime, waiting for a compiler fix, this workaround is there.

**Comment by aG0aep6G** [comment]
Is there a Bugzilla issue for the compiler bug? Looks nasty.

**Comment by quickfur** [comment]
Wow, this looks really nasty.  I think it needs to be fixed in the compiler. Hacking the identifier to be `__i` is just bandaging over the real problem.  Since Phobos fixes aren't going to be available until the next release anyway, what we need is a high-priority compiler bug to make sure the fix gets in by the next release.

**Pull request closed without merging**
