### PR TITLE
Fixed comparison bug

### PR DESCRIPTION
**Pull request by Vasniktel**
Fixed documentation and comparison operator for better memory utilization

### CODE REVIEW

**Comment by thewilsonator** [comment]
It would be nice to add a changelog entry or bug report for this so that people reading the changelog will find out about it.

**Comment by wilzbach** [comment]
Please don't forget to add a test too.

**Comment by thewilsonator** [comment]
Its an algorithmic performance thing, nit really testable.

**Comment by Vasniktel** [comment]
> It would be nice to add a changelog entry or bug report for this so that people reading the changelog will find out about it.

Added

**Comment by Vasniktel** [comment]
> Please don't forget to add a test too.

I'm not exactly sure what tests you want me to add in particular. All the tests, that had been previously defined, were passed.

This PR just fixes the strategy of memory allocation.
I could have been used any of `<`, `>`, `<=` or `>=` with exactly the same outcome except for the amount of memory being allocated.

Sorry for the inconvenience, this is just my first PR actually :)

**Pull request merged**
