### PR TITLE
Use double and float versions of sin,cos from core.stdc.math instead …

### PR DESCRIPTION
**Pull request by Alexibu**
…af real version.

### CODE REVIEW

**Comment by thewilsonator** [comment]
I totally agree we need to stop using real unless its asked for. 
I _believe_ the idea was to use steal some of the polynomial coefficients from CEPHES.

**Comment by ibuclaw** [comment]
C functions may violate pure.

**Comment by thewilsonator** [comment]
Also 
```
../../phobos/std/math.d(754): Error: `cos` cannot be interpreted at compile time, because it has no available source code
```

**Comment by Alexibu** [comment]
So I guess from the /* intrinsic */ after cos in core.math, that the compiler does something special with it, which magically makes cos pure.
I don't think people that evaluate cos at compile time care about performance. 
I am currently consuming a significant amount of electricity computing the long double version of cos when I have been asking for the float version knowing that it will save time.
I have my own local overloads now that fix the problem for me.

It looks like it could work to use ;
static if (__ctfe)
call the real one that is intrinsic
else
call the faster one.

I'll see if this passes tests, not sure about purity issues I don't use pure.

**Comment by ibuclaw** [comment]
> So I guess from the /* intrinsic */ after cos in core.math, that the compiler does something special with it, which magically makes cos pure.

They are all x87 asm ops.

**Comment by Alexibu** [comment]
OK, so I guess the reason no one has fixed it is because there is no difference in speed in the dmd reference compiler ?
In gdc, it results in calls to   _sinl and _cosl which are long double versions of sin and cos, and take a long time to execute.

**Comment by thewilsonator** [comment]
Also if you are caring about performance you shouldn't be using DMD.
LDC [does this properly](https://github.com/ldc-developers/phobos/blob/ldc/std/math.d#L778) already.

**Comment by ibuclaw** [comment]
> I believe the idea was to use steal some of the polynomial coefficients from CEPHES.

There is a pending refactor to split std math into asm and generic parts, similar to bigint.

There exists no support for IBM reals, which may be a good enough reason to introduce a pureCMath template, like pureMalloc, etc...

These can be discussed in bug reports.

**Comment by thewilsonator** [comment]
I suspect that DConf will be a much more effective medium ;)

**Comment by Alexibu** [comment]
> Also if you are caring about performance you shouldn't be using DMD.
> LDC [does this properly](https://github.com/ldc-developers/phobos/blob/ldc/std/math.d#L778) already.

I am using GDC, did you mean to say I shouldn't be using GDC ?

**Comment by thewilsonator** [comment]
No, GDC has good codegen as well, just don't use DMD ;) 
I'm just saying this problem for LDC is already fixed.

**Comment by Alexibu** [comment]
So the compilers have their own branches of phobos, that aren't being integrated with dlang/phobos ? That sounds a bit unsustainable.

**Comment by thewilsonator** [comment]
Not really, most of it is the same, and the bits that are different don't change too often.

**Comment by Alexibu** [comment]
OK, I can see the gdc phobos version doesn't have a version(GDC) with compiler specific cos functions.

**Comment by Alexibu** [comment]
OK,  that didn't work. 
I think this is a job for experts, not me trying to fix it through a web interface.
Thanks for your help.

**Comment by thewilsonator** [comment]
Hopefully we'll get this fixed at dconf.

**Comment by ibuclaw** [comment]
> OK, I can see the gdc phobos version doesn't have a version(GDC) with compiler specific cos functions.

That's because it isn't strictly required, core.math functions are all recognised intrinsics.  One proposal would be to add float and double overloads to core.math, then std.math becomes just an alias.

**Pull request closed without merging**
