### PR TITLE
add -preview=fieldwise to build

### PR DESCRIPTION
**Pull request by WalterBright**
Upgrade to spec compliant struct compares

### CODE REVIEW

**Comment by WalterBright** [comment]
Blocked by https://github.com/dlang/dmd/pull/9338

**Comment by ZombineDev** [comment]
This change will require upgrading the host compiler version to what would become 2.085.0.

**Comment by wilzbach** [comment]
> This change will require upgrading the host compiler version to what would become 2.085.0.

No, DMD latest is always used to build Phobos and druntime. The host compiler is only necessary for DMD and some build scripts.

**Comment by ZombineDev** [comment]
Never mind, for some reason I read `dlang/dmd`, instead of `dlang/phobos` 😄

**Comment by thewilsonator** [comment]
> Blocked by [dlang/dmd#9338](https://github.com/dlang/dmd/pull/9338)

9338 was merged, but the is still all red, is it still blocked?

**Comment by ZombineDev** [comment]
Rebased

**Comment by thewilsonator** [comment]
Thanks!

**Comment by thewilsonator** [comment]
`dsymbol/src/dsymbol/symbol.d(198): Deprecation: Cannot use `alias this` to partially initialize variable `part` of type `SymbolOwnership`. Use `part.ptr``

**Comment by ZombineDev** [comment]
@thewilsonator that issues comes from here:
https://github.com/dlang/phobos/blob/aef8bc7a28b528066c7c1bd8981ec36305b518a9/posix.mak#L550
In other words, building phobos with this flag causes the flag to be passed to dscanner, which is a tool built by the `style` target for linting D code.
@Basile-z can you look into this?

The other errors seemed to be "statement not reachable" when building `std.variant`.

**Comment by ZombineDev** [comment]
After restarting CircleCI, the Dscanner segfault went away (so as expected it was an intermittent failure). The new error is:
```
std/variant.d(270): Warning: statement is not reachable
```

**Comment by MoonlightSentinel** [comment]
Needs a rebase

**Comment by RazvanN7** [comment]
@WalterBright rebase this and let's see if we can get it in.

**Review by RazvanN7 — APPROVED** [review]

**Pull request merged**
