### PR TITLE
index.d: Use MREF to fix broken DDox links

### PR DESCRIPTION
**Pull request by CyberShadow**
Partial fix for issue 14085.

### CODE REVIEW

**Comment by CyberShadow** [comment]
chmgen does it (and can be run on any platform to do parsing without CHM generation), it's just not integrated into the build system.

**Comment by CyberShadow** [comment]
I'll look into integrating it then

**Comment by wilzbach** [comment]
> CyberShadow/DAutoTest — Build failed

I guess this needs a re-push/base after https://github.com/dlang/dlang.org/pull/1791?

**Comment by CyberShadow** [comment]
> I guess this needs a re-push/base after dlang/dlang.org#1791?

I don't know how other CI systems do it, but DAutoTest first tests commits it never tested before (in reverse chronological order), then it tests commits it tested before but not with that merge target (also in reverse chronological order). Meaning, it should get to this PR very quickly.

**Comment by CyberShadow** [comment]
I guess I should add auto-merge label prioritizing... but it's almost never blocking merges right now anyway, so...

**Comment by wilzbach** [comment]
> I don't know how other CI systems do it, but DAutoTest first tests commits it never tested before (in reverse chronological order), then it tests commits it tested before but not with that merge target (also in reverse chronological order). Meaning, it should get to this PR very quickly.

Ah I didn't know that. I always though it only runs a commit hash once. Nice!

> I guess I should add auto-merge label prioritizing... but it's almost never blocking merges right now anyway, so...

Yeah don't bother yourself - the other CIs are the bottleneck ;-)

**Comment by CyberShadow** [comment]
Oops, this doesn't actually fix anything right now since DDox does not use index.d yet.

Oh well, it's nice to have for when it does get around to that, and switching to MREF is good by itself.

**Pull request merged**
