### PR TITLE
copy() should not leak its source

### PR DESCRIPTION
**Pull request by WalterBright**

### CODE REVIEW

**Comment by WalterBright** [comment]
Blocked by https://github.com/dlang/dmd/pull/8346

**Comment by thewilsonator** [comment]
@WalterBright ping.  please rebase.

**Comment by wilzbach** [comment]
Rebased,

**Comment by LightBender** [comment]
@WalterBright is this still good to go? DIP1000 is such a fraught topic these days.

**Comment by dkorpel** [comment]
Since it's a template, scope should be inferred here, not annotated.

**Pull request closed without merging**
