### PR TITLE
[dmd-cxx] std.range.primitives: Fix static condition for X32 targets

### PR DESCRIPTION
**Pull request by ibuclaw**
Cherry-picked from #7447

### CODE REVIEW

**Comment by ibuclaw** [comment]
> ci/circleci: Build Error — Your tests failed on CircleCI 

Hmm, should fix that... maybe.

**Comment by Geod24** [comment]
```
#!/bin/sh -eo pipefail
# ERROR IN CONFIG FILE:
# [#] required key [jobs] not found
```

Looks like the config here needs an update.

**Comment by Geod24** [comment]
https://github.com/dlang/phobos/pull/7448#issuecomment-614559838

Yes please :)

**Comment by ibuclaw** [comment]
This is in druntime/dmd-cxx.
```
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:18.04
    parallelism: 1
    filters:
      branches:
        ignore: dmd-cxx
    steps:
      - run: echo pass
```

**Pull request merged**
