### PR TITLE
Fix issue 17724 remove conflict between module and function `digest`

### PR DESCRIPTION
**Pull request by schveiguy**

### CODE REVIEW

**Comment by schveiguy** [comment]
For those interested, this isn't targeting stable, because it's a regression in master -- hasn't been released yet.

**Comment by schveiguy** [comment]
ping @wilzbach see incorrect message from dlangbot.

**Comment by wilzbach** [comment]
> ping @wilzbach see incorrect message from dlangbot.

AFAICT it's nearly impossible to detect that the changes are entirely in master, that's why it's only a warning and gentle reminder. Sorry

**Comment by schveiguy** [comment]
> gentle reminder

hehe, lots of exclamations for a "gentle" reminder :)

> Wouldn't these be more succinctly written as

@MetaLang I believe the reason it was done this way is because deprecating an import statement doesn't cause a warning. See https://github.com/dlang/phobos/pull/5013#discussion_r116354661

**Comment by CyberShadow** [comment]
> AFAICT it's nearly impossible to detect that the changes are entirely in master, that's why it's only a warning and gentle reminder. Sorry

We could go with a convention. Bugs titled "[REG master]" (or also "[REG 2.076]" or whatever the next version is, if that wouldn't be too difficult) could be exempted from the warning.

**Pull request merged**
