### PR TITLE
std.simd work in progress, for consideration

### PR DESCRIPTION
**Pull request by TurkeyMan**
I'll leave this here for visibility and commentary.

### CODE REVIEW

**Comment by andralex** [comment]
Noice! ETA for getting this to reviewable state?

**Comment by TurkeyMan** [comment]
I really don't know, there are hurdles...
I don't know what SIMD level was supplied to any compiler on the command line (ie, '-msse2' needs to be reflected in a version or something), DMD doesn't even have such a command line option. The 'target' attribute has problems in GCC.  unittests are being a problem; CTFE doesn't work for loads of maths stuff (for unittesting).

There's a bunch of things, I'll attempt to recall the complete set and perhaps bug them individually or something?

**Comment by bearophile** [comment]
Yes, "bug" them individually in Bugzilla sounds like a good idea.

**Comment by quickfur** [comment]
ping
Any updates on this?  It's been a year...

**Comment by greenify** [comment]
I saw that @lakh has done his [own implementation](https://github.com/Iakh/simd) - maybe he might be able to tell us his reasons.
Btw DAutoTest is failing ...

**Comment by TurkeyMan** [comment]
It's still blocked on the compilers. I still have no way to detect what simd version was supplied to the compiler on the command line on GCC/Clang, and DMD has no such concept. The library can't emit opcodes that violate the simd level request made to the compiler; I need to know the level requested and then I can produce the best code for that level using static if.

@greenify His implementation comes at it from a totally different angle. His focuses on just wrapping up the arch-specific intrinsics rather than making a usable portable library, it's lower level than mine. It has its place, but I obviously don't agree that's the right approach or I would have written mine that way. Anyone who wants to hit the intrinsics directly will do just that. I tried very hard to strike a practical balance between low-level-ness, efficiency, high-level-usability, and portability.
I'm more-or-less happy with my API, but it doesn't work unless the compilers can provide the information I need at compile-time.

**Comment by JackStouffer** [comment]
@TurkeyMan Are there bugs for these problems?

**Comment by WalterBright** [comment]
newsgroup thread:
http://www.digitalmars.com/d/archives/digitalmars/D/Any_usable_SIMD_implementation_282806.html
bugzilla:
https://issues.dlang.org/show_bug.cgi?id=15873

**Comment by WalterBright** [comment]
> DMD has no such concept

See the `D_SIMD` predefined version:
https://dlang.org/spec/version.html

**Comment by wilzbach** [comment]
ping @TurkeyMan - did the SIMD discussion solve your problems?

**Comment by TurkeyMan** [comment]
Not really.
Honestly, I've been trying to identify the key thing that keeps me from pushing this task to my foreground, and possibly the biggest thing that's holding me back here is writing the literally zillions of unit tests required to get this across the line, and spending god-knows-how-many hours scrutinising code generation across the suite of architectures I care about. I just haven't had the time :/ .. The other problems I have discussed are indeed awkward and produce a decent friction to getting back on track, but I could find the motivation to push through them if not for the much larger load of grunt work waiting for me on the other side.
The color module is more critical to my current work, and I think it's significantly smaller in scope too... if I can't even get that in good shape to everyone's satisfaction, this feels even more daunting.

Anyway, I am keen to see this done, but it's a particularly hard module to get right. I think it might be best to approach broken into small sets of related functions?
Or if someone wants to help me with the unittesting the thing, I can then take that time to scrutinise codegen properly for all the target arch's.

**Comment by wilzbach** [comment]
> Anyway, I am keen to see this done, but it's a particularly hard module to get right. I think it might be best to approach broken into small sets of related functions?
Or if someone wants to help me with the unittesting the thing, I can then take that time to scrutinise codegen properly for all the target arch's.

Yep I would recommend to put it on dub, it's more visible to other people, easier to test and submit PRs ;-)

**Comment by TurkeyMan** [comment]
It's been there for like, a long time: https://code.dlang.org/packages/simd

**Comment by JackStouffer** [comment]
Why not make it work on one architecture just to start? Because it's experimental your proposal doesn't have to be feature complete.

**Comment by MetaLang** [comment]
I'm going to close this as it'll have to go through the Phobos review process regardless, and it's on dub so there's not a huge rush to get it into Phobos.

**Comment by bioinfornatics** [comment]
is it a dead feature request with any interest  ?

**Comment by wilzbach** [comment]
> is it a dead feature request with any interest ?

Well, the package is on dub (https://code.dlang.org/packages/simd) and so far there hasn't been much interest in pushing this into phobos.

That being said, this is up for take for anyone who's willing to push for this and open a PR to `std.experimental.simd`. Though I recommend starting a NG discussion before investing serious work.

**Comment by ZombineDev** [comment]
@bioinfornatics I recommend checking out https://github.com/AuburnSounds/intel-intrinsics

**Comment by TurkeyMan** [comment]
I'm still interested in this, but it needs to be done in a more incremental manner. It's impossible to get any major development through here without doing it in small steps.

**Comment by wilzbach** [comment]
FWIW we could start with a very small `std.experimental.simd`  (?) and slowly grow it over time as I agree that anything with a big diff just won't get reviews...

**Pull request closed without merging**
