### PR TITLE
Replace is(Unqual!T == Unqual!U) with is(immutable T == immutable U) for speed & memory usage

### PR DESCRIPTION
**Pull request by n8sh**
As https://github.com/dlang/druntime/pull/3181.

### CODE REVIEW

**Comment by burner** [comment]
whats is the speed and mem diff?

**Comment by edi33416** [comment]
This is a pretty cool trick! Do you have any benchmarks regarding the speed and memory improvements?
I see only one small downside to this: the intent is less clear now.

**Comment by wilzbach** [comment]
> This is a pretty cool trick! Do you have any benchmarks regarding the speed and memory improvements?

See https://github.com/dlang/druntime/pull/3181

**Comment by edi33416** [comment]
> > This is a pretty cool trick! Do you have any benchmarks regarding the speed and memory improvements?
> 
> See [dlang/druntime#3181](https://github.com/dlang/druntime/pull/3181)

I thought that applied only for `core.time`. Nice

**Comment by burner** [comment]
> > This is a pretty cool trick! Do you have any benchmarks regarding the speed and memory improvements?
> 
> See [dlang/druntime#3181](https://github.com/dlang/druntime/pull/3181)

thanks

**Pull request merged**
