### PR TITLE
A simple example added to Date - toString

### PR DESCRIPTION
**Pull request by Wulfklaue**
First attempt at using GIT for updating the documentation. Added a simple example to the date documentation.

### CODE REVIEW

**Comment by Wulfklaue** [comment]
I understand. The code has been updated.  Thanks for the feedback, i will use asserts in the future.

**Comment by ZombineDev** [comment]
@Wulfklaue I think you're confusing ddoc examples with unittests. A ddoc example is what you had initially - a code snippet enclosed between two `---` lines inside a ddoc comment (`/** ...  */`). A ddoc-ed unittest is just a regular unittest put after a function preceded by a potentially empty ddoc comment (`/** ...  */` or `/// ...`). 
So you need to move the unittest after the function.

**Comment by ZombineDev** [comment]
See also: http://dlang.org/spec/unittest.html#documented-unittests

**Comment by Wulfklaue** [comment]
Ok, got it figure out. A few times egg on the face but now i know the logic :)

Unfortunately, also discovered while the code is valid, the doc testing can not run it.

`/d446/f202.d(1): Error: module date is in file 'std/datetime/date.d' which cannot be read
import path[0] = /opt/compilers/dmd2/include
import path[1] = /opt/compilers/dmd2/bin64/../../src/phobos
import path[2] = /opt/compilers/dmd2/bin64/../../src/druntime/import`

Function std.datetime.date.Date.toString
Function std.datetime.date.Date.toSimpleString
Function std.datetime.date.Date.toISOString
...

All suffer from the same issue that the example is valid but the code runner has issues with it.

**Comment by ZombineDev** [comment]
> Unfortunately, also discovered while the code is valid, the doc testing can not run it.

Unfortunately that's a known problem and there's no simple fix. The issue is that online runner uses https://dpaste.dzfl.pl, which in turn uses the last stable dmd release, which means that some examples will become properly runnable only when the next version of dmd is released.

**Comment by wilzbach** [comment]
> Unfortunately that's a known problem and there's no simple fix. The issue is that online runner uses https://dpaste.dzfl.pl, which in turn uses the last stable dmd release, which means that some examples will become properly runnable only when the next version of dmd is released.

Absolutely correct.
@ZombineDev  I pinged @nazriel many times to support dmd-nightly on DPaste - unfortunately without success so far.

**Comment by jmdavis** [comment]
Okay, here's the thing. No on should be relying on the format of the output of `toString` like this. It wouldn't surprise me if someone is, but they shouldn't be. Aside from simply printing out a the `Date` (or `SysTime`, `DateTime`, etc.) as a string to see what it is without caring about it's format, you really should be using one of the specific `to*String` methods - probably `toISOExtString`. If you want to interoperate with anything or serialize the `Date` as a string and then deserialize it later, then a standard format is going to be needed anyway. I made the mistake of putting `toSimpleString` in std.datetime when I created it (it comes from Boost but is completely non-standard), and `toString` currently uses it. I've debated switching it to use `toISOExtString` instead, and I may or may not make that change in the future, but regardless, it would just be bad practice to rely on the output of `toString` over using one of the `to*String` functions that guarantees a specific format. And all of that being the case, I think that it's a mistake to put in the documentation what format `toString` prints out. It prints out the `Date` as a string in whatever format it prints it. If you care about a specific format, then use one of the `to*String` functions.

I should probably just add notes to the `toString` documentation to make it clear that the format is not guaranteed to stay the same and that no one should rely on its format.

**Comment by wilzbach** [comment]
> I think that it's a mistake to put in the documentation what format toString prints out. It prints out the Date as a string in whatever format it prints it. If you care about a specific format, then use one of the to*String functions.
> I should probably just add notes to the toString documentation to make it clear that the format is not guaranteed to stay the same and that no one should rely on its format.

@Wulfklaue maybe you can add the notes to the docs directly in this/your PR?

**Comment by braddr** [comment]
It's wishful thinking to not want dependencies on the format of the output of toString.  The output of that api (really any api) is a defacto contract for the api and the longer the language and libraries live the stronger that dependency grows.  Might as well accept and embrace it since it's the practical reality.

**Comment by wilzbach** [comment]
> The output of that api (really any api) is a defacto contract for the api and the longer the language and libraries live the stronger that dependency grows. Might as well accept and embrace it since it's the practical reality.

Ping @jmdavis for a decision

**Comment by andralex** [comment]
@braddr nailed it. As long as the code passes people will use it and assume the format.

**Comment by andralex** [comment]
@jmdavis is there a dependency on a global locale or something? If so, a comment `// The exact format may depend on the selected locale` should predate the assert.

**Comment by jmdavis** [comment]
> @jmdavis is there a dependency on a global locale or something? If so, a comment // The exact format may depend on the selected locale should predate the assert.

For `Date`? No. There are really two issues here. One, it calls `toSimpleString`, which comes from Boost but probably should have never been in std.datetime, because it's non-standard and causes folks to think that it should do something with locales, because it uses the English abbrevations for the months instead of numbers. Because of that I've considered changed it to calling `toISOExtString` instead but have never made the change and arguably shouldn't for the reasons that Brad brings up. The other issue is that anyone who actually depends on the time format should either be using a standard time format or specifically using a custom format based on what they need (preferably the standard time format), and such usage should be explicit. `toString` is just for converting an object to a string and thus makes sense for debugging or simply printing out the date without caring much about the format, but if you actually need to transmit it to someone or store it in a database or something, then you should be using a function for a specific format appropriate for that. So, I definitely think that the use of `toString` for anything that depends on the format of the string should be strongly discouraged.

**Pull request merged**
