### PR TITLE
[WIP] remove use of useless initializers

### PR DESCRIPTION
**Pull request by BBasile**

### CODE REVIEW

**Comment by quickfur** [comment]
Please don't do this.  Explicitly initializing declarations may be "useless" from the compiler's POV, but they are important for readers of the code to understand intent.  We should not blindlty remove these documentations of intent just for questionable "savings" of not generating extra AST nodes.  I object to this change.

**Comment by BBasile** [comment]
@quickfur, i understand and i have no special interest into seeing the PR merged. The fact is that i used phobos to improve a d-scanner plugin and now I'm happy to see that it covers 99.7 % of the cases and only errors on.. well 0.3...

That being said, there are inconsistencies in the way people init or not. For example:

```diff
     size_t consumed;
-    size_t element = 0;
+    size_t element;
```
`consumed` was not while just beyond, `element` is. Also people should know the language. There's no reason to init _just in case of_. The compiler will not randomly fail to initialize a variable just where you fear that it happens.

**Comment by CyberShadow** [comment]
https://github.com/dlang/phobos/pull/5497#discussion_r123669334

Thanks for the effort, but I'm fairly sure this is not a change we want.

**Comment by quickfur** [comment]
@BBasile  Writing an initializer to a default value is not "in case the compiler will randomly fail to initialize it".  It is a documentation of intent; it's saying "I am explicitly setting this variable to this value, so pay attention, code reader, because this is important".  Declaring a variable without an initializer is saying "x is a variable, it's not important what its initial value is".  Nobody writing D code is "afraid" that the compiler won't initialize the value properly; this is D, not C, after all. It's about conveying intent to whoever reads the code.

**Comment by BBasile** [comment]
It's okay, you don't need to be over-polite because i really don't give a shit about your explanations. I mean i don't care to see this closed.

**Comment by quickfur** [comment]
I was not trying to be polite.  If you don't care about it, then so be it.

**Pull request closed without merging**
