### PR TITLE
Fix Issue 19444: hasRawAliasing loops on class with static array

### PR DESCRIPTION
**Pull request by radcapricorn**

### CODE REVIEW

**Comment by thewilsonator** [comment]
Please target stable.

**Comment by radcapricorn** [comment]
Does it not auto-close the bugzilla when targeting stable, or just needs some time?

**Comment by thewilsonator** [comment]
No, only when it is merged back into master.

**Comment by wilzbach** [comment]
Yup, someone needs to run [`merge_stable`](https://github.com/wilzbach/git-tools/blob/master/merge_stable) or we finally add this to dlang-bot, s.t. it's done automatically.

**Comment by wilzbach** [comment]
Though thinking about this, we should probably change the Bugzilla branch to `stable` as that's the release branch.

**Pull request merged**
