### PR TITLE
Fix Issue 22511 - Add explicit copy ctor for Nullable

### PR DESCRIPTION
**Pull request by omerfirmak**

### CODE REVIEW

**Comment by radcapricorn** [comment]
Could do with testing that copy ctor for payload is actually getting called.

**Comment by omerfirmak** [comment]
> 
> 
> Could do with testing that copy ctor for payload is actually getting called.

Done

**Comment by RazvanN7** [comment]
I am trying to fix the fundamental issue. Maybe this will not be necessary once https://github.com/dlang/dmd/pull/13306 gets in.

**Comment by omerfirmak** [comment]
> 
> 
> I am trying to fix the fundamental issue. Maybe this will not be necessary once [dlang/dmd#13306](https://github.com/dlang/dmd/pull/13306) gets in.

This is another issue tho, isnt it? https://github.com/dlang/phobos/pull/8315 was the workaround for 22510.

**Comment by RazvanN7** [comment]
Ah scratch that, I didn't read carefully and I thought that this is another workaround for the cpctor issue.

**Review by RazvanN7 — APPROVED** [review]

**Pull request merged**
