### PR TITLE
changelog entry for removed @trusted attributes in etc.c.curl

### PR DESCRIPTION
**Pull request by aG0aep6G**
Follow-up to #4514.

### CODE REVIEW

**Comment by schveiguy** [comment]
meh, I don't know that such an in-depth description is needed. Just the main list item is fine.

**Comment by aG0aep6G** [comment]
> meh, I don't know that such an in-depth description is needed. Just the main list item is fine.

Should at least mention which functions are affected. So, just this directly in the top list, no jump link:

    $(LI Wrong
        $(LINK2 $(ROOT_DIR)spec/function.html#trusted-functions, `@trusted`)
        attributes have been
        removed from  $(MREF etc,c,curl) functions
        $(REF_ALTTEXT `curl_easy_escape`, curl_easy_escape, etc,c,curl),
        $(REF_ALTTEXT `curl_escape`, curl_escape, etc,c,curl),
        $(REF_ALTTEXT `curl_easy_unescape`, curl_easy_unescape, etc,c,curl), and
        $(REF_ALTTEXT `curl_unescape`, curl_unescape, etc,c,curl).)

Better?

**Comment by schveiguy** [comment]
IMO, we just need to identify that some functions were improperly trusted in curl. If someone is affected, they'll see the changelog note. If they aren't affected, there isn't a large chunk of the changelog dedicated to minor details. If you think we need more, @klickverbot, then I'll leave that up to you. Typically this kind of stuff is in a bug report, and the changelog just references.

**Comment by schveiguy** [comment]
> Better?

Yes, looks better to me.

**Comment by aG0aep6G** [comment]
> Yes, looks better to me.

Ok, changed to the shorter version.

**Pull request merged**
