### PR TITLE
Fix #16036: isEmail returns invalid for any email with EmailStatusCod…

### PR DESCRIPTION
**Pull request by jacob-carlborg**
…e.none

### CODE REVIEW

**Comment by CyberShadow** [comment]
Thanks for the speedy fix!

Perhaps the unit test should also test invalid emails?

**Comment by jacob-carlborg** [comment]
> Perhaps the unit test should also test invalid emails?

You mean when the error level is `EmailStatusCode.none`?

**Comment by CyberShadow** [comment]
> You mean when the error level is `EmailStatusCode.none`?

Um, yeah. (...?)

**Comment by jacob-carlborg** [comment]
Done. Actually found a bug 😃.

**Comment by jacob-carlborg** [comment]
I think that the `errorLevel` parameter should be removed. I believe the reason why the `errorLevel` parameter was there in the original PHP implementation was to be able to either return a bool or an int. Depending on if you need finer grained control or just a bool indicating if the address is valid or not. 

In the D implementation we're returning a struct containing both a bool and the status code. If you only care if it's valid or not, just look at the bool, otherwise look at the status code.

**Comment by BBasile** [comment]
can you rename the PR to `Fix issue 16036 - ....`, because the dlang-bot has not detected it's in bugzilla and you'll have to close by hand if it's merged.

**Comment by jacob-carlborg** [comment]
Why doesn't dlang-bot use the GitHub convetion to close issues 😠.

**Comment by CyberShadow** [comment]
Thanks!

**Pull request merged**
