### PR TITLE
Move deprecations along.

### PR DESCRIPTION
**Pull request by jmdavis**

### CODE REVIEW

**Comment by 9il** [comment]
`std\process.d(3457): Error: static assert  "Unsupported platform"`

**Comment by jmdavis** [comment]
In theory, that fixes the std.process problem on Windows, but we'll have to see what the auto-tester has to say.

**Comment by jmdavis** [comment]
Okay. That did fix the windows build problem.

**Comment by 9il** [comment]
Auto-merge toggled on

**Pull request merged**
