### PR TITLE
Fix issue 20043: support Tuple.rename on const tuples

### PR DESCRIPTION
**Pull request by FeepingCreature**

### CODE REVIEW

**Comment by thewilsonator** [comment]
Issue number / changelog entry? Also this is pretty trivial you may as well target stable.

**Comment by FeepingCreature** [comment]
Hm, didn't bother. Gonna file one and retrofit/rebase to stable.

**Comment by FeepingCreature** [comment]
Buildkite failure seems unrelated.

**Comment by Basile-z** [comment]
yes, it's related to the fact that some old D1 operators are still present in phobos.

**Pull request merged**
