### PR TITLE
Allow iota implementation of custom types

### PR DESCRIPTION
**Pull request by Shachar**
Change the phobos iota implementation so that it does not conflict with
custom types that have a custom implementation of iota.

### CODE REVIEW

**Comment by Shachar** [comment]
This is a retry of https://github.com/dlang/phobos/pull/4458, with the comments from @schveiguy. I did not introduce tests, as I'm not sure how to do that. I will need to add two modules in order to test it properly, and I'm not sure where is the correct place to add those.

**Comment by schveiguy** [comment]
I don't think tests are necessary here. There's no reason to compile `iota(x)` if `iota(0, x)` doesn't work. But I'm still curious what the lacking functionality is inside the main `iota` that makes it necessary to implement your own. What is `iota` doing that your type can't support?

**Comment by Shachar** [comment]
@schveiguy the main reason, but I completely agree it can be fixed by this very patch, is that `iota` excludes itself from working on anything which isn't an integral type, floating point or pointers. Custom types are specifically excluded, which means they must provide their own.

In theory (not relevant to my case), one might thing of a case where you'd want a type to be iteratable, but not to accept algebra. In such a case, you'd implement `iota`, but not `opBinary!"+"` and not `opUnary!"++"`.

Either way, I don't see any way in which this patch does not make phobos better. It can be argued, and it is worth looking into, that we should also relax the restrictions around `iota(begin, end)`. Since, unlike this patch, that is a breaking change, I'm a bit reluctant to simply introduce it as a PR without first discussing it on the forum.

**Comment by Shachar** [comment]
I looked again at our type and at the existing overloads of iota, and it seems the reason it does not use the default iota is because we failed to define opUnary!"++". Knowing the type's semantics, I believe this is a simple oversight. With my patch, this type should be able to use the standard iota.

**Comment by atilaneves** [comment]
I'd add a unit test using iota with such a custom type

**Comment by ZombineDev** [comment]
Related bug report:
https://issues.dlang.org/show_bug.cgi?id=10762

**Comment by schveiguy** [comment]
@Shachar Thanks for clarifying. I think it still feels correct for `iota` wrapper to be deselected if main `iota` cannot compile. So I still want to pull this.

@atilaneves the problem is, how do you check that the first version of iota doesn't get considered when iota doesn't compile? I don't think there's a way to verify the error message. Besides, this fix is so obvious and simple, we don't generally do exhaustive tests of template constraints normally.

@ZombineDev That's unrelated to this -- `iota(someDate)` doesn't make any sense because there is no expected 0 or obvious increment defined.

**Comment by schveiguy** [comment]
> the reason it does not use the default iota is because we failed to define opUnary!"++".

A good enhancement for iota would be to just do `x += E(1)` when `++` isn't defined but `+=` is.

**Comment by atilaneves** [comment]
@schveiguy You verify it by writing the test first and making sure it fails. Then introduce the change and it's green. Essentially, verifying which code path was taken isn't interesting; verifying that things work is. Tests aren't just for verification, their purpose is also to prevent regressions. If there's no test and somebody deletes that block of code, since nothing fails they could assume that the block was useless.

**Comment by Shachar** [comment]
@schveiguy Just to clarify. I need this patch in regardless of my most recent revelation. Without the change of `E begin = 0;` to `E begin = E(0);` nothing would work for my type.

As for the tests, I'm attaching the files I used to test this with. I do not see how you can run these tests in any meaningful way without using two extra modules dedicated to this. I don't know where would be a good place to place those files, nor how to construct the test in a way that will not interfere. I tend to think they are more trouble than they're worth, but I'm open to any reasonable consensus.

[ut.zip](https://github.com/dlang/phobos/files/332442/ut.zip)

**Comment by schveiguy** [comment]
I don't think it's worth adding two modules to test this.

**Comment by ZombineDev** [comment]
@schveiguy I didn't say that it was the same issue, just that it was related.

I'm not sure why you're bringing `iota(someDate)` up, but now that I think about it, it seems totally reasonable to expect that it would be equivalent to `iota(Date.init, someDate, dur!"days"(1))` (e.g. a calendar app that allows the user to go back to first day representable by the `Date` type).
If I understand you correctly, the issue you take with the unary case is that the start and step are ambiguous/undefined. What I think most people would find intuitive is that in general iota!T would generate elements stsrting from the first value representable by T to the last one and using the reasonably smallest step possible: `iota(T.min, T.max, T.epsilon)`, considering that epsilon is 1 for integers, 1 day for `Date` and e.g. 100ns for `MonoTime` (== MonoTime(1)). Providing `T.min` (or a usable `T.init`) and `T.max` when making a user type seems more generally useful than writing a specialization of iota for them. As for epsilon, iota should be able to guess it either by using `++` or by `+= E(1)`

**Comment by ZombineDev** [comment]
@Shachar is there a reason why you prefer `E(0)` over `E.init` or `E.min`? I think that implementing `iota` in terms of them is more general.;

**Comment by aG0aep6G** [comment]
> @Shachar is there a reason why you prefer E(0) over E.init or E.min? I think that implementing iota in terms of them is more general.

`E.min` would be surprising, I think. `int.min` is a negative number. `float.min` doesn't exist.

`E.init` is ok for integer types, but it's NaN for floating point types. Now, we could say that generally it's `E.init`, but for floating point types it's 0. But I think that just shows that we really want zero.

`Duration` has a [`zero`](https://dlang.org/phobos/core_time.html#.Duration.zero) property. `E.zero` could be another option for custom types. Would be a bit more specific than `E(0)`.

**Comment by Shachar** [comment]
@ZombineDev: Everything @aG0aep6G has said, plus one more which, I think, is the most important one. This discussion is unrelated to this PR.

This PR was meant to solve a specific problem with `iota`, as implemented, preventing custom implementations. As such, if the code says `E begin = 0;`, the only thing it **can** change to is `E begin = E(0);`.

Maybe it should be something else. With this PR merged, it can be, if that's what makes most sense for your type. Either way, this should be discussed in that context, not in this one.

**Comment by schveiguy** [comment]
@ZombineDev I bring up `iota(someDate)` because this PR is about making it so `iota(x)` compiles, and has nothing to do with the full `iota` call (which that issue is talking about).

**Comment by schveiguy** [comment]
Using `E(0)` is as correct as we can make it -- it handles all the builtin types, and allows custom types to define a default "zero" constructor. If one needs to get more specific, use the full `iota` call.

**Comment by Shachar** [comment]
So.... would someone please accept it?

**Comment by quickfur** [comment]
This needs a unittest to prevent regressions. Maybe something like:
````
unittest
{
    struct MyType
    {
        int impl;
        this(int value) { impl = value + 100; }
    }
    MyType x;
    auto r = iota(x);
    assert(r.front == MyType(100));
}
````

LGTM once a test is added.

**Comment by schveiguy** [comment]
@quickfur that doesn't help (note that your example doesn't work anyway, but I see what you meant). The reason to do this is when the main `iota` function doesn't work a your custom type. So you have to implement your own `iota` function for that type. However, the `iota(MyType)` call *did* get selected, so you couldn't override that.

In order to properly test this, you need another module that defines the custom type, and a third module that defines the custom iota (because a local iota would override the std.range one). I don't think it's worth it, when the result of the new code is very obvious. We don't generally test that constraints are valid in unit tests, we just care that things compile or not. Here, it's nuanced -- checking for failure to compile needs to fail in a certain way.

**Comment by quickfur** [comment]
I see. So can we merge this then? It's a small change (albeit with possibly large consequences).

**Comment by schveiguy** [comment]
Auto-merge toggled on

**Comment by schveiguy** [comment]
@quickfur I'm fine with merging it, I just wanted another thumbs up.

> albeit with possibly large consequences

I don't see what these would be...

**Comment by quickfur** [comment]
Well, maybe "large" is an overstatement. Let's merge and see. The revert button is always there if unexpected breakage occurs. :-)

**Pull request merged**
