### PR TITLE
std.math: Implement floor for ibmExtended reals.

### PR DESCRIPTION
**Pull request by ibuclaw**
This is just a slight extension of #5820.  Tested against PPC64/LE.

https://github.com/dlang/phobos/pull/5822/files?w=1

### CODE REVIEW

**Comment by quickfur** [comment]
ping reviewers: this PR has been rotting here for far too long. We need someone familiar with numerics to take a look!

**Comment by quickfur** [comment]
ping @klickverbot

**Comment by ibuclaw** [comment]
@redstar - Oh, and this you may be interested in also.

**Comment by ZombineDev** [comment]
Needs a rebase after https://github.com/dlang/phobos/pull/5823 is merged.

**Comment by JackStouffer** [comment]
Merging based on qualified review

**Comment by n8sh** [comment]
@wilzbach The reason this wasn't merged three days ago isn't due to anyone's objection, but because PR https://github.com/dlang/phobos/pull/5820 also by @ibuclaw was auto-merged first and it conflicts with this PR. As soon as the conflicts are resolved this PR can be merged.

**Comment by wilzbach** [comment]
Oh I was just marking the PR, s.t. I didn't forget to rebase it later (done that now).
BTW this helps when re-reviewing:

https://github.com/dlang/phobos/pull/5822/files?w=1

**Comment by ibuclaw** [comment]
@wilzbach didn't quite rebase it correctly, now I'm back I've fixed that. ;-)

**Pull request merged**
