### PR TITLE
Allmanify Phobos and add CI check

### PR DESCRIPTION
**Pull request by wilzbach**
again with the power of regular expressions :)

```
# find common cases
sed -E "s/^(\s*)((if|static if|for|foreach|foreach_reverse|while|unittest|switch|else).*)\s*\{$/\1\2\n\1{/" -i **/*.d
# catch else-if
sed -E "s/^(\s*)} (else static if| if|else)(.*)\s*\{$/\1}\n\1\2\n\1{/" -i **/*.d
# remove created trailing whitespace
sed -i 's/[ \t]*$//' **/*.d
```

afterwards only a small manual fixup was needed.

edit:
1) In case you aren't that familar with regular expressions - the grep just check when there is a `{` at the end of the line, so `while (true) { }` is still valid
2) this PR doesn't check for the all-man style in functions, that will be a follow-up once Dscanner has this functionality.

### CODE REVIEW

**Comment by ZombineDev** [comment]
Nice work! All LGTM, except for a couple template constraints in the second commit.
(We should add a rule for that to the Phobos style guide.)

**Comment by DmitryOlshansky** [comment]
> again with the power of regular expressions :)

Cool ;)

LGTM

**Comment by atilaneves** [comment]
LGTM

**Comment by DmitryOlshansky** [comment]
Auto-merge toggled on

**Comment by andralex** [comment]
Nice! (IIRC these aren't manly braces, Allman is an actual person.) Is this style going to be automatically enforced going forward?

**Comment by wilzbach** [comment]
> Is this style going to be automatically enforced going forward?

Yes this was the entire point. Currently only with non-D grep, but in the future Dscanner will support this too ;-)

**Pull request merged**
