### PR TITLE
Changelog entry to zlib update.

### PR DESCRIPTION
**Pull request by ibara**

### CODE REVIEW

**Comment by ibuclaw** [comment]
You should target stable now.

**Comment by dkorpel** [comment]
It also needs a description

> Changelog entries should consist of one title line, a blank separator line, and a description.

**Comment by ibara** [comment]
> You should target stable now.

Will it get moved over for 2.100.0?

**Comment by ibuclaw** [comment]
> > You should target stable now.
> 
> Will it get moved over for 2.100.0?

2.100 has already been tagged, master won't be merged into stable for another two months.

**Comment by RazvanN7** [comment]
ping @ibara

**Comment by ibara** [comment]
> ping @ibara 

Sorry. Just been busy with end of semester things.

Will try to get on it today.

**Pull request closed without merging**
