### PR TITLE
Rewrite std.meta.Stride using AliasAssign

### PR DESCRIPTION
**Pull request by WalterBright**
Also added shortcut when stepSize is 1.

### CODE REVIEW

**Comment by WalterBright** [comment]
@Razvan7 the failures are the same as the ones for https://github.com/dlang/phobos/pull/7756

Was something pulled that broke the Phobos tests?

**Comment by Geod24** [comment]
> Was something pulled that broke the Phobos tests?

Master was green 4 hours ago, so I doubt so: https://github.com/dlang/phobos/commits/master

**Comment by pbackus** [comment]
I saw similar failures recently in #7702. They went away after a rebase.

**Comment by RazvanN7** [comment]
@WalterBright Please rebase.

**Comment by RazvanN7** [comment]
ping @WalterBright . Where are we with this?

**Comment by RazvanN7** [comment]
Closing in favor of #8047 as it produces the same change but in less lines of code.

**Pull request closed without merging**
