### PR TITLE
SortedRange: add example for search by key

### PR DESCRIPTION
**Pull request by Panke**

### CODE REVIEW

**Comment by thewilsonator** [comment]
```
std/range/package.d(10656): Error: function `std.range.SortedRange!(S[], byI, SortedRangeOptions.assumeSorted).SortedRange.geq!(S, int).geq` cannot get frame pointer to `std.range.__unittest_L11160_C7.byI!(S, int).byI`
```
Needs to be static?
Also 
```
grep -nr 'import std.algorithm : ' $(find etc std -name '*.d') ; test $? -eq 1
--
  | std/range/package.d:11162:    import std.algorithm : equal;
```
Maybe try `import std.algorithm.comparison : equal;`?

**Comment by Panke** [comment]
> ```
> std/range/package.d(10656): Error: function `std.range.SortedRange!(S[], byI, SortedRangeOptions.assumeSorted).SortedRange.geq!(S, int).geq` cannot get frame pointer to `std.range.__unittest_L11160_C7.byI!(S, int).byI`
> ```
> 
> Needs to be static?
> Also
> 
> ```
> grep -nr 'import std.algorithm : ' $(find etc std -name '*.d') ; test $? -eq 1
> --
>   | std/range/package.d:11162:    import std.algorithm : equal;
> ```
> 
> Maybe try `import std.algorithm.comparison : equal;`?

Thanks for the review. I'll come back to this around christmas, but I have to set up a proper phobos development environment first.

**Comment by RazvanN7** [comment]
@Panke What is the status on this?

**Comment by Panke** [comment]
> @Panke What is the status on this?

Just updated the PR. If the docs look good, it should be ready.

**Review by thewilsonator — APPROVED** [review]

**Pull request merged**
