### PR TITLE
adding assert messages to std.datetime.package

### PR DESCRIPTION
**Pull request by burner**

### CODE REVIEW

**Comment by burner** [comment]
thank you

**Comment by burner** [comment]
ldc buildkite failed with: virtual memory exhausted: Cannot allocate memory

**Comment by berni44** [comment]
> ldc buildkite failed with: virtual memory exhausted: Cannot allocate memory

There are a lot of such false positives around currently...

**Comment by burner** [comment]
@berni44 @thewilsonator  thank you

**Pull request merged**
