### PR TITLE
Faster to import std.regex, by lazy eval of wordMatcher

### PR DESCRIPTION
**Pull request by DmitryOlshansky**
After:
▶ time dmd test_case.d
dmd test_case.d  0.24s user 0.03s system 98% cpu 0.269 total

▶ gco master
Switched to branch 'master'

Before:
▶ time dmd test_case.d
dmd test_case.d  1.10s user 0.12s system 99% cpu 1.228 total

### CODE REVIEW

**Comment by quickfur** [comment]
Woohoo!

**Comment by DmitryOlshansky** [comment]
Credits go to @andralex actually

**Comment by CyberShadow** [comment]
Before:

After:


Awesome!

**Comment by quickfur** [comment]
Looks like `std.uni` is the next candidate for improvement. :-P

**Comment by andralex** [comment]
@CyberShadow would be so nice to have that kind of information nicely visible on the website! "The upfront time cost of importing std modules"

**Pull request merged**
