### PR TITLE
fix Issue 17472 - typeof(stdin) is no longer a File

### PR DESCRIPTION
**Pull request by MartinNowak**
Fixup of #5421

### CODE REVIEW

**Comment by MartinNowak** [comment]
Should fix the Jenkins dub project tester.

**Comment by andralex** [comment]
Was just working on a PR like this - including identical unittest :). Thanks!

**Comment by andralex** [comment]
BTW we should at some point consider making makeGlobal `@trusted`. In that case it should return a `shared(File)` and we should support shared methods for it.

**Comment by CyberShadow** [comment]
Thanks Martin, you're a star :)

**Pull request merged**
