### PR TITLE
fix issue 15991 - std.datetime.StopWatch is not @nogc

### PR DESCRIPTION
**Pull request by BBasile**

### CODE REVIEW

**Comment by aG0aep6G** [comment]
Just adding a bunch of `@nogc`s, looks good to me.

**Comment by JackStouffer** [comment]
👍

**Comment by ZombineDev** [comment]
++LGTM

**Comment by BBasile** [comment]
By the way...I pity the guy who'll have the bad idea to take "nogc" as nickname on GH.

**Comment by Hackerpilot** [comment]
Auto-merge toggled on

**Pull request merged**
