### PR TITLE
Update a missed dirEntries overload (fixup for #5569)

### PR DESCRIPTION
**Pull request by CyberShadow**
Apologies, I missed an overload in #5569.

### CODE REVIEW

**Comment by wilzbach** [comment]
> Apologies, I missed an overload in #5569.

This sound like an excellent opportunity to combine the docs from both overloads and use `/// DITTO` ;-)

**Comment by CyberShadow** [comment]
Good idea, done

**Comment by wilzbach** [comment]
Btw as mentioned on #5569, Ddox needs the full reference.
So how about directly fixing it here?

```diff
diff --git a/std/file.d b/std/file.d
index 7a6edb481..259dc0dc3 100644
--- a/std/file.d
+++ b/std/file.d
@@ -3944,9 +3944,9 @@ public:
                   std,_path).
 
         mode = Whether the directory's sub-directories should be
-               iterated in depth-first port-order ($(LREF depth)),
-               depth-first pre-order ($(LREF breadth)), or not at all
-               ($(LREF shallow)).
+               iterated in depth-first port-order ($(LREF SpanMode.depth)),
+               depth-first pre-order ($(LREF SpanMode.breadth)), or not at all
+               ($(LREF SpanMode.shallow)).
 
         followSymlink = Whether symbolic links which point to directories
                          should be treated as directories and their contents
```

(I wasn't sure whether you agree, hence only as patch)

**Comment by wilzbach** [comment]
> Btw as mentioned on #5569, Ddox needs the full reference.
> So how about directly fixing it here?

OTOH this is a bit more verbose, but as this is also required by the user, maybe even an improvement:

image

**Comment by CyberShadow** [comment]
> (I wasn't sure whether you agree, hence only as patch)

It's not about agreement, it's that your patch doesn't work - it will generate broken links (at least in DDoc).

**Comment by wilzbach** [comment]
> It's not about agreement, it's that your patch doesn't work - it will generate broken links (at least in DDoc).

Oh I didn't think about this, but this seems like a general problem, see e.g. http://dlang.org/phobos-prerelease/std_regex.html#regex (LREF doesn't work here as well, and the link is just silently "broken".

**Pull request merged**
