### PR TITLE
[HOTFIX] Fix Travis CI

### PR DESCRIPTION
**Pull request by JackStouffer**
Ping @schveiguy @klickverbot

### CODE REVIEW

**Comment by JackStouffer** [comment]
ping @Hackerpilot @burner 

Let's get this pulled quickly so more problems don't sneak in other PRs

**Comment by schveiguy** [comment]
Auto-merge toggled on

**Comment by schveiguy** [comment]
I still don't know why we can't do what was there. Why is importing another module forbidden? It does not override any symbols.

**Comment by schveiguy** [comment]
Don't know. It was green when it was merged. I wonder if the tester is flawed

**Comment by JackStouffer** [comment]
The auto tester is not tied to Travis. IIRC @wilzbach or @braddr is working on it.

**Pull request merged**
