### PR TITLE
Allow iota implementation of custom types

### PR DESCRIPTION
**Pull request by Shachar**
Change the phobos iota implementation so that it does not prevent custom
types with custom implementation of iota.

### CODE REVIEW

**Comment by Shachar** [comment]
Explanation:
In general, my case would be solved by simply changing:
E start = 0;
to
E start = E(0);

The problem is that this doesn't work. My version of iota(MyType start, MyType end) isn't reachable from std.range. As such, the above does not compile. The only thing I *can* do is move the phobos implementation out of the way, so that it does not prevent me from defining my own, which is what I did in this patch.

**Comment by schveiguy** [comment]
Hm... could we make the assumption that `E.init` is equivalent to 0? Does that work for your use case? You would need a specialization for floating point, since `E.init` is `nan` (could just be a static if inside the `iota` call).

Note: I'm surprised you can call other items from E, but not the ctor... That seems buggy to me.

**Comment by schveiguy** [comment]
Can I ask one favor: can you change the call to the other iota to match your if constraint? When I first saw this, the `E(0)` confused me, because of the difference between the check and the actual call.

Other than that, LGTM.

**Comment by MetaLang** [comment]
This should have at least one test as well.

**Comment by wilzbach** [comment]
> This should have at least one test as well.

@Shachar a good guide to get started is here: http://wiki.dlang.org/Contributing_to_Phobos
Plus we have a more general about D: http://wiki.dlang.org/Starting_as_a_Contributor

Btw I just approved you for the AutoTester, you are ready to rock!

**Comment by Shachar** [comment]
@schveiguy, the "init" does not solve my case, because the problem with my type isn't with E(0). E(0) works just fine for it. The problem is the recursive call to iota(begin, end). Since my (custom) type is neither an integral nor a floating point, none of the other iotas match it. In order for it to work, this iota needs to call an iota defined in another module, one which std.range does not import (obviously). This does not work.

Failing that, I fall back to have this implementation of iota not interfere. This way, I define a (completely identical) iota(end) in my other module, and I can import both my other module and std.range without a problem. Not ideal, but better than the alternatives.

**Comment by Shachar** [comment]
I used the wrong branch to create this PR. I've opened #4459 with the updated PR. Sorry about the noise.

**Pull request closed without merging**
