### PR TITLE
fix issue 20937 - std.range.array of a lengthless range with indirection is not @safe

### PR DESCRIPTION
**Pull request by dukc**
Also replaced `emplaceRef` with `emplace` to remove dependency on DRuntime internals.

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by thewilsonator** [comment]
It seems this fails CI

**Comment by RazvanN7** [comment]
This seems to have uncovered an ICE in the compiler.

**Comment by RazvanN7** [comment]
Does this work as intended if emplaceRef is used?

**Comment by dukc** [comment]
Let's test...

**Comment by dukc** [comment]
Nope, does not. Changing back.

**Comment by dukc** [comment]
Now I'm definitely seeing a failure with `emplaceRef` version. Hopefully this is the last switchback I'll do

**Comment by dukc** [comment]
Ouch, we have a heisenbug indeed. Even though I'm using the latest Linux dmd, compiling the same file with same flags as the autotester, the ICE does not reproduce locally.

**Comment by dukc** [comment]
DMD issue pinned - reported here: https://issues.dlang.org/show_bug.cgi?id=22228

**Comment by BorisCarvajal** [comment]
Sorry, I should've target master in dlang/dmd#13007 . But you know, someone could say regressions go to stable, no exceptions.

I suppose an early merge should be possible. (HELP!)

**Comment by RazvanN7** [comment]
@dukc Please rebase against stable so that we can get this in.

**Comment by dukc** [comment]
> Sorry, I should've target master in [dlang/dmd#13007](https://github.com/dlang/dmd/pull/13007) . But you know, someone could say regressions go to stable, no exceptions.
> 
> I suppose an early merge should be possible. (HELP!)

Since the PR that caused the bug in first place was merged into stable, it was correct thing to do to target stable yourself. It's up to me to rebase in situations like these, or alternatively just wait for the stable merge.

**Comment by dukc** [comment]
CircleCI fails because... DMD fails to build?

**Comment by RazvanN7** [comment]
Are you sure you are using the latest stable branch?

**Comment by dukc** [comment]
I update my local stable, then rebased my local PR branch against that and then force-pushed. And also I changed this PR:s target branch.

My fork repo still compares the PR branch against master though - how do I rebase that?

**Pull request merged**
