### PR TITLE
Fix issue 17667 - regex([r".", r"[\(\{[\]\}\)]"]);

### PR DESCRIPTION
**Pull request by DmitryOlshansky**
Missing check in charset parser + side effect of how multi-pattern regex was implemented.

### CODE REVIEW

**Comment by DmitryOlshansky** [comment]
> Why does all that code appear uncovered?

Well at least one of the ifs I think is uncovered the others dunno.
Will add a couple of tests to cover all.

**Comment by DmitryOlshansky** [comment]
Done. Also fixed a number of unreported issues with multi-pattern regex.

**Comment by andralex** [comment]
@MartinNowak OK to override the failing codecov?

**Comment by DmitryOlshansky** [comment]
Regex unittests historically leave in a separate file, that may have fooled the codecov.

**Comment by MartinNowak** [comment]
> Regex unittests historically leave in a separate file, that may have fooled the codecov.

Yes, see https://github.com/dlang/phobos/pull/5579#issuecomment-313875232.
We'd need to change the single test make target to also compile the separate tests with `-unittest`.

**Pull request merged**
