### PR TITLE
Fix Issue 19838 - RefCounted fails to instantiate due to pureness of …

### PR DESCRIPTION
**Pull request by marcioapm**
…moveEmplace

### CODE REVIEW

**Comment by wilzbach** [comment]
Please add a test case to avoid future regressions.

**Comment by marcioapm** [comment]
I can't find a reduced test case that reproduces the behavior on our codebase.

Somehow it seems that inferring pureness doesn't work in this particular case, which points to a deeper issue.

This PR will alleviate the situation introduced by manually annotating `RefCountedStore.move()` as `pure` in https://github.com/dlang/phobos/commit/c4324f405c6aea75c9c074c42a21b42a2a361d76#diff-4e008aedb3026d4a84f58323e53bf017

**Comment by atilaneves** [comment]
Shouldn't this be a dmd bug?

**Comment by marcioapm** [comment]
Ping! Any comments on this and if this, or a better fix are going to be merged?

**Comment by thewilsonator** [comment]
Please add the test case for the issue.

**Comment by marcioapm** [comment]
I did try to find a reduced test case but wasn't able to. I suppose once the real bug is found and understood better it will be easier.

Despite not being a real fix, it will at least hopefully revert things to how they used to be before the bug was introduced.

This bug is preventing us from upgrading without a big code refactor so we are stuck in 2.083.1

**Comment by thewilsonator** [comment]
OK.

**Comment by thewilsonator** [comment]
Also please target stable.

**Comment by marcioapm** [comment]
Done - Thanks!

**Pull request merged**
