### PR TITLE
fix Issue 14136 - std.uni.utfMatcher breaks @safety

### PR DESCRIPTION
**Pull request by WalterBright**

### CODE REVIEW

**Comment by JackStouffer** [comment]
This looks like a bandaid rather than addressing the issue. If that's what you want to go for, then can you please reword the commit message to say "Partial fix for ...".

**Comment by John-Colvin** [comment]
@trusted on a public range template? Isn't that a terrible idea? If I take an `@system` range and pass it to match, I'll get an `@trusted` result...

**Comment by schveiguy** [comment]
1. This is very dangerous. Any time you mark a function `@trusted` that calls generic code, you are asking for disaster. (ack @John-Colvin as I was writing this :)
2. This needs a unit test regardless.

I think the proper approach is to try a range that is `@safe`, tag the function as `@safe`, see what makes the compiler incorrectly flag the function as `@system`, and escape those pieces as `@trusted`

**Comment by WalterBright** [comment]
> 1.This is very dangerous.

Removing @trusted is not dangerous.

**Comment by John-Colvin** [comment]
haha, I think both me and @schveiguy read the diff the wrong way around!

**Comment by schveiguy** [comment]
> I think both me and @schveiguy read the diff the wrong way around!

Oh right! @John-Colvin indeed we did.

> *No description provided.*

Would help if you added a short explanation next time :)

I think this still should have a unit test. e.g. call with `@safe` range from `@safe` unittest, make sure it works, call with `@system` range from `@safe` unittest, make sure it doesn't. Actually, such a mechanism for testing ranges should really be global, is there one?

**Comment by WalterBright** [comment]
In general, templates should be inferring nothrow, pure, @nogc and @safe rather than having them specified. There are also other templates in that file with incorrect @trusted. Given the heat in the forum yesterday about @safe, there are 49 other issues I am looking at. So if someone wants to take this PR over, I'd appreciate it.

**Comment by DmitryOlshansky** [comment]
I see no harm in removing trusted, so going to merge

**Comment by DmitryOlshansky** [comment]
Auto-merge toggled on

**Comment by WalterBright** [comment]
@DmitryOlshansky since you're the original author of this module, do you want to take charge of removing the @trusted from the templates?

**Comment by DmitryOlshansky** [comment]
@WalterBright absolutely, it may be tricky though.

**Pull request merged**
