### PR TITLE
Fix segregator alignedReallocate and empty

### PR DESCRIPTION
**Pull request by edi33416**
It looks like `alignedReallocate` had some residues, probably from a copy-paste.

Fixed the typos and updated the docs.

@andralex @wilzbach

### CODE REVIEW

**Comment by andralex** [comment]
@edi33416 rebase

**Comment by andralex** [comment]
ping @edi33416

**Comment by edi33416** [comment]
@andralex I've rebased this last week. The style checker segfaults, but I have no ideea why as this wasn't happening before.

**Comment by edi33416** [comment]
Seems to be the same behavior as #5784, but I don't know if they are related. I'll redo a rebase with master later today, as I'm away from my PC right now

**Comment by andralex** [comment]
cc @wilzbach will force pull

**Comment by wilzbach** [comment]
> The style checker segfaults, but I have no ideea why as this wasn't happening before.

Sadly that seems to be appearing quite frequent in the last two weeks. It might have sth. to do with infrastructure changes at CircleCi - I am not sure yet :/

**Pull request merged**
