### PR TITLE
Move allSatisfy, anySatisfy and staticIndexOf to searching category in the quick index table

### PR DESCRIPTION
**Pull request by ZombineDev**
Follow up to #4376

### CODE REVIEW

**Comment by DmitryOlshansky** [comment]
LGTM

**Comment by wilzbach** [comment]
@ZombineDev sorry for the extra work - LGTM.

**Comment by DmitryOlshansky** [comment]
Auto-merge toggled on

**Comment by ZombineDev** [comment]
Thanks!

@wilzbach no worries.

**Pull request merged**
