### PR TITLE
use constructors instead of `move`

### PR DESCRIPTION
**Pull request by aG0aep6G**
This is a fix-up of #6346 and #6935.

As far as I understand, @WalterBright favors this style (cf. #6900, #6903).

Most of these are straight forward, but `chain` and `roundRobin` are still a bit awkward, because they involve tuples. We don't have some kind of `map` for tuples in Phobos, do we?

### CODE REVIEW

**Comment by aG0aep6G** [comment]
> One possibility would be to (re)do this when copy constructors get released

I'm not sure how you'd use copy constructors here. Make every copy save the range? That's fine for new code, but changing the copy behavior of existing types seems like asking for trouble.

**Comment by aG0aep6G** [comment]
I saw CircleCI and Buildkite failing with errors that seemed unrelated, so I thought I'd give them a kick with a force push. But I guess that was a bad idea. It only managed to remove the auto-merge label. Checks are still failing.

Can someone help me out here?

**Comment by thewilsonator** [comment]
If you haven't rebased this recently please do so.

**Comment by thewilsonator** [comment]
Yep, this was forked off from an old master we've since fixed the issues with circle but you need to have branched off after that to see those fixes on this PR, a rebase will fix your problems.

**Comment by aG0aep6G** [comment]
> Yep, this was forked off from an old master we've since fixed the issues with circle but you need to have branched off after that to see those fixes on this PR, a rebase will fix your problems.

I've rebased, but this PR is against stable, not master. Does that make a difference?

**Comment by thewilsonator** [comment]
Ah, circle will still fail, but is not require to pass, sorry I missed that. I'm more concerned about the build kite failure but that might just be an unfortunate feature of the current stable.

**Comment by thewilsonator** [comment]
In short this needs a manual merge, which I will do tomorrow.

**Pull request merged**
