### PR TITLE
Added `%t` tuple format

### PR DESCRIPTION
**Pull request by Bolpat**
The tuple lacks an easy to use format. The default format `%s` adds the type of the tuple what is useful for debugging but less useful for a simple user interface. The default format for the tuple one would expect is `(%(%s%|, %))`. This PR adds `%t` as an abbreviation for this.

Furthermore, like for arrays, the dash in the format can be used to suppress escaping of strings, except for the `%(…%)` format without separator where all components are listed together.
This also works with `%-t` and even `%-s`.

This does not target *reading* tuples.

### CODE REVIEW

**Comment by quickfur** [comment]
Arguably, it should be `%s` that produces the user-friendly output, and the version that includes the type name should be a different specifier. But then that would break existing code. :-(

**Comment by Bolpat** [comment]
I have never understood who the type info is for. You can usw `typeof(t).stringof` if you need.
Ans ideas how to realize a deprecation process?

**Comment by Bolpat** [comment]
I tried to fix the bad table formatting in the spec of [Tuple.toString](https://dlang.org/library/std/typecons/tuple.to_string.to_string.html), but replacing the problematic comma by `%(COMMA)` as suggested [here](https://wiki.dlang.org/Contributing_to_dlang.org) doesn't change it, see [here](http://dtest.dlang.io/artifact/website-b415173ce423b9b2c8aebcc54335f5d38582bf95-0bbe2ab39a1c5654f1a0d111ca0d739e/web/library-prerelease/std/typecons/tuple.to_string.html).
I don't know how to do this correctly. Running `dmd -c -D typecons.d` doesn't print the table to the HTML file at all. It's not that important, but rather awful and embarrassing.

**Comment by Bolpat** [comment]
Another question is, why codecov/patch is failing. Can someone have a look at it? I don't know what to do exactly. As the name suggests, it tests for coverage with unit tests. My commits shouldn't have hurt coverage. Any new concepts have their unit tests.

**Comment by Bolpat** [comment]
Ping @quickfur.

**Comment by quickfur** [comment]
I think this needs @andralex to review / approve.

**Comment by Bolpat** [comment]
For short, you want it without parentheses around.
Just to be sure, did you mean rather this?
```
struct S { int a; string b; }
writefln("%t", S(1, "x").tupleof);
```
Because a general format specifier is not supported by the current design. Any user-defined type can have its own custom specifiers. So, yes, the thing in my comment is trivial.
About leaving out the parentheses: Its a tuple, and from a user perspective, I'd expect them. It's not a big deal using `(%t)` to get them. Just saying.

**Comment by andralex** [comment]
No parens please because they are trivial to add.

**Comment by quickfur** [comment]
@Bolpat  If I understand it correctly, Andrei is asking for `"%t"` to *automatically* perform a `.tupleof`, i.e.:
````
struct S { int x; string y; }
auto s = S(123, "abc");
writefln("%t", s); // note: NO .tupleof
````
The output should be `123, "abc"`.

The point here is that `%t` should apply to all arguments, not just `Tuple`, in order to maximize its usefulness across all types.

**Comment by quickfur** [comment]
P.S. In order to implement `%t` across the board, you'll of course need to do it in `std.format` rather than in `Tuple.toString`.

**Comment by Bolpat** [comment]
Thanks. General format specifiers are not supported by the current design (let the *underlying type* decide what format specifiers are available; except for builtin types). Implementing `%t` for all types (theoretically) breaks types using `%t` already. More importantly, it changes the design completely and makes it inconsistent.
I'd argue that writing `.tupleof` is not a big deal, too.

**Comment by Bolpat** [comment]
Why does CircleCI fail? The error message looks like there is something internally wrong.

**Comment by andralex** [comment]
@Bolpat there's a bit of confusion. Consider:

```d
struct S { int a; double b; }
void main() {
    auto s = S(1, 2.4);
    import std.stdio;
    writefln("%s", s.tupleof);
}
```
This prints `1`, NOT `1, 2.4`. This is because `.tupleof` expands the structure in such a way that makes the call above equivalent to `writefln("%s", 1, 2.4)`. So expanding `.tupleof` is awkward on the user side (they'd need to provide a format string with as many format specifiers as members).

That's why `%t` is useful as a universal format specifiers. It works for all data and provides useful functionality that is not easy to do on the user side. Best of all, it works nicely with `Tuple` itself. Could you please implement that. Thanks!

**Comment by ZombineDev** [comment]
>  Implementing %t for all types (theoretically) breaks types using %t already.

I think this can be solved by speculatively formatting the argument with `%W` to probe if the type has a custom `%W` handling and if that's the case use the custom behavior, otherwise use the default, where `W` is any format specifier. Of course, this should happen in a try-catch / __traits(compiles, ...) block at compile-time, so there shouldn't be a run-time performance drawback.

**Comment by Bolpat** [comment]
I still don't like the idea to alter the interface. It's already complicated enough.
What about a new library function template which unlike `.tupleof` does not return an `AliasSeq` of the members, but rather a `Tuple` for which the `%t` can be used?
```d
auto toTuple(T)(auto ref T value)
{
    import std.typecons : tuple;
    return tuple(value.tupleof);
}
```
It's easy to use and straightforward.
```d
struct S { int a; double b; }
void main() {
    auto s = S(1, 2.4);
    import std.stdio;
    writefln("%t", s.toTuple); // prints 1, 2.4
}
```
This is completely transparent for the reader. It is easy to guess what `toTuple` does if one doesn't know it. Then (assuming `toTuple` returns a suitable `Tuple`) one can further guess that `%t` is a `Tuple` specific format.

With the current implementation in mind, seeing
```d
struct S { int a; double b; }
S s;
writefln("%t", s);
```
is a big surprise. In converse to the widely known default `%s`, it is not clear what `%t` does.

**Comment by andralex** [comment]
@Bolpat it's a judgment call that could go either way, but can't go both ways. I think wanting to print the decomposed tuple of an object is a good thing to want universally, in fact was looking for a while for more universal formats than %s and %r. A simple and good thing to do is support %t for all types, so let's do that. In addition there are the following opportunities challenges:

* A modifier to transitively decompose the object down to primitive types, i.e. if it has a direct struct member it should print the tuple of that struct
* A mechanism to use a different separator than `", "`, similar to what we do with formatting arrays.

Would be great if you could look into that. Thanks!

**Comment by Bolpat** [comment]
>It's a judgment call that could go either way, but can't go both ways. I think wanting to print the decomposed tuple of an object is a good thing to want universally, in fact was looking for a while for more universal formats than %s and %r. A simple and good thing to do is support %t for all types, so let's do that. In addition there are the following opportunities challenges:
>
> * A modifier to transitively decompose the object down to primitive types, i.e. if it has a direct struct member it should print the tuple of that struct

I suggest to use `%#t` for that.

Remaining question: Say you have
```d
struct T { int a; string b;
struct S { T t; double c; }
S s S(T(1, "2"), 3.2);
writefln("%*t", s);
```
Should the final line print `1, "2", 3.2` or `(1, "2"), 3,2`, i.e. group the decomposed parts together? One could abuse the FormatSpec options for that (or invent new ones).

> * A mechanism to use a different separator than ", ", similar to what we do with formatting arrays.

That's kind of hard because one cannot inject the separator easily. One can (ab)use the range interface which then collides for all ranges. Therefore I'd just argue to use `toTuple` and the `%(%s%|sep%)` format with your desired separator. I expect `%t` to be used mostly for debugging. The need for a custom separator will be very low.

Roadmap:
1. Implement `%#t` for `Tuple` with grouping; only the outermost tuple will not have parentheses. Removing the parentheses later should be easy.
2. Create a default implementation for `%t` via `std.format` if it is not there.

While 1. fits perfectly in this PR, I'd open a separate one for 2.

**Comment by quickfur** [comment]
The separator could be injected via an additional argument. See: PR #5303, the new "," specifier can take an optional parameter to specify a different separator to use. Example:
````
format("%,3d", 1000000); // 1,000,000
format("%,?3d", '_', 1000000); // 1_000_000
````
The `?` flag after the `,` modifier indicates to use the modifier specified in the additional argument instead of the built-in `,`.

**Comment by quickfur** [comment]
About `%#t` vs. `%t`, I think it's better to do both in a single implementation.  I don't see any good reason why `%#t` should be specific to the Phobos `tuple` type only; that's a lot of effort for something with a rather narrow scope.  Your nested struct example could be perfectly solved by supporting `%#t` for all types, not just `Tuple`, and is a good reason why it's better to implement a general solution (i.e., `%t` for all types) instead of a specific solution (`%#t` only for `Tuple`).

In fact, it's rather ugly to have `%#t` be specific to `Tuple` and `%t` work for general types; bugs are bound to arise when you have such conflicting scopes (general/narrow, with implementations in two places).

Since @andralex wants `%t` for general types, why not just implement `%#t` for general types too?

**Comment by quickfur** [comment]
ping @Bolpat @andralex 

How should we proceed with this one? Should we close this, or should we implement `%t` as @andralex suggested?

**Comment by andralex** [comment]
I think we're okay to close this unless someone wants to work on it.

**Comment by quickfur** [comment]
Closing. Please reopen if/when there is interest to go through with it.

**Pull request closed without merging**
