### PR TITLE
Refactor Socket.select documentation, add check for empty socket sets

### PR DESCRIPTION
**Pull request by andrewlalis**
I noticed an issue where I had mistakenly passed an empty set, and two null sets to `Socket.select`. This makes no sense, since there's nothing to wait for, since no update could ever come. On my Windows pipelines, this issue was reported as a socket error originating from the underlying Winsock2 implementation.

I thought it'd make sense to ensure at the library level that `Socket.select` is only called with at least one non-null, non-empty set.

I also refactored the documentation to split the text into related paragraphs, fix small grammatical errors, etc.

Note that there is (as far as I can tell) no unit tests whatsoever for `Socket.select`. I did not add a new unittest in this PR, therefore. It can be added separately.

### CODE REVIEW

**Review by CyberShadow — CHANGES_REQUESTED** [review]
> This makes no sense, since there's nothing to wait for, since no update could ever come.

This is only true if we ignore the `timeout` parameter. See e.g. https://stackoverflow.com/questions/15109527/return-value-of-select-with-empty-sets

> On my Windows pipelines, this issue was reported as a socket error originating from the underlying Winsock2 implementation.

Yes, WinSock2 does not support `select` with all empty sets, but that is a quirk specific to that implementation.



> Note that there is (as far as I can tell) no unit tests whatsoever for `Socket.select`.

See e.g. https://github.com/dlang/phobos/blob/36e977578c1b059c67d8b0129ed1ef17a896f9cd/std/socket.d#L2509

**Comment by andrewlalis** [comment]
> Yes, WinSock2 does not support select with all empty sets, but that is a quirk specific to that implementation.
Changed to limit the assertion to only `version(Windows)` scope instead of for all calls to `Socket.select()`. Also adjusted the documentation to reflect that change.

**Comment by CyberShadow** [comment]
Thanks; question, then why do we need the `assert`, if we're going to get an error from the operating system anyway?

I'm worried that this might be a breaking change and someone somewhere is relying on e.g. `select` throwing = no more active sockets so time to exit the program.

I'd be happy to just merge the doc change.

**Comment by andrewlalis** [comment]
> Thanks; question, then why do we need the assert, if we're going to get an error from the operating system anyway?

My argument for needing an assert is that a D assertion error is familiar to D programmers, and the message provided with the assertion should make it really clear to programmers as to what the error is, while the Windows error message is simply "One or more parameters are invalid.", which isn't as clear in my opinion.

Let me know if that's convinced you; otherwise, I can remove the assertion.

**Comment by andrewlalis** [comment]
@CyberShadow ping in case you forgot

**Comment by andrewlalis** [comment]
Closing this as it's gotten pretty old without any updates.

**Comment by PetarKirov** [comment]
@CyberShadow @schveiguy @jmdavis Can you guys review this PR? In my opinion this change makes sense.

**Comment by CyberShadow** [comment]
Well, as mentioned above, I don't like the `assert`. It is a breaking change and it duplicates the operating system's behavior. The documentation changes are good, IIRC.

**Pull request closed without merging**
