### PR TITLE
map std.traits.mangledName directly to mangleof

### PR DESCRIPTION
**Pull request by rainers**
There seems to be no difference in results anymore. The current implementation relies on a given mangling scheme, but his might change soon with https://github.com/dlang/dmd/pull/5855.

### CODE REVIEW

**Comment by rainers** [comment]
> but shouldn't we at least undocument or even deprecate this function

Fine with me, but these are already too many options ;-)
Without deprecation it will likely linger forever, so I guess a deprecation (until June 2018?) should be better.

**Comment by wilzbach** [comment]
> Without deprecation it will likely linger forever, so I guess a deprecation (until June 2018?) should be better.

Fair point. Looks reasonable to me.
CCing our deprecation tzar @jmdavis

**Comment by jmdavis** [comment]
Yeah, sounds like deprecation would be the right approach. I'd put

    // @@@DEPRECATED_2018-06@@@

right above the comment (so that I can grep for it and move it along to being undocumented when next June rolls around) and something like

    $(RED This is deprecated and will be removed in June 2018. Please use
          the `.mangelof` property instead, as there is no longer a difference
          between it and this trait.)

at the top of the ddoc comment. And then of course, the template itself would be marked with something like

    deprecated("Please use the .mangleof property instead")

**Comment by rainers** [comment]
Thanks, added your messages. Unfortunately, the deprecation message does not seem to appear if attached to an enum value or the enclosing template.

**Comment by ZombineDev** [comment]
Why do we need to deprecate this template? It is useful when used in combination with things like `staticMap`.

**Comment by rainers** [comment]
> Why do we need to deprecate this template? It is useful when used in combination with things like staticMap.

Hmmm, I didn't consider that. If we keep it, the documentation should point to that use case, though. Do you have a nice example to add?

**Comment by rainers** [comment]
@ZombineDev @jmdavis Any updates on this? I can't imagine a sensible use case for this. Especially one that doesn't break if https://github.com/dlang/dmd/pull/5855 is merged.

Using mangleof for type reflection is not recommended anymore in favor of traits, so I think deprecation would still be appropriate.

**Comment by wilzbach** [comment]
> Any updates on this? I can't imagine a sensible use case for this. Especially one that doesn't break if dlang/dmd#5855 is merged.

I am still in favor of going with a deprecation and as we now have two months to next release I would merge the deprecation. Any vetoers? @ZombineDev?

**Comment by ZombineDev** [comment]
I'm fine with the deprecation. The template is trivial to write anyway.

**Comment by jmdavis** [comment]
Well, if someone really is using this in something like `staticMap`, then the deprecation will be annoying, but it is pretty easy to rewrite now. So, I'd probably favor keeping it and not deprecating it in order to avoid forcing folks to change code as well as to avoid forcing folks to write their own replacement when they need it as a template argument, but if you guys really want to deprecate it, I won't argue.

**Comment by rainers** [comment]
Ok, I've removed the deprecation. It didn't show up anyway (problems on enums?), which would cause a sudden breakage for someone not stumbling over the warning in the documentation.

Instead I changed the documentation to pretend it might still be useful and added a very simple documentation unittest calling staticMap.

**Comment by ZombineDev** [comment]
@rainers feel free to auto-merge when ready.

**Pull request merged**
