### PR TITLE
Issue 12866: Allows concatenating of std.container.array with static arrays as T.

### PR DESCRIPTION
**Pull request by dmarquant**

### CODE REVIEW

**Comment by ZombineDev** [comment]
(Closing & reopening in order to restart the dub test on Jenkins, which is known to sporadically fail.)

**Comment by schveiguy** [comment]
Lgtm but can stuff be auto ref? Otherwise you are copying the entire static array to make the call.

**Comment by schveiguy** [comment]
I made the update. @ZombineDev auto merge if you agree.

**Comment by ZombineDev** [comment]
Restarting the CI, due to the usual transient failures.

**Comment by schveiguy** [comment]
> Restarting the CI, due to the usual transient failures.

Ugh. You can restart them by logging into Circle CI (no need to close and reopen).

What are the "usual transient failures"? I can't make heads or tails of the output from "has_public_example". Wondering if this is due to the circleci.sh script not being up to date?

ping @wilzbach can the message be more explanatory? Such as "Sorry, your circleci.sh needs to be updated, please rebase as instructed here: http:// ..."

**Comment by wilzbach** [comment]
> ping @wilzbach can the message be more explanatory? Such as "Sorry, your circleci.sh needs to be updated, please rebase as instructed here: http:// ..."

Hmm, not sure, but we can fix it, s.t. rebasing is not needed: https://github.com/dlang/phobos/pull/5514

**Comment by ZombineDev** [comment]
> Ugh. You can restart them by logging into Circle CI (no need to close and reopen).

@schveiguy Sorry for not being specific, by "CI" I meant all of the checks. While I can now restart CircleCI, that's not the case with Jenkins. I asked Martin about that by email and he replied:

>>On 06/17/2017 05:31 PM, Petar Kirov wrote:
>> What's proper workflow for forcing Jenkins to redo a pipeline run for a
>> particular PR?

> Unfortunately requires quite some config in Jenkins to make this work,
because we'd need accounts.
https://github.com/dlang/ci/issues/36
For the time being pushing a rebuild commit, or changing the PR state do
work.

Hence why I used the close&reopen technique as it's the easiest one (unfortunately at the expense of spamming the PR discussion). 

> What are the "usual transient failures"? I can't make heads or tails of the output from "has_public_example". Wondering if this is due to the circleci.sh script not being up to date?

Yes, one is the "has_public_example", which looks like it's more a fault of CircleCI's infrastructure, than our own. See #5514 for a possible solution. The other one is on Jenkins and is more of a collection of issues with dub and vibe.d. See https://github.com/dlang/ci/pull/47 for some discussion on the dub issue.

I'm hopeful that soon those issues will be resolved (for one Martin said that his going to run a code.dlang.org mirror on his setup, so the tests won't be subject to an external server's availability) and the need to restart the CI process would become much more rare.

**Comment by wilzbach** [comment]
> I'm hopeful that soon those issues will be resolved (for one Martin said that his going to run a code.dlang.org mirror on his setup, so the tests won't be subject to an external server's availability) and the need to restart the CI process would become much more rare.

He already does:
https://github.com/dlang/ci/pull/48
https://code-mirror.dlang.io

Unfortunately, not all issues are resolved with this.

**Comment by ZombineDev** [comment]
It looks like #5514 fixed CircleCI, thanks @wilzbach!

**Pull request merged**
