### PR TITLE
Backport: Fix unaligned access in std.digest.murmurhash

### PR DESCRIPTION
**Pull request by jpf91**
Backport for GDC/`dmd-cxx` from latest stable to fix  https://gcc.gnu.org/bugzilla/show_bug.cgi?id=89177

### CODE REVIEW

**Comment by wilzbach** [comment]
It would be a lot better to use [`merge_stable`](https://github.com/wilzbach/git-tools/blob/master/merge_stable) or similar tools as this will avoid merge conflicts for the release manager.

**Comment by jpf91** [comment]
Is the `dmd-cxx` branch ever merged back into stable/master? I though this is a GDC-only branch?

**Comment by wilzbach** [comment]
Ah sorry. I read "from latest stable" to fast. Nevermind then.

**Comment by jpf91** [comment]
Maybe I should have added a better description ;-)

**Comment by ibuclaw** [comment]
I usually prefix [dmd-cxx] just in case there's any room for doubt

**Pull request merged**
