### PR TITLE
Remove dead code from std.conv

### PR DESCRIPTION
**Pull request by JackStouffer**

### CODE REVIEW

**Comment by gchatelet** [comment]
LGTM

**Comment by wilzbach** [comment]
Isn't it possible to detect such dead pieces automatically? Is there already an existing tool?

**Comment by DmitryOlshansky** [comment]
> Isn't it possible to detect such dead pieces automatically? Is there already an existing tool?

Code coverage ?

**Comment by DmitryOlshansky** [comment]
Auto-merge toggled on

**Pull request merged**
