### PR TITLE
Add scope decorations to std.socket

### PR DESCRIPTION
**Pull request by schveiguy**
This is to fix issues with compiling projects with dip1000.

I'm not sure how to add appropriate tests, since dip1000 is a compiler switch.

### CODE REVIEW

**Comment by schveiguy** [comment]
Is there a way to check if dip1000 compiles phobos? We must be checking this somewhere...

**Comment by adamdruppe** [comment]
Worth noting that this is a breaking change so it will need to be called out in the documentation, but the transition is easy so it is surely worth the minor hassle.

**Comment by iK4tsu** [comment]
>Is there a way to check if dip1000 compiles phobos? 

I think it adds the flag automatically already: https://github.com/dlang/phobos/blob/master/posix.mak#L138

**Comment by schveiguy** [comment]
For reference, I discovered this when trying to build mysql-native with my new safe patch with dip1000 turned on. Adam is right that this is a breaking change. I have it in draft until I can think about how to properly do the deprecation (if it's even possible).

**Comment by iK4tsu** [comment]
Why is it a breaking change? Without dip1000 `scope` does nothing here right?

**Comment by schveiguy** [comment]
Because if you derive from std.socket (e.g. to make a SSL socket), then you have to repeat the scope attributes, or it breaks. So if you haven't already done that, then your code won't compile with this version.

**Comment by adamdruppe** [comment]
On Fri, Apr 22, 2022 at 01:58:45PM -0700, Steven Schveighoffer wrote:
> Because if you derive from Socket (e.g. to make a SSL socket), then you have to repeat the scope attributes, or it breaks. So if you haven't already done that, then your code won't compile with this version.

Worth noting this is quite minor breakage that you can probably just rip
the band-aid off.

**Comment by thewilsonator** [comment]
cc @ikod

**Comment by ikod** [comment]
> cc @ikod

Thanks!

Sorry if this is wrong place to ask. If I understand correctly I only have to change overrided Socket calls and this should work?

```
diff --git a/source/requests/streams.d b/source/requests/streams.d
index b1e54d0..b78e044 100644
--- a/source/requests/streams.d
+++ b/source/requests/streams.d
@@ -898,17 +898,17 @@ else {
             return this;
         }
         @trusted
-        override ptrdiff_t send(const(void)[] buf, SocketFlags flags) scope {
+        override ptrdiff_t send(scope const(void)[] buf, SocketFlags flags) scope {
             return openssl.SSL_write(ssl, buf.ptr, cast(uint) buf.length);
         }
-        override ptrdiff_t send(const(void)[] buf) scope {
+        override ptrdiff_t send(scope const(void)[] buf) scope {
             return send(buf, SocketFlags.NONE);
         }
         @trusted
         override ptrdiff_t receive(void[] buf, SocketFlags flags) scope {
             return openssl.SSL_read(ssl, buf.ptr, cast(int)buf.length);
         }
-        override ptrdiff_t receive(void[] buf) scope {
+        override ptrdiff_t receive(scope void[] buf) scope {
             return receive(buf, SocketFlags.NONE);
         }
         this(AddressFamily af, SocketType type = SocketType.STREAM, SSLOptions opts = SSLOptions()) {
```

**Comment by adamdruppe** [comment]
On Sat, Apr 23, 2022 at 12:36:49AM -0700, ikod wrote:
> Sorry if this is wrong place to ask. If I understand correctly I only have to change overrided Socket calls and this should work?

Yes, and it should compile now, even without the phobos pr, meaning you
can make the change any time without breaking old compiler
compatibility.

I gotta do the same thing to my lib.

**Comment by ikod** [comment]
> On Sat, Apr 23, 2022 at 12:36:49AM -0700, ikod wrote: Sorry if this is wrong place to ask. If I understand correctly I only have to change overrided Socket calls and this should work?
> Yes, and it should compile now, even without the phobos pr, meaning you can make the change any time without breaking old compiler compatibility. I gotta do the same thing to my lib.

fixed in v2.0.5

**Comment by thewilsonator** [comment]
> fixed in v2.0.5

Thanks for the quick response!

**Comment by schveiguy** [comment]
Damn, still broken, I think some functions got missed. @ikod I'll see if I can make a PR.

**Comment by ikod** [comment]
> Damn, still broken, I think some functions got missed. @ikod I'll see if I can make a PR.

sorry! merged, released 2.0.6

**Comment by schveiguy** [comment]
Thanks @ikod for your help! Hopefully all done. I had to force push, as buildkite seemed to be stalled.

**Comment by schveiguy** [comment]
should be green now (dlang-requests now passing). I need either a bug report or a changelog now...

**Review by RazvanN7 — APPROVED** [review]
Looks good! A changelog will suffice.

**Comment by schveiguy** [comment]
Please review changelog entry before merging.

**Review by RazvanN7 — APPROVED** [review]

**Review by CyberShadow — CHANGES_REQUESTED** [review]
Flagging just to make sure we're on the same page, thanks @schveiguy .

We've previously rejected pull requests which cause breakage of this type. In particular `TestSocket` is considered "holy" and may not be changed, as the need of doing so signals that the rest of the changes are likely to be breaking.

 Is there anything special about this case that's different from the previous ones, or is it time to reconsider those decisions too?

**Comment by PetarKirov** [comment]
If making the interface defined by `Socket` more strict is deemed an unacceptable breaking change in general, are there any blockers to defining a new derived class (say `SafeSocket` or `RefinedSocket` (well, not the best name)), that would have a more strict interface (perhaps that class could even be final)?

**Comment by PetarKirov** [comment]
An alternative solution would be to move the implementation to `struct SocketImpl` with as tight attributes as possible and then have the `Socket` class act as a backwards compatibility proxy interface.

**Comment by adamdruppe** [comment]
It depends on what attributes you are doing. Scope is pretty easy - you can always just .dup  it if you need to store it and it is unlikely anyone would; it seems like I've written most the subclasses of Socket in the wild myself..........

On the other hand, something like nogc would be a tougher sell here (though a possibility for socket) since if you have existing code that actually relies on it that's a lot harder to escape; you can't just .dup and get back to work.

**Comment by schveiguy** [comment]
I'm OK with having a "SafeSocket" etc, if that's what needs to happen. But we are still going to run into a brick wall.

Adding scope to `Socket` methods seems like a no-brainer, and I'm not exactly sure why a derivative cannot add these as well. Yes, it's a breaking change, but that train is headed towards existing projects anyway when dip1000 is going to be the default. E.g. I currently have mysql-native marked `@safe`, but it will not build with dip1000 unless `Socket` is marked with scope decorations. No changes are needed in my project, there's nothing unsafe about it, it's just Phobos that has the problem (I'm not deriving any sockets). So it's going to break code one way (adding scope decorations) or another (turning on dip1000 by default).

It might be time to reconsider, if we are serious about making dip1000 the default.

**Comment by schveiguy** [comment]
> We've previously rejected pull requests which cause breakage of this type.

Do you have links to such rejections if you can remember them?

**Comment by CyberShadow** [comment]
> Do you have links to such rejections if you can remember them?

Here's what I found:
- https://github.com/dlang/phobos/pull/4273 (tried to add `@nogc`, was reverted)
- https://github.com/dlang/phobos/pull/5496 (tried to add `in` on the parameters)
- https://github.com/dlang/phobos/pull/6204 (tried to add `scope` on the method)
- https://github.com/dlang/phobos/pull/6730 (tried to add `@nogc`)
- https://github.com/dlang/phobos/pull/7433 (tried to add `@nogc`)
- https://github.com/dlang/phobos/pull/8438 (tries to add `scope` on the parameters - this pull request)

> It might be time to reconsider, if we are serious about making dip1000 the default.

Would it make sense to somehow add these attributes only if `-dip1000` is in effect?

**Comment by schveiguy** [comment]
Thanks.

> Would it make sense to somehow add these attributes only if `-dip1000` is in effect?

Is there a way to do that? That would solve my problem for sure.

**Comment by CyberShadow** [comment]
> Is there a way to do that?

Well, technically, string mixins is a way... Not sure if we have anything better right now.

**Comment by RazvanN7** [comment]
I agree with @schveiguy here. Since dip1000 will become the default we might as well swallow the pill and move on. cc @atilaneves what are your thoughts on this?

**Comment by CyberShadow** [comment]
I think that's the most reasonable way forward as well, we're just delaying the inevitable otherwise.

Though, I've been thinking if it was possible to do so in a way so that such breakage will happen just once. We may be able to isolate it by dividing the use case of `Socket` classes into two categories:

- Code which just uses instances of the `Socket` class as it is declared in `std.socket`, and will want to benefit from future language additions that will further tighten its methods' signatures.
- Code which needs to expand the `Socket` class and is therefore bound to the contracts decided when the `Socket` class was written.

So, maybe something like this would work:
- Introduce `BaseSocket` with the original lax requirements of `Socket`.
- Make `Socket` a final class which has the new strict signatures.
- `BaseSocket` should still have the behavior of `Socket`; I don't think we can do that with inheritance here, so maybe it could forward calls to a private scoped `Socket` instance.

It wouldn't allow interoperability with code which accepts `Socket` types, though. I don't know how much of a concern that is.

Would be nice to get feedback from users of `std.socket` who subclass `Socket`. @ikod, perhaps you could share your thoughts on this?

**Comment by schveiguy** [comment]
I'm thinking of using this kind of template. I can use this to define the methods as needed. What do you think?

```d
template isDip1000Enabled()
{
    void foo(const(char)[] buf) @safe {}    
    void bar()(char[5] x) @safe { foo(x[]); }
    enum isDip1000Enabled = !__traits(compiles, bar!());
}
```

Where would this template go? std.traits? This is really a compiler feature.

**Comment by schveiguy** [comment]
I'm also good not having to check for this specific case, but I'm assuming that other cases will also have similar problems.

**Comment by ikod** [comment]
> Would be nice to get feedback from users of `std.socket` who subclass `Socket`. @ikod, perhaps you could share your thoughts on this?

Hello,
I didn't have any problems, just added `scope` in proper places. As Adam said - it just make sense. I do not expose any socket internals to  API users, so no changes in `requests` API required.

**Comment by schveiguy** [comment]
Is this unittest even being run? I don't see how this passes with dip1000 enabled: https://github.com/dlang/phobos/blob/3443e0080d9617c9282265dfd6a8fd5f0297d462/std/socket.d#L2648-L2649

It's guarded by `debug (std_socket)`, so I'm not sure what that is for.

**Comment by schveiguy** [comment]
OK, I think that test would not pass if compiled with dip1000. I think that's a coincidence, since the debug switch was added 2 years ago (probably long before dip1000 testing was added to phobos).

**Comment by schveiguy** [comment]
OK, so give me a path forward. My current plan was to change the virtual functions to skinny wrappers with the "correct" attributes around the real implementation, based on detection of dip1000. I'd have to do that to the unittest wrapper socket as well.

Is that satisfactory?

**Comment by CyberShadow** [comment]
> OK, I think that test would not pass if compiled with dip1000

Without looking at the specifics, I think the intention of `debug(std_socket)` is to test (our bindings to) network functionality, not things like lifetime or const-correctness. So, it might be a bug (or at least something fixable) in the test, or then again it might be that the test is representative of code using `std.socket`.

Looking at the specifics, it looks a lot like the second case. Sending a single byte is a common pattern to e.g. wake up an event loop, and a static array makes sense for that.

> My current plan was to change the virtual functions to skinny wrappers with the "correct" attributes around the real implementation, based on detection of dip1000. I'd have to do that to the unittest wrapper socket as well.

I can't picture how this would look like and work. Could you make a simple example with one method?

The idea of the `TestSocket` class is that it represents a worst-case scenario of someone subclassing `Socket` in their project. Any changes that need to be done to `TestSocket` would therefore (in this worst-case scenario) have to be done in users' code. I think ideally we would want to look for a solution which doesn't require overly complicated changes on behalf of users.

I can do the same for my proposal in https://github.com/dlang/phobos/pull/8438#issuecomment-1114678551 if you want.

**Comment by CyberShadow** [comment]
I think we should change all `debug(std_socket)` blocks to always compile the code, but never run it unless `debug=std_socket`.

**Review by CyberShadow — CHANGES_REQUESTED** [review]
OK, here it is. (It's forcing me to enter a comment.)

**Comment by schveiguy** [comment]
Wait, I don't think this is going to work. Scope is in the mangling. So if Phobos is compiled with dip1000, but when you compile against it, you have dip1000 off, it won't link.

So that idea is no good... damn.

**Comment by schveiguy** [comment]
> Not sure if this approach will work with all relevant language changes; I think it should at least work with `const`, `@nogc`, and `scope`.

I don't know that `const` or `@nogc` are appropriate for sockets. E.g. a buffered socket derivative might want to use the GC to allocate buffers, and store them in the socket instance.

However `scope` is a declaration that the socket class won't squirrel away a reference to the buffer you hand it, which has always been implied for sockets.

**Comment by CyberShadow** [comment]
> Rereading that comment, I'm not loving this idea. If `Socket` is final, then you can't derive from it, and get all the enforcement of attributes that we would put there. You'd have to derive from BaseSocket, and then add those attributes manually yourself.

Yes. But that simultaneously gives us the freedom to keep tightening the `Socket` interface.

> It also would break any code that accepts a `Socket`, but you want to pass in your special flavor of socket to. All that could would have to change to accepting `BaseSocket`, which is now breaking a lot more code than just socket derivatives.

Yes, I mentioned this as well in my comment above. The benefit is that this breaking change will happen once.

> I don't know that `const` or `@nogc` are appropriate for sockets. E.g. a buffered socket derivative might want to use the GC to allocate buffers, and store them in the socket instance.

This is a good point.

If we don't foresee many other *necessary* changes to `Socket`s interface, then simply changing it does make the most sense.

There is also https://github.com/dlang/phobos/pull/5496, which tried to add `const` to some `Address` parameters, which I think still does make sense.

**Comment by schveiguy** [comment]
> There is also #5496, which tried to add `const` to some `Address` parameters, which I think still does make sense.

It does make sense, and it also doesn't. But not because of Address (all methods have a `const` overload requirement), but because of the pain of using `const` class references in D. Since all Address methods are const, you can assume that Address is essentially a const class.

Overloads based on const are possible, but of course, you'd have to overload both, so it still breaks using that path.

But I'm not sure it's important to do. If not for that single `name` method, then it wouldn't even be a problem to cast away const in order to call the functions. And the amount of code that keeps a const Address is probably near zero.

**Comment by CyberShadow** [comment]
I think it's much more likely that `Address` will be `const` by transitivity (e.g. you have some `struct Context` which you have no business writing to, and you're given a `const` pointer to it, but you can't use `context.address` in the socket code).

**Comment by schveiguy** [comment]
yeah, good point. Perhaps worth doing now, which means we would have to have the current derivers update their types again.

**Comment by atilaneves** [comment]
Good points about breakage and what got rejected earlier, but adding `@nogc` is very different I think since it's not going to be the default, whereas dip1000 is. I'm in favour, especially after @adamdruppe 's investigation into possible breakage.

**Review by CyberShadow — APPROVED** [review]
Right, so I think this is good to go as-is.

**Comment by schveiguy** [comment]
Thanks for the thoughtful discussion. This really opened my eyes as to what is coming when dip1000 becomes the default, we need to tread cautiously!

**Pull request merged**
