### PR TITLE
fix substitute for single subrange subst

### PR DESCRIPTION
**Pull request by John-Colvin**
I've targeted stable because this is a horrible bug

### CODE REVIEW

**Comment by ZombineDev** [comment]
Can you rebase as well:
```
git rebase --onto stable master substitute_fix
```

**Comment by John-Colvin** [comment]
I think I've fixed the rebase issue now?

**Comment by ZombineDev** [comment]
Yep, I think commented too soon ;)

**Comment by dukc** [comment]
[link to issue](https://issues.dlang.org/show_bug.cgi?id=19207)

**Pull request merged**
