### PR TITLE
Remove orphaned std.regex.internal.shiftor

### PR DESCRIPTION
**Pull request by kinke**
I don't know why this seems to work for DMD. LDC failed to compile the unittests for this module.

Firstly, `alias std.regex.internal.kickstart.Kickstart = std.regex.internal.kickstart.ShiftOr` wasn't found. That seems okay, as std.regex.internal.kickstart is only imported locally in a struct in imported std.regex.internal.ir.

When working around that, LDC complained that class std.regex.internal.**shiftor**.ShiftOr can't derive from **struct** std.regex.internal.**kickstart**.ShiftOr.

When fixing that by not deriving from anything (there was a std.regex.internal.ir.Kickstart interface before dlang/phobos@5a2491a), further compile errors arised as one can't foreach over a CodepointSet directly. I patched the problematic sites via copying code from the almost identical struct Kickstart in module kickstart, so that it now really works (for LDC at least).

### CODE REVIEW

**Comment by kinke** [comment]
auto-tester and DAutoTest seem to reuse the cached results for the same commit wrongly targeting branch `master` (#5243)...

**Comment by DmitryOlshansky** [comment]
> When working around that, LDC complained that class std.regex.internal.shiftor.ShiftOr can't derive from struct std.regex.internal.kickstart.ShiftOr.

This seems scary. It smells like botched merge but I astonished it doesn't cause any problems so far.

**Comment by kinke** [comment]
> astonished it doesn't cause any problems so far

The `shiftor` module is missing in the Phobos makefile. LDC doesn't use it.

**Comment by kinke** [comment]
It really appears to be an accidental remainder from the reverted regex overhaul (?); the `shiftor` module (apparently providing a `pure` ShiftOr variant) wasn't there in 2.072.2.

**Comment by kinke** [comment]
(File removed. CI problems should be unrelated.)

**Comment by JackStouffer** [comment]
@kinke The doc builder error is an error that was fixed here https://github.com/dlang/dlang.org/pull/1568

I don't know why it's manifesting again.

**Comment by kinke** [comment]
Somebody please retrigger CircleCI manually, I can't...

**Comment by JackStouffer** [comment]
Yeah, it's some weird error on circle. CC @wilzbach

**Comment by JackStouffer** [comment]
Auto-merge toggled off

**Comment by JackStouffer** [comment]
Auto-merge toggled on

**Pull request merged**
