### PR TITLE
Avoid deprecation warning from getSymbolsByUDA.

### PR DESCRIPTION
**Pull request by rcorre**
Due to more strict accessibility rules, `getSymbolsByUDA` can no longer
return non-public members, as they are not visible to `std.traits`.

See discussion in #3827.

### CODE REVIEW

**Comment by andralex** [comment]
what's with travis?

**Comment by wilzbach** [comment]
> what's with travis?

We seem to get some weird networks errors lately. CC @MartinNowak 
@MartinNowak already included a retry loop quite recently (https://github.com/dlang/installer/pull/187), but it seems that it doesn't help if the server isn't available :/
In any case
- Travis is just running coverage analysis for Phobos / Druntime atm
- One of the reasons we want to switch to CircleCi (#4719),  is that Travis got less reliable and clogged lately

**Comment by MartinNowak** [comment]
> One of the reasons we want to switch to CircleCi (#4719), is that Travis got less reliable and clogged lately

To put it more correctly, we clogged our Travis-CI fair use share (accounted on dlang), by slowing down dmd by ~1.5x and then doubling the tests by adding 32-bit. As you see from the response times, reducing our test times to an acceptable level fixed that.
Regarding the test failure (which is about downloading dub). Maybe @s-ludwig redeployed the website recently or had some other issues? But we should definitely work on the reliability of the site (for dub) and the downloads (for the installer).
A simple fix would be to mirror the dub downloads on our downloads.dlang.org site or simply upload them to github releases. With 2.072.0 dub will be contained in dmd releases anyhow.

**Comment by MartinNowak** [comment]
> Due to more strict accessibility rules, getSymbolsByUDA can no longer
> return non-public members, as they are not visible to std.traits.

Let's not rush this PR and wait how we resolve visibility of private members in meta code.

**Comment by MartinNowak** [comment]
Think this can be closed now, the next release will allow getMember to pass visibility checks. Access checks for getMember will be dropped in a later release (though likely are marked unsafe).

**Comment by andralex** [comment]
alrighty

**Comment by rcorre** [comment]
@andralex did you mean to reopen it? It sounded like you were agreeing with closing it :)

**Comment by andralex** [comment]
sorry!

**Pull request closed without merging**
