### PR TITLE
std.file: don't initialize stat struct here

### PR DESCRIPTION
**Pull request by ljmf00**
Signed-off-by: Luís Ferreira <contact@lsferreira.net>

### CODE REVIEW

**Comment by CyberShadow** [comment]
The old code looks good to me. `statbuf` is declared with ` = void`, so it's initialized before the `stat` call populates it partially or fully. What is the problem?

**Comment by ljmf00** [comment]
> The old code looks good to me. `statbuf` is declared with ` = void`, so it's initialized before the `stat` call populates it partially or fully. What is the problem?

According to the specification:
> **19.16.3.3. Ref and Out Parameters:** An out parameter is similar to a ref parameter, except it is initialized with x.init upon function invocation.

Even if it is void initialized, `out` parameter can't be optimized by the compiler since `stat` function is an external source.

See https://run.dlang.io/is/V9s6Jd .

**Comment by CyberShadow** [comment]
> Even if it is void initialized, `out` parameter can't be optimized by the compiler since `stat` function is an external source.

Optimized how? What are you trying to achieve?

**Comment by ljmf00** [comment]
> > Even if it is void initialized, `out` parameter can't be optimized by the compiler since `stat` function is an external source.
> 
> Optimized how? What are you trying to achieve?

If the `stat` source is reachable and variable is initialized, the `out` storage class will do nothing in practice, as the optimizer will forget the initialization, but because it is an external source, this will always call `.init` and ` = void` is useless there. To use the benefits of the void initializer `ref` storage class should be used instead.

Also, currently, my change does run on the Phobos test suite but not on mine which also runs tests with `-O -cov` arguments, so lets not merge this yet. Related to this issue: https://issues.dlang.org/show_bug.cgi?id=19320 and a PR solving and discussing this was created https://github.com/dlang/dmd/pull/13015 .

**Comment by CyberShadow** [comment]
But, we don't know to what extent the OS/libc will initialize the `stat` structure, so the `out` initialization seems useful to me.

**Comment by ljmf00** [comment]
> But, we don't know to what extent the OS/libc will initialize the `stat` structure, so the `out` initialization seems useful to me.

If the `stat` runs successfully it shall set the required field as a POSIX conformant syscall.

**Comment by CyberShadow** [comment]
> If the `stat` runs successfully it shall set the required field as a POSIX conformant syscall.

That's an assumption. Not all POSIX implementations are necessarily compliant fully compliant. The cost of making such assumptions, versus the cost of initializing a variable, is generally not worth it when making an I/O call.

A stronger argument is that pretty much all `stat` calls in `std.file` already use and rely on `void`-initialization, so this change improves consistency in that regard.

**Review by CyberShadow — APPROVED** [review]

**Comment by maxhaton** [comment]
Doing this in the name of optimization seems pretty daft, as CyberShadow points out. A very quick test suggests that a call to stat is thousands and thousands of times slower than the system call itself.

**Comment by ljmf00** [comment]
> Doing this in the name of optimization seems pretty daft, as CyberShadow points out. A very quick test suggests that a call to stat is thousands and thousands of times slower than the system call itself.

I know that this is an I/O syscall and I/O operations take a ton of time, in fact, I didn't make this PR just because it is more optimized but because the current behaviour it is producing is just pointless.

I was reading `DirEntry` implementation and saw that combination of `= void` initializer and `out` parameters storage class. If the `void` initializer doesn't produce any effect here, why we are using `out`? To make the code harder to understand? If people vaguely read this function body they doubt about `stat_t` being initialized or not.

Another thing to point in the untrusted `stat` syscall implementation is: if you are sure that you are running in a POSIX compliant system, what is the problem? If we take this strictly, then, the problem is not about `getSize()` but maybe because (a) `version(POSIX)` is laying or (b) `core.sys.posix.sys.stat` documentation is laying.

**Review by RazvanN7 — APPROVED** [review]

**Comment by CyberShadow** [comment]
> I was reading `DirEntry` implementation and saw that combination of `= void` initializer and `out` parameters storage class. If the `void` initializer doesn't produce any effect here, why we are using `out`? To make the code harder to understand? If people vaguely read this function body they doubt about `stat_t` being initialized or not.

@ljmf00 That's a nice explanation, and it would have saved us both some time if it was included in the commit message.

In the future, it would be great if you could write a paragraph describing *why* you are making the change, and add it to the commit message.

https://www.google.com/search?q=good+commit+messages

**Comment by ljmf00** [comment]
> > I was reading `DirEntry` implementation and saw that combination of `= void` initializer and `out` parameters storage class. If the `void` initializer doesn't produce any effect here, why we are using `out`? To make the code harder to understand? If people vaguely read this function body they doubt about `stat_t` being initialized or not.
> 
> @ljmf00 That's a nice explanation, and it would have saved us both some time if it was included in the commit message.
> 
> In the future, it would be great if you could write a paragraph describing _why_ you are making the change, and add it to the commit message.
> 
> [google.com/search?q=good+commit+messages](https://www.google.com/search?q=good+commit+messages)

I'm sorry for the lack of explanation. I often do that either in the PR description or in the commit body but I wrongly saw this as a trivial patch.

**Pull request merged**
