### PR TITLE
Simple workaround for DMD issue #14447 in std.utf.decodeImpl().

### PR DESCRIPTION
**Pull request by tsbockman**
This PR works around [DMD issue #14447](https://issues.dlang.org/show_bug.cgi?id=14447), which led to the addition of a redundant parameter to `std.utf.decodeImpl()`.

The first commit keeps the redundant parameter, so that its consistency with the internally
computed `canIndex` could be verified by the autotester (done now). The next commit removes it,
and fixes all the call sites.

With the second commit, this PR:
* Makes Phobos more DRY.
* Makes it easier to call `decodeImpl()` correctly.
* Reduces the number of repetitive type checks of `S` - arguably making this PR superior to the original, commented out solution.

The function is `private`, so this should be a 100% non-breaking change.

### CODE REVIEW

**Comment by tsbockman** [comment]
Everything except Win64 (which takes forever to run) has gone green on the auto-tester, so I'm going to go ahead and call it "good enough" on the `assert (canIndex == _canIndex);` test. (See my first commit).

I will upload the rest of this PR now.

**Comment by tsbockman** [comment]
I threw in a third commit, just to fix some style inconsistencies I noticed with respect to the use of `Flag!"useReplacementDchar"`. It is not important to me; if there is no consensus I will just revert that one.

The [first](https://github.com/tsbockman/phobos/commit/2b1585c95ac990aa6ede8f1ee804ff41d469e2d5) and [second](https://github.com/tsbockman/phobos/commit/42c882943f1c1b5f7e1d3b0f10db675dfa168a6d) commits are the important parts here.

**Comment by tsbockman** [comment]
@jmdavis Could you review this for me? Since it is related to [your PR #4012](https://github.com/D-Programming-Language/phobos/pull/4012).

**Comment by tsbockman** [comment]
I have submitted a [more complex alternative](https://github.com/D-Programming-Language/phobos/pull/4073) to this PR, which also solves an additional problem with misuse of `@trusted` in `std.utf`. I will leave this PR open until I see if the other is rejected as too large.

**Comment by tsbockman** [comment]
Rebased.

**Comment by tsbockman** [comment]
I'll close this now: it looks like if anything gets accepted here, it will be the alternative PR linked above.

**Comment by jibal** [comment]
This is why bugs persist.

**Comment by 0xEAB** [comment]
Your chance send a rebased PR, jibal :)

**Pull request closed without merging**
