### PR TITLE
CheckBy postblit should be scope

### PR DESCRIPTION
**Pull request by WalterBright**
This was discovered here:

https://github.com/dlang/dmd/pull/16145#issuecomment-1933424830

### CODE REVIEW

**Comment by WalterBright** [comment]
Blocking https://github.com/dlang/dmd/pull/16145#issuecomment-1933424830

**Review by PetarKirov — APPROVED** [review]

**Comment by WalterBright** [comment]
why isn't dlang-phobos running?

**Comment by ibuclaw** [comment]
> why isn't dlang-phobos running?

Because they were deleted #8900

I'll remove them as a "required" pipeline from our settings to unblock you.

**Comment by WalterBright** [comment]
@ibuclaw @thewilsonator thanks!

**Pull request merged**
