### PR TITLE
Change the findSplit example into a documented unit test

### PR DESCRIPTION
**Pull request by MetaLang**
A followup to https://github.com/dlang/phobos/pull/5752

### CODE REVIEW

**Comment by MetaLang** [comment]
I swear the whitespace/tab checks will be the death of me

**Comment by MetaLang** [comment]
Since Andrei already added the auto-merge tag and it was removed by the bot, I'll re-add it myself.

**Comment by andralex** [comment]
@MetaLang that's the spirit

**Comment by MetaLang** [comment]
Sounds like a good idea to me.

**Comment by wilzbach** [comment]
@MetaLang: thanks a lot for pushing this. Highly appreciated!

**Pull request merged**
