### PR TITLE
fix table formatting in uni.d

### PR DESCRIPTION
**Pull request by wilzbach**
follow-up to #4354 - this document is hard to read with all the unnecessary whitespace.

http://dlang.org/phobos/std_uni.html

### CODE REVIEW

**Comment by aG0aep6G** [comment]
As with #4358, dmd's handling of empty lines should be fixed instead of working around it here.

**Comment by DmitryOlshansky** [comment]
Ehm I don't understand something... Why indenting the text will fix unnecessary whitespace?

**Comment by wilzbach** [comment]
> Ehm I don't understand something... Why indenting the text will fix unnecessary whitespace?

Indendation was done to make it easier for the eye to grasp the context. The important part is that the lines between the paragraph have been removed.

```
$(P
 ...
)
<this line was removed>
$(P
```

See yourself:
http://dtest.thecybershadow.net/artifact/website-fc52239a89c0f31ce8fab3844f156b775682a9e6-c2b018c0699f83c6d7e130c5be336046/web/phobos-prerelease/std_uni.html
http://dlang.org/phobos/std_uni.html

**Comment by DmitryOlshansky** [comment]
Auto-merge toggled on

**Pull request merged**
