### PR TITLE
Deprecate the range API functions on Nullable.

### PR DESCRIPTION
**Pull request by jmdavis**
I don't know how acceptable it is to do this (the functionality was added in
2.100.0 back in May 2022, so it's not particularly old, but it's not exactly
new either). However, I'm sick of dealing with bugs related to Nullables being
treated as ranges. We got rid of the alias this on Nullable precisely to fix
problems related to implict conversions and Nullable, and making Nullable a
range just added a whole new set of them - ones which typically pop up in
generic code, forcing you to do stuff like check that a type is not an instance
of a Nullable or add an overload just for Nullables so that the range-based
overload doesn't take it.

Code that wants to get a range from Nullable can do so by slicing it, just like
you can with static arrays and other container types. So, code that wants to
continue to use Nullables as ranges can do so quite easily by simply adding [].
In the meantime, they'll get a deprecation message, so no code will break -
though unfortunately, the problems with Nullable being a range will of course
continue until we can actually remove the deprecated functions down the road.

The second commit fixes the few tests which need to use [] to get rid of the deprecation messages - and it unfortunately also removes the unittest block that's intended to test that the range API functions on Nullable work properly, since apparently, Phobos is currently compiled with -de, which makes it impossible to actually test deprecated code.

### CODE REVIEW

**Comment by Herringway** [comment]
Nullables are ranges. Code that doesn't want to be generic and treat them specially for some reason can simply check the type.

**Comment by jmdavis** [comment]
> Nullables are ranges. Code that doesn't want to be generic and treat them specially for some reason can simply check the type.

Nullables are a type for indicating whether there's a value or not, which is definitely not the same as a range. Yes, they can be given the API of a range and then have 0 elements or 1 element, but the use case for Nullables and the use case for ranges are fundamentally different. Nullable's are pointers without the heap allocation, and treating a Nullable like a range is like treating a pointer like a range. Sure, you _could_ give a pointer the API of a range, but that's really not what pointers are used for, and it's going to cause problems - particularly with generic code.

All I am seeing from this "feature" is bugs and issues with generic code. Anyone who wants a range can slice the Nullable just like they can with any container.

We got rid of the alias this on Nullables precisely because that kind of implicit conversion caused issues, and making Nullables a range is the same kind of problem. And IMHO, it has to go for basically the same reasons. It's just plain error-prone. It is not onerous to need to use [] to get a range from a Nullable, just like it isn't onerous to require an explicit call to get to get the value from a Nullable.

**Comment by Herringway** [comment]
> > Nullables are ranges. Code that doesn't want to be generic and treat them specially for some reason can simply check the type.
> 
> Nullables are a type for indicating whether there's a value or not, which is definitely not the same as a range. Yes, they can be given the API of a range and then have 0 elements or 1 element, but the use case for Nullables and the use case for ranges are fundamentally different. Nullable's are pointers without the heap allocation, and treating a Nullable like a range is like treating a pointer like a range. Sure, you _could_ give a pointer the API of a range, but that's really not what pointers are used for, and it's going to cause problems - particularly with generic code.
> 
> All I am seeing from this "feature" is bugs and issues with generic code. Anyone who wants a range can slice the Nullable just like they can with any container.
> 
> We got rid of the alias this on Nullables precisely because that kind of implicit conversion caused issues, and making Nullables a range is the same kind of problem. And IMHO, it has to go for basically the same reasons. It's just plain error-prone. It is not onerous to need to use [] to get a range from a Nullable, just like it isn't onerous to require an explicit call to get to get the value from a Nullable.

If you want to treat things differently for arbitrary reasons, you're not writing generic code. I have in fact written code that gives pointers a range interface, and it was quite pleasant to use. It can allow you to write less code to handle more! Generic code is a real blessing.

Nullables are not pointers. They cannot be dereferenced. Pointers have absolutely nothing to do with heap allocation, either. Can they be allocated on the heap? Yes, just like a Nullable can be. `assert(Nullable!int is null);` does not compile. Why? Because it's not a pointer. Because null isn't a value for it. It is a state. The documentation states this clearly: `Defines a value paired with a distinctive "null" state that denotes the absence of a value.` A Nullable is either zero values or one value. It is a range.

There is no implicit conversion occurring here. Nullables are ranges, because range-ness is determined by interface, which they implement. They can be passed to functions accepting ranges, without their type changing. Similarly, it is not an implicit conversion for arrays to be treated as ranges, even though they don't even have range members. In neither case is an implicit conversion occurring, because they will always retain their type until explicitly converted.

If you want to give a Nullable special treatment, then you're going to be writing code to do that, regardless of whether or not this feature is removed. This PR is a net loss for convenience.

**Comment by jmdavis** [comment]
> If you want to treat things differently for arbitrary reasons, you're not writing generic code. I have in fact written code that gives pointers a range interface, and it was quite pleasant to use. It can allow you to write less code to handle more! Generic code is a real blessing.
> 
> Nullables are not pointers. They cannot be dereferenced. Pointers have absolutely nothing to do with heap allocation, either. Can they be allocated on the heap? Yes, just like a Nullable can be. `assert(Nullable!int is null);` does not compile. Why? Because it's not a pointer. Because null isn't a value for it. It is a state. The documentation states this clearly: `Defines a value paired with a distinctive "null" state that denotes the absence of a value.` A Nullable is either zero values or one value. It is a range.
> 
> There is no implicit conversion occurring here. Nullables are ranges, because range-ness is determined by interface, which they implement. They can be passed to functions accepting ranges, without their type changing. Similarly, it is not an implicit conversion for arrays to be treated as ranges, even though they don't even have range members. In neither case is an implicit conversion occurring, because they will always retain their type until explicitly converted.
> 
> If you want to give a Nullable special treatment, then you're going to be writing code to do that, regardless of whether or not this feature is removed. This PR is a net loss for convenience.

The intent behind a function returning a nullable type is completely different from a function returning a range. The whole point is to be returning a value that might not be there. That's completely different from returning a type that gives you a range over a list of values. And most code uses the two completely differently - whether the nullable type is a `Nullable`, a pointer, or something else

It's one thing to be able to get a range from a type like a `Nullable` or a pointer. It's another thing entirely to give them the range API and treat them like a range. All I have seen from that is bugs. If you want a range from a `Nullable`, then all that's required is to wrap it in a range - and for better or worse, `[]` does that on `Nullable`. But having `Nullable` itself be treated as a range easily results in code that accidentally ends up doing the wrong thing with it, because it ended up being used a range somewhere when the API in question never intended to use it as a range, because if it did, it would have returned a range, not a `Nullable` or a pointer. It gets particularly bad in code that uses type introspection heavily or which does code generation. Now `Nullable` has to be special-cased just to have it actually be treated as a nullable type.

Clearly, we're not going to come to an agreement on this, but from everything I've seen, it was a huge mistake to add the range API to `Nullable`. It was not designed with the idea that it would be a range, and that's not how it's typically used. Most code that wants to return a range of values will return a range specific to what that function is doing, not return a pointer or a `Nullable` or any other kind of nullable type. The usages of a nullable type and a range are normally distinct. That does not preclude getting a range from a nullable type so that code that wants a range can have a range, but the fact that `Nullable`'s API was changed to make it a range everywhere forces it and causes problems for code that's really just trying to provide a nullable value. As things stand, I'm tempted to advise that folks actively avoid Phobos' `Nullable`, because in my experience, the fact that it has the range API on it directly is nothing but a source of bugs.

As for `Nullable`'s API being distinct from a pointer, it really should be closer to a pointer than it is. The main reason that it isn't is because we made the mistake of having an `alias this` to `get` on it originally, which makes it a disaster to do stuff like dereferencing it or casting it to `bool`, because then that can get really buggy. It was thought that having the `alias this` on it would improve its usability, but experience showed the opposite. With the `alias this` gone, having dereferencing and casting to `bool` on `Nullable` would no longer be a problem, and it would actually be a usability boost if we we added that functionality to it - especially the ability to cast it to `bool` to check whether it's null, because then we could use it directly in the conditions of if statements.

**Comment by dkorpel** [comment]
Do you have references for those bugs you encountered (forum posts, GitHub issues, examples etc.)? Having some concrete code helps the discussion.

**Comment by jmdavis** [comment]
> Do you have references for those bugs you encountered (forum posts, GitHub issues, examples etc.)? Having some concrete code helps the discussion.

I can't really point to github issues and the like, because the worst of these issues have been in symmetry code.

However, a basic example would be code that needs to have one overload take individual objects, and another which takes ranges of objects (e.g. because individual objects are wrapped differently from range-based objects and given a completely different API when being presented to another language). Without the range API, `Nullable` is treated as a single object, whereas with the range API, it ends up in the overload that takes ranges. And since nullable types are very much intended to be single objects in any of the code that I'm dealing with, having Phobos' `Nullable` take the range overload results in bugs, some of which are quickly found, and some of which are not. And since there are many, many layers of templates and type introspection involved, the situation is often complex, and the bugs that are triggered are not necessarily close to where a change was made.

The situation would be a bit like if you had a container type which had the range API added to it instead of simply providing a function that would give you a range over its elements so that you could pass that to range-based code. Generic code would need to treat the container like a container and pass it around as a single object that could then be operated on, but instead, it gets treated as a range of values to be consumed, because that range API was added to it. And since whether the code treats the object as a single object or as a range of objects is determined by type introspection, it's all quite automatic.

So, having a type have an API on it which makes it so that it can work with a different set of code with a different set of semantics rather than providing a way to convert from one to the other so that the programmer can do it explicitly when they want to causes issues and results in needing a bunch of special-casing in template constraints to avoid those issues. It's one thing to provide a function to get a range from a type. It's quite a different matter to make the type itself a range. The former adds potentially useful functionality, whereas the latter has a huge impact on what happens with general type introspection.

A lot of symmetry's code unfortunately uses Mir's `Nullable` (which has a different set of issues), and it doesn't treat `Nullable` as a range. So, as code within symmetry is switched away from using Mir - or has to be reworked to work properly with both Mir's `Nullable` and Phobos `Nullable` - there are a variety of issues where code that worked perfectly well with Mir's `Nullable` then breaks with Phobos' `Nulalble`, because Phobos' `Nullable` is now a range. And this kind of issue often happens with code that has no direct connection to any kind of nullable type, because there are a lot of layers, plenty of which are doing a lot type introspection and auto-generating code based on that information. And none of this code was written with the idea that a nullable type even might be a range. It might contain a range, but it isn't intended to be a range. It's just a way to return a value that may or may not be there, and that then starts getting really problematic when several layers away from there it gets passed into a function that's supposed to treat ranges one way and individual objects another way, and it wasn't written to special-case Phobos `Nullable`, because of course it wasn't. It's not something that you'd normally even think about. And so nullable types - which were very much intended to be treated as individual objects - suddenly get treated as ranges instead, and whether that gets caught quickly or not very much depends on what exactly that affects and how good the testing was in that particular area.

And you get similar issues with code that has been using Phobos `Nullable` the whole time but didn't use it anywhere that might test whether it's a range, and then when a related piece of code gets refactored, suddenly that `Nullable` ends up being passed to a function that's doing something specific to ranges, and the code does the wrong thing, because Phobos' `Nullable` has the range API, and of course, none of the code involved special-cased Phobos' `Nullable`, because no one involved even thought about the idea that Phobos `Nullable` might be a range, since nullable types aren't normally ranges (and Phobos' wasn't until less than two years ago).

A simpler code base would have fewer issues with this sort of thing, and maybe then I'd be less angry about this, but fundamentally, `Nullable` is intended to represent a value that might be null, which is very different from a range of values, even if it can be represented as a range of values. And increasingly, my experience is that having a user-defined type present the range API when it's intended to be used as anything other than a range is a mistake. Providing a way to get a range from the type can be very useful, but the core type should not be a range. And this becomes far, far more important when you're dealing with a code base that's doing code introspection on a huge variety of types so that it can generate code.

And I'd love to be able to point at a slew of bug reports where the fact that `Nullable` being a range has caused issues, but these aren't bugs that pop up in stuff like Phobos, because Phobos code isn't using `Nullable` as a range, and with all of the stuff I've been dealing with where bugs pop up, either you see it and you add a bunch of special-casing to your code to avoid the bug, or it's deep in proprietary code where nothing gets reported externally. So, you find it at some point when someone makes a seemingly unrelated change that exposes the bug, or a user reports an issue that you track down to `Nullable`. And even if these issues were in open source code, the worst of them often include a lot of layers of templates that make reducing the code sufficiently to report anything problematic.

The core problem comes from the fact that you use a nullable type for a completely different use case from when you provide a range of values, and when type introspection gets involved, having the range API on the nullable type goes from being a nice-to-have just so that it can also work with range-based functions to something that is actively making the nullable type take the wrong code path in generic code, because type introspection sees that it's a range.

Simply having `opSlice` on the `Nullable` gives you the nice-to-have of being able to get a range from it to pass to range-based code without all of those extra problems that come with the `Nullable` itself being seen as a range by type-introspection. So, from what I can see, having that `opSlice` solves the use case that folks who want to treat a `Nullable` as a range have, and it doesn't then require that code special-case `Nullable` just so that it can actually be treated as a single object as per its original design and core use case.

**Comment by Herringway** [comment]
I really wish the fact that it was corporate code that was affected was mentioned at the beginning of this PR. I wouldn't have wasted my time fighting the inevitable merging of this PR then.

**Comment by jmdavis** [comment]
> In general, I think implementing the range API for a type ought to be considered a non-breaking change (since it's purely additive). So if a user has written code that's broken by such a change, my instinct is to say, that's their own problem, not Phobos's.

It has a significant impact on type introspection, and I think that in general, it's an abuse of the range API to put it on stuff that isn't fundamentally a range and is intended to be used as something other than a range. There are plenty of types where it makes sense to provide a way to get a range from them without it making sense to turn them into a range. And I think that putting the range API on a user-defined nullable type makes exactly as much sense as it does to put it on a pointer - that is, not at all. They represent a nullable value, not a list of values. Explicitly wrapping a nullable type or a pointer in a range might be useful functionality under some set of circumstances, but they're not the kind of types where IMHO it makes any sense for them to be treated as ranges by default. In essence, by putting the range API on a type that isn't designed specifically to be used as a range rather than anything else adds an implicit conversion, and it fundamentally changes how code that uses type introspection will treat the type.

The reality of the matter is that there isn't really such a thing as purely additive changes when type introspection is involved - especially when we're talking about adding a well-known API that is routinely tested for by type introspection. And yes, to an extent, adding members to a type always risks breaking code, but in this case, we're talking about a core type in Phobos whose primarily functionality has nothing to do with ranges, and it forces code to then explicitly test for it in order to not have it accidentally treated as a range. It would be like adding the range API to a container. Sure, you _can_ do it, but it's not its intended purpose, and it causes problems with its intended purpose.

IMHO, if we want the ability to use a type as a range rather than whatever it was originally designed as, then we should add the ability to wrap it in a range, but we shouldn't be making it a range - especially not in Phobos where it affects pretty much everyone using D.

**Comment by schveiguy** [comment]
I haven't used the Nullable as a range feature, but just finding out about it, I intend to, and I would be sad if this were removed.

I did this exact thing in [dcollections cursors](https://github.com/schveiguy/dcollections/blob/master/concepts.txt#L21) and I found it to be a really nice abstraction.

> Treating `Nullable` as a range has been causing problems for generic code
similar to when `Nullable` used `alias this` with `get`, so it was clearly
a mistake to add that functionality.

Fully disagree here (not that it is causing problems, but that the problems are similar). Alias this with get had a completely different problem -- if you unwrapped a Nullable that is null you get a runtime error, and it was too easy to trigger by accident without requiring unwrapping. In the range mechanism, you can't accidentally unwrap a null value.

Now, it might match templates you wouldn't expect, but this is par for the course with Nullable. I typically have overloads specifically for Nullable. If you want to take both Nullable!T and RangeOf!T, then you will need to differentiate those template constraints.

FWIW, I've been writing lots of code using Nullable (a database wrapper, and a json parser) and never ran into this problem, even in the last 2 years. So I don't think it's a huge problem.

> A lot of symmetry's code unfortunately uses Mir's Nullable (which has a different set of issues), and it doesn't treat Nullable as a range. So, as code within symmetry is switched away from using Mir - or has to be reworked to work properly with both Mir's Nullable and Phobos Nullable - there are a variety of issues where code that worked perfectly well with Mir's Nullable then breaks with Phobos' Nulalble, because Phobos' Nullable is now a range. 

So you are saying, you were using another type from another library, and it doesn't have the same API as a similarly named type in Phobos? Now, we may want to incorporate those restrictions here, but also, that in itself isn't a reason the current API should be changed.

**Comment by jmdavis** [comment]
> So you are saying, you were using another type from another library, and it doesn't have the same API as a similarly named type in Phobos? Now, we may want to incorporate those restrictions here, but also, that in itself isn't a reason the current API should be changed.

We've been using a mixture of types, and std.typecons' `Nullable` has been problematic, because it gets treated as a range by type introspection. We've been trying to move away from Mir's `Nullable`, which has increased how much std.typecons' `Nullable` is being used, and the fact that it's a range has been a problem. But we'd have exactly the same problem if we were writing completely fresh code that was using `Nullable` and using type introspection to figure out what code to generate for the type. So, regardless of what's going on with Mir's `Nullable`, the fact that std.typecons' `Nullable` now has a range interface has been a problem.

The fundamental problem here is that a nullable type's primary use case has nothing to do with ranges. It's for returning a possible result, not for returning a list of values. So, having a nullable type get treated as a range is just wrong IMHO. It's less of a problem when you're not doing much with type introspection, since then you can ignore the extra functionality if you don't use it, but it's definitely a problem with type introspection, because it means that the nullable type gets treated as something other than a nullable type, and you're forced to special-case it just because some extra functionality which has nothing to do with its core functionality was put on it. And if you do end up passing a `Nullable` to a range-based function, you get weird stuff like this: https://issues.dlang.org/show_bug.cgi?id=24233

Based on my experiences up to this point, I'm of the opinion that types in general should not be made into ranges unless that's pretty much their sole purpose, which is very much not the case with a nullable type. It's like making a container into a range. You can technically do it, but it results in a type being presented as something other than what it is, and it makes it so that if you use it in the wrong place, it gets consumed. However, it's definitely worse when type introspection is involved, because then the type gets treated as something other than what it's supposed to be unless the code generation does special casing for that particular type.

I don't see a problem with a type providing a way to get a range to then pass to range-based code where that makes sense, since then it gives that functionality without making the type itself a range, but I'm completely convinced at this point that arbitrarily making stuff ranges just because they can be is a mistake. At best, it doesn't matter in cases where that functionality is not used and type introspection isn't being used, but at worst, it causes bugs with type introspection, because it's presenting an API that has nothing to do with its primary use case. On the other hand, if we just provide a way to get a range from the type, the folks who actually want that functionality can use it without compromising the type itself.

But clearly, I don't know how to convince anyone who doesn't agree on this.

**Comment by pbackus** [comment]
> The fundamental problem here is that a nullable type's primary use case has nothing to do with ranges. It's for returning a possible result, not for returning a list of values. So, having a nullable type get treated as a range is just wrong IMHO.

The fundamental problem is that your code is assuming it can determine a type's "primary use case" by checking for the presence or absence of range methods. This is not an assumption you can rely on, unless you're working in a closed system where you control all the code. If `Nullable` hadn't broken it, something else would have eventually.

> Based on my experiences up to this point, I'm of the opinion that types in general should not be made into ranges unless that's pretty much their sole purpose, which is very much not the case with a nullable type.

Even if this is true, does it justify introducing a breaking change to Phobos? There are plenty of interfaces in Phobos that we can all agree are badly-designed, but in general, we're waiting for Phobos v3 to fix them. What's different about this specific change that justifies fast-tracking it?

**Comment by schveiguy** [comment]
> But we'd have exactly the same problem if we were writing completely fresh code that was using `Nullable` and using type introspection to figure out what code to generate for the type.

If you want to distinguish between a range, and a specific range, you can do it. This is no different.

People often have code that is overloaded for ranges and specialized for arrays. Nobody complains that arrays are also ranges, they just write `if(isInputRange!R && !isArray!R)` and move on.

**Comment by jmdavis** [comment]
> The fundamental problem is that your code is assuming it can determine a type's "primary use case" by checking for the presence or absence of range methods. This is not an assumption you can rely on, unless you're working in a closed system where you control all the code. If Nullable hadn't broken it, something else would have eventually.
    
> If you want to distinguish between a range, and a specific range, you can do it. This is no different.

If something is reporting itself as a range, then it's saying that it's presenting a list of values. However, fundamentally, `Nullable` is not a list of values. It's a singular value that's been given the range API. The entire point of a nullable type is to present a value that may or may not be there, but it's a singular value, not a list, not a range. Putting the range API on `Nullable` is like putting it on a pointer. It's presenting a singular value as if it were a list of values.

So, IMHO, it's not a matter of distinguishing between range types. It's a matter of distinguishing a type that never should have had the range API in the first place so that it can actually be treated like the singular value that it is.

> Even if this is true, does it justify introducing a breaking change to Phobos? There are plenty of interfaces in Phobos that we can all agree are badly-designed, but in general, we're waiting for Phobos v3 to fix them. What's different about this specific change that justifies fast-tracking it?

It's a deprecation for a relatively new feature that never should have been there, so no code is actually broken by this change (it will have to be changed eventually and will then break if it isn't, but it will continue to work as-is until the deprecated symbols are removed). And it's bad enough IMHO to merit deprecating it ASAP so that what little code is out there that uses it can be changed, and then we can eventually make it so that no code has to deal with this bad behavior any longer. And the folks who actually want to get a range from a `Nullable` can just add a `[]` to their code to slice it and pass it to whatever range code their dealing with, without the `Nullable` itself being treated as a range. So, it's not like they even lose out on the functionality.

But I guess that no one else here sees the problem or cares, and I clearly don't know how to convince you guys that this is bad enough to be worth deprecating. I really wish that I'd been paying enough attention when the PR to add the range API to `Nullable` had been made in the first place so that I could have objected then, but I wasn't.

So, while I think that this behavior really needs to go ASAP, I guess that arguing about it further is a waste of time, and code is just going to have to continue to work around the bad behavior until Phobos v2 actually stops being used.

**Comment by schveiguy** [comment]
> However, fundamentally, `Nullable` is not a list of values. It's a singular value that's been given the range API.

See also https://dlang.org/phobos/std_range.html#only

**Pull request closed without merging**
