### PR TITLE
Remove uses of INLINE_YL2X from std.math

### PR DESCRIPTION
**Pull request by ibuclaw**
To initially get std.math bootstrapped onto being `pure @trusted nothrow`, yl2x did have a purpose.

Now though, its role is meaningless as we have long since had proper `pure @trusted nothrow` implementations.  And if anything, it's now harmful since the introduction of https://github.com/D-Programming-Language/dmd/pull/4012 as it leaves it open to misuse.

I'm not against having these functions as CTFE-able.  I'm just against library maintainers leveraging (unwittingly, as it's not actually _their_ fault if code seems to work for them) non-portable CTFE builtins.

### CODE REVIEW

**Comment by ibuclaw** [comment]
I need the autotester to report feedback, as it works for me locally.  @braddr

**Comment by WalterBright** [comment]
Due to whitespace and reformatting changes, this is nearly impossible to review. I can't tell what is substantive and what isn't without spending a great deal of time.

**Comment by yebblies** [comment]
@WalterBright Github can hide the whitespace changes from the diff, making review much easier.  I don't think it's exposed in the UI anywhere, but you can enable it by adding `&w=1` to the url.

Link for this pull: https://github.com/D-Programming-Language/phobos/pull/3310/files?w=1

**Comment by ibuclaw** [comment]
Regardless of ``&w=1`` - what part of "Removes INLINE_YL2X" is not understood here?  I'm no Kenji or Igor.  I don't have time (nor care) about micro re-formatting every line I come across and include it in PRs that have nothing to do with said reformat (that's not to say I haven't undone reformatting done by one or the other though).

**Comment by WalterBright** [comment]
@yebblies you're right, thanks for the link.

**Comment by WalterBright** [comment]
So, does the non-INLINE_YL2X branch generate the same code as the INLINE_YL2X branch with dmd?

**Comment by ibuclaw** [comment]
> So, does the non-INLINE_YL2X branch generate the same code as the INLINE_YL2X branch with dmd?

If you are asking, does the non-INLINE-YL2X branch compile down to the same assembly?  Answer no.  If you are asking performance? That will need to be tested.

A brief look at an instruction reference manual tells me that the INLINE_YL2X branches will execute at least 63 ops and has a latency of at least 158 (clock ticks or cycles is not specified).

As for the non-INLINE_YL2X branch, that is difficult to say.  Someone will need to find the most common path and work out if the accululated fsub/fadd/fmul/fdiv's account for less or more than a single fyl2x instruction.

But rather than being too bogged down on such matter, Instead, you should be asking about comparison of results.  Is non-INLINE_YL2X less or more accurate than INLINE_YL2X?

**Comment by ibuclaw** [comment]
Autotester can't test these unless this is pulled in: https://github.com/D-Programming-Language/phobos/pull/3309

**Comment by ibuclaw** [comment]
Until you fix Phobos builds, this is blocked.

**Comment by 9il** [comment]
Probably we need relax gamma function unittests?

**Comment by 9il** [comment]
#3309 was merged, however unittests fails.

**Comment by ibuclaw** [comment]
I have the same test passing with gdc.  Could be that dmd is using an inline assembly code path that is producing subtly a different result from the software version.  But that is just speculation...

**Comment by DmitryOlshansky** [comment]
> Until you fix Phobos builds, this is blocked.

Guess now it's unblocked. @WalterBright

**Comment by quickfur** [comment]
ping @WalterBright 
It has been a while. What's the status with dmd on this PR?

**Comment by ibuclaw** [comment]
Who's idea was it to add ``FP magic with dmd`` to the list of phobos labels?

**Comment by 9il** [comment]
my

**Comment by ibuclaw** [comment]
Assuming that the line of failure reported by the auto-tester is correct.  https://github.com/D-Programming-Language/phobos/blob/b2f1987cb3ec2d34739a02e55bff19e4443c0b36/std/internal/math/gammafunction.d#L540

GDC does not have this problem, which could indicate an issue with DMD codegen.  But then again, maybe not if the inline assembler is involved in producing one of the answers.

**Comment by DmitryOlshansky** [comment]
Seems like it started to pass

**Comment by 9il** [comment]
@ibuclaw rebase please

**Comment by ibuclaw** [comment]
From what I recall, spoke to Don about this and I think we uncovered a problem with the asm implementation of exp2, where it was less accurate than the generic version if it fell into the slow branch.  I suspect that it's not helped by y2lx not being a very accurate instruction either.

**Comment by MetaLang** [comment]
@ibuclaw what's the status of this?

**Comment by ibuclaw** [comment]
I'll mark it as blocked until the non-asm implementations become ctfe-able.

In the meantime, someone should look at why the asm implementation for exp2 is less accurate.  And remove / fix tests that check for this inaccuracy.

**Comment by ibuclaw** [comment]
Superseded by #7668

**Pull request closed without merging**
