### PR TITLE
[doc] Fix argument naming.

### PR DESCRIPTION
**Pull request by veelo**

### CODE REVIEW

**Comment by JackStouffer** [comment]
Auto-merge toggled on

**Comment by WalterBright** [comment]
In the future, please use more descriptive branch names than `patch` which gives no clue what it is about. For example, see https://auto-tester.puremagic.com/pulls.ghtml?projectid=1

**Comment by veelo** [comment]
> please use more descriptive branch names

I use the "Improve this page" link in the documentation, and edit in my browser. If there is a way to specify the branch name in this work flow, I have missed it...

**Comment by WalterBright** [comment]
Hmm, I've never used that interface. To create a new branch, I use:
```
git checkout -b newbranchname
```

**Pull request merged**
